Repository OHF-Voice/intents, pull requests merged in 2022-12, with the labels that each got.

#2 Add language script
  script/add_language.py
  script/lint
  sentences/en/climate_HassClimateGetTemperature.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
  sentences/en/light_HassLightSet.yaml
  tests/__init__.py
  tests/test_language_intents.py
Labels: cla-signed

#3 Update add language script
  .github/workflows/ci.yaml
  script/intentfest/__init__.py
  script/intentfest/__main__.py
  script/intentfest/add_language.py
  script/intentfest/error.py
  script/intentfest/util.py
  script/lint
  tests/__init__.py
  tests/conftest.py
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#4 Add validate script
  .github/workflows/ci.yaml
  script/format
  script/intentfest/__init__.py
  script/intentfest/add_language.py
  script/intentfest/const.py
  script/intentfest/util.py
  script/intentfest/validate.py
  script/lint
Labels: cla-signed

#5 Add basis for NL
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/cover_HassCloseCover.yaml
  sentences/nl/cover_HassOpenCover.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassToggle.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/_common.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
  tests/nl/homeassistant_HassToggle.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassLightSet.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
  tests/test_language_sentences.py
Labels: cla-signed

#6 Clean up some slot values
  sentences/en/climate_HassClimateGetTemperature.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
  sentences/en/cover_HassCloseCover.yaml
  sentences/en/cover_HassOpenCover.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateSetTemperature.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/test_language_sentences.py
Labels: cla-signed

#7 Add intentfest parse
  README.md
  script/intentfest/parse.py
  script/intentfest/util.py
Labels: cla-signed

#8 Remove category
  sentences/README.md
  sentences/en/cover_HassCloseCover.yaml
  sentences/en/cover_HassOpenCover.yaml
Labels: cla-signed

#9 Validate the YAML files against schema
  mypy.ini
  requirements.txt
  script/intentfest/validate.py
  sentences/README.md
  sentences/en/_common.yaml
  tests/test_language_intents.py
Labels: cla-signed

#10 Validate referenced slots/lists in sentences and expansion rules
  script/intentfest/validate.py
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
Labels: cla-signed

#11 Allow test slot shorthand notation
  script/intentfest/validate.py
  tests/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateSetTemperature.yaml
  tests/en/cover_HassCloseCover.yaml
  tests/en/cover_HassOpenCover.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/homeassistant_HassToggle.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
  tests/test_language_sentences.py
Labels: cla-signed

#12 Init french
  responses/fr/HassClimateGetTemperature.yaml
  sentences/fr/_common.yaml
  sentences/fr/climate_HassClimateGetTemperature.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  sentences/fr/cover_HassCloseCover.yaml
  sentences/fr/cover_HassOpenCover.yaml
  sentences/fr/fan_HassTurnOff.yaml
  sentences/fr/fan_HassTurnOn.yaml
  sentences/fr/homeassistant_HassToggle.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/_common.yaml
  tests/fr/climate_HassClimateGetTemperature.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/cover_HassCloseCover.yaml
  tests/fr/cover_HassOpenCover.yaml
  tests/fr/fan_HassTurnOff.yaml
  tests/fr/fan_HassTurnOn.yaml
  tests/fr/homeassistant_HassToggle.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed

#15 Update Dutch test coverage
  script/intentfest/validate.py
  sentences/nl/cover_HassCloseCover.yaml
  sentences/nl/cover_HassOpenCover.yaml
  tests/nl/_common.yaml
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
Labels: cla-signed

#13 feat(german): add first german intents
  README.md
  responses/de/HassClimateGetTemperature.yaml
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/cover_HassCloseCover.yaml
  sentences/de/cover_HassOpenCover.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  sentences/de/homeassistant_HassToggle.yaml
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/_common.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateSetTemperature.yaml
  tests/de/cover_HassCloseCover.yaml
  tests/de/cover_HassOpenCover.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
  tests/de/homeassistant_HassToggle.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
  tests/de/light_HassLightSet.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed

#17 Add dev container
  .devcontainer.json
  requirements.txt
Labels: cla-signed

#20 Complete French test coverage
  tests/fr/homeassistant_HassToggle.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
Labels: cla-signed

#21 Fix English test coverage
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/light_HassTurnOff.yaml
  tests/en/_common.yaml
  tests/en/cover_HassCloseCover.yaml
  tests/en/cover_HassOpenCover.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed

#18 Add dependabot
  .github/dependabot.yml
Labels: cla-signed

#14 Validate that all sentences have at least 1 test
  script/intentfest/validate.py
Labels: cla-signed

#25 Note expansion_rules native
  sentences/README.md
Labels: cla-signed

#19 Add base for NB (Norwegian Bokmål)
  README.md
  responses/nb/HassClimateGetTemperature.yaml
  sentences/nb/_common.yaml
  sentences/nb/climate_HassClimateGetTemperature.yaml
  sentences/nb/climate_HassClimateSetTemperature.yaml
  sentences/nb/cover_HassCloseCover.yaml
  sentences/nb/cover_HassOpenCover.yaml
  sentences/nb/fan_HassTurnOff.yaml
  sentences/nb/fan_HassTurnOn.yaml
  sentences/nb/homeassistant_HassToggle.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  sentences/nb/light_HassLightSet.yaml
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  tests/nb/_common.yaml
  tests/nb/climate_HassClimateGetTemperature.yaml
  tests/nb/climate_HassClimateSetTemperature.yaml
  tests/nb/cover_HassCloseCover.yaml
  tests/nb/cover_HassOpenCover.yaml
  tests/nb/fan_HassTurnOff.yaml
  tests/nb/fan_HassTurnOn.yaml
  tests/nb/homeassistant_HassToggle.yaml
  tests/nb/homeassistant_HassTurnOff.yaml
  tests/nb/homeassistant_HassTurnOn.yaml
  tests/nb/light_HassLightSet.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
Labels: cla-signed

#29 Add CLI tool for generating example sentences
  parser/README.md
  parser/hassil/__main__.py
  parser/hassil/generate.py
  parser/tests/test_generate.py
Labels: cla-signed

#30 Clarify expansion rule guidelines
  sentences/README.md
Labels: cla-signed

#31 Remove toggle intent sentences
  intents.yaml
  parser/README.md
  sentences/de/homeassistant_HassToggle.yaml
  sentences/en/homeassistant_HassToggle.yaml
  sentences/fr/homeassistant_HassToggle.yaml
  sentences/nb/homeassistant_HassToggle.yaml
  sentences/nl/homeassistant_HassToggle.yaml
  tests/de/homeassistant_HassToggle.yaml
  tests/en/homeassistant_HassToggle.yaml
  tests/fr/homeassistant_HassToggle.yaml
  tests/nb/homeassistant_HassToggle.yaml
  tests/nl/homeassistant_HassToggle.yaml
Labels: cla-signed

#34 Rename generate to sample
  parser/README.md
  parser/hassil/expression_listener.py
  parser/hassil/sample.py
  parser/tests/test_sample.py
Labels: cla-signed

#35 Move hassil to PyPI
  parser/.gitignore
  parser/.isort.cfg
  parser/HassILGrammar.g4
  parser/LICENSE.md
  parser/Makefile
  parser/README.md
  parser/hassil/VERSION
  parser/hassil/__init__.py
  parser/hassil/__main__.py
  parser/hassil/_resources.py
  parser/hassil/expression.py
  parser/hassil/expression_listener.py
  parser/hassil/grammar/HassILGrammar.interp
  parser/hassil/grammar/HassILGrammar.tokens
  parser/hassil/grammar/HassILGrammarLexer.interp
  parser/hassil/grammar/HassILGrammarLexer.py
  parser/hassil/grammar/HassILGrammarLexer.tokens
  parser/hassil/grammar/HassILGrammarListener.py
  parser/hassil/grammar/HassILGrammarParser.py
  parser/hassil/grammar/HassILGrammarVisitor.py
  parser/hassil/intents.py
  parser/hassil/parse.py
  parser/hassil/py.typed
  parser/hassil/recognize.py
  parser/hassil/sample.py
  parser/hassil/util.py
  parser/mypy.ini
  parser/pylintrc
  parser/requirements.txt
  parser/requirements_dev.txt
  parser/script/format
  parser/script/lint
  parser/script/setup
  parser/script/test
  parser/setup.cfg
  parser/setup.py
  parser/tests/__init__.py
  parser/tests/test_expression_listener.py
  parser/tests/test_intents.py
  parser/tests/test_recognize.py
  parser/tests/test_sample.py
  requirements.txt
  script/setup
  tests/test_language_intents.py
Labels: cla-signed

#44 Add empty templates for Catalan and Spanish
  responses/ca/HassClimateGetTemperature.yaml
  responses/es/HassClimateGetTemperature.yaml
  sentences/ca/_common.yaml
  sentences/ca/climate_HassClimateGetTemperature.yaml
  sentences/ca/climate_HassClimateSetTemperature.yaml
  sentences/ca/cover_HassCloseCover.yaml
  sentences/ca/cover_HassOpenCover.yaml
  sentences/ca/fan_HassTurnOff.yaml
  sentences/ca/fan_HassTurnOn.yaml
  sentences/ca/homeassistant_HassTurnOff.yaml
  sentences/ca/homeassistant_HassTurnOn.yaml
  sentences/ca/light_HassLightSet.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  sentences/es/climate_HassClimateSetTemperature.yaml
  sentences/es/cover_HassCloseCover.yaml
  sentences/es/cover_HassOpenCover.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/ca/_common.yaml
  tests/ca/climate_HassClimateGetTemperature.yaml
  tests/ca/climate_HassClimateSetTemperature.yaml
  tests/ca/cover_HassCloseCover.yaml
  tests/ca/cover_HassOpenCover.yaml
  tests/ca/fan_HassTurnOff.yaml
  tests/ca/fan_HassTurnOn.yaml
  tests/ca/homeassistant_HassTurnOff.yaml
  tests/ca/homeassistant_HassTurnOn.yaml
  tests/ca/light_HassLightSet.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/ca/light_HassTurnOn.yaml
  tests/es/_common.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
  tests/es/cover_HassCloseCover.yaml
  tests/es/cover_HassOpenCover.yaml
  tests/es/fan_HassTurnOff.yaml
  tests/es/fan_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca, lang: es

#45 Add empty Croatian templates (hr)
  responses/hr/HassClimateGetTemperature.yaml
  sentences/hr/_common.yaml
  sentences/hr/climate_HassClimateGetTemperature.yaml
  sentences/hr/climate_HassClimateSetTemperature.yaml
  sentences/hr/cover_HassCloseCover.yaml
  sentences/hr/cover_HassOpenCover.yaml
  sentences/hr/fan_HassTurnOff.yaml
  sentences/hr/fan_HassTurnOn.yaml
  sentences/hr/homeassistant_HassTurnOff.yaml
  sentences/hr/homeassistant_HassTurnOn.yaml
  sentences/hr/light_HassLightSet.yaml
  sentences/hr/light_HassTurnOff.yaml
  sentences/hr/light_HassTurnOn.yaml
  tests/hr/_common.yaml
  tests/hr/climate_HassClimateGetTemperature.yaml
  tests/hr/climate_HassClimateSetTemperature.yaml
  tests/hr/cover_HassCloseCover.yaml
  tests/hr/cover_HassOpenCover.yaml
  tests/hr/fan_HassTurnOff.yaml
  tests/hr/fan_HassTurnOn.yaml
  tests/hr/homeassistant_HassTurnOff.yaml
  tests/hr/homeassistant_HassTurnOn.yaml
  tests/hr/light_HassLightSet.yaml
  tests/hr/light_HassTurnOff.yaml
  tests/hr/light_HassTurnOn.yaml
Labels: cla-signed, lang: hr

#52 Add empty Turkish templates (tr)
  responses/tr/HassClimateGetTemperature.yaml
  sentences/tr/_common.yaml
  sentences/tr/climate_HassClimateGetTemperature.yaml
  sentences/tr/climate_HassClimateSetTemperature.yaml
  sentences/tr/cover_HassCloseCover.yaml
  sentences/tr/cover_HassOpenCover.yaml
  sentences/tr/fan_HassTurnOff.yaml
  sentences/tr/fan_HassTurnOn.yaml
  sentences/tr/homeassistant_HassTurnOff.yaml
  sentences/tr/homeassistant_HassTurnOn.yaml
  sentences/tr/light_HassLightSet.yaml
  sentences/tr/light_HassTurnOff.yaml
  sentences/tr/light_HassTurnOn.yaml
  tests/tr/_common.yaml
  tests/tr/climate_HassClimateGetTemperature.yaml
  tests/tr/climate_HassClimateSetTemperature.yaml
  tests/tr/cover_HassCloseCover.yaml
  tests/tr/cover_HassOpenCover.yaml
  tests/tr/fan_HassTurnOff.yaml
  tests/tr/fan_HassTurnOn.yaml
  tests/tr/homeassistant_HassTurnOff.yaml
  tests/tr/homeassistant_HassTurnOn.yaml
  tests/tr/light_HassLightSet.yaml
  tests/tr/light_HassTurnOff.yaml
  tests/tr/light_HassTurnOn.yaml
Labels: cla-signed, lang: tr

#69 Add empty Urdu templates (ur)
  responses/ur/HassClimateGetTemperature.yaml
  sentences/ur/_common.yaml
  sentences/ur/climate_HassClimateGetTemperature.yaml
  sentences/ur/climate_HassClimateSetTemperature.yaml
  sentences/ur/cover_HassCloseCover.yaml
  sentences/ur/cover_HassOpenCover.yaml
  sentences/ur/fan_HassTurnOff.yaml
  sentences/ur/fan_HassTurnOn.yaml
  sentences/ur/homeassistant_HassTurnOff.yaml
  sentences/ur/homeassistant_HassTurnOn.yaml
  sentences/ur/light_HassLightSet.yaml
  sentences/ur/light_HassTurnOff.yaml
  sentences/ur/light_HassTurnOn.yaml
  tests/ur/_common.yaml
  tests/ur/climate_HassClimateGetTemperature.yaml
  tests/ur/climate_HassClimateSetTemperature.yaml
  tests/ur/cover_HassCloseCover.yaml
  tests/ur/cover_HassOpenCover.yaml
  tests/ur/fan_HassTurnOff.yaml
  tests/ur/fan_HassTurnOn.yaml
  tests/ur/homeassistant_HassTurnOff.yaml
  tests/ur/homeassistant_HassTurnOn.yaml
  tests/ur/light_HassLightSet.yaml
  tests/ur/light_HassTurnOff.yaml
  tests/ur/light_HassTurnOn.yaml
Labels: cla-signed, lang: ur

#59 Add empty Czech templates (cs)
  responses/cs/HassClimateGetTemperature.yaml
  sentences/cs/_common.yaml
  sentences/cs/climate_HassClimateGetTemperature.yaml
  sentences/cs/climate_HassClimateSetTemperature.yaml
  sentences/cs/cover_HassCloseCover.yaml
  sentences/cs/cover_HassOpenCover.yaml
  sentences/cs/fan_HassTurnOff.yaml
  sentences/cs/fan_HassTurnOn.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/light_HassLightSet.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/_common.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/climate_HassClimateSetTemperature.yaml
  tests/cs/cover_HassCloseCover.yaml
  tests/cs/cover_HassOpenCover.yaml
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
  tests/cs/homeassistant_HassTurnOff.yaml
  tests/cs/homeassistant_HassTurnOn.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#55 Initial Danish language support
  responses/dk/HassClimateGetTemperature.yaml
  sentences/dk/_common.yaml
  sentences/dk/climate_HassClimateGetTemperature.yaml
  sentences/dk/climate_HassClimateSetTemperature.yaml
  sentences/dk/cover_HassCloseCover.yaml
  sentences/dk/cover_HassOpenCover.yaml
  sentences/dk/fan_HassTurnOff.yaml
  sentences/dk/fan_HassTurnOn.yaml
  sentences/dk/homeassistant_HassTurnOff.yaml
  sentences/dk/homeassistant_HassTurnOn.yaml
  sentences/dk/light_HassLightSet.yaml
  sentences/dk/light_HassTurnOff.yaml
  sentences/dk/light_HassTurnOn.yaml
  tests/dk/_common.yaml
  tests/dk/climate_HassClimateGetTemperature.yaml
  tests/dk/climate_HassClimateSetTemperature.yaml
  tests/dk/cover_HassCloseCover.yaml
  tests/dk/cover_HassOpenCover.yaml
  tests/dk/fan_HassTurnOff.yaml
  tests/dk/fan_HassTurnOn.yaml
  tests/dk/homeassistant_HassTurnOff.yaml
  tests/dk/homeassistant_HassTurnOn.yaml
  tests/dk/light_HassLightSet.yaml
  tests/dk/light_HassTurnOff.yaml
  tests/dk/light_HassTurnOn.yaml
Labels: cla-signed, lang: dk

#56 Add french turn on/off lights sentences
  sentences/fr/_common.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/_common.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#60 add some Hungarian sentences for lights
  sentences/hu/_common.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  tests/hu/_common.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#70 Add empty Greek templates (el)
  responses/el/HassClimateGetTemperature.yaml
  sentences/el/_common.yaml
  sentences/el/climate_HassClimateGetTemperature.yaml
  sentences/el/climate_HassClimateSetTemperature.yaml
  sentences/el/cover_HassCloseCover.yaml
  sentences/el/cover_HassOpenCover.yaml
  sentences/el/fan_HassTurnOff.yaml
  sentences/el/fan_HassTurnOn.yaml
  sentences/el/homeassistant_HassTurnOff.yaml
  sentences/el/homeassistant_HassTurnOn.yaml
  sentences/el/light_HassLightSet.yaml
  sentences/el/light_HassTurnOff.yaml
  sentences/el/light_HassTurnOn.yaml
  tests/el/_common.yaml
  tests/el/climate_HassClimateGetTemperature.yaml
  tests/el/climate_HassClimateSetTemperature.yaml
  tests/el/cover_HassCloseCover.yaml
  tests/el/cover_HassOpenCover.yaml
  tests/el/fan_HassTurnOff.yaml
  tests/el/fan_HassTurnOn.yaml
  tests/el/homeassistant_HassTurnOff.yaml
  tests/el/homeassistant_HassTurnOn.yaml
  tests/el/light_HassLightSet.yaml
  tests/el/light_HassTurnOff.yaml
  tests/el/light_HassTurnOn.yaml
Labels: cla-signed, lang: el

#71 Add empty Italian templates (it)
  responses/it/HassClimateGetTemperature.yaml
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateGetTemperature.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
  sentences/it/cover_HassCloseCover.yaml
  sentences/it/cover_HassOpenCover.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/light_HassLightSet.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  tests/it/_common.yaml
  tests/it/climate_HassClimateGetTemperature.yaml
  tests/it/climate_HassClimateSetTemperature.yaml
  tests/it/cover_HassCloseCover.yaml
  tests/it/cover_HassOpenCover.yaml
  tests/it/fan_HassTurnOff.yaml
  tests/it/fan_HassTurnOn.yaml
  tests/it/homeassistant_HassTurnOff.yaml
  tests/it/homeassistant_HassTurnOn.yaml
  tests/it/light_HassLightSet.yaml
  tests/it/light_HassTurnOff.yaml
  tests/it/light_HassTurnOn.yaml
Labels: cla-signed, lang: it

#63 Add Polish response, sentences and tests
  responses/pl/HassClimateGetTemperature.yaml
  sentences/pl/_common.yaml
  sentences/pl/climate_HassClimateGetTemperature.yaml
  sentences/pl/climate_HassClimateSetTemperature.yaml
  sentences/pl/cover_HassCloseCover.yaml
  sentences/pl/cover_HassOpenCover.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/homeassistant_HassTurnOff.yaml
  sentences/pl/homeassistant_HassTurnOn.yaml
  sentences/pl/light_HassLightSet.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  tests/pl/_common.yaml
  tests/pl/climate_HassClimateGetTemperature.yaml
  tests/pl/climate_HassClimateSetTemperature.yaml
  tests/pl/cover_HassCloseCover.yaml
  tests/pl/cover_HassOpenCover.yaml
  tests/pl/fan_HassTurnOff.yaml
  tests/pl/fan_HassTurnOn.yaml
  tests/pl/homeassistant_HassTurnOff.yaml
  tests/pl/homeassistant_HassTurnOn.yaml
  tests/pl/light_HassLightSet.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
Labels: cla-signed, lang: pl, cla-error

#75 Add empty Serbian templates (sr)
  responses/sr/HassClimateGetTemperature.yaml
  sentences/sr/_common.yaml
  sentences/sr/climate_HassClimateGetTemperature.yaml
  sentences/sr/climate_HassClimateSetTemperature.yaml
  sentences/sr/cover_HassCloseCover.yaml
  sentences/sr/cover_HassOpenCover.yaml
  sentences/sr/fan_HassTurnOff.yaml
  sentences/sr/fan_HassTurnOn.yaml
  sentences/sr/homeassistant_HassTurnOff.yaml
  sentences/sr/homeassistant_HassTurnOn.yaml
  sentences/sr/light_HassLightSet.yaml
  sentences/sr/light_HassTurnOff.yaml
  sentences/sr/light_HassTurnOn.yaml
  tests/sr/_common.yaml
  tests/sr/climate_HassClimateGetTemperature.yaml
  tests/sr/climate_HassClimateSetTemperature.yaml
  tests/sr/cover_HassCloseCover.yaml
  tests/sr/cover_HassOpenCover.yaml
  tests/sr/fan_HassTurnOff.yaml
  tests/sr/fan_HassTurnOn.yaml
  tests/sr/homeassistant_HassTurnOff.yaml
  tests/sr/homeassistant_HassTurnOn.yaml
  tests/sr/light_HassLightSet.yaml
  tests/sr/light_HassTurnOff.yaml
  tests/sr/light_HassTurnOn.yaml
Labels: cla-signed, lang: sr

#78 Add intentfest sample and sample_template commands
  CONTRIBUTING.md
  README.md
  intents.yaml
  requirements.txt
  responses/README.md
  script/intentfest/sample.py
  script/intentfest/sample_template.py
  script/intentfest/util.py
  sentences/README.md
  tests/README.md
Labels: cla-signed

#79 Cleanup fixtures
  CONTRIBUTING.md
  script/intentfest/add_language.py
  script/intentfest/parse.py
  script/intentfest/sample.py
  script/intentfest/validate.py
  tests/README.md
  tests/ca/_common.yaml
  tests/ca/_fixtures.yaml
  tests/cs/_common.yaml
  tests/cs/_fixtures.yaml
  tests/de/_fixtures.yaml
  tests/dk/_common.yaml
  tests/dk/_fixtures.yaml
  tests/el/_common.yaml
  tests/el/_fixtures.yaml
  tests/en/_fixtures.yaml
  tests/es/_common.yaml
  tests/es/_fixtures.yaml
  tests/fr/_fixtures.yaml
  tests/hr/_common.yaml
  tests/hr/_fixtures.yaml
  tests/hu/_common.yaml
  tests/hu/_fixtures.yaml
  tests/it/_common.yaml
  tests/it/_fixtures.yaml
  tests/nb/_common.yaml
  tests/nb/_fixtures.yaml
  tests/nl/_fixtures.yaml
  tests/pl/_fixtures.yaml
  tests/sl/_common.yaml
  tests/sl/_fixtures.yaml
  tests/sr/_common.yaml
  tests/sr/_fixtures.yaml
  tests/sv/_common.yaml
  tests/sv/_fixtures.yaml
  tests/tr/_common.yaml
  tests/tr/_fixtures.yaml
  tests/ur/_common.yaml
  tests/ur/_fixtures.yaml
Labels: cla-signed, lang: de, lang: en, lang: nb, lang: nl, lang: fr, lang: hu, lang: pl, lang: sl, lang: ca, lang: es, lang: hr, lang: dk, lang: cs, lang: el, lang: it, lang: sr

#84 Fix a typo in the Polish common sentences
  sentences/pl/_common.yaml
Labels: cla-signed, lang: pl

#73 Add .vscode to .gitignore
  .gitignore
Labels: cla-signed

#64 Add Dutch sentences to set lights
  sentences/nl/_common.yaml
  sentences/nl/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: nl

#89 Add docs for workflows
  CONTRIBUTING.md
  docs/codespace/README.md
  docs/codespace/branch_button.jpg
  docs/codespace/branch_name.jpg
  docs/codespace/commit_message.jpg
  docs/codespace/commit_pull_request.jpg
  docs/codespace/create_branch.jpg
  docs/codespace/create_codespace.jpg
  docs/codespace/create_pull_request.jpg
  docs/codespace/editor.jpg
  docs/codespace/run_task.jpg
  docs/codespace/run_tests.jpg
  docs/codespace/test_success.jpg
  docs/forking/README.md
  docs/github/README.md
  docs/github/create_branch.jpg
  docs/github/edit_button.jpg
Labels: cla-signed

#90 Update _fixtures.yaml
  tests/sl/_fixtures.yaml
Labels: cla-signed, lang: sl

#94 Add Slovak language
  responses/sk/HassClimateGetTemperature.yaml
  sentences/sk/_common.yaml
  sentences/sk/climate_HassClimateGetTemperature.yaml
  sentences/sk/climate_HassClimateSetTemperature.yaml
  sentences/sk/cover_HassCloseCover.yaml
  sentences/sk/cover_HassOpenCover.yaml
  sentences/sk/fan_HassTurnOff.yaml
  sentences/sk/fan_HassTurnOn.yaml
  sentences/sk/homeassistant_HassTurnOff.yaml
  sentences/sk/homeassistant_HassTurnOn.yaml
  sentences/sk/light_HassLightSet.yaml
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
  tests/sk/_fixtures.yaml
  tests/sk/climate_HassClimateGetTemperature.yaml
  tests/sk/climate_HassClimateSetTemperature.yaml
  tests/sk/cover_HassCloseCover.yaml
  tests/sk/cover_HassOpenCover.yaml
  tests/sk/fan_HassTurnOff.yaml
  tests/sk/fan_HassTurnOn.yaml
  tests/sk/homeassistant_HassTurnOff.yaml
  tests/sk/homeassistant_HassTurnOn.yaml
  tests/sk/light_HassLightSet.yaml
  tests/sk/light_HassTurnOff.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#92 Review of #42 with a few code changes and added some tests
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/cover_HassCloseCover.yaml
  sentences/de/cover_HassOpenCover.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/_fixtures.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateSetTemperature.yaml
  tests/de/cover_HassCloseCover.yaml
  tests/de/cover_HassOpenCover.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
  tests/de/light_HassLightSet.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#80 Added some new sentences and tests for EN US
  sentences/en/climate_HassClimateGetTemperature.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
  sentences/en/cover_HassCloseCover.yaml
  sentences/en/cover_HassOpenCover.yaml
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/fan_HassTurnOn.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateSetTemperature.yaml
  tests/en/cover_HassCloseCover.yaml
  tests/en/cover_HassOpenCover.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#97 add hot/cold to English
  sentences/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: en

#99 Use better fixture name for cover
  tests/en/_fixtures.yaml
  tests/en/cover_HassCloseCover.yaml
  tests/en/cover_HassOpenCover.yaml
  tests/nl/_fixtures.yaml
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
Labels: cla-signed, lang: en, lang: nl

#86 Added Slovak "sk" language
  sentences/sk/_common.yaml
Labels: cla-signed, lang: sk

#96 [NL] Add Dutch color change sentences
  sentences/nl/_common.yaml
  sentences/nl/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: nl

#101 Add empty Vietnamese sentences
  responses/vi/HassClimateGetTemperature.yaml
  sentences/vi/_common.yaml
  sentences/vi/climate_HassClimateGetTemperature.yaml
  sentences/vi/climate_HassClimateSetTemperature.yaml
  sentences/vi/cover_HassCloseCover.yaml
  sentences/vi/cover_HassOpenCover.yaml
  sentences/vi/fan_HassTurnOff.yaml
  sentences/vi/fan_HassTurnOn.yaml
  sentences/vi/homeassistant_HassTurnOff.yaml
  sentences/vi/homeassistant_HassTurnOn.yaml
  sentences/vi/light_HassLightSet.yaml
  sentences/vi/light_HassTurnOff.yaml
  sentences/vi/light_HassTurnOn.yaml
  tests/vi/_fixtures.yaml
  tests/vi/climate_HassClimateGetTemperature.yaml
  tests/vi/climate_HassClimateSetTemperature.yaml
  tests/vi/cover_HassCloseCover.yaml
  tests/vi/cover_HassOpenCover.yaml
  tests/vi/fan_HassTurnOff.yaml
  tests/vi/fan_HassTurnOn.yaml
  tests/vi/homeassistant_HassTurnOff.yaml
  tests/vi/homeassistant_HassTurnOn.yaml
  tests/vi/light_HassLightSet.yaml
  tests/vi/light_HassTurnOff.yaml
  tests/vi/light_HassTurnOn.yaml
Labels: cla-signed, lang: vi

#102 [NL] Merge doe_enkelvoud and doe_meervoud
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: nl

#105 [DE] use native languag for expansion rules
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/cover_HassCloseCover.yaml
  sentences/de/cover_HassOpenCover.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#95 [NL] Add some Dutch sentences for climate
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#106 Update Slovenian errors
  sentences/sl/_common.yaml
Labels: cla-signed, lang: sl

#109 Added up/down sentences+tests for covers
  sentences/de/_common.yaml
  sentences/de/cover_HassCloseCover.yaml
  sentences/de/cover_HassOpenCover.yaml
  tests/de/cover_HassCloseCover.yaml
  tests/de/cover_HassOpenCover.yaml
Labels: cla-signed, lang: de

#110 Template syntax guide
  README.md
  docs/README.md
  docs/templates.md
Labels: cla-signed

#83 Updated Hungarian
  responses/hu/HassClimateGetTemperature.yaml
  sentences/hu/_common.yaml
  sentences/hu/climate_HassClimateGetTemperature.yaml
  sentences/hu/climate_HassClimateSetTemperature.yaml
  sentences/hu/cover_HassCloseCover.yaml
  sentences/hu/cover_HassOpenCover.yaml
  sentences/hu/fan_HassTurnOff.yaml
  sentences/hu/fan_HassTurnOn.yaml
  sentences/hu/homeassistant_HassTurnOff.yaml
  sentences/hu/homeassistant_HassTurnOn.yaml
  sentences/hu/light_HassLightSet.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  tests/hu/_fixtures.yaml
  tests/hu/climate_HassClimateGetTemperature.yaml
  tests/hu/climate_HassClimateSetTemperature.yaml
  tests/hu/cover_HassCloseCover.yaml
  tests/hu/cover_HassOpenCover.yaml
  tests/hu/fan_HassTurnOff.yaml
  tests/hu/fan_HassTurnOn.yaml
  tests/hu/homeassistant_HassTurnOff.yaml
  tests/hu/homeassistant_HassTurnOn.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#114 Add empty Romanian templates (ro)
  responses/ro/HassClimateGetTemperature.yaml
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
  sentences/ro/cover_HassCloseCover.yaml
  sentences/ro/cover_HassOpenCover.yaml
  sentences/ro/fan_HassTurnOff.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassLightSet.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/climate_HassClimateSetTemperature.yaml
  tests/ro/cover_HassCloseCover.yaml
  tests/ro/cover_HassOpenCover.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#115 Add empty Arabic templates (ar)
  responses/ar/HassClimateGetTemperature.yaml
  sentences/ar/_common.yaml
  sentences/ar/climate_HassClimateGetTemperature.yaml
  sentences/ar/climate_HassClimateSetTemperature.yaml
  sentences/ar/cover_HassCloseCover.yaml
  sentences/ar/cover_HassOpenCover.yaml
  sentences/ar/fan_HassTurnOff.yaml
  sentences/ar/fan_HassTurnOn.yaml
  sentences/ar/homeassistant_HassTurnOff.yaml
  sentences/ar/homeassistant_HassTurnOn.yaml
  sentences/ar/light_HassLightSet.yaml
  sentences/ar/light_HassTurnOff.yaml
  sentences/ar/light_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/climate_HassClimateGetTemperature.yaml
  tests/ar/climate_HassClimateSetTemperature.yaml
  tests/ar/cover_HassCloseCover.yaml
  tests/ar/cover_HassOpenCover.yaml
  tests/ar/fan_HassTurnOff.yaml
  tests/ar/fan_HassTurnOn.yaml
  tests/ar/homeassistant_HassTurnOff.yaml
  tests/ar/homeassistant_HassTurnOn.yaml
  tests/ar/light_HassLightSet.yaml
  tests/ar/light_HassTurnOff.yaml
  tests/ar/light_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#117 [de] Added one more sentence to get temperature
  sentences/de/climate_HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: de

#118 Add empty Portugese sentences
  responses/pt/HassClimateGetTemperature.yaml
  sentences/pt/_common.yaml
  sentences/pt/climate_HassClimateGetTemperature.yaml
  sentences/pt/climate_HassClimateSetTemperature.yaml
  sentences/pt/cover_HassCloseCover.yaml
  sentences/pt/cover_HassOpenCover.yaml
  sentences/pt/fan_HassTurnOff.yaml
  sentences/pt/fan_HassTurnOn.yaml
  sentences/pt/homeassistant_HassTurnOff.yaml
  sentences/pt/homeassistant_HassTurnOn.yaml
  sentences/pt/light_HassLightSet.yaml
  sentences/pt/light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOn.yaml
  tests/pt/_fixtures.yaml
  tests/pt/climate_HassClimateGetTemperature.yaml
  tests/pt/climate_HassClimateSetTemperature.yaml
  tests/pt/cover_HassCloseCover.yaml
  tests/pt/cover_HassOpenCover.yaml
  tests/pt/fan_HassTurnOff.yaml
  tests/pt/fan_HassTurnOn.yaml
  tests/pt/homeassistant_HassTurnOff.yaml
  tests/pt/homeassistant_HassTurnOn.yaml
  tests/pt/light_HassLightSet.yaml
  tests/pt/light_HassTurnOff.yaml
  tests/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#122 Make sure HU outputs English color names
  sentences/hu/_common.yaml
  tests/hu/light_HassLightSet.yaml
Labels: cla-signed, lang: hu

#123 ADD Hebrew leader
  CODEOWNERS
  README.md
Labels: cla-signed

#125 [NL] Remove duplicate sentences
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#121 Make sure SV outputs English color names
  sentences/sv/_common.yaml
Labels: cla-signed, lang: sv

#120 Make sure NB outputs English color names
  sentences/nb/_common.yaml
Labels: cla-signed, lang: nb

#119 Validate color names are outputted in English
  script/intentfest/validate.py
Labels: cla-signed

#103 [NL] Add sentences to turn fans on and off
  sentences/nl/_common.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#129 Fine tuning hu
  sentences/hu/_common.yaml
  sentences/hu/climate_HassClimateGetTemperature.yaml
  sentences/hu/climate_HassClimateSetTemperature.yaml
  sentences/hu/fan_HassTurnOff.yaml
  sentences/hu/fan_HassTurnOn.yaml
  sentences/hu/homeassistant_HassTurnOff.yaml
  sentences/hu/homeassistant_HassTurnOn.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  tests/hu/_fixtures.yaml
Labels: cla-signed, lang: hu

#128 Refactor tests to move some from validate to tests
  script/intentfest/validate.py
  tests/__init__.py
  tests/conftest.py
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#130 Make validation more strict
  script/intentfest/validate.py
  tests/__init__.py
  tests/test_language_sentences.py
Labels: cla-signed

#81 Add Urdu language
  responses/ur/HassClimateGetTemperature.yaml
  sentences/en/_common.yaml
  sentences/ur/_common.yaml
  sentences/ur/climate_HassClimateGetTemperature.yaml
  sentences/ur/climate_HassClimateSetTemperature.yaml
  sentences/ur/cover_HassCloseCover.yaml
  sentences/ur/cover_HassOpenCover.yaml
  sentences/ur/fan_HassTurnOff.yaml
  sentences/ur/fan_HassTurnOn.yaml
  sentences/ur/homeassistant_HassTurnOff.yaml
  sentences/ur/homeassistant_HassTurnOn.yaml
  sentences/ur/light_HassLightSet.yaml
  sentences/ur/light_HassTurnOff.yaml
  sentences/ur/light_HassTurnOn.yaml
  tests/ur/_fixtures.yaml
  tests/ur/climate_HassClimateGetTemperature.yaml
  tests/ur/climate_HassClimateSetTemperature.yaml
  tests/ur/cover_HassCloseCover.yaml
  tests/ur/cover_HassOpenCover.yaml
  tests/ur/fan_HassTurnOff.yaml
  tests/ur/fan_HassTurnOn.yaml
  tests/ur/homeassistant_HassTurnOff.yaml
  tests/ur/homeassistant_HassTurnOn.yaml
  tests/ur/light_HassLightSet.yaml
  tests/ur/light_HassTurnOff.yaml
  tests/ur/light_HassTurnOn.yaml
Labels: cla-signed, lang: en, lang: ur

#32 Adding initial Hebrew support for sentences.
  CODEOWNERS
  README.md
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  sentences/he/climate_HassClimateSetTemperature.yaml
  sentences/he/cover_HassCloseCover.yaml
  sentences/he/cover_HassOpenCover.yaml
  sentences/he/fan_HassTurnOff.yaml
  sentences/he/fan_HassTurnOn.yaml
  sentences/he/homeassistant_HassTurnOff.yaml
  sentences/he/homeassistant_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  sentences/he/light_HassTurnOff.yaml
  sentences/he/light_HassTurnOn.yaml
Labels: cla-signed, lang: he

#133 [DE] Minor adjustments
  sentences/de/_common.yaml
Labels: cla-signed, lang: de

#131 Split language intents tests by file
  README.md
  script/intentfest/validate.py
  tests/__init__.py
  tests/conftest.py
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#140 Add more types to tests
  tests/__init__.py
  tests/conftest.py
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#149 fix wrong language in area
  tests/en/_fixtures.yaml
Labels: cla-signed, lang: en

#144 [UK] Added Ukrainian language
  responses/uk/HassClimateGetTemperature.yaml
  sentences/uk/_common.yaml
  sentences/uk/climate_HassClimateGetTemperature.yaml
  sentences/uk/climate_HassClimateSetTemperature.yaml
  sentences/uk/cover_HassCloseCover.yaml
  sentences/uk/cover_HassOpenCover.yaml
  sentences/uk/fan_HassTurnOff.yaml
  sentences/uk/fan_HassTurnOn.yaml
  sentences/uk/homeassistant_HassTurnOff.yaml
  sentences/uk/homeassistant_HassTurnOn.yaml
  sentences/uk/light_HassLightSet.yaml
  sentences/uk/light_HassTurnOff.yaml
  sentences/uk/light_HassTurnOn.yaml
  tests/uk/_fixtures.yaml
  tests/uk/climate_HassClimateGetTemperature.yaml
  tests/uk/climate_HassClimateSetTemperature.yaml
  tests/uk/cover_HassCloseCover.yaml
  tests/uk/cover_HassOpenCover.yaml
  tests/uk/fan_HassTurnOff.yaml
  tests/uk/fan_HassTurnOn.yaml
  tests/uk/homeassistant_HassTurnOff.yaml
  tests/uk/homeassistant_HassTurnOn.yaml
  tests/uk/light_HassLightSet.yaml
  tests/uk/light_HassTurnOff.yaml
  tests/uk/light_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#146 [EL] Minor refinements
  responses/el/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: el

#126 [ES] Initial spanish language support
  responses/es/HassClimateGetTemperature.yaml
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  sentences/es/climate_HassClimateSetTemperature.yaml
  sentences/es/cover_HassCloseCover.yaml
  sentences/es/cover_HassOpenCover.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
  tests/es/cover_HassCloseCover.yaml
  tests/es/cover_HassOpenCover.yaml
  tests/es/fan_HassTurnOff.yaml
  tests/es/fan_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#152 Make test output slightly more readable if slot missing
  tests/test_language_sentences.py
Labels: cla-signed

#151 Add VSCode task to test current file or language
  .vscode/tasks.json
  docs/codespace/README.md
  script/test_file
Labels: cla-signed

#154 [HE] Added Hebrew language
  CODEOWNERS
  README.md
  responses/he/HassClimateGetTemperature.yaml
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  sentences/he/climate_HassClimateSetTemperature.yaml
  sentences/he/cover_HassCloseCover.yaml
  sentences/he/cover_HassOpenCover.yaml
  sentences/he/fan_HassTurnOff.yaml
  sentences/he/fan_HassTurnOn.yaml
  sentences/he/homeassistant_HassTurnOff.yaml
  sentences/he/homeassistant_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  sentences/he/light_HassTurnOff.yaml
  sentences/he/light_HassTurnOn.yaml
  tests/he/_fixtures.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
  tests/he/climate_HassClimateSetTemperature.yaml
  tests/he/cover_HassCloseCover.yaml
  tests/he/cover_HassOpenCover.yaml
  tests/he/fan_HassTurnOff.yaml
  tests/he/fan_HassTurnOn.yaml
  tests/he/homeassistant_HassTurnOff.yaml
  tests/he/homeassistant_HassTurnOn.yaml
  tests/he/light_HassLightSet.yaml
  tests/he/light_HassTurnOff.yaml
  tests/he/light_HassTurnOn.yaml
Labels: cla-signed, lang: he

#162 First Portugese translations
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassTurnOff.yaml
  sentences/pt/homeassistant_HassTurnOn.yaml
  tests/pt/homeassistant_HassTurnOff.yaml
  tests/pt/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#156 [SR] add errors responses
  sentences/sr/_common.yaml
Labels: cla-signed, lang: sr

#159 [ES] commons yaml fixes in spanish
  sentences/es/_common.yaml
Labels: cla-signed, lang: ca, lang: es

#111 [CA] Initial Catalan language support
  responses/ca/HassClimateGetTemperature.yaml
  sentences/ca/_common.yaml
  sentences/ca/climate_HassClimateGetTemperature.yaml
  sentences/ca/climate_HassClimateSetTemperature.yaml
  sentences/ca/cover_HassCloseCover.yaml
  sentences/ca/cover_HassOpenCover.yaml
  sentences/ca/fan_HassTurnOff.yaml
  sentences/ca/fan_HassTurnOn.yaml
  sentences/ca/homeassistant_HassTurnOff.yaml
  sentences/ca/homeassistant_HassTurnOn.yaml
  sentences/ca/light_HassLightSet.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  tests/ca/_fixtures.yaml
  tests/ca/climate_HassClimateGetTemperature.yaml
  tests/ca/climate_HassClimateSetTemperature.yaml
  tests/ca/cover_HassCloseCover.yaml
  tests/ca/cover_HassOpenCover.yaml
  tests/ca/fan_HassTurnOff.yaml
  tests/ca/fan_HassTurnOn.yaml
  tests/ca/homeassistant_HassTurnOff.yaml
  tests/ca/homeassistant_HassTurnOn.yaml
  tests/ca/light_HassLightSet.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#165 Validate area ids correct
  script/intentfest/validate.py
  tests/pl/_fixtures.yaml
  tests/pl/cover_HassCloseCover.yaml
  tests/pl/cover_HassOpenCover.yaml
Labels: cla-signed, lang: pl

#158 [uk]Added fan intents to Ukrainian language
  sentences/uk/fan_HassTurnOff.yaml
  sentences/uk/fan_HassTurnOn.yaml
  tests/uk/_fixtures.yaml
  tests/uk/fan_HassTurnOff.yaml
  tests/uk/fan_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#166 Validate to guard no question marks added to sentences
  script/intentfest/validate.py
Labels: cla-signed

#168 [SR] Light sentences
  sentences/sr/_common.yaml
  sentences/sr/light_HassLightSet.yaml
  sentences/sr/light_HassTurnOff.yaml
  sentences/sr/light_HassTurnOn.yaml
  tests/sr/_fixtures.yaml
  tests/sr/light_HassLightSet.yaml
  tests/sr/light_HassTurnOff.yaml
  tests/sr/light_HassTurnOn.yaml
Labels: cla-signed, lang: sr

#169 [PT] Added Portuguese sentences
  intents.yaml
  responses/pt/HassClimateGetTemperature.yaml
  sentences/pt/_common.yaml
  sentences/pt/climate_HassClimateGetTemperature.yaml
  sentences/pt/climate_HassClimateSetTemperature.yaml
  sentences/pt/cover_HassCloseCover.yaml
  sentences/pt/cover_HassOpenCover.yaml
  sentences/pt/fan_HassTurnOff.yaml
  sentences/pt/fan_HassTurnOn.yaml
  sentences/pt/homeassistant_HassTurnOff.yaml
  sentences/pt/homeassistant_HassTurnOn.yaml
  sentences/pt/light_HassLightSet.yaml
  sentences/pt/light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOn.yaml
  tests/pt/_fixtures.yaml
  tests/pt/climate_HassClimateGetTemperature.yaml
  tests/pt/climate_HassClimateSetTemperature.yaml
  tests/pt/cover_HassCloseCover.yaml
  tests/pt/cover_HassOpenCover.yaml
  tests/pt/fan_HassTurnOff.yaml
  tests/pt/fan_HassTurnOn.yaml
  tests/pt/homeassistant_HassTurnOff.yaml
  tests/pt/homeassistant_HassTurnOn.yaml
  tests/pt/light_HassLightSet.yaml
  tests/pt/light_HassTurnOff.yaml
  tests/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#172 Fix command to add new language
  docs/forking/README.md
Labels: cla-signed

#170 [ES] More color options
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#173 Rename Danish from DK to DA
  responses/da/HassClimateGetTemperature.yaml
  sentences/da/_common.yaml
  sentences/da/climate_HassClimateGetTemperature.yaml
  sentences/da/climate_HassClimateSetTemperature.yaml
  sentences/da/cover_HassCloseCover.yaml
  sentences/da/cover_HassOpenCover.yaml
  sentences/da/fan_HassTurnOff.yaml
  sentences/da/fan_HassTurnOn.yaml
  sentences/da/homeassistant_HassTurnOff.yaml
  sentences/da/homeassistant_HassTurnOn.yaml
  sentences/da/light_HassLightSet.yaml
  sentences/da/light_HassTurnOff.yaml
  sentences/da/light_HassTurnOn.yaml
  sentences/dk/fan_HassTurnOff.yaml
  sentences/dk/fan_HassTurnOn.yaml
  sentences/dk/light_HassTurnOff.yaml
  sentences/dk/light_HassTurnOn.yaml
  tests/da/_fixtures.yaml
  tests/da/climate_HassClimateGetTemperature.yaml
  tests/da/climate_HassClimateSetTemperature.yaml
  tests/da/cover_HassCloseCover.yaml
  tests/da/cover_HassOpenCover.yaml
  tests/da/fan_HassTurnOff.yaml
  tests/da/fan_HassTurnOn.yaml
  tests/da/homeassistant_HassTurnOff.yaml
  tests/da/homeassistant_HassTurnOn.yaml
  tests/da/light_HassLightSet.yaml
  tests/da/light_HassTurnOff.yaml
  tests/da/light_HassTurnOn.yaml
  tests/dk/climate_HassClimateGetTemperature.yaml
  tests/dk/climate_HassClimateSetTemperature.yaml
  tests/dk/cover_HassCloseCover.yaml
  tests/dk/cover_HassOpenCover.yaml
  tests/dk/fan_HassTurnOff.yaml
  tests/dk/fan_HassTurnOn.yaml
  tests/dk/homeassistant_HassTurnOff.yaml
  tests/dk/homeassistant_HassTurnOn.yaml
  tests/dk/light_HassLightSet.yaml
  tests/dk/light_HassTurnOff.yaml
  tests/dk/light_HassTurnOn.yaml
Labels: cla-signed, lang: dk, lang: da

#176 Add languages yaml
  .github/workflows/ci.yaml
  CONTRIBUTING.md
  README.md
  docs/forking/README.md
  languages.yaml
  script/intentfest/add_language.py
  script/intentfest/const.py
  script/intentfest/validate.py
Labels: cla-signed

#175 [RU] Add russian language support
  README.md
  responses/ru/HassClimateGetTemperature.yaml
  sentences/ru/_common.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateSetTemperature.yaml
  sentences/ru/cover_HassCloseCover.yaml
  sentences/ru/cover_HassOpenCover.yaml
  sentences/ru/fan_HassTurnOff.yaml
  sentences/ru/fan_HassTurnOn.yaml
  sentences/ru/homeassistant_HassTurnOff.yaml
  sentences/ru/homeassistant_HassTurnOn.yaml
  sentences/ru/light_HassLightSet.yaml
  sentences/ru/light_HassTurnOff.yaml
  sentences/ru/light_HassTurnOn.yaml
  tests/ru/_fixtures.yaml
  tests/ru/climate_HassClimateGetTemperature.yaml
  tests/ru/climate_HassClimateSetTemperature.yaml
  tests/ru/cover_HassCloseCover.yaml
  tests/ru/cover_HassOpenCover.yaml
  tests/ru/fan_HassTurnOff.yaml
  tests/ru/fan_HassTurnOn.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
  tests/ru/light_HassLightSet.yaml
  tests/ru/light_HassTurnOff.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#177 Add Russian language leader
  CODEOWNERS
  README.md
  languages.yaml
Labels: cla-signed

#178 Add empty Chinese (zh) templates
  languages.yaml
  responses/zh/HassClimateGetTemperature.yaml
  sentences/zh/_common.yaml
  sentences/zh/climate_HassClimateGetTemperature.yaml
  sentences/zh/climate_HassClimateSetTemperature.yaml
  sentences/zh/cover_HassCloseCover.yaml
  sentences/zh/cover_HassOpenCover.yaml
  sentences/zh/fan_HassTurnOff.yaml
  sentences/zh/fan_HassTurnOn.yaml
  sentences/zh/homeassistant_HassTurnOff.yaml
  sentences/zh/homeassistant_HassTurnOn.yaml
  sentences/zh/light_HassLightSet.yaml
  sentences/zh/light_HassTurnOff.yaml
  sentences/zh/light_HassTurnOn.yaml
  tests/zh/_fixtures.yaml
  tests/zh/climate_HassClimateGetTemperature.yaml
  tests/zh/climate_HassClimateSetTemperature.yaml
  tests/zh/cover_HassCloseCover.yaml
  tests/zh/cover_HassOpenCover.yaml
  tests/zh/fan_HassTurnOff.yaml
  tests/zh/fan_HassTurnOn.yaml
  tests/zh/homeassistant_HassTurnOff.yaml
  tests/zh/homeassistant_HassTurnOn.yaml
  tests/zh/light_HassLightSet.yaml
  tests/zh/light_HassTurnOff.yaml
  tests/zh/light_HassTurnOn.yaml
Labels: cla-signed, lang: zh

#179 Add apostrophe to valid sentence characters
  script/intentfest/validate.py
Labels: cla-signed

#180 Add domain to intents
  intents.yaml
  script/intentfest/validate.py
  script/test_file
Labels: cla-signed

#181 Add website
  .github/workflows/gh-pages.yml
  .gitignore
  script/intentfest/util.py
  script/intentfest/website_summary.py
  website/.eleventy.js
  website/.gitignore
  website/.nvmrc
  website/package-lock.json
  website/package.json
  website/public/style.css
  website/script/build
  website/script/develop
  website/src-11ty/_data/intentSummary.json
  website/src-11ty/_includes/base.html
  website/src-11ty/index.html
Labels: cla-signed

#174 Add Urdu Language leader
  CODEOWNERS
  README.md
Labels: cla-signed

#183 [NL] Update cover sentences
  sentences/nl/cover_HassCloseCover.yaml
  sentences/nl/cover_HassOpenCover.yaml
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/cover_HassOpenCover.yaml
Labels: cla-signed, lang: nl

#186 [PT] New skip_word and error message "no_entity" tweak
  sentences/pt/_common.yaml
Labels: cla-signed, lang: pt

#193 [PT] Correcting orthographic error
  tests/pt/_fixtures.yaml
  tests/pt/cover_HassCloseCover.yaml
  tests/pt/cover_HassOpenCover.yaml
Labels: cla-signed, lang: pt

#192 Fixed PR #145
  tests/sv/_fixtures.yaml
  tests/sv/fan_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#157 [IT] Italian Support
  CODEOWNERS
  README.md
  responses/it/HassClimateGetTemperature.yaml
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateGetTemperature.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
  sentences/it/cover_HassCloseCover.yaml
  sentences/it/cover_HassOpenCover.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/light_HassLightSet.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  tests/it/_fixtures.yaml
  tests/it/climate_HassClimateGetTemperature.yaml
  tests/it/climate_HassClimateSetTemperature.yaml
  tests/it/cover_HassCloseCover.yaml
  tests/it/cover_HassOpenCover.yaml
  tests/it/fan_HassTurnOff.yaml
  tests/it/fan_HassTurnOn.yaml
  tests/it/homeassistant_HassTurnOff.yaml
  tests/it/homeassistant_HassTurnOn.yaml
  tests/it/light_HassLightSet.yaml
  tests/it/light_HassTurnOff.yaml
  tests/it/light_HassTurnOn.yaml
Labels: cla-signed, lang: it

#195 Add empty Kannada (ka) templates
  languages.yaml
  responses/ka/HassClimateGetTemperature.yaml
  sentences/ka/_common.yaml
  sentences/ka/climate_HassClimateGetTemperature.yaml
  sentences/ka/climate_HassClimateSetTemperature.yaml
  sentences/ka/cover_HassCloseCover.yaml
  sentences/ka/cover_HassOpenCover.yaml
  sentences/ka/fan_HassTurnOff.yaml
  sentences/ka/fan_HassTurnOn.yaml
  sentences/ka/homeassistant_HassTurnOff.yaml
  sentences/ka/homeassistant_HassTurnOn.yaml
  sentences/ka/light_HassLightSet.yaml
  sentences/ka/light_HassTurnOff.yaml
  sentences/ka/light_HassTurnOn.yaml
  tests/ka/_fixtures.yaml
  tests/ka/climate_HassClimateGetTemperature.yaml
  tests/ka/climate_HassClimateSetTemperature.yaml
  tests/ka/cover_HassCloseCover.yaml
  tests/ka/cover_HassOpenCover.yaml
  tests/ka/fan_HassTurnOff.yaml
  tests/ka/fan_HassTurnOn.yaml
  tests/ka/homeassistant_HassTurnOff.yaml
  tests/ka/homeassistant_HassTurnOn.yaml
  tests/ka/light_HassLightSet.yaml
  tests/ka/light_HassTurnOff.yaml
  tests/ka/light_HassTurnOn.yaml
Labels: cla-signed, lang: ka

#196 Add script to generate language table
  README.md
  languages.yaml
  script/intentfest/const.py
  script/intentfest/language_table.py
  script/intentfest/util.py
Labels: cla-signed

#190 [uk]Added climate intents
  CODEOWNERS
  README.md
  languages.yaml
  sentences/uk/_common.yaml
  sentences/uk/climate_HassClimateGetTemperature.yaml
  sentences/uk/climate_HassClimateSetTemperature.yaml
  tests/uk/climate_HassClimateGetTemperature.yaml
  tests/uk/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: uk

#197 Add empty Bulgarian (bg) templates
  languages.yaml
  responses/bg/HassClimateGetTemperature.yaml
  sentences/bg/_common.yaml
  sentences/bg/climate_HassClimateGetTemperature.yaml
  sentences/bg/climate_HassClimateSetTemperature.yaml
  sentences/bg/cover_HassCloseCover.yaml
  sentences/bg/cover_HassOpenCover.yaml
  sentences/bg/fan_HassTurnOff.yaml
  sentences/bg/fan_HassTurnOn.yaml
  sentences/bg/homeassistant_HassTurnOff.yaml
  sentences/bg/homeassistant_HassTurnOn.yaml
  sentences/bg/light_HassLightSet.yaml
  sentences/bg/light_HassTurnOff.yaml
  sentences/bg/light_HassTurnOn.yaml
  tests/bg/_fixtures.yaml
  tests/bg/climate_HassClimateGetTemperature.yaml
  tests/bg/climate_HassClimateSetTemperature.yaml
  tests/bg/cover_HassCloseCover.yaml
  tests/bg/cover_HassOpenCover.yaml
  tests/bg/fan_HassTurnOff.yaml
  tests/bg/fan_HassTurnOn.yaml
  tests/bg/homeassistant_HassTurnOff.yaml
  tests/bg/homeassistant_HassTurnOn.yaml
  tests/bg/light_HassLightSet.yaml
  tests/bg/light_HassTurnOff.yaml
  tests/bg/light_HassTurnOn.yaml
Labels: cla-signed, lang: bg

#198 Added initial translations
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#199 generate codeowners based on languages.yaml
  .github/workflows/ci.yaml
  CODEOWNERS
  languages.yaml
  script/intentfest/codeowners.py
  script/intentfest/util.py
Labels: cla-signed

#200 Add language leaders to website
  README.md
  script/intentfest/website_summary.py
  website/src-11ty/_data/intentSummary.json
  website/src-11ty/index.html
Labels: cla-signed

#201 [uk]Added cover intents
  sentences/uk/_common.yaml
  sentences/uk/cover_HassCloseCover.yaml
  sentences/uk/cover_HassOpenCover.yaml
  tests/uk/_fixtures.yaml
  tests/uk/cover_HassCloseCover.yaml
  tests/uk/cover_HassOpenCover.yaml
Labels: cla-signed, lang: uk

#202 Ro intents basic
  sentences/ro/_common.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#203 Added ClimateGet
  sentences/sk/_common.yaml
  sentences/sk/climate_HassClimateGetTemperature.yaml
  sentences/sk/climate_HassClimateSetTemperature.yaml
  tests/sk/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sk

#211 Fix typo on line 46 of main README.md
  README.md
Labels: cla-signed

#214 Added lights
  sentences/sk/_common.yaml
  sentences/sk/light_HassLightSet.yaml
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
  tests/sk/_fixtures.yaml
  tests/sk/light_HassLightSet.yaml
  tests/sk/light_HassTurnOff.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#213 Ro intents basic
  sentences/ro/_common.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassLightSet.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro
