Repository OHF-Voice/intents, pull requests merged in 2023-09, with the labels that each got.

#1511 [Fr] Add lock_HassTurnOff and lock_HassTurnOn
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/lock_HassTurnOff.yaml
  sentences/fr/lock_HassTurnOn.yaml
  tests/fr/lock_HassTurnOff.yaml
  tests/fr/lock_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1519 fix control lights of a room
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1451 [EN] HassGetState for sensors with different device_class
  sentences/en/_common.yaml
  sentences/en/sensor_HassGetState.yaml
  tests/en/_fixtures.yaml
  tests/en/sensor_HassGetState.yaml
Labels: cla-signed, lang: en

#1516 Fix "all" response grammar and include the state
  responses/en/HassGetState.yaml
  tests/en/binary_sensor_HassGetState.yaml
  tests/en/cover_HassGetState.yaml
  tests/en/homeassistant_HassGetState.yaml
  tests/en/lock_HassGetState.yaml
Labels: cla-signed, lang: en

#1517 Update files to match new home assistant changes
  responses/sr/HassClimateGetTemperature.yaml
  responses/sr/HassGetState.yaml
  responses/sr/HassTurnOff.yaml
  responses/sr/HassTurnOn.yaml
  sentences/sr/_common.yaml
  sentences/sr/binary_sensor_HassGetState.yaml
  sentences/sr/climate_HassClimateGetTemperature.yaml
  sentences/sr/cover_HassGetState.yaml
  sentences/sr/cover_HassTurnOff.yaml
  sentences/sr/cover_HassTurnOn.yaml
  sentences/sr/light_HassLightSet.yaml
  sentences/sr/light_HassTurnOff.yaml
  sentences/sr/light_HassTurnOn.yaml
  tests/sr/_fixtures.yaml
  tests/sr/binary_sensor_HassGetState.yaml
  tests/sr/climate_HassClimateGetTemperature.yaml
  tests/sr/cover_HassGetState.yaml
  tests/sr/cover_HassTurnOff.yaml
  tests/sr/cover_HassTurnOn.yaml
  tests/sr/light_HassLightSet.yaml
  tests/sr/light_HassTurnOff.yaml
  tests/sr/light_HassTurnOn.yaml
Labels: cla-signed, lang: sr

#1522 [SR]: ClimateSetTemperature sentences, gramar fix for ClimateGetTempe…
  responses/sr/HassClimateGetTemperature.yaml
  responses/sr/HassClimateSetTemperature.yaml
  sentences/sr/_common.yaml
  sentences/sr/climate_HassClimateSetTemperature.yaml
  tests/sr/_fixtures.yaml
  tests/sr/climate_HassClimateGetTemperature.yaml
  tests/sr/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: sr

#1521 [SR] Added translation for shoping list
  responses/sr/HassShoppingListAddItem.yaml
  sentences/sr/shopping_list_HassShoppingListAddItem.yaml
  tests/sr/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: sr

#1525 [cs] Fix light intents, add HassTurnOff for all lights
  responses/cs/HassTurnOff.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1526 [cs] Add shopping list intents
  responses/cs/HassShoppingListAddItem.yaml
  sentences/cs/_common.yaml
  sentences/cs/shopping_list_HassShoppingListAddItem.yaml
  tests/cs/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: cs

#1529 [en] Add alternative sentences for scenes
  sentences/en/_common.yaml
  sentences/en/scene_HassTurnOn.yaml
  tests/en/scene_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1527 [cs] Adjust responses to follow style guide
  responses/cs/HassClimateGetTemperature.yaml
  responses/cs/HassClimateSetTemperature.yaml
  responses/cs/HassGetState.yaml
  responses/cs/HassLightSet.yaml
  responses/cs/HassTurnOff.yaml
  responses/cs/HassTurnOn.yaml
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  sentences/cs/light_HassLightSet.yaml
  tests/cs/_fixtures.yaml
  tests/cs/cover_HassGetState.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1409 [DE] Add binary sensors door and garage door
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1530 [RO] HassGetState default response
  responses/ro/HassGetState.yaml
Labels: cla-signed, lang: ro

#1531 [NL] Add default response for HassGetState
  responses/nl/HassGetState.yaml
Labels: cla-signed, lang: nl

#1532 [NL] HassGetState for sensors using device_class
  sentences/nl/_common.yaml
  sentences/nl/sensor_HassGetState.yaml
  tests/nl/_fixtures.yaml
  tests/nl/sensor_HassGetState.yaml
Labels: cla-signed, lang: nl
