Repository OHF-Voice/intents, pull requests merged in 2023-07, with the labels that each got.

#1441 [KO] Update Korean topic marker and sentence ending
  sentences/ko/fan_HassTurnOff.yaml
  sentences/ko/fan_HassTurnOn.yaml
  sentences/ko/homeassistant_HassGetState.yaml
  sentences/ko/light_HassTurnOff.yaml
  sentences/ko/light_HassTurnOn.yaml
  sentences/ko/scene_HassTurnOn.yaml
  sentences/ko/script_HassTurnOn.yaml
  tests/ko/fan_HassTurnOff.yaml
  tests/ko/fan_HassTurnOn.yaml
  tests/ko/homeassistant_HassGetState.yaml
  tests/ko/light_HassTurnOff.yaml
  tests/ko/light_HassTurnOn.yaml
  tests/ko/scene_HassTurnOn.yaml
  tests/ko/script_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1414 [IT] - improvement in conversation for cover_HassTurnOn and cover_HassTurnOff
  responses/it/HassTurnOff.yaml
  responses/it/HassTurnOn.yaml
  sentences/it/_common.yaml
  sentences/it/cover_HassTurnOff.yaml
  sentences/it/cover_HassTurnOn.yaml
  tests/it/cover_HassTurnOff.yaml
  tests/it/cover_HassTurnOn.yaml
  tests/it/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: it

#1446 Fix #1444
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1448 Local expansion rules
  requirements.txt
  script/intentfest/validate.py
  tests/test_language_intents.py
Labels: cla-signed

#1447 Fix recursive rule detection
  tests/test_language_intents.py
Labels: cla-signed

#1383 [DE] improve <irgend> for binary_sensor
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1453 Update _common.yaml
  sentences/nb/_common.yaml
Labels: cla-signed, lang: nb

#1456 [IS] Improve lights add setters and add covers
  responses/is/HassGetState.yaml
  responses/is/HassLightSet.yaml
  responses/is/HassTurnOff.yaml
  responses/is/HassTurnOn.yaml
  sentences/is/_common.yaml
  sentences/is/cover_HassGetState.yaml
  sentences/is/cover_HassTurnOff.yaml
  sentences/is/cover_HassTurnOn.yaml
  sentences/is/light_HassLightSet.yaml
  tests/is/_fixtures.yaml
  tests/is/cover_HassGetState.yaml
  tests/is/cover_HassTurnOff.yaml
  tests/is/cover_HassTurnOn.yaml
  tests/is/light_HassLightSet.yaml
Labels: cla-signed, lang: is

#1460 [IS] Add scenes and scripts
  responses/is/HassTurnOn.yaml
  sentences/is/_common.yaml
  sentences/is/scene_HassTurnOn.yaml
  sentences/is/script_HassTurnOn.yaml
  tests/is/_fixtures.yaml
  tests/is/scene_HassTurnOn.yaml
  tests/is/script_HassTurnOn.yaml
Labels: cla-signed, lang: is

#1461 [IS] Use proper responses, test responses and add HASS sentences
  responses/is/HassGetState.yaml
  responses/is/HassTurnOff.yaml
  responses/is/HassTurnOn.yaml
  sentences/is/_common.yaml
  sentences/is/cover_HassTurnOff.yaml
  sentences/is/cover_HassTurnOn.yaml
  sentences/is/homeassistant_HassGetState.yaml
  sentences/is/homeassistant_HassTurnOff.yaml
  sentences/is/homeassistant_HassTurnOn.yaml
  sentences/is/light_HassLightSet.yaml
  sentences/is/light_HassTurnOff.yaml
  sentences/is/light_HassTurnOn.yaml
  tests/is/_fixtures.yaml
  tests/is/cover_HassGetState.yaml
  tests/is/cover_HassTurnOff.yaml
  tests/is/homeassistant_HassGetState.yaml
  tests/is/homeassistant_HassTurnOff.yaml
  tests/is/homeassistant_HassTurnOn.yaml
  tests/is/light_HassTurnOff.yaml
  tests/is/light_HassTurnOn.yaml
Labels: cla-signed, lang: is

#1462 [IS] Add climate control
  responses/is/HassClimateGetTemperature.yaml
  responses/is/HassClimateSetTemperature.yaml
  sentences/is/_common.yaml
  sentences/is/climate_HassClimateGetTemperature.yaml
  sentences/is/climate_HassClimateSetTemperature.yaml
  tests/is/_fixtures.yaml
  tests/is/climate_HassClimateGetTemperature.yaml
  tests/is/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: is

#1465 Bump hassil to 1.2.0
  requirements.txt
Labels: cla-signed

#1467 Bugfixes from hassil 1.2.2
  requirements.txt
  sentences/bg/cover_HassTurnOff.yaml
  sentences/bg/cover_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  sentences/vi/fan_HassTurnOff.yaml
  sentences/vi/fan_HassTurnOn.yaml
  tests/bg/cover_HassTurnOff.yaml
  tests/bg/cover_HassTurnOn.yaml
  tests/bg/homeassistant_HassTurnOff.yaml
  tests/bg/homeassistant_HassTurnOn.yaml
  tests/he/homeassistant_HassTurnOff.yaml
  tests/he/homeassistant_HassTurnOn.yaml
  tests/he/light_HassLightSet.yaml
  tests/hr/light_HassLightSet.yaml
  tests/ka/light_HassTurnOff.yaml
  tests/ka/light_HassTurnOn.yaml
  tests/ms/cover_HassTurnOff.yaml
  tests/ms/cover_HassTurnOn.yaml
  tests/ms/fan_HassTurnOff.yaml
  tests/ms/fan_HassTurnOn.yaml
  tests/ms/homeassistant_HassTurnOff.yaml
  tests/ms/homeassistant_HassTurnOn.yaml
  tests/vi/fan_HassTurnOff.yaml
  tests/vi/fan_HassTurnOn.yaml
Labels: cla-signed, lang: he, lang: hr, lang: vi, lang: ka, lang: bg, lang: ms

#1466 Add HassShoppingListAddItem intent + wildcards
  intents.yaml
  responses/README.md
  responses/en/HassShoppingListAddItem.yaml
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/shopping_list_HassShoppingListAddItem.yaml
  tests/en/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: en

#1470 Fix validation for permutations
  script/intentfest/validate.py
Labels: cla-signed

#1469 [RO] Binary sensors refactoring
  sentences/ro/_common.yaml
  sentences/ro/binary_sensor_HassGetState.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  sentences/ro/cover_HassGetState.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/homeassistant_HassGetState.yaml
  sentences/ro/light_HassGetState.yaml
  sentences/ro/lock_HassGetState.yaml
  tests/ro/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: ro

#1478 [Fr] Add shopping list translation
  responses/fr/HassShoppingListAddItem.yaml
  sentences/fr/_common.yaml
  sentences/fr/shopping_list_HassShoppingListAddItem.yaml
  tests/fr/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: fr

#1480 Bump hassil to 1.2.5
  requirements.txt
  sentences/en/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: en

#1473 [DE] Add HassShoppingListAddItem intent
  responses/de/HassShoppingListAddItem.yaml
  sentences/de/_common.yaml
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
  tests/de/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: de

#1482 [de-CH] Add HassShoppingListAddItem
  responses/de-CH/HassShoppingListAddItem.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml
  tests/de-CH/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: de-ch

#1483 [RO] Added HassShoppingListAddItem
  responses/ro/HassShoppingListAddItem.yaml
  sentences/ro/_common.yaml
  sentences/ro/shopping_list_HassShoppingListAddItem.yaml
  tests/ro/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ro

#1485 [SK] Add shopping list intent
  responses/sk/HassShoppingListAddItem.yaml
  sentences/sk/_common.yaml
  sentences/sk/shopping_list_HassShoppingListAddItem.yaml
  tests/sk/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: sk

#1486 [NB] Add item to shopping list
  responses/nb/HassShoppingListAddItem.yaml
  sentences/nb/_common.yaml
  sentences/nb/shopping_list_HassShoppingListAddItem.yaml
  tests/nb/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: nb

#1484 [NL] Add shopping list intent
  responses/nl/HassShoppingListAddItem.yaml
  sentences/nl/_common.yaml
  sentences/nl/shopping_list_HassShoppingListAddItem.yaml
  tests/nl/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: nl
