Repository OHF-Voice/intents, pull requests merged in 2023-12, with the labels that each got.

#1701 HassClimateGetTemperature response fix decimals
  responses/sl/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sl

#1702 [FR] last translation in sensor_HassGetState
  sentences/fr/_common.yaml
  sentences/fr/sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1703 [cs] Minor improvements/fixes for lights area intents
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1705 Create release-drafter.yml
  .github/release-drafter.yml
Labels: cla-signed

#1514 [ET] Fixed two translations
  responses/et/HassTurnOff.yaml
  responses/et/HassTurnOn.yaml
  tests/et/homeassistant_HassTurnOff.yaml
  tests/et/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: et

#1706 [RO] Fix temperature values for TTS
  responses/ro/HassClimateGetTemperature.yaml
  responses/ro/HassGetWeather.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ro

#1708 pt: Remove nevermind response; add climate entity sentence
  responses/pt/HassNevermind.yaml
  sentences/pt/climate_HassClimateGetTemperature.yaml
  tests/pt/climate_HassClimateGetTemperature.yaml
  tests/pt/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: pt

#1711 [SK] add intent nevermind
  responses/sk/HassNevermind.yaml
  sentences/sk/homeassistant_HassNevermind.yaml
  tests/sk/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sk

#1712 [SK] todo list intent
  responses/sk/HassListAddItem.yaml
  sentences/sk/todo_HassListAddItem.yaml
  tests/sk/_fixtures.yaml
  tests/sk/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sk

#1713 [SK] add get weather
  responses/sk/HassGetWeather.yaml
  sentences/sk/weather_HassGetWeather.yaml
  tests/sk/_fixtures.yaml
  tests/sk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sk

#1715 [uk] Added HassNevermind intent
  sentences/uk/homeassistant_HassNevermind.yaml
  tests/uk/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: uk

#1717 [SL] added binary sensors - partly, sentences,, tests, amended fixtures and common, responses
  responses/sl/HassGetState.yaml
  responses/sl/HassNevermind.yaml
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  sentences/sl/cover_HassTurnOn.yaml
  sentences/sl/todo_HassListAddItem.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
  tests/sl/cover_HassGetState.yaml
  tests/sl/cover_HassTurnOff.yaml
  tests/sl/cover_HassTurnOn.yaml
  tests/sl/lock_HassGetState.yaml
  tests/sl/person_HassGetState.yaml
  tests/sl/shopping_list_HassShoppingListAddItem.yaml
  tests/sl/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sl

#1714 [PL] Nevermind
  sentences/pl/homeassistant_HassNevermind.yaml
  tests/pl/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: pl

#1721 [EN] Add "current" as an optional temps attribute
  sentences/en/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: en

#1724 [SL] Binary sensors - sentences, test, responses
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1729 [ES] Adding <ahora> to getClimate sentences
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: es

#1730 [de-CH] slight adjustment of GetTemperature
  responses/de-CH/HassListAddItem.yaml
  responses/de-CH/HassShoppingListAddItem.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/climate_HassClimateGetTemperature.yaml
  sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml
  sentences/de-CH/todo_HassListAddItem.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/shopping_list_HassShoppingListAddItem.yaml
  tests/de-CH/todo_HassListAddItem.yaml
Labels: cla-signed, lang: de-ch

#1732 [de-CH] implement HassGetWeather
  responses/de-CH/HassGetWeather.yaml
  sentences/de-CH/weather_HassGetWeather.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/weather_HassGetWeather.yaml
Labels: cla-signed, lang: de-ch

#1716 [uk] Added HassListAddItem intent
  responses/uk/HassListAddItem.yaml
  sentences/uk/todo_HassListAddItem.yaml
  tests/uk/_fixtures.yaml
  tests/uk/todo_HassListAddItem.yaml
Labels: cla-signed, lang: uk

#1734 [RU] Add Nevermind intent
  sentences/ru/homeassistant_HassNevermind.yaml
  tests/ru/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: ru

#1735 [RU] Add HassListAddItem intent
  responses/ru/HassListAddItem.yaml
  sentences/ru/todo_HassListAddItem.yaml
  tests/ru/_fixtures.yaml
  tests/ru/todo_HassListAddItem.yaml
Labels: cla-signed, lang: ru

#1736 [SL] binary sensor for gas added
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1737 [RU] Add HassGetWeather intent
  responses/ru/HassGetWeather.yaml
  sentences/ru/weather_HassGetWeather.yaml
  tests/ru/_fixtures.yaml
  tests/ru/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ru

#1727 [PT] Set empty reponse for HassNevermind
  tests/pt/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: pt

#1739 [es] Returning decimals in temperature with a decimal comma
  responses/es/HassClimateGetTemperature.yaml
  tests/es/_fixtures.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: es

#1740 [NL] Weather intent without providing name
  sentences/nl/weather_HassGetWeather.yaml
  tests/nl/_fixtures.yaml
  tests/nl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: nl

#1733 [uk] Added script_HassTurnOn intent
  responses/uk/HassTurnOn.yaml
  sentences/uk/script_HassTurnOn.yaml
  tests/uk/_fixtures.yaml
  tests/uk/script_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#1752 [SL] binary sensors heat, light
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1754 [SL] binary sensors, lock, moisture
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1744 [DE] added 'nichts' as an option for HassNevermind
  sentences/de/homeassistant_HassNevermind.yaml
  tests/de/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: de

#1743 [DE] added 'et' option to 'schalten' expansion rule + test
  sentences/de/_common.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1725 [DE] added 't' option to 'machen' expansion rule
  sentences/de/_common.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
  tests/de/lock_HassTurnOff.yaml
  tests/de/lock_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1759 [SL] binary sensor - motion
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1748 [GL] Replace <name> expansion rule by <nome>
  sentences/gl/_common.yaml
  sentences/gl/cover_HassTurnOff.yaml
  sentences/gl/cover_HassTurnOn.yaml
  sentences/gl/homeassistant_HassTurnOff.yaml
  sentences/gl/homeassistant_HassTurnOn.yaml
  sentences/gl/light_HassLightSet.yaml
Labels: cla-signed, lang: gl

#1760 [GL] Added some more skip words
  sentences/gl/_common.yaml
Labels: cla-signed, lang: gl

#1749 [GL] Shopping list sentences
  responses/gl/HassShoppingListAddItem.yaml
  sentences/gl/_common.yaml
  sentences/gl/shopping_list_HassShoppingListAddItem.yaml
  tests/gl/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: gl

#1753 [DE] add degrees sign to temperature expansion rule
  sentences/de/_common.yaml
  tests/de/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: de, cla-error

#1751 [GL] GetState sentences
  responses/gl/HassGetState.yaml
  sentences/gl/_common.yaml
  sentences/gl/homeassistant_HassGetState.yaml
  tests/gl/_fixtures.yaml
  tests/gl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: gl

#1747 [GL] Add weather sentences
  responses/gl/HassClimateGetTemperature.yaml
  responses/gl/HassClimateSetTemperature.yaml
  responses/gl/HassGetWeather.yaml
  sentences/gl/weather_HassGetWeather.yaml
  tests/gl/_fixtures.yaml
  tests/gl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: gl

#1764 [RU] Fix HassGetWeather translation
  responses/ru/HassGetWeather.yaml
  tests/ru/_fixtures.yaml
Labels: cla-signed, lang: ru

#1765 [RU] Fix _common.yaml
  sentences/ru/_common.yaml
  tests/ru/_fixtures.yaml
  tests/ru/cover_HassGetState.yaml
  tests/ru/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: ru

#1766 [SL] lights, climate fixed
  responses/sl/HassLightSet.yaml
  responses/sl/HassTurnOff.yaml
  sentences/sl/_common.yaml
  sentences/sl/climate_HassClimateGetTemperature.yaml
  sentences/sl/light_HassLightSet.yaml
  sentences/sl/light_HassTurnOff.yaml
  sentences/sl/light_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/light_HassLightSet.yaml
  tests/sl/light_HassTurnOff.yaml
  tests/sl/light_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1772 [RU] add script_HassTurnOn support
  responses/ru/HassTurnOn.yaml
  sentences/ru/_common.yaml
  sentences/ru/homeassistant_HassTurnOn.yaml
  sentences/ru/script_HassTurnOn.yaml
  tests/ru/script_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#1660 [NL] Turn lights on/off in the area of a satellite
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1775 [EL] Add HassGetWeather intents
  responses/el/HassGetWeather.yaml
  sentences/el/weather_HassGetWeather.yaml
  tests/el/_fixtures.yaml
  tests/el/weather_HassGetWeather.yaml
Labels: cla-signed, lang: el

#1767 [EN] Fix intents with untranslated state
  responses/en/HassGetState.yaml
  responses/en/HassGetWeather.yaml
  sentences/en/_common.yaml
  sentences/en/person_HassGetState.yaml
  tests/en/_fixtures.yaml
  tests/en/person_HassGetState.yaml
  tests/en/weather_HassGetWeather.yaml
Labels: cla-signed, lang: en

#1769 [RO] Fix intents with untranslated state
  responses/ro/HassGetState.yaml
  responses/ro/HassGetWeather.yaml
  sentences/ro/_common.yaml
  sentences/ro/person_HassGetState.yaml
  tests/ro/_fixtures.yaml
  tests/ro/person_HassGetState.yaml
Labels: cla-signed, lang: ro

#1657 [DE] add support for person_HassGetState
  responses/de/HassGetState.yaml
  sentences/de/_common.yaml
  sentences/de/person_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/person_HassGetState.yaml
Labels: cla-signed, lang: de

#1777 [DE] Fix intents with untranslated states
  responses/de/HassGetState.yaml
  responses/de/HassGetWeather.yaml
  sentences/de/_common.yaml
  sentences/de/person_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/person_HassGetState.yaml
Labels: cla-signed, lang: de

#1778 [EL] Fix intents with untranslated state
  responses/el/HassGetWeather.yaml
  tests/el/_fixtures.yaml
  tests/el/weather_HassGetWeather.yaml
Labels: cla-signed, lang: el

#1770 [ES] Fix intents with untranslated state
  responses/es/HassGetState.yaml
  responses/es/HassGetWeather.yaml
  sentences/es/_common.yaml
  sentences/es/person_HassGetState.yaml
  tests/es/_fixtures.yaml
  tests/es/person_HassGetState.yaml
  tests/es/weather_HassGetWeather.yaml
Labels: cla-signed, lang: es

#1779 [PL] Fix intents with untranslated state (#1767) AND MORE
  responses/pl/HassGetState.yaml
  responses/pl/HassGetWeather.yaml
  sentences/pl/_common.yaml
  sentences/pl/person_HassGetState.yaml
  sentences/pl/weather_HassGetWeather.yaml
  tests/pl/_fixtures.yaml
  tests/pl/homeassistant_HassNevermind.yaml
  tests/pl/person_HassGetState.yaml
  tests/pl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: pl

#1776 [NL] Turn lights on/off in the area of a satellite
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1780 [EL] Add HassListAddItem intents
  responses/el/HassListAddItem.yaml
  sentences/el/todo_HassListAddItem.yaml
  tests/el/_fixtures.yaml
  tests/el/todo_HassListAddItem.yaml
Labels: cla-signed, lang: el

#1771 [NL] Fix intents with untranslated states
  responses/nl/HassGetState.yaml
  responses/nl/HassGetWeather.yaml
  sentences/nl/_common.yaml
  sentences/nl/person_HassGetState.yaml
  tests/nl/_fixtures.yaml
  tests/nl/person_HassGetState.yaml
Labels: cla-signed, lang: nl

#1774 [SL] ] Fix intents with untranslated states
  responses/sl/HassGetState.yaml
  responses/sl/HassGetWeather.yaml
  sentences/sl/_common.yaml
  sentences/sl/person_HassGetState.yaml
  sentences/sl/weather_HassGetWeather.yaml
  tests/sl/_fixtures.yaml
  tests/sl/person_HassGetState.yaml
  tests/sl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sl

#1782 [PT] Fix weather intents with untranslated state
  responses/pt/HassGetWeather.yaml
  tests/pt/_fixtures.yaml
  tests/pt/weather_HassGetWeather.yaml
Labels: cla-signed, lang: pt

#1789 [RU] add sensor_HassGetState support
  responses/ru/HassGetState.yaml
  sentences/ru/_common.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  sentences/ru/sensor_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/sensor_HassGetState.yaml
Labels: cla-signed, lang: ru

#1784 [EN] Improve light_HassLightSet sentences
  sentences/en/_common.yaml
  sentences/en/light_HassLightSet.yaml
  tests/en/light_HassLightSet.yaml
Labels: cla-signed, lang: en

#1792 [RU] Fix intents with untranslated states
  responses/ru/HassGetState.yaml
  responses/ru/HassGetWeather.yaml
  sentences/ru/_common.yaml
  sentences/ru/person_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/person_HassGetState.yaml
Labels: cla-signed, lang: ru

#1793 [PT] Add person support
  responses/pt/HassGetState.yaml
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassGetState.yaml
  sentences/pt/person_HassGetState.yaml
  tests/pt/_fixtures.yaml
  tests/pt/person_HassGetState.yaml
Labels: cla-signed, lang: pt

#1799 [SL] binary sensors - occupancy added
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1742 [uk] Added HassGetWeather intent
  responses/uk/HassGetWeather.yaml
  sentences/uk/weather_HassGetWeather.yaml
  tests/uk/_fixtures.yaml
  tests/uk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: uk

#1805 [SL] added opening and plug, modified connectivity
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1809 [SL] fixed sentence todo_HassListAddItem
  sentences/sl/todo_HassListAddItem.yaml
  tests/sl/_fixtures.yaml
  tests/sl/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sl

#1818 [Fr] light with satellite intents
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1539 [en] Add definite article for object of HassTurnOn/HassTurnOff responses
  responses/en/HassTurnOff.yaml
  responses/en/HassTurnOn.yaml
  tests/en/cover_HassTurnOff.yaml
  tests/en/cover_HassTurnOn.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1819 Improve expansion rules for french intents
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  sentences/fr/climate_HassClimateGetTemperature.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  sentences/fr/cover_HassGetState.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/fan_HassTurnOff.yaml
  sentences/fr/fan_HassTurnOn.yaml
  sentences/fr/homeassistant_HassGetState.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  sentences/fr/lock_HassGetState.yaml
  sentences/fr/lock_HassTurnOff.yaml
  sentences/fr/lock_HassTurnOn.yaml
  sentences/fr/person_HassGetState.yaml
  sentences/fr/scene_HassTurnOn.yaml
  sentences/fr/script_HassTurnOn.yaml
  sentences/fr/sensor_HassGetState.yaml
  sentences/fr/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fr

#1820 [fr] Light intents rework 20231221
  sentences/fr/_common.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1821 [PT] Improve recognition for lists by adding "a"
  sentences/pt/_common.yaml
  sentences/pt/shopping_list_HassShoppingListAddItem.yaml
  sentences/pt/todo_HassListAddItem.yaml
  tests/pt/shopping_list_HassShoppingListAddItem.yaml
  tests/pt/todo_HassListAddItem.yaml
Labels: cla-signed, lang: pt

#1822 [RU] Add turn on/off light locally
  sentences/ru/light_HassTurnOff.yaml
  sentences/ru/light_HassTurnOn.yaml
  tests/ru/light_HassTurnOff.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#1828 Fix Hebrew response for HassClimateGetTemperature
  responses/he/HassClimateGetTemperature.yaml
  tests/he/_fixtures.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: he

#1762 [GL] ListAddItem sentences
  responses/gl/HassListAddItem.yaml
  sentences/gl/todo_HassListAddItem.yaml
  tests/gl/_fixtures.yaml
  tests/gl/todo_HassListAddItem.yaml
Labels: cla-signed, lang: gl

#1761 [GL] Nevermind sentences
  sentences/gl/homeassistant_HassNevermind.yaml
  tests/gl/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: gl

#1750 [NB] Add item to todo
  responses/nb/HassListAddItem.yaml
  sentences/nb/todo_HassListAddItem.yaml
  tests/nb/_fixtures.yaml
  tests/nb/todo_HassListAddItem.yaml
Labels: cla-signed, lang: nb

#1831 [NB] Add Norwegian nevermind
  sentences/nb/homeassistant_HassNevermind.yaml
  tests/nb/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: nb

#1837 [NB] Initial HassGetSensor for humidity & battery
  sentences/nb/_common.yaml
  sentences/nb/sensor_HassGetState.yaml
  tests/nb/_fixtures.yaml
  tests/nb/sensor_HassGetState.yaml
Labels: cla-signed, lang: nb

#1839 [NL] Add additional pronouns to list intents
  sentences/nl/shopping_list_HassShoppingListAddItem.yaml
  sentences/nl/todo_HassListAddItem.yaml
  tests/nl/shopping_list_HassShoppingListAddItem.yaml
  tests/nl/todo_HassListAddItem.yaml
Labels: cla-signed, lang: nl
