Repository OHF-Voice/intents, pull requests merged in 2023-08, with the labels that each got.

#1488 [KO] Add shopping list sentences
  responses/ko/HassGetState.yaml
  responses/ko/HassShoppingListAddItem.yaml
  sentences/ko/_common.yaml
  sentences/ko/shopping_list_HassShoppingListAddItem.yaml
  tests/ko/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ko

#1474 Add basic shopping list sentences for Russian
  responses/ru/HassShoppingListAddItem.yaml
  sentences/ru/_common.yaml
  sentences/ru/shopping_list_HassShoppingListAddItem.yaml
  tests/ru/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ru

#1487 [RO] Binary sensors extra
  responses/ro/HassGetState.yaml
  sentences/ro/_common.yaml
  sentences/ro/binary_sensor_HassGetState.yaml
  tests/ro/binary_sensor_HassGetState.yaml
  tests/ro/light_HassGetState.yaml
  tests/ro/lock_HassGetState.yaml
Labels: cla-signed, lang: ro

#1490 [uk] Added shopping list intent
  responses/uk/HassShoppingListAddItem.yaml
  sentences/uk/_common.yaml
  sentences/uk/shopping_list_HassShoppingListAddItem.yaml
  tests/uk/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: uk

#1491 add shopping_list
  responses/pl/HassShoppingListAddItem.yaml
  sentences/pl/_common.yaml
  sentences/pl/shopping_list_HassShoppingListAddItem.yaml
  tests/pl/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: pl

#1494 [de-CH] minor adjustments and improvements
  responses/de-CH/HassTurnOff.yaml
  responses/de-CH/HassTurnOn.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/fan_HassTurnOff.yaml
  sentences/de-CH/fan_HassTurnOn.yaml
  sentences/de-CH/homeassistant_HassTurnOff.yaml
  sentences/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/fan_HassTurnOff.yaml
  tests/de-CH/fan_HassTurnOn.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
Labels: cla-signed, lang: de-ch

#1495 Added shopping list sentences in Swedish
  responses/sv/HassShoppingListAddItem.yaml
  sentences/sv/_common.yaml
  sentences/sv/shopping_list_HassShoppingListAddItem.yaml
  tests/sv/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: sv

#1489 [ca] Add new shopping list, scripts and scenes
  responses/ca/HassShoppingListAddItem.yaml
  responses/ca/HassTurnOn.yaml
  sentences/ca/_common.yaml
  sentences/ca/scene_HassTurnOn.yaml
  sentences/ca/script_HassTurnOn.yaml
  sentences/ca/shopping_list_HassShoppingListAddItem.yaml
  tests/ca/_fixtures.yaml
  tests/ca/scene_HassTurnOn.yaml
  tests/ca/script_HassTurnOn.yaml
  tests/ca/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ca

#1497 [es] Adds support for shopping list voice commands
  responses/es/HassShoppingListAddItem.yaml
  sentences/es/_common.yaml
  sentences/es/shopping_list_HassShoppingListAddItem.yaml
  tests/es/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: es

#1498 Add binary_sensors, scripts and scenes, and lots of other fixes
  responses/es/HassClimateSetTemperature.yaml
  responses/es/HassLightSet.yaml
  responses/es/HassTurnOff.yaml
  responses/es/HassTurnOn.yaml
  sentences/es/_common.yaml
  sentences/es/binary_sensor_HassGetState.yaml
  sentences/es/cover_HassTurnOff.yaml
  sentences/es/cover_HassTurnOn.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/homeassistant_HassGetState.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  sentences/es/lock_HassGetState.yaml
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
  sentences/es/scene_HassTurnOn.yaml
  sentences/es/script_HassTurnOn.yaml
  sentences/es/shopping_list_HassShoppingListAddItem.yaml
  tests/es/_fixtures.yaml
  tests/es/binary_sensor_HassGetState.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
  tests/es/cover_HassTurnOff.yaml
  tests/es/cover_HassTurnOn.yaml
  tests/es/fan_HassTurnOff.yaml
  tests/es/fan_HassTurnOn.yaml
  tests/es/homeassistant_HassGetState.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
  tests/es/lock_HassGetState.yaml
  tests/es/lock_HassTurnOff.yaml
  tests/es/lock_HassTurnOn.yaml
  tests/es/scene_HassTurnOn.yaml
  tests/es/script_HassTurnOn.yaml
  tests/es/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: es

#1501 Add short forms for light onOff with area at the end
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1496 added new ways to ask for state
  sentences/pl/homeassistant_HassGetState.yaml
  tests/pl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pl

#1513 [cs] Make error responses gender neutral
  sentences/cs/_common.yaml
Labels: cla-signed, lang: cs
