Repository OHF-Voice/intents, pull requests merged in 2023-11, with the labels that each got.

#1506 pt: add more setence variants
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassGetState.yaml
  tests/pt/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pt

#1508 pt: add shopping list sentences and responses
  responses/pt/HassShoppingListAddItem.yaml
  sentences/pt/_common.yaml
  sentences/pt/shopping_list_HassShoppingListAddItem.yaml
  tests/pt/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: pt

#1601 Spanish lenguage improvements
  responses/es/HassGetState.yaml
  responses/es/HassNevermind.yaml
  sentences/es/_common.yaml
  sentences/es/homeassistant_HassGetState.yaml
  sentences/es/homeassistant_HassNevermind.yaml
  sentences/es/sensor_HassGetState.yaml
  tests/es/_fixtures.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/homeassistant_HassGetState.yaml
  tests/es/homeassistant_HassNevermind.yaml
  tests/es/sensor_HassGetState.yaml
Labels: cla-signed, lang: es

#1604 Translate 2023.9.22 to spanish
  responses/es/HassGetState.yaml
  responses/es/HassTurnOn.yaml
  sentences/es/_common.yaml
  sentences/es/binary_sensor_HassGetState.yaml
  sentences/es/scene_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/binary_sensor_HassGetState.yaml
  tests/es/cover_HassGetState.yaml
  tests/es/homeassistant_HassGetState.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/lock_HassGetState.yaml
  tests/es/lock_HassTurnOn.yaml
  tests/es/scene_HassTurnOn.yaml
  tests/es/sensor_HassGetState.yaml
Labels: cla-signed, lang: es

#1605 [es] Improving nevermind and removing wrong sentence
  sentences/es/_common.yaml
  sentences/es/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: es

#1615 [en] Allow singular use of lock or door for lock and unlock
  sentences/en/lock_HassTurnOff.yaml
  sentences/en/lock_HassTurnOn.yaml
  tests/en/lock_HassTurnOff.yaml
  tests/en/lock_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1614 [en] Extend lock HassGetState sentences with some alternatives
  sentences/en/lock_HassGetState.yaml
  tests/en/lock_HassGetState.yaml
Labels: cla-signed, lang: en

#1581 [DE] Add binary sensor heat
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de, Hacktoberfest

#1616 [PT] Add HassNevermind
  responses/pt/HassNevermind.yaml
  sentences/pt/homeassistant_HassNevermind.yaml
  tests/pt/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: pt

#1577 [DE] Add binary sensor gas
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de, Hacktoberfest

#1617 [DE] Change naming of co-sensor
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1618 [PT] Simplify responses + remove redundant sentences
  responses/pt/HassClimateSetTemperature.yaml
  responses/pt/HassGetState.yaml
  responses/pt/HassLightSet.yaml
  responses/pt/HassTurnOff.yaml
  responses/pt/HassTurnOn.yaml
  sentences/pt/homeassistant_HassTurnOff.yaml
  sentences/pt/homeassistant_HassTurnOn.yaml
  tests/pt/climate_HassClimateSetTemperature.yaml
  tests/pt/homeassistant_HassGetState.yaml
  tests/pt/homeassistant_HassTurnOff.yaml
  tests/pt/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#1619 [PT] Add missing response tests
  sentences/pt/fan_HassTurnOff.yaml
  tests/pt/fan_HassTurnOff.yaml
  tests/pt/fan_HassTurnOn.yaml
  tests/pt/light_HassLightSet.yaml
  tests/pt/light_HassTurnOff.yaml
  tests/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#1606 Update light_HassTurnOn.yaml
  sentences/sr/light_HassTurnOn.yaml
Labels: cla-signed, lang: sr

#1607 Update light_HassTurnOff.yaml
  sentences/sr/light_HassTurnOff.yaml
Labels: cla-signed, lang: sr

#1608 Update climate_HassClimateGetTemperature.yaml
  sentences/sr/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sr

#1609 Update _common.yaml
  sentences/sr/_common.yaml
Labels: cla-signed, lang: sr

#1611 Update HassGetState.yaml
  responses/sr/HassGetState.yaml
Labels: cla-signed, lang: sr

#1620 [fr] add new sentence control brightness and fix all areas
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1621 Bump hassil to 1.4.0
  requirements.txt
Labels: cla-signed

#1624 Fix minimum translation
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#1500 Fix "all" placeholders for name/area
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/light_HassTurnOff.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/light_HassTurnOff.yaml
Labels: cla-signed, lang: en

#1625 Add Slovenian language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1628 [es] Improving responses
  responses/es/HassTurnOff.yaml
  responses/es/HassTurnOn.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
  tests/es/cover_HassTurnOff.yaml
  tests/es/cover_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/lock_HassTurnOff.yaml
  tests/es/lock_HassTurnOn.yaml
  tests/es/scene_HassTurnOn.yaml
Labels: cla-signed, lang: es

#1629 Simlpify french responses for the cover domain
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1630 [en] Don't produce <N>percent
  sentences/en/_common.yaml
Labels: cla-signed, lang: en

#1633 [SL] language pack added (sentences, responses, tests, common and fixtures)
  .vscode/tasks.json
  responses/sl/HassClimateGetTemperature.yaml
  responses/sl/HassClimateSetTemperature.yaml
  responses/sl/HassGetState.yaml
  responses/sl/HassLightSet.yaml
  responses/sl/HassTurnOff.yaml
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/climate_HassClimateGetTemperature.yaml
  sentences/sl/climate_HassClimateSetTemperature.yaml
  sentences/sl/cover_HassGetState.yaml
  sentences/sl/cover_HassTurnOff.yaml
  sentences/sl/cover_HassTurnOn.yaml
  sentences/sl/fan_HassTurnOff.yaml
  sentences/sl/fan_HassTurnOn.yaml
  sentences/sl/homeassistant_HassGetState.yaml
  sentences/sl/homeassistant_HassTurnOff.yaml
  sentences/sl/homeassistant_HassTurnOn.yaml
  sentences/sl/light_HassLightSet.yaml
  sentences/sl/light_HassTurnOff.yaml
  sentences/sl/light_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/climate_HassClimateSetTemperature.yaml
  tests/sl/cover_HassGetState.yaml
  tests/sl/cover_HassTurnOff.yaml
  tests/sl/cover_HassTurnOn.yaml
  tests/sl/fan_HassTurnOff.yaml
  tests/sl/fan_HassTurnOn.yaml
  tests/sl/homeassistant_HassGetState.yaml
  tests/sl/homeassistant_HassTurnOff.yaml
  tests/sl/homeassistant_HassTurnOn.yaml
  tests/sl/light_HassLightSet.yaml
  tests/sl/light_HassTurnOff.yaml
  tests/sl/light_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1637 Bump to hassil 1.5.0
  requirements.txt
Labels: cla-signed

#1627 Add HassGetWeather intent
  intents.yaml
  responses/en/HassGetWeather.yaml
  sentences/en/weather_HassGetWeather.yaml
  tests/en/_fixtures.yaml
  tests/en/weather_HassGetWeather.yaml
Labels: cla-signed, lang: en

#1626 Add HassListAddItem intent
  intents.yaml
  responses/en/HassListAddItem.yaml
  sentences/en/todo_HassListAddItem.yaml
  tests/en/_fixtures.yaml
  tests/en/todo_HassListAddItem.yaml
Labels: cla-signed, lang: en

#1639 Fix #1602
  sentences/es/_common.yaml
  sentences/es/shopping_list_HassShoppingListAddItem.yaml
  tests/es/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: es

#1641 [RO] Added todo_HassListAddItem
  responses/ro/HassListAddItem.yaml
  sentences/ro/todo_HassListAddItem.yaml
  tests/ro/_fixtures.yaml
  tests/ro/todo_HassListAddItem.yaml
Labels: cla-signed, lang: ro

#1642 [RO] Add HassGetWeather
  responses/ro/HassGetWeather.yaml
  sentences/ro/weather_HassGetWeather.yaml
  tests/ro/_fixtures.yaml
  tests/ro/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ro

#1644 [RO] Improve sentences for light_HassTurnOn/Off
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#1645 [ES] Updating translations to 2023.11.13 release
  responses/es/HassGetState.yaml
  responses/es/HassGetWeather.yaml
  responses/es/HassListAddItem.yaml
  sentences/es/_common.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  sentences/es/lock_HassGetState.yaml
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
  sentences/es/person_HassGetState.yaml
  sentences/es/todo_HassListAddItem.yaml
  sentences/es/weather_HassGetWeather.yaml
  tests/es/_fixtures.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
  tests/es/lock_HassGetState.yaml
  tests/es/lock_HassTurnOff.yaml
  tests/es/person_HassGetState.yaml
  tests/es/todo_HassListAddItem.yaml
  tests/es/weather_HassGetWeather.yaml
Labels: cla-signed, lang: es

#1643 [RO] Add person_HassGetState
  responses/ro/HassGetState.yaml
  sentences/ro/_common.yaml
  sentences/ro/person_HassGetState.yaml
  tests/ro/_fixtures.yaml
  tests/ro/person_HassGetState.yaml
Labels: cla-signed, lang: ro

#1648 [es] fix lock/door confussion
  sentences/es/lock_HassGetState.yaml
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
  sentences/es/person_HassGetState.yaml
  tests/es/lock_HassGetState.yaml
  tests/es/lock_HassTurnOn.yaml
Labels: cla-signed, lang: es

#1651 [en] Bump hassil to 1.5.1, remove "all" from light
  requirements.txt
  script/intentfest/parse.py
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1653 Mark HassGetWeather and HassListAddItem as supported
  intents.yaml
Labels: cla-signed

#1654 Updating ES translations to 2023.11.17 tag
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#1655 [Fr] sensor_HassGetState
  responses/fr/HassGetState.yaml
  responses/fr/HassGetWeather.yaml
  responses/fr/HassListAddItem.yaml
  sentences/fr/_common.yaml
  sentences/fr/person_HassGetState.yaml
  sentences/fr/sensor_HassGetState.yaml
  sentences/fr/shopping_list_HassShoppingListAddItem.yaml
  sentences/fr/todo_HassListAddItem.yaml
  sentences/fr/weather_HassGetWeather.yaml
  tests/fr/_fixtures.yaml
  tests/fr/person_HassGetState.yaml
  tests/fr/sensor_HassGetState.yaml
  tests/fr/todo_HassListAddItem.yaml
  tests/fr/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fr

#1646 [DE] HassGetWeather
  responses/de/HassGetWeather.yaml
  sentences/de/weather_HassGetWeather.yaml
  tests/de/_fixtures.yaml
  tests/de/weather_HassGetWeather.yaml
Labels: cla-signed, lang: de

#1640 [DE] HassListAddItem
  responses/de/HassListAddItem.yaml
  sentences/de/todo_HassListAddItem.yaml
  tests/de/_fixtures.yaml
  tests/de/todo_HassListAddItem.yaml
Labels: cla-signed, lang: de

#1593 [cs] Add scene support
  responses/cs/HassGetState.yaml
  responses/cs/HassTurnOn.yaml
  sentences/cs/_common.yaml
  sentences/cs/scene_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/scene_HassTurnOn.yaml
Labels: cla-signed, lang: cs, Hacktoberfest

#1665 [FR] Add homeassistant_HassNevermind.yaml
  sentences/fr/homeassistant_HassNevermind.yaml
  tests/fr/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: fr

#1666 [FR] Add translation for more device classes in sensor_HassGetState
  sentences/fr/_common.yaml
  sentences/fr/sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1668 [EL] Fix default response to HassTurnOn/HassTurnOff
  responses/el/HassTurnOff.yaml
  responses/el/HassTurnOn.yaml
Labels: cla-signed, lang: el

#1662 [NL] Add HassGetWeather
  responses/nl/HassGetWeather.yaml
  sentences/nl/weather_HassGetWeather.yaml
  tests/nl/_fixtures.yaml
  tests/nl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: nl

#1659 [NL] Add person_HassGetState
  responses/nl/HassGetState.yaml
  sentences/nl/_common.yaml
  sentences/nl/person_HassGetState.yaml
  tests/nl/_fixtures.yaml
  tests/nl/person_HassGetState.yaml
Labels: cla-signed, lang: nl

#1670 [UK] New colours, brightness, locks and binary sensors were added.
  sentences/uk/_common.yaml
Labels: cla-signed, lang: uk

#1667 [FR] New device classes translation
  sentences/fr/_common.yaml
  sentences/fr/sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1672 fixed typo in area in common.yaml
  sentences/sl/_common.yaml
Labels: cla-signed, lang: sl

#1674 Migrate HassClimateGetTemperature fixtures/responses
  intents.yaml
  package/home_assistant_intents/domains.py
  responses/af/HassClimateGetTemperature.yaml
  responses/ar/HassClimateGetTemperature.yaml
  responses/cs/HassClimateGetTemperature.yaml
  responses/de/HassClimateGetTemperature.yaml
  responses/en/HassClimateGetTemperature.yaml
  responses/eu/HassClimateGetTemperature.yaml
  responses/fi/HassClimateGetTemperature.yaml
  responses/fr/HassClimateGetTemperature.yaml
  responses/hr/HassClimateGetTemperature.yaml
  responses/is/HassClimateGetTemperature.yaml
  responses/ko/HassClimateGetTemperature.yaml
  responses/lt/HassClimateGetTemperature.yaml
  responses/nb/HassClimateGetTemperature.yaml
  responses/pt/HassClimateGetTemperature.yaml
  responses/sl/HassClimateGetTemperature.yaml
  responses/zh-cn/HassClimateGetTemperature.yaml
  responses/zh-tw/HassClimateGetTemperature.yaml
  script/intentfest/validate.py
  sentences/en/climate_HassClimateGetTemperature.yaml
  shared/__init__.py
  tests/ar/_fixtures.yaml
  tests/ar/climate_HassClimateGetTemperature.yaml
  tests/ar/homeassistant_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
  tests/en/_fixtures.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
  tests/fi/_fixtures.yaml
  tests/fi/climate_HassClimateGetTemperature.yaml
  tests/fr/_fixtures.yaml
  tests/hr/_fixtures.yaml
  tests/hr/climate_HassClimateGetTemperature.yaml
  tests/is/_fixtures.yaml
  tests/is/climate_HassClimateGetTemperature.yaml
  tests/ko/_fixtures.yaml
  tests/ko/climate_HassClimateGetTemperature.yaml
  tests/nb/_fixtures.yaml
  tests/nb/climate_HassClimateGetTemperature.yaml
  tests/pt/_fixtures.yaml
  tests/pt/climate_HassClimateGetTemperature.yaml
  tests/sl/_fixtures.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
  tests/zh-cn/_fixtures.yaml
  tests/zh-cn/climate_HassClimateGetTemperature.yaml
  tests/zh-tw/_fixtures.yaml
  tests/zh-tw/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: de, lang: en, lang: nb, lang: fr, lang: sl, lang: hr, lang: cs, lang: lt, lang: ar, lang: pt, lang: fi, lang: is, lang: ko, lang: eu, lang: af

#1675 [RO] HassClimateGetTemperature attribute fix
  responses/ro/HassClimateGetTemperature.yaml
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ro

#1676 [cs] Fix light intents clashing with generic HassTurnOn/Off
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1677 [cs] Add todo domain (HassListAddItem) sentences
  responses/cs/HassListAddItem.yaml
  sentences/cs/todo_HassListAddItem.yaml
  tests/cs/_fixtures.yaml
  tests/cs/todo_HassListAddItem.yaml
Labels: cla-signed, lang: cs

#1681 [SL] ClimateHassGetTemperature attribute fix, added sentences and tests
  responses/sl/HassClimateGetTemperature.yaml
  sentences/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/_fixtures.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sl

#1682 [SL] grammar related fix in light response , added "izklopi" and "prižgi"
  responses/sl/HassTurnOff.yaml
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/light_HassTurnOff.yaml
  sentences/sl/light_HassTurnOn.yaml
  tests/sl/light_HassTurnOff.yaml
  tests/sl/light_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1684 [SL] added Nevermind sentences and tests
  sentences/sl/homeassistant_HassNevermind.yaml
  tests/sl/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sl

#1685 [SL] added shopping_list_HassShoppingListAddItem.yaml, sentences and tests, response, common fixed
  responses/sl/HassShoppingListAddItem.yaml
  sentences/sl/_common.yaml
  sentences/sl/shopping_list_HassShoppingListAddItem.yaml
  tests/sl/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: sl

#1686 [SL] added sceneHassTurnOn.yaml, sentence and tests
  sentences/sl/scene_HassTurnOn.yaml
  tests/sl/scene_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1687 [SL] added script_HassTurnOn, sentence and test, response
  sentences/sl/script_HassTurnOn.yaml
  tests/sl/script_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1688 [SL] added weather_HassGetWeather
  responses/sl/HassGetWeather.yaml
  sentences/sl/_common.yaml
  sentences/sl/weather_HassGetWeather.yaml
  tests/sl/_fixtures.yaml
  tests/sl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sl

#1689 [SL] added HassListAddItem, sentence, test, response, amended fixtures
  responses/sl/HassListAddItem.yaml
  sentences/sl/todo_HassListAddItem.yaml
  tests/sl/_fixtures.yaml
  tests/sl/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sl

#1690 [en] Fix weather sentences without a name
  sentences/en/weather_HassGetWeather.yaml
  shared/__init__.py
  tests/en/weather_HassGetWeather.yaml
Labels: cla-signed, lang: en

#1691 Es/2023.11.29
  sentences/es/weather_HassGetWeather.yaml
  tests/es/weather_HassGetWeather.yaml
Labels: cla-signed, lang: es

#1693 [SL] added person_HassGetState, sentences etc
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
  sentences/sl/person_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/person_HassGetState.yaml
Labels: cla-signed, lang: sl

#1694 [SL] added lock_HassGetState, lock_HassTurnOn, lock_HassTurnOff
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/lock_HassGetState.yaml
  sentences/sl/lock_HassTurnOff.yaml
  sentences/sl/lock_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/lock_HassGetState.yaml
  tests/sl/lock_HassTurnOff.yaml
  tests/sl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1696 [RO] Fix weather without name
  sentences/ro/weather_HassGetWeather.yaml
  tests/ro/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ro

#1680 [fr]Update _common.yaml: add « à, au » to <dans>
  sentences/fr/_common.yaml
Labels: cla-signed, lang: fr

#1679 [fr]Update climate_HassClimateGetTemperature.yaml: make <dans> optional
  sentences/fr/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: fr

#1692 [FR] Add device classes translation in sensor_HassGetState
  sentences/fr/lock_HassTurnOff.yaml
  sentences/fr/lock_HassTurnOn.yaml
  sentences/fr/sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1697 [RO] Fix context area for lights
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#1699 Fixing GetTemperature while providing device name
  sentences/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: es

#1700 Fixing issue #1695
  responses/es/HassClimateGetTemperature.yaml
  tests/es/_fixtures.yaml
Labels: cla-signed, lang: es
