Repository OHF-Voice/intents, pull requests merged in 2023-06, with the labels that each got.

#1279 DE translation brightness_level
  sentences/de/_common.yaml
  sentences/de/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de, cla-error

#1377 [DE] small improvements to fans
  sentences/de/_common.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1410 [DE] improve all lights
  sentences/de/_common.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de

#1418 [BG] Fix a typo
  sentences/bg/_common.yaml
Labels: cla-signed, lang: bg

#1408 [EU] Add Basque language
  languages.yaml
  responses/eu/HassClimateGetTemperature.yaml
  responses/eu/HassClimateSetTemperature.yaml
  responses/eu/HassGetState.yaml
  responses/eu/HassLightSet.yaml
  responses/eu/HassTurnOff.yaml
  responses/eu/HassTurnOn.yaml
  sentences/eu/_common.yaml
  sentences/eu/binary_sensor_HassGetState.yaml
  sentences/eu/climate_HassClimateGetTemperature.yaml
  sentences/eu/climate_HassClimateSetTemperature.yaml
  sentences/eu/cover_HassGetState.yaml
  sentences/eu/cover_HassTurnOff.yaml
  sentences/eu/cover_HassTurnOn.yaml
  sentences/eu/fan_HassTurnOff.yaml
  sentences/eu/fan_HassTurnOn.yaml
  sentences/eu/homeassistant_HassGetState.yaml
  sentences/eu/homeassistant_HassTurnOff.yaml
  sentences/eu/homeassistant_HassTurnOn.yaml
  sentences/eu/light_HassLightSet.yaml
  sentences/eu/light_HassTurnOff.yaml
  sentences/eu/light_HassTurnOn.yaml
  sentences/eu/lock_HassGetState.yaml
  sentences/eu/lock_HassTurnOff.yaml
  sentences/eu/lock_HassTurnOn.yaml
  sentences/eu/scene_HassTurnOn.yaml
  sentences/eu/script_HassTurnOn.yaml
  tests/eu/_fixtures.yaml
  tests/eu/binary_sensor_HassGetState.yaml
  tests/eu/climate_HassClimateGetTemperature.yaml
  tests/eu/climate_HassClimateSetTemperature.yaml
  tests/eu/cover_HassGetState.yaml
  tests/eu/cover_HassTurnOff.yaml
  tests/eu/cover_HassTurnOn.yaml
  tests/eu/fan_HassTurnOff.yaml
  tests/eu/fan_HassTurnOn.yaml
  tests/eu/homeassistant_HassGetState.yaml
  tests/eu/homeassistant_HassTurnOff.yaml
  tests/eu/homeassistant_HassTurnOn.yaml
  tests/eu/light_HassLightSet.yaml
  tests/eu/light_HassTurnOff.yaml
  tests/eu/light_HassTurnOn.yaml
  tests/eu/lock_HassGetState.yaml
  tests/eu/lock_HassTurnOff.yaml
  tests/eu/lock_HassTurnOn.yaml
  tests/eu/scene_HassTurnOn.yaml
  tests/eu/script_HassTurnOn.yaml
Labels: cla-signed, lang: eu

#1422 [KO] Update _common.yaml
  sentences/ko/_common.yaml
Labels: cla-signed, lang: ko

#1396 [KO] Update for light entities
  responses/ko/HassTurnOff.yaml
  responses/ko/HassTurnOn.yaml
  sentences/ko/_common.yaml
  sentences/ko/light_HassTurnOff.yaml
  sentences/ko/light_HassTurnOn.yaml
  tests/ko/_fixtures.yaml
  tests/ko/light_HassTurnOff.yaml
  tests/ko/light_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1395 [KO] Update for fan entities
  sentences/ko/fan_HassTurnOff.yaml
  sentences/ko/fan_HassTurnOn.yaml
  tests/ko/fan_HassTurnOff.yaml
  tests/ko/fan_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1394 [KO] Update for cover entities
  sentences/ko/cover_HassTurnOff.yaml
  sentences/ko/cover_HassTurnOn.yaml
  tests/ko/cover_HassTurnOff.yaml
  tests/ko/cover_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1423 Add ko language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1400 [KO] Add climate intents
  responses/ko/HassClimateGetTemperature.yaml
  responses/ko/HassClimateSetTemperature.yaml
  sentences/ko/climate_HassClimateGetTemperature.yaml
  sentences/ko/climate_HassClimateSetTemperature.yaml
  tests/ko/climate_HassClimateGetTemperature.yaml
  tests/ko/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ko

#1402 [KO] Add HassLightSet sentence and response
  responses/ko/HassLightSet.yaml
  sentences/ko/light_HassLightSet.yaml
  tests/ko/light_HassLightSet.yaml
Labels: cla-signed, lang: ko

#1403 [KO] Add scene and script intents
  responses/ko/HassTurnOn.yaml
  sentences/ko/scene_HassTurnOn.yaml
  sentences/ko/script_HassTurnOn.yaml
  tests/ko/_fixtures.yaml
  tests/ko/scene_HassTurnOn.yaml
  tests/ko/script_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1424 [KO] Add lock entities
  responses/ko/HassTurnOff.yaml
  responses/ko/HassTurnOn.yaml
  sentences/ko/_common.yaml
  sentences/ko/lock_HassTurnOff.yaml
  sentences/ko/lock_HassTurnOn.yaml
  tests/ko/_fixtures.yaml
  tests/ko/lock_HassTurnOff.yaml
  tests/ko/lock_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1425 [KO] Add HassGetState sentence and response
  responses/ko/HassGetState.yaml
  sentences/ko/_common.yaml
  sentences/ko/cover_HassGetState.yaml
  sentences/ko/homeassistant_HassGetState.yaml
  sentences/ko/lock_HassGetState.yaml
  tests/ko/_fixtures.yaml
  tests/ko/cover_HassGetState.yaml
  tests/ko/homeassistant_HassGetState.yaml
  tests/ko/lock_HassGetState.yaml
Labels: cla-signed, lang: ko

#1429 [KO] Updated missing spaces
  responses/ko/HassGetState.yaml
  tests/ko/binary_sensor_HassGetState.yaml
  tests/ko/cover_HassGetState.yaml
  tests/ko/lock_HassGetState.yaml
Labels: cla-signed, lang: ko

#1434 [NL] Add area to generic turn on and off
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1348 [te] Light on/Off for Telugu language
  sentences/te/light_HassTurnOff.yaml
  sentences/te/light_HassTurnOn.yaml
  tests/te/light_HassTurnOff.yaml
  tests/te/light_HassTurnOn.yaml
Labels: cla-signed, lang: te

#1438 [NB] Add binary sensors and locks
  responses/nb/HassLightSet.yaml
  responses/nb/HassTurnOff.yaml
  responses/nb/HassTurnOn.yaml
  sentences/nb/_common.yaml
  sentences/nb/binary_sensor_HassGetState.yaml
  sentences/nb/fan_HassTurnOff.yaml
  sentences/nb/fan_HassTurnOn.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  sentences/nb/light_HassLightSet.yaml
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  sentences/nb/lock_HassTurnOff.yaml
  sentences/nb/lock_HassTurnOn.yaml
  tests/nb/_fixtures.yaml
  tests/nb/binary_sensor_HassGetState.yaml
  tests/nb/fan_HassTurnOff.yaml
  tests/nb/fan_HassTurnOn.yaml
  tests/nb/light_HassLightSet.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
  tests/nb/lock_HassTurnOff.yaml
  tests/nb/lock_HassTurnOn.yaml
Labels: cla-signed, lang: nb
