Repository OHF-Voice/intents, pull requests merged in 2023-02, with the labels that each got.

#831 [SK] clear spaces
  sentences/sk/_common.yaml
  sentences/sk/climate_HassClimateGetTemperature.yaml
  sentences/sk/fan_HassTurnOff.yaml
  sentences/sk/fan_HassTurnOn.yaml
  sentences/sk/homeassistant_HassTurnOff.yaml
  sentences/sk/homeassistant_HassTurnOn.yaml
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
  tests/sk/_fixtures.yaml
Labels: cla-signed, lang: sk

#832 [SK] units fixes
  sentences/sk/_common.yaml
  tests/sk/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: sk

#840 [RO] some reviews and edits due to Hassil update
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ro

#839 Update HassClimateGetTemperature.yaml
  responses/mn/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: mn

#844 [CS] fixtures
  responses/cs/HassClimateGetTemperature.yaml
  responses/cs/HassClimateSetTemperature.yaml
  sentences/cs/_common.yaml
  sentences/cs/fan_HassTurnOff.yaml
  sentences/cs/fan_HassTurnOn.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/light_HassLightSet.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/climate_HassClimateSetTemperature.yaml
  tests/cs/homeassistant_HassTurnOff.yaml
  tests/cs/homeassistant_HassTurnOn.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: de, lang: en, lang: fr, lang: hu, lang: ca, lang: es, lang: hr, lang: cs, lang: el, lang: it, lang: da, lang: ka, lang: bg, lang: gl, lang: id, lang: lb

#849 [KA] Refine On/Off for Lights
  sentences/ka/_common.yaml
  sentences/ka/light_HassTurnOff.yaml
  sentences/ka/light_HassTurnOn.yaml
  tests/ka/light_HassTurnOff.yaml
  tests/ka/light_HassTurnOn.yaml
Labels: cla-signed, lang: ka

#851 Clean up some spaces and adding test
  sentences/sv/_common.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  tests/sv/homeassistant_HassTurnOff.yaml
  tests/sv/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#853 [KA] Translate responses
  responses/ka/HassClimateGetTemperature.yaml
  responses/ka/HassClimateSetTemperature.yaml
  responses/ka/HassLightSet.yaml
  responses/ka/HassTurnOff.yaml
  responses/ka/HassTurnOn.yaml
Labels: cla-signed, lang: ka

#848 [BG] add (°) for degree symbol and merge sentences
  sentences/bg/_common.yaml
  sentences/bg/climate_HassClimateGetTemperature.yaml
  sentences/bg/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: bg

#860 Remove extra spaces to conform the new parser
  responses/bg/HassClimateGetTemperature.yaml
  responses/bg/HassClimateSetTemperature.yaml
  responses/bg/HassLightSet.yaml
  responses/bg/HassTurnOff.yaml
  responses/bg/HassTurnOn.yaml
  sentences/bg/fan_HassTurnOn.yaml
  sentences/bg/homeassistant_HassTurnOff.yaml
  sentences/bg/homeassistant_HassTurnOn.yaml
  sentences/bg/light_HassLightSet.yaml
  sentences/bg/light_HassTurnOff.yaml
  sentences/bg/light_HassTurnOn.yaml
  tests/bg/_fixtures.yaml
  tests/bg/homeassistant_HassTurnOff.yaml
  tests/bg/homeassistant_HassTurnOn.yaml
  tests/bg/light_HassLightSet.yaml
  tests/bg/light_HassTurnOff.yaml
  tests/bg/light_HassTurnOn.yaml
Labels: cla-signed, lang: bg

#862 Uploading improvements in Spanish responses
  responses/es/HassClimateSetTemperature.yaml
  sentences/es/_common.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
  tests/es/fan_HassTurnOff.yaml
Labels: cla-signed, lang: es

#867 Added graag to skip words and make doe optional
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#756 Fix some dependencies regarding context
  script/intentfest/validate.py
  tests/test_language_intents.py
Labels: cla-signed

#878 [BG] new sentences after test ASSIST
  sentences/bg/_common.yaml
  sentences/bg/light_HassLightSet.yaml
  tests/bg/light_HassLightSet.yaml
Labels: cla-signed, lang: bg

#869 [RO] Updated sentences for SetLight
  sentences/ro/_common.yaml
  sentences/ro/light_HassLightSet.yaml
  tests/ro/light_HassLightSet.yaml
Labels: cla-signed, lang: ro

#880 Add 've' option to area in Czech.
  sentences/cs/_common.yaml
Labels: cla-signed, lang: cs

#843 [NL] Add fixed domain after name
  sentences/nl/_common.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/_fixtures.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#881 [NL] Add a an extra sentences for light_HassTurn(On | Off)
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#876 [NL] Review existing intents and update
  responses/nl/HassTurnOn.yaml
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/_fixtures.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassLightSet.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#891 [RU] Update sentences
  sentences/ru/_common.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateSetTemperature.yaml
  sentences/ru/homeassistant_HassTurnOff.yaml
  sentences/ru/homeassistant_HassTurnOn.yaml
  sentences/ru/light_HassLightSet.yaml
  tests/ru/fan_HassTurnOn.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/light_HassLightSet.yaml
Labels: cla-signed, lang: ru

#892 [RO] Context fixes and refactorings
  responses/ro/HassClimateGetTemperature.yaml
  responses/ro/HassClimateSetTemperature.yaml
  responses/ro/HassLightSet.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
  sentences/ro/fan_HassTurnOff.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassLightSet.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/climate_HassClimateSetTemperature.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#655 [PL] New expansion rules and usage in multiple tests, some optimizations
  sentences/pl/_common.yaml
  sentences/pl/climate_HassClimateSetTemperature.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  tests/pl/_fixtures.yaml
  tests/pl/climate_HassClimateSetTemperature.yaml
  tests/pl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#803 [PL] Updated polish translation, added responses, added more areas, added extra entities
  responses/pl/HassClimateGetTemperature.yaml
  responses/pl/HassClimateSetTemperature.yaml
  responses/pl/HassLightSet.yaml
  responses/pl/HassTurnOff.yaml
  responses/pl/HassTurnOn.yaml
  sentences/pl/climate_HassClimateGetTemperature.yaml
  sentences/pl/climate_HassClimateSetTemperature.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/homeassistant_HassTurnOff.yaml
  sentences/pl/homeassistant_HassTurnOn.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  tests/pl/_fixtures.yaml
  tests/pl/climate_HassClimateGetTemperature.yaml
  tests/pl/climate_HassClimateSetTemperature.yaml
  tests/pl/fan_HassTurnOff.yaml
  tests/pl/fan_HassTurnOn.yaml
  tests/pl/homeassistant_HassTurnOff.yaml
  tests/pl/homeassistant_HassTurnOn.yaml
  tests/pl/light_HassLightSet.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#889 [zh-tw] Added _common.yaml translation
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/climate_HassClimateGetTemperature.yaml
  tests/zh-tw/_fixtures.yaml
  tests/zh-tw/climate_HassClimateGetTemperature.yaml
Labels: cla-signed

#894 Hassil whitespace fix
  requirements.txt
  sentences/el/_common.yaml
  sentences/el/climate_HassClimateGetTemperature.yaml
  sentences/el/fan_HassTurnOff.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  sentences/he/climate_HassClimateSetTemperature.yaml
  sentences/it/_common.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  sentences/lv/_common.yaml
  sentences/lv/climate_HassClimateGetTemperature.yaml
  sentences/lv/homeassistant_HassTurnOff.yaml
  sentences/lv/homeassistant_HassTurnOn.yaml
  sentences/lv/light_HassLightSet.yaml
  sentences/uk/homeassistant_HassTurnOn.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
  tests/he/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: he, lang: el, lang: it, lang: uk, lang: lv

#865 [HE] Add more sentences
  sentences/he/_common.yaml
  sentences/he/light_HassTurnOff.yaml
  sentences/he/light_HassTurnOn.yaml
Labels: cla-signed, lang: he

#899 [HE] Hassil whitespace fix
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  sentences/he/climate_HassClimateSetTemperature.yaml
  sentences/he/fan_HassTurnOff.yaml
  sentences/he/fan_HassTurnOn.yaml
  sentences/he/homeassistant_HassTurnOff.yaml
  sentences/he/homeassistant_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
  tests/he/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: he

#895 [PL] Fixed entity typo in fixtures
  tests/pl/_fixtures.yaml
Labels: cla-signed, lang: pl

#828 [IT] Apply Style Guidelines
  responses/it/HassClimateGetTemperature.yaml
  responses/it/HassClimateSetTemperature.yaml
  responses/it/HassLightSet.yaml
  responses/it/HassTurnOff.yaml
  responses/it/HassTurnOn.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/light_HassLightSet.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  tests/it/_fixtures.yaml
  tests/it/climate_HassClimateGetTemperature.yaml
  tests/it/climate_HassClimateSetTemperature.yaml
  tests/it/fan_HassTurnOff.yaml
  tests/it/fan_HassTurnOn.yaml
  tests/it/homeassistant_HassTurnOff.yaml
  tests/it/homeassistant_HassTurnOn.yaml
  tests/it/light_HassLightSet.yaml
  tests/it/light_HassTurnOff.yaml
  tests/it/light_HassTurnOn.yaml
Labels: cla-signed, lang: it

#905 Updated responses for Icelandic language.
  responses/is/HassClimateGetTemperature.yaml
  responses/is/HassClimateSetTemperature.yaml
  responses/is/HassLightSet.yaml
  responses/is/HassTurnOff.yaml
  responses/is/HassTurnOn.yaml
Labels: cla-signed, lang: is

#904 [NB] Update of expansions
  sentences/nb/_common.yaml
  sentences/nb/light_HassTurnOn.yaml
  tests/nb/light_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#909 Update HassTurnOn.yaml
  responses/lb/HassTurnOn.yaml
Labels: cla-signed, lang: lb

#910 Update HassTurnOff.yaml
  responses/lb/HassTurnOff.yaml
Labels: cla-signed, lang: lb

#913 Bump hassil to 1.0.2 (skip words can ignore whitespace)
  requirements.txt
Labels: cla-signed

#914 [zh-tw] Update climate_HassClimateSetTemperature.yaml
  sentences/zh-tw/climate_HassClimateSetTemperature.yaml
  tests/zh-tw/climate_HassClimateSetTemperature.yaml
Labels: cla-signed

#908 [SV] Tuned nuances of responses
  responses/sv/HassLightSet.yaml
  responses/sv/HassTurnOff.yaml
  responses/sv/HassTurnOn.yaml
Labels: cla-signed, lang: sv

#917 [CS] Reponses fix
  responses/cs/HassLightSet.yaml
  responses/cs/HassTurnOff.yaml
  sentences/cs/_common.yaml
  sentences/cs/light_HassLightSet.yaml
  tests/cs/_fixtures.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#918 [RU] Add prep "на" to <area> parts
  sentences/ru/light_HassLightSet.yaml
Labels: cla-signed, lang: ru

#921 [RU] Remove duplicated preps from <area> parts
  sentences/ru/homeassistant_HassTurnOff.yaml
  sentences/ru/light_HassLightSet.yaml
  tests/ru/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ru

#925 [ZH-TW] Update light_HassTurnOn.yaml
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/light_HassTurnOn.yaml
  tests/zh-tw/light_HassTurnOn.yaml
Labels: cla-signed

#922 [NB] Add fans
  sentences/nb/_common.yaml
  sentences/nb/fan_HassTurnOff.yaml
  sentences/nb/fan_HassTurnOn.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  tests/nb/_fixtures.yaml
  tests/nb/fan_HassTurnOff.yaml
  tests/nb/fan_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#901 Portugues brasileiro
  languages.yaml
  responses/pt-br/HassClimateGetTemperature.yaml
  responses/pt-br/HassClimateSetTemperature.yaml
  responses/pt-br/HassLightSet.yaml
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/climate_HassClimateGetTemperature.yaml
  sentences/pt-br/climate_HassClimateSetTemperature.yaml
  sentences/pt-br/fan_HassTurnOff.yaml
  sentences/pt-br/fan_HassTurnOn.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  sentences/pt-br/light_HassLightSet.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/climate_HassClimateGetTemperature.yaml
  tests/pt-br/climate_HassClimateSetTemperature.yaml
  tests/pt-br/fan_HassTurnOff.yaml
  tests/pt-br/fan_HassTurnOn.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/homeassistant_HassTurnOn.yaml
  tests/pt-br/light_HassLightSet.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#870 [NB] Add set/get temperature
  sentences/nb/_common.yaml
  sentences/nb/climate_HassClimateGetTemperature.yaml
  sentences/nb/climate_HassClimateSetTemperature.yaml
  tests/nb/climate_HassClimateGetTemperature.yaml
  tests/nb/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nb

#936 Add nb language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#912 translate common.yaml for zh-hk
  responses/zh-hk/HassClimateGetTemperature.yaml
  responses/zh-hk/HassClimateSetTemperature.yaml
  responses/zh-hk/HassLightSet.yaml
  responses/zh-hk/HassTurnOff.yaml
  responses/zh-hk/HassTurnOn.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/climate_HassClimateGetTemperature.yaml
  sentences/zh-hk/climate_HassClimateSetTemperature.yaml
  sentences/zh-hk/fan_HassTurnOff.yaml
  sentences/zh-hk/fan_HassTurnOn.yaml
  sentences/zh-hk/light_HassTurnOff.yaml
  sentences/zh-hk/light_HassTurnOn.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/climate_HassClimateGetTemperature.yaml
  tests/zh-hk/climate_HassClimateSetTemperature.yaml
  tests/zh-hk/fan_HassTurnOff.yaml
  tests/zh-hk/fan_HassTurnOn.yaml
  tests/zh-hk/light_HassTurnOff.yaml
  tests/zh-hk/light_HassTurnOn.yaml
Labels: cla-signed

#938 [NB] Minor clean-ups of definitions
  sentences/nb/_common.yaml
  sentences/nb/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nb

#944 [CS] Fixing mix/min sentences for brightness (#938)
  sentences/cs/light_HassLightSet.yaml
Labels: cla-signed, lang: cs

#940 [NB] Fix sentences (updated parser rule)
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#896 [de-CH] Update files to consider additional dialects
  languages.yaml
  responses/de-CH/HassClimateGetTemperature.yaml
  responses/de-CH/HassClimateSetTemperature.yaml
  responses/de-CH/HassLightSet.yaml
  responses/de-CH/HassTurnOff.yaml
  responses/de-CH/HassTurnOn.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/fan_HassTurnOff.yaml
  sentences/de-CH/fan_HassTurnOn.yaml
  sentences/de-CH/homeassistant_HassTurnOff.yaml
  sentences/de-CH/homeassistant_HassTurnOn.yaml
  sentences/de-CH/light_HassLightSet.yaml
  sentences/de-CH/light_HassTurnOff.yaml
  sentences/de-CH/light_HassTurnOn.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/fan_HassTurnOff.yaml
  tests/de-CH/fan_HassTurnOn.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/light_HassLightSet.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
Labels: cla-signed

#946 [CS] One light entity fix
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#949 [de] Fix typo
  sentences/de/_common.yaml
Labels: cla-signed, lang: de

#957 [uk] Whitespaces
  sentences/uk/_common.yaml
  sentences/uk/homeassistant_HassTurnOff.yaml
  sentences/uk/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#858 Add definite form of "temperatur"
  sentences/sv/_common.yaml
  tests/sv/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sv

#960 [uk] Add responses to tests
  tests/uk/climate_HassClimateSetTemperature.yaml
  tests/uk/fan_HassTurnOff.yaml
  tests/uk/fan_HassTurnOn.yaml
  tests/uk/homeassistant_HassTurnOff.yaml
  tests/uk/homeassistant_HassTurnOn.yaml
  tests/uk/light_HassLightSet.yaml
  tests/uk/light_HassTurnOff.yaml
  tests/uk/light_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#954 Add polite questions to the NL sentences v2
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassLightSet.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#962 Modified fixtures, brightness expansion rule
  sentences/lb/_common.yaml
  sentences/lb/homeassistant_HassTurnOff.yaml
  sentences/lb/homeassistant_HassTurnOn.yaml
  tests/lb/_fixtures.yaml
  tests/lb/homeassistant_HassTurnOff.yaml
  tests/lb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: lb

#964 lb translations light_HassTurnOff / On
  responses/lb/HassLightSet.yaml
  responses/lb/HassTurnOff.yaml
  responses/lb/HassTurnOn.yaml
  sentences/lb/_common.yaml
  sentences/lb/homeassistant_HassTurnOff.yaml
  sentences/lb/light_HassTurnOff.yaml
  sentences/lb/light_HassTurnOn.yaml
  tests/lb/homeassistant_HassTurnOff.yaml
  tests/lb/light_HassTurnOff.yaml
  tests/lb/light_HassTurnOn.yaml
Labels: cla-signed, lang: lb

#968 Added lb light_HassLightSet sentences & responses
  responses/lb/HassLightSet.yaml
  sentences/lb/_common.yaml
  sentences/lb/light_HassLightSet.yaml
  tests/lb/light_HassLightSet.yaml
Labels: cla-signed, lang: lb

#970 Add description of HassGetState intent
  intents.yaml
Labels: cla-signed

#966 [de-CH] fix small typo
  responses/de-CH/HassTurnOff.yaml
Labels: cla-signed

#967 [de-CH] fix another small typo
  sentences/de-CH/_common.yaml
Labels: cla-signed

#973 Make je, jij and u optional
  sentences/nl/_common.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#956 [de-CH] add HassClimateGetTemperature and smaller changes
  responses/de-CH/HassClimateGetTemperature.yaml
  responses/de-CH/HassTurnOff.yaml
  responses/de-CH/HassTurnOn.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/climate_HassClimateGetTemperature.yaml
  sentences/de-CH/homeassistant_HassTurnOff.yaml
  sentences/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/climate_HassClimateGetTemperature.yaml
  tests/de-CH/light_HassLightSet.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
Labels: cla-signed

#963 [NL] Add expansion rule words
  sentences/nl/_common.yaml
Labels: cla-signed, lang: nl

#974 [NL] Capitalize first character of responses
  responses/nl/HassLightSet.yaml
  responses/nl/HassTurnOff.yaml
  responses/nl/HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#969 [NB] Min / max light brightness
  sentences/nb/_common.yaml
  sentences/nb/light_HassLightSet.yaml
  tests/nb/light_HassLightSet.yaml
Labels: cla-signed, lang: nb

#947 [HU] Response
  sentences/hu/climate_HassClimateSetTemperature.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#983 [SK] fix tests - case sensitivity
  tests/sk/_fixtures.yaml
  tests/sk/homeassistant_HassTurnOff.yaml
  tests/sk/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#984 [NB] HassGetState - first pass
  responses/nb/HassGetState.yaml
  sentences/nb/_common.yaml
  sentences/nb/homeassistant_HassGetState.yaml
  tests/nb/_fixtures.yaml
  tests/nb/homeassistant_HassGetState.yaml
  tests/nb/homeassistant_HassTurnOff.yaml
  tests/nb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#986 [VI] update HassGetState
  responses/vi/HassGetState.yaml
  sentences/vi/_common.yaml
  sentences/vi/cover_HassGetState.yaml
  sentences/vi/homeassistant_HassGetState.yaml
  tests/vi/_fixtures.yaml
  tests/vi/climate_HassClimateSetTemperature.yaml
  tests/vi/cover_HassGetState.yaml
  tests/vi/fan_HassTurnOn.yaml
  tests/vi/homeassistant_HassGetState.yaml
  tests/vi/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: vi

#987 [VI] Update HassGetState and HassTurnOn Response
  responses/vi/HassTurnOn.yaml
Labels: cla-signed, lang: vi

#988 Hebrew response fixes.
  responses/he/HassTurnOff.yaml
  responses/he/HassTurnOn.yaml
Labels: cla-signed, lang: he

#985 [NB] Adding covers
  sentences/nb/_common.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  tests/nb/homeassistant_HassTurnOff.yaml
  tests/nb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#993 [RO] Implemented HassGetState
  responses/ro/HassGetState.yaml
  sentences/ro/_common.yaml
  sentences/ro/cover_HassGetState.yaml
  sentences/ro/homeassistant_HassGetState.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/climate_HassClimateSetTemperature.yaml
  tests/ro/cover_HassGetState.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/homeassistant_HassGetState.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#995 Heb sentences
  sentences/he/fan_HassTurnOff.yaml
  sentences/he/fan_HassTurnOn.yaml
  sentences/he/homeassistant_HassTurnOff.yaml
  sentences/he/homeassistant_HassTurnOn.yaml
  tests/he/fan_HassTurnOff.yaml
  tests/he/fan_HassTurnOn.yaml
  tests/he/homeassistant_HassTurnOff.yaml
  tests/he/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: he

#996 [SK] ha get state
  responses/sk/HassGetState.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassGetState.yaml
  tests/sk/_fixtures.yaml
  tests/sk/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: sk

#981 [NL] First start for HassGetState
  responses/nl/HassGetState.yaml
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassGetState.yaml
  tests/nl/_fixtures.yaml
  tests/nl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nl

#958 Add more cover sentences for French
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1001 Allow in/out for states in test fixtures.
  script/intentfest/validate.py
  shared/__init__.py
Labels: cla-signed

#1003 Add fr-CA language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1005 Use hass state for comparsion
  shared/__init__.py
Labels: cla-signed

#991 [NB] Adding HassGetState for covers
  sentences/nb/_common.yaml
  sentences/nb/cover_HassGetState.yaml
  tests/nb/_fixtures.yaml
  tests/nb/cover_HassGetState.yaml
Labels: cla-signed, lang: nb

#1006 [NL] Use in/out states for fixtures
  responses/nl/HassGetState.yaml
  tests/nl/_fixtures.yaml
Labels: cla-signed, lang: nl

#999 [NL] HassGetState for covers
  responses/nl/HassGetState.yaml
  sentences/nl/_common.yaml
  sentences/nl/cover_HassGetState.yaml
  tests/nl/_fixtures.yaml
  tests/nl/cover_HassGetState.yaml
Labels: cla-signed, lang: nl

#1002 [NL] Add sentences and tests for homeassistant_HassGetState
  responses/nl/HassGetState.yaml
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassGetState.yaml
  tests/nl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nl

#1011 [NL] Avoid concatenation in response template
  responses/nl/HassGetState.yaml
Labels: cla-signed, lang: nl

#1016 [BG] Add curtains in to fixtures
  tests/bg/_fixtures.yaml
Labels: cla-signed, lang: bg

#1012 [NL] Apply template on all relevant responses
  responses/nl/HassGetState.yaml
  tests/nl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nl

#1017 [BG] Add fixtures state translations
  tests/bg/_fixtures.yaml
Labels: cla-signed, lang: bg

#961 [NL] alle/overal mandatory when turning all off
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/light_HassTurnOff.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/light_HassTurnOff.yaml
Labels: cla-signed, lang: nl

#1029 [zh-TW] Update Responses
  responses/zh-tw/HassClimateGetTemperature.yaml
  responses/zh-tw/HassClimateSetTemperature.yaml
  responses/zh-tw/HassLightSet.yaml
  responses/zh-tw/HassTurnOff.yaml
  responses/zh-tw/HassTurnOn.yaml
Labels: cla-signed

#1031 [RO] Several fixes for GetState, contexts and style guides
  responses/ro/HassGetState.yaml
  responses/ro/HassTurnOff.yaml
  responses/ro/HassTurnOn.yaml
  sentences/ro/_common.yaml
  sentences/ro/cover_HassGetState.yaml
  sentences/ro/cover_HassTurnOff.yaml
  sentences/ro/cover_HassTurnOn.yaml
  sentences/ro/homeassistant_HassGetState.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/climate_HassClimateSetTemperature.yaml
  tests/ro/cover_HassGetState.yaml
  tests/ro/cover_HassTurnOff.yaml
  tests/ro/cover_HassTurnOn.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/homeassistant_HassGetState.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/homeassistant_HassTurnOn.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#1010 [NB] Tidy up of _common
  sentences/nb/_common.yaml
Labels: cla-signed, lang: nb

#1007 [NB] Adding in/out values for fixtures
  tests/nb/_fixtures.yaml
  tests/nb/cover_HassGetState.yaml
  tests/nb/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nb

#1032 [NB] Correct translation of autogenerated cover tests
  tests/nb/cover_HassTurnOff.yaml
  tests/nb/cover_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#1034 Upgrade to hassil 1.0.5
  requirements.txt
  sentences/it/cover_HassTurnOff.yaml
  sentences/it/cover_HassTurnOn.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/sk/_common.yaml
  sentences/sv/_common.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-tw/_common.yaml
  shared/__init__.py
  tests/he/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: he, lang: sv, lang: it, lang: sk

#1038 [NL] Small change in response to turn off lights
  responses/nl/HassTurnOff.yaml
Labels: cla-signed, lang: nl

#1039 [zh-tw] Update T.Chinese translation.
  responses/zh-tw/HassLightSet.yaml
  responses/zh-tw/HassTurnOff.yaml
  responses/zh-tw/HassTurnOn.yaml
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/fan_HassTurnOff.yaml
  sentences/zh-tw/fan_HassTurnOn.yaml
  sentences/zh-tw/homeassistant_HassTurnOff.yaml
  sentences/zh-tw/homeassistant_HassTurnOn.yaml
  sentences/zh-tw/light_HassLightSet.yaml
  tests/zh-tw/fan_HassTurnOff.yaml
  tests/zh-tw/fan_HassTurnOn.yaml
  tests/zh-tw/homeassistant_HassTurnOff.yaml
  tests/zh-tw/homeassistant_HassTurnOn.yaml
  tests/zh-tw/light_HassLightSet.yaml
  tests/zh-tw/light_HassTurnOff.yaml
  tests/zh-tw/light_HassTurnOn.yaml
Labels: cla-signed

#1040 Clean up English
  intents.yaml
  responses/en/HassClimateGetTemperature.yaml
  responses/en/HassClimateSetTemperature.yaml
  responses/en/HassGetState.yaml
  responses/en/HassLightSet.yaml
  responses/en/HassTurnOff.yaml
  responses/en/HassTurnOn.yaml
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
  sentences/en/cover_HassGetState.yaml
  sentences/en/cover_HassTurnOff.yaml
  sentences/en/cover_HassTurnOn.yaml
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/light_HassLightSet.yaml
  shared/__init__.py
  tests/en/_fixtures.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateSetTemperature.yaml
  tests/en/cover_HassGetState.yaml
  tests/en/cover_HassTurnOff.yaml
  tests/en/cover_HassTurnOn.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1033 [NL] Change split covers
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1047 Whitespaces cleanup
  sentences/hr/_common.yaml
  sentences/hr/climate_HassClimateGetTemperature.yaml
  sentences/hr/climate_HassClimateSetTemperature.yaml
  sentences/hr/cover_HassTurnOff.yaml
  sentences/hr/cover_HassTurnOn.yaml
  sentences/hr/homeassistant_HassTurnOff.yaml
  sentences/hr/light_HassLightSet.yaml
  sentences/hr/light_HassTurnOff.yaml
  sentences/hr/light_HassTurnOn.yaml
  tests/hr/_fixtures.yaml
Labels: cla-signed, lang: hr

#1049 [CS] cover GetState
  responses/cs/HassGetState.yaml
  sentences/cs/_common.yaml
  sentences/cs/cover_HassGetState.yaml
  tests/cs/_fixtures.yaml
  tests/cs/cover_HassGetState.yaml
Labels: cla-signed, lang: cs

#1051 [CS] Fixing lights intents
  responses/cs/HassTurnOn.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1053 [zh-tw] Update Responses for T.Chinese
  responses/zh-tw/HassClimateGetTemperature.yaml
  responses/zh-tw/HassClimateSetTemperature.yaml
  responses/zh-tw/HassGetState.yaml
  responses/zh-tw/HassLightSet.yaml
  responses/zh-tw/HassTurnOff.yaml
  responses/zh-tw/HassTurnOn.yaml
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/homeassistant_HassTurnOff.yaml
  sentences/zh-tw/homeassistant_HassTurnOn.yaml
  sentences/zh-tw/light_HassLightSet.yaml
  tests/zh-tw/_fixtures.yaml
  tests/zh-tw/fan_HassTurnOff.yaml
  tests/zh-tw/fan_HassTurnOn.yaml
  tests/zh-tw/homeassistant_HassTurnOff.yaml
  tests/zh-tw/homeassistant_HassTurnOn.yaml
  tests/zh-tw/light_HassLightSet.yaml
  tests/zh-tw/light_HassTurnOff.yaml
  tests/zh-tw/light_HassTurnOn.yaml
Labels: cla-signed

#1055 [zh-tw] Update climate/cover files for T.Chinese
  sentences/zh-tw/climate_HassClimateSetTemperature.yaml
  sentences/zh-tw/cover_HassGetState.yaml
  sentences/zh-tw/cover_HassTurnOff.yaml
  sentences/zh-tw/cover_HassTurnOn.yaml
  sentences/zh-tw/light_HassTurnOff.yaml
  tests/zh-tw/climate_HassClimateGetTemperature.yaml
  tests/zh-tw/climate_HassClimateSetTemperature.yaml
  tests/zh-tw/cover_HassGetState.yaml
  tests/zh-tw/cover_HassTurnOff.yaml
  tests/zh-tw/cover_HassTurnOn.yaml
Labels: cla-signed

#1056 [zh-tw] Fix for on/off translation with responses
  responses/zh-tw/HassGetState.yaml
  tests/zh-tw/_fixtures.yaml
  tests/zh-tw/cover_HassGetState.yaml
  tests/zh-tw/homeassistant_HassGetState.yaml
Labels: cla-signed

#1041 [SK] - some fixes
  responses/sk/HassTurnOff.yaml
  responses/sk/HassTurnOn.yaml
  tests/sk/_fixtures.yaml
  tests/sk/cover_HassTurnOff.yaml
  tests/sk/cover_HassTurnOn.yaml
  tests/sk/fan_HassTurnOn.yaml
  tests/sk/light_HassTurnOff.yaml
Labels: cla-signed, lang: sk

#1008 [BG] Add HassGetState sentences for Bulgarian
  responses/bg/HassGetState.yaml
  sentences/bg/_common.yaml
  sentences/bg/cover_HassGetState.yaml
  tests/bg/cover_HassGetState.yaml
Labels: cla-signed, lang: bg

#990 [de-CH] implement HassGetState
  responses/de-CH/HassGetState.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/homeassistant_HassGetState.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/homeassistant_HassGetState.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/light_HassLightSet.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
Labels: cla-signed

#1061 [CS] Fix typo, adding sentence for garage door
  responses/cs/HassTurnOff.yaml
  responses/cs/HassTurnOn.yaml
  sentences/cs/_common.yaml
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  sentences/cs/fan_HassTurnOff.yaml
  sentences/cs/fan_HassTurnOn.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
  tests/cs/homeassistant_HassTurnOff.yaml
  tests/cs/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1009 [zh-cn] Add HassGetState for Simplified Chinese
  responses/zh-cn/HassGetState.yaml
  sentences/zh-cn/_common.yaml
  sentences/zh-cn/cover_HassGetState.yaml
  sentences/zh-cn/homeassistant_HassGetState.yaml
  tests/zh-cn/_fixtures.yaml
  tests/zh-cn/cover_HassGetState.yaml
  tests/zh-cn/homeassistant_HassGetState.yaml
Labels: cla-signed

#1064 Add zh-cn leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1063 Working on Hebrew
  responses/he/HassClimateSetTemperature.yaml
  responses/he/HassGetState.yaml
  responses/he/HassLightSet.yaml
  responses/he/HassTurnOff.yaml
  responses/he/HassTurnOn.yaml
Labels: cla-signed, lang: he

#926 [zh-cn] Updates for HassClimateGetTemperature
  sentences/zh-cn/_common.yaml
  sentences/zh-cn/climate_HassClimateGetTemperature.yaml
Labels: cla-signed

#971 [zh-cn] Updates for HassLightSet
  sentences/zh-cn/light_HassLightSet.yaml
Labels: cla-signed

#1069 [RO] Added light-specific responses
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#1072 Check for TODO in responses instead of directly comparing to English
  responses/ar/HassClimateGetTemperature.yaml
  responses/ar/HassClimateSetTemperature.yaml
  responses/ar/HassLightSet.yaml
  responses/ar/HassTurnOff.yaml
  responses/ar/HassTurnOn.yaml
  script/intentfest/add_language.py
  script/intentfest/website_summary.py
  sentences/ar/_common.yaml
  website/script/build
  website/script/develop
  website/src-11ty/_data/intentSummary.json
Labels: cla-signed, lang: ar

#1057 [hr] Covers rewrite
  responses/hr/HassTurnOff.yaml
  responses/hr/HassTurnOn.yaml
  sentences/hr/_common.yaml
  sentences/hr/cover_HassTurnOff.yaml
  sentences/hr/cover_HassTurnOn.yaml
  sentences/hr/homeassistant_HassTurnOff.yaml
  sentences/hr/homeassistant_HassTurnOn.yaml
  tests/hr/_fixtures.yaml
  tests/hr/cover_HassTurnOff.yaml
  tests/hr/cover_HassTurnOn.yaml
  tests/hr/homeassistant_HassTurnOff.yaml
  tests/hr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: hr

#1082 [zh-cn] Ignore whitespace for Simplified Chinese
  responses/zh-cn/HassClimateGetTemperature.yaml
  responses/zh-cn/HassClimateSetTemperature.yaml
  sentences/zh-cn/_common.yaml
  sentences/zh-cn/cover_HassGetState.yaml
  sentences/zh-cn/cover_HassTurnOn.yaml
  sentences/zh-cn/homeassistant_HassGetState.yaml
  sentences/zh-cn/homeassistant_HassTurnOff.yaml
  sentences/zh-cn/homeassistant_HassTurnOn.yaml
  sentences/zh-cn/light_HassLightSet.yaml
Labels: cla-signed

#1085 [zh-cn] Fix for Simplified Chinese
  responses/zh-cn/HassClimateGetTemperature.yaml
  responses/zh-cn/HassClimateSetTemperature.yaml
  responses/zh-cn/HassGetState.yaml
  sentences/zh-cn/cover_HassTurnOff.yaml
  sentences/zh-cn/cover_HassTurnOn.yaml
  sentences/zh-cn/homeassistant_HassTurnOff.yaml
  sentences/zh-cn/homeassistant_HassTurnOn.yaml
  tests/zh-cn/_fixtures.yaml
  tests/zh-cn/climate_HassClimateGetTemperature.yaml
  tests/zh-cn/climate_HassClimateSetTemperature.yaml
  tests/zh-cn/cover_HassGetState.yaml
  tests/zh-cn/cover_HassTurnOff.yaml
  tests/zh-cn/cover_HassTurnOn.yaml
  tests/zh-cn/homeassistant_HassGetState.yaml
  tests/zh-cn/homeassistant_HassTurnOff.yaml
  tests/zh-cn/homeassistant_HassTurnOn.yaml
Labels: cla-signed

#1071 [de-CH] Prepare sentences for all actions
  responses/de-CH/HassClimateSetTemperature.yaml
  responses/de-CH/HassGetState.yaml
  responses/de-CH/HassTurnOff.yaml
  responses/de-CH/HassTurnOn.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/climate_HassClimateSetTemperature.yaml
  sentences/de-CH/cover_HassGetState.yaml
  sentences/de-CH/cover_HassTurnOff.yaml
  sentences/de-CH/cover_HassTurnOn.yaml
  sentences/de-CH/homeassistant_HassGetState.yaml
  sentences/de-CH/homeassistant_HassTurnOff.yaml
  sentences/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/climate_HassClimateGetTemperature.yaml
  tests/de-CH/climate_HassClimateSetTemperature.yaml
  tests/de-CH/cover_HassGetState.yaml
  tests/de-CH/cover_HassTurnOff.yaml
  tests/de-CH/cover_HassTurnOn.yaml
  tests/de-CH/fan_HassTurnOff.yaml
  tests/de-CH/fan_HassTurnOn.yaml
  tests/de-CH/homeassistant_HassGetState.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
Labels: cla-signed, lang: gu

#1086 Feature/translating get response
  responses/es/HassGetState.yaml
  sentences/es/_common.yaml
  sentences/es/cover_HassGetState.yaml
  sentences/es/homeassistant_HassGetState.yaml
  tests/es/_fixtures.yaml
  tests/es/cover_HassGetState.yaml
  tests/es/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: es

#1083 More HassGetSentences for English
  package/pyproject.toml
  responses/en/HassTurnOn.yaml
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassGetState.yaml
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/lock_HassGetState.yaml
  sentences/en/scene_HassTurnOn.yaml
  sentences/en/script_HassTurnOn.yaml
  tests/__init__.py
  tests/en/_fixtures.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/lock_HassGetState.yaml
  tests/en/scene_HassTurnOn.yaml
  tests/en/script_HassTurnOn.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed, lang: en

#1091 [BG] Initial translation of homeassistant_HassGetState
  sentences/bg/homeassistant_HassGetState.yaml
  tests/bg/_fixtures.yaml
  tests/bg/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: bg

#1087 [uk] Added 'get state' translations
  responses/uk/HassGetState.yaml
  sentences/uk/_common.yaml
  sentences/uk/cover_HassGetState.yaml
  sentences/uk/homeassistant_HassGetState.yaml
  tests/uk/_fixtures.yaml
  tests/uk/cover_HassGetState.yaml
  tests/uk/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: uk

#1088 [De] Add myself as additional de language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed, lang: de

#1093 Add pt language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1081 SV: Adding GetState and response
  responses/sv/HassGetState.yaml
  sentences/sv/_common.yaml
  sentences/sv/homeassistant_HassGetState.yaml
  tests/sv/_fixtures.yaml
  tests/sv/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: sv

#1094 Switch de-CH leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1084 [UR] adding Hass Get state
  responses/ur/HassGetState.yaml
  sentences/en/homeassistant_HassGetState.yaml
  sentences/ur/_common.yaml
  sentences/ur/homeassistant_HassGetState.yaml
  tests/ur/_fixtures.yaml
  tests/ur/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en, lang: ur

#884 [PT] Add portuguese suggestion
  responses/pt/HassClimateSetTemperature.yaml
Labels: cla-signed, lang: pt

#1043 [PT] Responses Light
  responses/pt/HassLightSet.yaml
Labels: cla-signed, lang: pt

#1044 [PT] Responses Turn
  responses/pt/HassTurnOff.yaml
  responses/pt/HassTurnOn.yaml
Labels: cla-signed, lang: pt

#1098 [PT] Responses
  responses/pt/HassClimateGetTemperature.yaml
  responses/pt/HassLightSet.yaml
  responses/pt/HassTurnOff.yaml
  responses/pt/HassTurnOn.yaml
  sentences/pt/cover_HassTurnOff.yaml
  sentences/pt/cover_HassTurnOn.yaml
  tests/pt/cover_HassTurnOff.yaml
  tests/pt/cover_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#1099 [PT] Initial HassGetState
  responses/pt/HassGetState.yaml
  sentences/pt/_common.yaml
  sentences/pt/cover_HassGetState.yaml
  sentences/pt/homeassistant_HassGetState.yaml
  tests/pt/_fixtures.yaml
  tests/pt/cover_HassGetState.yaml
  tests/pt/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pt

#1100 [PT] HassGetState Cover
  sentences/pt/_common.yaml
  sentences/pt/cover_HassGetState.yaml
  tests/pt/_fixtures.yaml
  tests/pt/cover_HassGetState.yaml
Labels: cla-signed, lang: pt

#1101 [PT] HassGetState 3
  responses/pt/HassGetState.yaml
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassGetState.yaml
  tests/pt/_fixtures.yaml
  tests/pt/cover_HassGetState.yaml
  tests/pt/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pt

#1075 Added lb HassGetState responses
  responses/lb/HassGetState.yaml
  sentences/lb/_common.yaml
  sentences/lb/cover_HassGetState.yaml
  sentences/lb/homeassistant_HassGetState.yaml
  tests/lb/_fixtures.yaml
  tests/lb/cover_HassGetState.yaml
  tests/lb/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: lb

#1090 [NB] Shorter response according to style guide
  responses/nb/HassTurnOff.yaml
  responses/nb/HassTurnOn.yaml
  tests/nb/cover_HassTurnOff.yaml
  tests/nb/cover_HassTurnOn.yaml
  tests/nb/homeassistant_HassTurnOff.yaml
  tests/nb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#1103 Add lb responses with localised status feedback
  responses/lb/HassGetState.yaml
  tests/lb/_fixtures.yaml
  tests/lb/cover_HassGetState.yaml
  tests/lb/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: lb

#1097 [EN] Updates to the basic sentences
  responses/en/HassTurnOff.yaml
  sentences/en/_common.yaml
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/fan_HassTurnOn.yaml
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  sentences/en/scene_HassTurnOn.yaml
  sentences/en/script_HassTurnOn.yaml
  tests/en/_fixtures.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassTurnOff.yaml
  tests/en/homeassistant_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
  tests/en/scene_HassTurnOn.yaml
  tests/en/script_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1105 Add Finnish language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1106 Remove inactive leaders
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1109 Binary sensor sentences for English
  script/intentfest/add_language.py
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/binary_sensor_HassGetState.yaml
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  shared/__init__.py
  tests/bg/cover_HassTurnOff.yaml
  tests/bg/cover_HassTurnOn.yaml
  tests/en/_fixtures.yaml
  tests/en/binary_sensor_HassGetState.yaml
  tests/en/cover_HassTurnOff.yaml
  tests/en/cover_HassTurnOn.yaml
  tests/hr/cover_HassTurnOff.yaml
  tests/hr/cover_HassTurnOn.yaml
  tests/ro/cover_HassGetState.yaml
  tests/ro/cover_HassTurnOff.yaml
  tests/ro/cover_HassTurnOn.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
  tests/zh-cn/cover_HassTurnOff.yaml
  tests/zh-cn/cover_HassTurnOn.yaml
  tests/zh-tw/cover_HassTurnOff.yaml
  tests/zh-tw/cover_HassTurnOn.yaml
Labels: cla-signed, lang: en, lang: hr, lang: ro, lang: bg

#1078 ca: Updated and extended set climate
  sentences/ca/climate_HassClimateSetTemperature.yaml
  tests/ca/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ca

#1102 [NL] Update and add missing intents compared to EN
  responses/nl/HassClimateSetTemperature.yaml
  responses/nl/HassLightSet.yaml
  responses/nl/HassTurnOff.yaml
  responses/nl/HassTurnOn.yaml
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassGetState.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  sentences/nl/lock_HassGetState.yaml
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  tests/nl/_fixtures.yaml
  tests/nl/cover_HassTurnOn.yaml
  tests/nl/light_HassLightSet.yaml
  tests/nl/lock_HassGetState.yaml
  tests/nl/scene_HassTurnOn.yaml
  tests/nl/script_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1112 [PT] HassLightSet
  sentences/pt/_common.yaml
  sentences/pt/light_HassLightSet.yaml
Labels: cla-signed, lang: pt

#1114 [EN] Add "turn" to <set>
  sentences/en/_common.yaml
  tests/en/light_HassLightSet.yaml
Labels: cla-signed, lang: en

#1118 [de-CH] add sentences for lock
  sentences/de-CH/_common.yaml
  sentences/de-CH/homeassistant_HassGetState.yaml
  sentences/de-CH/lock_HassGetState.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/lock_HassGetState.yaml
Labels: cla-signed

#1119 [RO] Grammar fixes
  responses/ro/HassGetState.yaml
  responses/ro/HassLightSet.yaml
  responses/ro/HassTurnOff.yaml
  responses/ro/HassTurnOn.yaml
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
  sentences/ro/cover_HassGetState.yaml
  sentences/ro/cover_HassTurnOff.yaml
  sentences/ro/cover_HassTurnOn.yaml
  sentences/ro/fan_HassTurnOff.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/homeassistant_HassGetState.yaml
  sentences/ro/light_HassGetState.yaml
  sentences/ro/light_HassLightSet.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/cover_HassGetState.yaml
  tests/ro/cover_HassTurnOff.yaml
  tests/ro/cover_HassTurnOn.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/homeassistant_HassGetState.yaml
  tests/ro/light_HassGetState.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro
