Repository OHF-Voice/intents, pull requests merged in 2023-01, with the labels that each got.

#189 [NL] add variations for light toggling
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/_fixtures.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#219 Update light_HassTurnOn.yaml
  sentences/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#224 Add additional sentences for temperature requests
  sentences/en/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: en

#218 Update light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOff.yaml
Labels: cla-signed, lang: pt

#167 Add command to generate merged output
  script/intentfest/merged_output.py
  script/intentfest/util.py
Labels: cla-signed

#243 Rename brightness_pct to brightness
  intents.yaml
  sentences/ca/_common.yaml
  sentences/de/_common.yaml
  sentences/en/_common.yaml
  sentences/es/_common.yaml
  sentences/he/_common.yaml
  sentences/hu/_common.yaml
  sentences/it/_common.yaml
  sentences/nl/_common.yaml
  sentences/pl/_common.yaml
  sentences/pt/_common.yaml
  sentences/ro/_common.yaml
  sentences/ru/_common.yaml
  sentences/sk/_common.yaml
  sentences/sr/_common.yaml
  sentences/sv/_common.yaml
  sentences/uk/_common.yaml
  sentences/ur/_common.yaml
  tests/ca/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
  tests/en/light_HassLightSet.yaml
  tests/es/light_HassLightSet.yaml
  tests/he/light_HassLightSet.yaml
  tests/hu/light_HassLightSet.yaml
  tests/it/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
  tests/pl/light_HassLightSet.yaml
  tests/pt/light_HassLightSet.yaml
  tests/ro/light_HassLightSet.yaml
  tests/ru/light_HassLightSet.yaml
  tests/sk/light_HassLightSet.yaml
  tests/sr/light_HassLightSet.yaml
  tests/uk/light_HassLightSet.yaml
  tests/ur/light_HassLightSet.yaml
Labels: cla-signed, lang: de, lang: he, lang: en, lang: nl, lang: hu, lang: pl, lang: ca, lang: es, lang: sv, lang: ur, lang: it, lang: sr, lang: sk, lang: ro, lang: pt, lang: uk, lang: ru

#242 Update light_HassLightSet.yaml
  sentences/pt/light_HassLightSet.yaml
Labels: cla-signed, lang: pt

#241 [LT] Added Lithuanian language
  languages.yaml
  responses/lt/HassClimateGetTemperature.yaml
  sentences/lt/_common.yaml
  sentences/lt/climate_HassClimateGetTemperature.yaml
  sentences/lt/climate_HassClimateSetTemperature.yaml
  sentences/lt/cover_HassCloseCover.yaml
  sentences/lt/cover_HassOpenCover.yaml
  sentences/lt/fan_HassTurnOff.yaml
  sentences/lt/fan_HassTurnOn.yaml
  sentences/lt/homeassistant_HassTurnOff.yaml
  sentences/lt/homeassistant_HassTurnOn.yaml
  sentences/lt/light_HassLightSet.yaml
  sentences/lt/light_HassTurnOff.yaml
  sentences/lt/light_HassTurnOn.yaml
  tests/lt/_fixtures.yaml
  tests/lt/climate_HassClimateGetTemperature.yaml
  tests/lt/climate_HassClimateSetTemperature.yaml
  tests/lt/cover_HassCloseCover.yaml
  tests/lt/cover_HassOpenCover.yaml
  tests/lt/fan_HassTurnOff.yaml
  tests/lt/fan_HassTurnOn.yaml
  tests/lt/homeassistant_HassTurnOff.yaml
  tests/lt/homeassistant_HassTurnOn.yaml
  tests/lt/light_HassLightSet.yaml
  tests/lt/light_HassTurnOff.yaml
  tests/lt/light_HassTurnOn.yaml
Labels: cla-signed, lang: lt

#238 Improve Danish error responses
  sentences/da/_common.yaml
Labels: cla-signed, lang: da

#251 Update _common.yaml
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#262 [PL] removed hardcoded device name
  sentences/pl/light_HassLightSet.yaml
Labels: cla-signed, lang: pl

#249 Improve Danish homeassistant sentences
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassTurnOff.yaml
  sentences/da/homeassistant_HassTurnOn.yaml
  tests/da/_fixtures.yaml
  tests/da/homeassistant_HassTurnOff.yaml
  tests/da/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: da

#275 Revert "Update _common.yaml"
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#256 Update cover_HassCloseCover.yaml
  sentences/en/cover_HassCloseCover.yaml
Labels: cla-signed, lang: en

#255 Update climate_HassClimateSetTemperature.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: en

#254 Update homeassistant_HassTurnOn.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: en

#282 Fix expected slots for Hebrew tests
  tests/he/climate_HassClimateSetTemperature.yaml
  tests/he/cover_HassCloseCover.yaml
  tests/he/cover_HassOpenCover.yaml
  tests/he/fan_HassTurnOff.yaml
  tests/he/fan_HassTurnOn.yaml
  tests/he/light_HassLightSet.yaml
  tests/he/light_HassTurnOn.yaml
Labels: cla-signed, lang: he

#280 Fix expected slots for Spanish tests
  tests/es/cover_HassCloseCover.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#281 Fix expected slots for French tests
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#279 Fix expected slots for English tests
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#283 Fix expected slots for Hungarian tests
  tests/hu/cover_HassCloseCover.yaml
  tests/hu/cover_HassOpenCover.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#278 Fix German expected slots for German tests
  tests/de/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: de

#288 Fix expected slots for Polish tests
  tests/pl/light_HassLightSet.yaml
Labels: cla-signed, lang: pl

#287 Fix expected slots for Dutch tests
  tests/nl/cover_HassCloseCover.yaml
  tests/nl/light_HassLightSet.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#285 Fix expected slots for Lithuanian tests
  tests/lt/homeassistant_HassTurnOff.yaml
  tests/lt/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: lt

#292 Fix expected slots for Slovakian tests
  tests/sk/light_HassLightSet.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#291 Fix expected slots for Russian tests
  tests/ru/light_HassLightSet.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#290 Fix expected slots for Romanian tests
  tests/ro/light_HassLightSet.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#289 Fix expected slots for Portugese tests
  tests/pt/light_HassLightSet.yaml
  tests/pt/light_HassTurnOff.yaml
  tests/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#293 Fix expected slots for Ukranian tests
  tests/uk/light_HassLightSet.yaml
Labels: cla-signed, lang: uk

#294 Fix expected slots for Urdu tests
  tests/ur/climate_HassClimateSetTemperature.yaml
  tests/ur/light_HassLightSet.yaml
  tests/ur/light_HassTurnOn.yaml
Labels: cla-signed, lang: ur

#284 Fix expected slots for Italian tests
  tests/it/cover_HassCloseCover.yaml
  tests/it/cover_HassOpenCover.yaml
  tests/it/light_HassLightSet.yaml
Labels: cla-signed, lang: it

#277 Expect tests to specify all matched slots
  tests/test_language_sentences.py
Labels: cla-signed

#301 Added more intents for Urdu
  sentences/ur/_common.yaml
  sentences/ur/climate_HassClimateGetTemperature.yaml
  sentences/ur/cover_HassOpenCover.yaml
  sentences/ur/homeassistant_HassTurnOn.yaml
  sentences/ur/light_HassTurnOn.yaml
  tests/ur/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ur

#308 Update climate_HassClimateGetTemperature.yaml
  sentences/it/_common.yaml
  tests/it/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: it

#298 Restored and fixed pull request #251
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#336 Re-organize tests for Catalan
  sentences/ca/fan_HassTurnOff.yaml
  sentences/ca/fan_HassTurnOn.yaml
  tests/ca/fan_HassTurnOff.yaml
  tests/ca/fan_HassTurnOn.yaml
  tests/ca/homeassistant_HassTurnOff.yaml
  tests/ca/homeassistant_HassTurnOn.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#341 Re-organize tests for German
  tests/de/homeassistant_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#343 Re-organize tests for Polish
  tests/pl/homeassistant_HassTurnOff.yaml
  tests/pl/homeassistant_HassTurnOn.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#335 Validate that domain tests only test domain sentences
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#246 [SV] Add improvements to Swedish language
  sentences/sv/_common.yaml
  sentences/sv/climate_HassClimateGetTemperature.yaml
  sentences/sv/fan_HassTurnOn.yaml
  sentences/sv/homeassistant_HassTurnOff.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  sentences/sv/light_HassTurnOff.yaml
  sentences/sv/light_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/climate_HassClimateGetTemperature.yaml
  tests/sv/homeassistant_HassTurnOn.yaml
  tests/sv/light_HassTurnOff.yaml
  tests/sv/light_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#239 [FA] Initial Persian Support
  languages.yaml
  responses/fa/HassClimateGetTemperature.yaml
  sentences/fa/_common.yaml
  sentences/fa/climate_HassClimateGetTemperature.yaml
  sentences/fa/climate_HassClimateSetTemperature.yaml
  sentences/fa/cover_HassCloseCover.yaml
  sentences/fa/cover_HassOpenCover.yaml
  sentences/fa/fan_HassTurnOff.yaml
  sentences/fa/fan_HassTurnOn.yaml
  sentences/fa/homeassistant_HassTurnOff.yaml
  sentences/fa/homeassistant_HassTurnOn.yaml
  sentences/fa/light_HassLightSet.yaml
  sentences/fa/light_HassTurnOff.yaml
  sentences/fa/light_HassTurnOn.yaml
  tests/fa/_fixtures.yaml
  tests/fa/climate_HassClimateGetTemperature.yaml
  tests/fa/climate_HassClimateSetTemperature.yaml
  tests/fa/cover_HassCloseCover.yaml
  tests/fa/cover_HassOpenCover.yaml
  tests/fa/fan_HassTurnOff.yaml
  tests/fa/fan_HassTurnOn.yaml
  tests/fa/homeassistant_HassTurnOff.yaml
  tests/fa/homeassistant_HassTurnOn.yaml
  tests/fa/light_HassLightSet.yaml
  tests/fa/light_HassTurnOff.yaml
  tests/fa/light_HassTurnOn.yaml
Labels: cla-signed, lang: fa

#232 Update homeassistant_HassTurnOn.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: es

#236 [EL] Greek initial support
  sentences/el/_common.yaml
  sentences/el/homeassistant_HassTurnOff.yaml
  sentences/el/homeassistant_HassTurnOn.yaml
  tests/el/_fixtures.yaml
  tests/el/homeassistant_HassTurnOff.yaml
  tests/el/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: el

#362 Ensure YAML indent is correct for HA linter
  script/intentfest/add_language.py
  script/intentfest/merged_output.py
  script/intentfest/util.py
Labels: cla-signed

#364 Add empty Hindi templates (hi)
  languages.yaml
  responses/hi/HassClimateGetTemperature.yaml
  sentences/hi/_common.yaml
  sentences/hi/climate_HassClimateGetTemperature.yaml
  sentences/hi/climate_HassClimateSetTemperature.yaml
  sentences/hi/cover_HassCloseCover.yaml
  sentences/hi/cover_HassOpenCover.yaml
  sentences/hi/fan_HassTurnOff.yaml
  sentences/hi/fan_HassTurnOn.yaml
  sentences/hi/homeassistant_HassTurnOff.yaml
  sentences/hi/homeassistant_HassTurnOn.yaml
  sentences/hi/light_HassLightSet.yaml
  sentences/hi/light_HassTurnOff.yaml
  sentences/hi/light_HassTurnOn.yaml
  tests/hi/_fixtures.yaml
  tests/hi/climate_HassClimateGetTemperature.yaml
  tests/hi/climate_HassClimateSetTemperature.yaml
  tests/hi/cover_HassCloseCover.yaml
  tests/hi/cover_HassOpenCover.yaml
  tests/hi/fan_HassTurnOff.yaml
  tests/hi/fan_HassTurnOn.yaml
  tests/hi/homeassistant_HassTurnOff.yaml
  tests/hi/homeassistant_HassTurnOn.yaml
  tests/hi/light_HassLightSet.yaml
  tests/hi/light_HassTurnOff.yaml
  tests/hi/light_HassTurnOn.yaml
Labels: cla-signed, lang: hi

#354 Validate non domain files
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  tests/ca/homeassistant_HassTurnOff.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOn.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed, lang: fr, lang: ca

#317 [LT] Added temperature control sentences
  sentences/lt/_common.yaml
  sentences/lt/climate_HassClimateGetTemperature.yaml
  sentences/lt/climate_HassClimateSetTemperature.yaml
  tests/lt/_fixtures.yaml
  tests/lt/climate_HassClimateGetTemperature.yaml
  tests/lt/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: lt

#377 Add el leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#380 Add Swahilli
  languages.yaml
  responses/sw/HassClimateGetTemperature.yaml
  sentences/sw/_common.yaml
  sentences/sw/climate_HassClimateGetTemperature.yaml
  sentences/sw/climate_HassClimateSetTemperature.yaml
  sentences/sw/cover_HassCloseCover.yaml
  sentences/sw/cover_HassOpenCover.yaml
  sentences/sw/fan_HassTurnOff.yaml
  sentences/sw/fan_HassTurnOn.yaml
  sentences/sw/homeassistant_HassTurnOff.yaml
  sentences/sw/homeassistant_HassTurnOn.yaml
  sentences/sw/light_HassLightSet.yaml
  sentences/sw/light_HassTurnOff.yaml
  sentences/sw/light_HassTurnOn.yaml
  tests/sw/_fixtures.yaml
  tests/sw/climate_HassClimateGetTemperature.yaml
  tests/sw/climate_HassClimateSetTemperature.yaml
  tests/sw/cover_HassCloseCover.yaml
  tests/sw/cover_HassOpenCover.yaml
  tests/sw/fan_HassTurnOff.yaml
  tests/sw/fan_HassTurnOn.yaml
  tests/sw/homeassistant_HassTurnOff.yaml
  tests/sw/homeassistant_HassTurnOn.yaml
  tests/sw/light_HassLightSet.yaml
  tests/sw/light_HassTurnOff.yaml
  tests/sw/light_HassTurnOn.yaml
Labels: cla-signed, lang: sw

#376 Add Danish fan sentences
  sentences/da/_common.yaml
  sentences/da/fan_HassTurnOff.yaml
  sentences/da/fan_HassTurnOn.yaml
  tests/da/fan_HassTurnOff.yaml
  tests/da/fan_HassTurnOn.yaml
Labels: cla-signed, lang: da

#383 Add da leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#237 Add turn_on/off(_light) expansion rules for czech
  sentences/cs/_common.yaml
Labels: cla-signed, lang: cs

#384 Tweaks to scripts
  .vscode/tasks.json
  pylintrc
  pyproject.toml
  script/intentfest/add_language.py
  script/intentfest/util.py
  script/intentfest/validate.py
  tests/test_language_sentences.py
Labels: cla-signed

#378 [EL] Climate extension/support
  sentences/el/_common.yaml
  sentences/el/climate_HassClimateGetTemperature.yaml
  sentences/el/climate_HassClimateSetTemperature.yaml
  tests/el/_fixtures.yaml
  tests/el/climate_HassClimateGetTemperature.yaml
  tests/el/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: el

#260 [PL] Update cover opening sentences
  sentences/pl/cover_HassOpenCover.yaml
Labels: cla-signed, lang: pl

#386 Add da MTrab
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#379 [FR] Add more sentences
  sentences/fr/_common.yaml
  sentences/fr/climate_HassClimateGetTemperature.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  sentences/fr/cover_HassCloseCover.yaml
  sentences/fr/cover_HassOpenCover.yaml
  sentences/fr/fan_HassTurnOff.yaml
  tests/fr/_fixtures.yaml
  tests/fr/climate_HassClimateGetTemperature.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/cover_HassCloseCover.yaml
  tests/fr/cover_HassOpenCover.yaml
Labels: cla-signed, lang: fr

#319 [RO] HassClimateGetTemperature and a synonym
  responses/ro/HassClimateGetTemperature.yaml
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  tests/ro/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ro

#253 Adding more words to HassOpenCover and HassCloseCover in Polish
  sentences/pl/cover_HassCloseCover.yaml
  sentences/pl/cover_HassOpenCover.yaml
Labels: cla-signed, lang: pl

#402 Add language leader for sr
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#418 Add Malay (ms) templates
  languages.yaml
  responses/ms/HassClimateGetTemperature.yaml
  sentences/ms/_common.yaml
  sentences/ms/climate_HassClimateGetTemperature.yaml
  sentences/ms/climate_HassClimateSetTemperature.yaml
  sentences/ms/cover_HassCloseCover.yaml
  sentences/ms/cover_HassOpenCover.yaml
  sentences/ms/fan_HassTurnOff.yaml
  sentences/ms/fan_HassTurnOn.yaml
  sentences/ms/homeassistant_HassTurnOff.yaml
  sentences/ms/homeassistant_HassTurnOn.yaml
  sentences/ms/light_HassLightSet.yaml
  sentences/ms/light_HassTurnOff.yaml
  sentences/ms/light_HassTurnOn.yaml
  tests/ms/_fixtures.yaml
  tests/ms/climate_HassClimateGetTemperature.yaml
  tests/ms/climate_HassClimateSetTemperature.yaml
  tests/ms/cover_HassCloseCover.yaml
  tests/ms/cover_HassOpenCover.yaml
  tests/ms/fan_HassTurnOff.yaml
  tests/ms/fan_HassTurnOn.yaml
  tests/ms/homeassistant_HassTurnOff.yaml
  tests/ms/homeassistant_HassTurnOn.yaml
  tests/ms/light_HassLightSet.yaml
  tests/ms/light_HassTurnOff.yaml
  tests/ms/light_HassTurnOn.yaml
Labels: cla-signed, lang: ms

#421 Add Telugu (te) templates
  languages.yaml
  responses/te/HassClimateGetTemperature.yaml
  sentences/te/_common.yaml
  sentences/te/climate_HassClimateGetTemperature.yaml
  sentences/te/climate_HassClimateSetTemperature.yaml
  sentences/te/cover_HassCloseCover.yaml
  sentences/te/cover_HassOpenCover.yaml
  sentences/te/fan_HassTurnOff.yaml
  sentences/te/fan_HassTurnOn.yaml
  sentences/te/homeassistant_HassTurnOff.yaml
  sentences/te/homeassistant_HassTurnOn.yaml
  sentences/te/light_HassLightSet.yaml
  sentences/te/light_HassTurnOff.yaml
  sentences/te/light_HassTurnOn.yaml
  tests/te/_fixtures.yaml
  tests/te/climate_HassClimateGetTemperature.yaml
  tests/te/climate_HassClimateSetTemperature.yaml
  tests/te/cover_HassCloseCover.yaml
  tests/te/cover_HassOpenCover.yaml
  tests/te/fan_HassTurnOff.yaml
  tests/te/fan_HassTurnOn.yaml
  tests/te/homeassistant_HassTurnOff.yaml
  tests/te/homeassistant_HassTurnOn.yaml
  tests/te/light_HassLightSet.yaml
  tests/te/light_HassTurnOff.yaml
  tests/te/light_HassTurnOn.yaml
Labels: cla-signed, lang: te

#428 Add Icelandic (is) templates
  languages.yaml
  responses/is/HassClimateGetTemperature.yaml
  sentences/is/_common.yaml
  sentences/is/climate_HassClimateGetTemperature.yaml
  sentences/is/climate_HassClimateSetTemperature.yaml
  sentences/is/cover_HassCloseCover.yaml
  sentences/is/cover_HassOpenCover.yaml
  sentences/is/fan_HassTurnOff.yaml
  sentences/is/fan_HassTurnOn.yaml
  sentences/is/homeassistant_HassTurnOff.yaml
  sentences/is/homeassistant_HassTurnOn.yaml
  sentences/is/light_HassLightSet.yaml
  sentences/is/light_HassTurnOff.yaml
  sentences/is/light_HassTurnOn.yaml
  tests/is/_fixtures.yaml
  tests/is/climate_HassClimateGetTemperature.yaml
  tests/is/climate_HassClimateSetTemperature.yaml
  tests/is/cover_HassCloseCover.yaml
  tests/is/cover_HassOpenCover.yaml
  tests/is/fan_HassTurnOff.yaml
  tests/is/fan_HassTurnOn.yaml
  tests/is/homeassistant_HassTurnOff.yaml
  tests/is/homeassistant_HassTurnOn.yaml
  tests/is/light_HassLightSet.yaml
  tests/is/light_HassTurnOff.yaml
  tests/is/light_HassTurnOn.yaml
Labels: cla-signed, lang: is

#415 Add Danish light set sentences
  sentences/da/_common.yaml
  sentences/da/light_HassLightSet.yaml
  tests/da/light_HassLightSet.yaml
Labels: cla-signed, lang: da

#438 Initial commit of _common.yaml in bulgarian language
  sentences/bg/_common.yaml
Labels: cla-signed, lang: bg

#401 czech language for ClimateGetTemperature
  sentences/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/_fixtures.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: cs

#396 [FR] Add reponse for HassClimateGetTemperature
  responses/fr/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: fr

#404 Add Danish cover sentences
  sentences/da/_common.yaml
  sentences/da/cover_HassCloseCover.yaml
  sentences/da/cover_HassOpenCover.yaml
  tests/da/_fixtures.yaml
  tests/da/cover_HassCloseCover.yaml
  tests/da/cover_HassOpenCover.yaml
Labels: cla-signed, lang: da

#390 Slot values no dict
  script/intentfest/validate.py
  tests/ca/cover_HassOpenCover.yaml
  tests/en/cover_HassCloseCover.yaml
  tests/en/cover_HassOpenCover.yaml
  tests/es/cover_HassCloseCover.yaml
  tests/es/cover_HassOpenCover.yaml
  tests/fr/cover_HassCloseCover.yaml
  tests/fr/cover_HassOpenCover.yaml
  tests/hu/cover_HassOpenCover.yaml
  tests/pl/cover_HassCloseCover.yaml
  tests/pl/cover_HassOpenCover.yaml
  tests/pt/cover_HassCloseCover.yaml
  tests/pt/cover_HassOpenCover.yaml
  tests/ru/cover_HassCloseCover.yaml
  tests/ru/cover_HassOpenCover.yaml
  tests/test_language_sentences.py
  tests/uk/cover_HassCloseCover.yaml
  tests/uk/cover_HassOpenCover.yaml
Labels: cla-signed, lang: en, lang: fr, lang: hu, lang: pl, lang: ca, lang: es, lang: pt, lang: uk, lang: ru

#436 [ES] Improve area expansion to support for masculine areas
  sentences/es/_common.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#440 Fixed typo for temp value
  sentences/bg/_common.yaml
Labels: cla-signed, lang: bg

#450 fix isuues > discussions link
  README.md
Labels: cla-signed

#446 Turkish Climate and Common Comit
  responses/tr/HassClimateGetTemperature.yaml
  sentences/tr/_common.yaml
  sentences/tr/climate_HassClimateGetTemperature.yaml
  tests/tr/_fixtures.yaml
  tests/tr/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: tr

#397 [LV] Add Latvian language
  languages.yaml
  responses/lv/HassClimateGetTemperature.yaml
  sentences/lv/_common.yaml
  sentences/lv/climate_HassClimateGetTemperature.yaml
  sentences/lv/climate_HassClimateSetTemperature.yaml
  sentences/lv/cover_HassCloseCover.yaml
  sentences/lv/cover_HassOpenCover.yaml
  sentences/lv/fan_HassTurnOff.yaml
  sentences/lv/fan_HassTurnOn.yaml
  sentences/lv/homeassistant_HassTurnOff.yaml
  sentences/lv/homeassistant_HassTurnOn.yaml
  sentences/lv/light_HassLightSet.yaml
  sentences/lv/light_HassTurnOff.yaml
  sentences/lv/light_HassTurnOn.yaml
  tests/lv/_fixtures.yaml
  tests/lv/climate_HassClimateGetTemperature.yaml
  tests/lv/climate_HassClimateSetTemperature.yaml
  tests/lv/cover_HassCloseCover.yaml
  tests/lv/cover_HassOpenCover.yaml
  tests/lv/fan_HassTurnOff.yaml
  tests/lv/fan_HassTurnOn.yaml
  tests/lv/homeassistant_HassTurnOff.yaml
  tests/lv/homeassistant_HassTurnOn.yaml
  tests/lv/light_HassLightSet.yaml
  tests/lv/light_HassTurnOff.yaml
  tests/lv/light_HassTurnOn.yaml
Labels: cla-signed, lang: lv

#453 [ML] Add Malayalam language
  languages.yaml
  responses/ml/HassClimateGetTemperature.yaml
  sentences/ml/_common.yaml
  sentences/ml/climate_HassClimateGetTemperature.yaml
  sentences/ml/climate_HassClimateSetTemperature.yaml
  sentences/ml/cover_HassCloseCover.yaml
  sentences/ml/cover_HassOpenCover.yaml
  sentences/ml/fan_HassTurnOff.yaml
  sentences/ml/fan_HassTurnOn.yaml
  sentences/ml/homeassistant_HassTurnOff.yaml
  sentences/ml/homeassistant_HassTurnOn.yaml
  sentences/ml/light_HassLightSet.yaml
  sentences/ml/light_HassTurnOff.yaml
  sentences/ml/light_HassTurnOn.yaml
  tests/ml/_fixtures.yaml
  tests/ml/climate_HassClimateGetTemperature.yaml
  tests/ml/climate_HassClimateSetTemperature.yaml
  tests/ml/cover_HassCloseCover.yaml
  tests/ml/cover_HassOpenCover.yaml
  tests/ml/fan_HassTurnOff.yaml
  tests/ml/fan_HassTurnOn.yaml
  tests/ml/homeassistant_HassTurnOff.yaml
  tests/ml/homeassistant_HassTurnOn.yaml
  tests/ml/light_HassLightSet.yaml
  tests/ml/light_HassTurnOff.yaml
  tests/ml/light_HassTurnOn.yaml
Labels: cla-signed, lang: ml

#449 Initial changes for ms (Malay Language/Bahasa Melayu)
  languages.yaml
  sentences/ms/_common.yaml
Labels: cla-signed, lang: ms

#318 Update _common.yaml
  sentences/sl/_common.yaml
Labels: cla-signed, lang: sl

#442 Update _common.yaml
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#441 Add temperature and its tests in bulgarian
  sentences/bg/_common.yaml
  sentences/bg/climate_HassClimateGetTemperature.yaml
  tests/bg/_fixtures.yaml
  tests/bg/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: bg

#464 Hassil 0.2
  requirements.txt
  sentences/ca/light_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  tests/ca/light_HassTurnOn.yaml
  tests/he/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: he, lang: nl, lang: ca

#461 [LV] Add more to common
  sentences/lv/_common.yaml
  sentences/lv/homeassistant_HassTurnOff.yaml
  sentences/lv/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: lv

#468 Add Set Temperature and its tests in bulgarian language
  sentences/bg/_common.yaml
  sentences/bg/climate_HassClimateSetTemperature.yaml
  tests/bg/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: bg

#476 Add cs language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#479 Czech- climate domain
  sentences/cs/_common.yaml
  sentences/cs/climate_HassClimateGetTemperature.yaml
  sentences/cs/climate_HassClimateSetTemperature.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/climate_HassClimateSetTemperature.yaml
  tests/cs/homeassistant_HassTurnOff.yaml
  tests/cs/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#475 [BG] Add sentences for light
  responses/bg/HassClimateGetTemperature.yaml
  sentences/bg/_common.yaml
  sentences/bg/light_HassLightSet.yaml
  sentences/bg/light_HassTurnOff.yaml
  sentences/bg/light_HassTurnOn.yaml
  tests/bg/_fixtures.yaml
  tests/bg/light_HassLightSet.yaml
  tests/bg/light_HassTurnOff.yaml
  tests/bg/light_HassTurnOn.yaml
Labels: cla-signed, lang: bg

#472 Set light intensity for swedish
  sentences/sv/_common.yaml
  sentences/sv/light_HassLightSet.yaml
  tests/sv/_fixtures.yaml
  tests/sv/light_HassLightSet.yaml
Labels: cla-signed, lang: sv

#477 [SK] lights - update
  sentences/sk/_common.yaml
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
  tests/sk/_fixtures.yaml
  tests/sk/light_HassTurnOff.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#478 [HE] Fix HassLightSet
  sentences/he/_common.yaml
  sentences/he/light_HassLightSet.yaml
  tests/he/light_HassLightSet.yaml
Labels: cla-signed, lang: he

#483 Add script/package to build PyPI package
  package/.gitignore
  package/LICENSE.md
  package/MANIFEST.in
  package/home_assistant_intents/__init__.py
  package/setup.py
  script/intentfest/merged_output.py
  script/package
Labels: cla-signed

#503 Czech fan update
  sentences/cs/fan_HassTurnOff.yaml
  sentences/cs/fan_HassTurnOn.yaml
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#508 Add Danish climate sentences
  sentences/da/_common.yaml
  sentences/da/climate_HassClimateGetTemperature.yaml
  sentences/da/climate_HassClimateSetTemperature.yaml
  tests/da/climate_HassClimateGetTemperature.yaml
  tests/da/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: da

#506 Czech fan domain - test update
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#505 [LV] Add light domain
  sentences/lv/_common.yaml
  sentences/lv/homeassistant_HassTurnOff.yaml
  sentences/lv/homeassistant_HassTurnOn.yaml
  sentences/lv/light_HassLightSet.yaml
  sentences/lv/light_HassTurnOff.yaml
  sentences/lv/light_HassTurnOn.yaml
  tests/lv/_fixtures.yaml
  tests/lv/homeassistant_HassTurnOff.yaml
  tests/lv/homeassistant_HassTurnOn.yaml
  tests/lv/light_HassLightSet.yaml
  tests/lv/light_HassTurnOff.yaml
  tests/lv/light_HassTurnOn.yaml
Labels: cla-signed, lang: lv

#467 czech response for HassClimateGetTemperature
  responses/cs/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: cs

#482 czech - light domain
  sentences/cs/_common.yaml
  sentences/cs/light_HassLightSet.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#497 [SV] Streamline language of fixtures
  sentences/sv/_common.yaml
  tests/sv/_fixtures.yaml
  tests/sv/climate_HassClimateGetTemperature.yaml
  tests/sv/fan_HassTurnOn.yaml
  tests/sv/homeassistant_HassTurnOff.yaml
  tests/sv/homeassistant_HassTurnOn.yaml
  tests/sv/light_HassLightSet.yaml
  tests/sv/light_HassTurnOff.yaml
Labels: cla-signed, lang: sv

#235 [NL] Sentences to toggle all
  sentences/nl/_common.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#504 [SK] light update and climate set update
  sentences/sk/_common.yaml
  sentences/sk/climate_HassClimateGetTemperature.yaml
  sentences/sk/climate_HassClimateSetTemperature.yaml
  sentences/sk/light_HassLightSet.yaml
  tests/sk/_fixtures.yaml
  tests/sk/climate_HassClimateGetTemperature.yaml
  tests/sk/climate_HassClimateSetTemperature.yaml
  tests/sk/light_HassLightSet.yaml
Labels: cla-signed, lang: sk

#509 Add sk language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#498 [BG] add HassTurnOn/Off strings
  sentences/bg/fan_HassTurnOff.yaml
  sentences/bg/fan_HassTurnOn.yaml
  sentences/bg/homeassistant_HassTurnOff.yaml
  sentences/bg/homeassistant_HassTurnOn.yaml
  tests/bg/_fixtures.yaml
  tests/bg/fan_HassTurnOff.yaml
  tests/bg/fan_HassTurnOn.yaml
  tests/bg/homeassistant_HassTurnOff.yaml
  tests/bg/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: bg

#511 Add bg language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#495 czech - all expansion verb names in infinite form
  sentences/cs/_common.yaml
  sentences/cs/climate_HassClimateSetTemperature.yaml
  sentences/cs/light_HassLightSet.yaml
Labels: cla-signed, lang: cs

#514 czech - cover_HassCloseCover.yaml
  sentences/cs/_common.yaml
  sentences/cs/cover_HassCloseCover.yaml
  tests/cs/cover_HassCloseCover.yaml
Labels: cla-signed, lang: cs

#519 [EL] Add cover support
  sentences/el/_common.yaml
  sentences/el/cover_HassCloseCover.yaml
  sentences/el/cover_HassOpenCover.yaml
  tests/el/_fixtures.yaml
  tests/el/cover_HassCloseCover.yaml
  tests/el/cover_HassOpenCover.yaml
Labels: cla-signed, lang: el

#520 czech - light domian - purging code
  sentences/cs/light_HassLightSet.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#522 [EL] Add fan support
  sentences/el/_common.yaml
  sentences/el/fan_HassTurnOff.yaml
  sentences/el/fan_HassTurnOn.yaml
  tests/el/fan_HassTurnOff.yaml
  tests/el/fan_HassTurnOn.yaml
Labels: cla-signed, lang: el

#521 czech - climate domain add senteses
  sentences/cs/climate_HassClimateSetTemperature.yaml
  tests/cs/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: cs

#524 Fix website leader open position URL
  website/src-11ty/index.html
Labels: cla-signed

#523 [LV] Add climate domain
  responses/lv/HassClimateGetTemperature.yaml
  sentences/lv/_common.yaml
  sentences/lv/climate_HassClimateGetTemperature.yaml
  sentences/lv/climate_HassClimateSetTemperature.yaml
  tests/lv/climate_HassClimateGetTemperature.yaml
  tests/lv/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: lv

#516 [LV] Add cover domain
  sentences/lv/_common.yaml
  sentences/lv/cover_HassCloseCover.yaml
  sentences/lv/cover_HassOpenCover.yaml
  tests/lv/_fixtures.yaml
  tests/lv/cover_HassCloseCover.yaml
  tests/lv/cover_HassOpenCover.yaml
Labels: cla-signed, lang: lv

#518 Add lv language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#486 Add Georgian (ka) language and revert #195
  languages.yaml
  sentences/ka/_common.yaml
  sentences/ka/climate_HassClimateGetTemperature.yaml
  sentences/ka/climate_HassClimateSetTemperature.yaml
  sentences/ka/cover_HassCloseCover.yaml
  sentences/ka/cover_HassOpenCover.yaml
  sentences/ka/fan_HassTurnOff.yaml
  sentences/ka/fan_HassTurnOn.yaml
  sentences/ka/homeassistant_HassTurnOff.yaml
  sentences/ka/homeassistant_HassTurnOn.yaml
  sentences/ka/light_HassLightSet.yaml
  sentences/ka/light_HassTurnOff.yaml
  sentences/ka/light_HassTurnOn.yaml
  tests/ka/_fixtures.yaml
  tests/ka/climate_HassClimateGetTemperature.yaml
  tests/ka/climate_HassClimateSetTemperature.yaml
  tests/ka/cover_HassCloseCover.yaml
  tests/ka/cover_HassOpenCover.yaml
  tests/ka/fan_HassTurnOff.yaml
  tests/ka/fan_HassTurnOn.yaml
  tests/ka/homeassistant_HassTurnOff.yaml
  tests/ka/homeassistant_HassTurnOn.yaml
  tests/ka/light_HassLightSet.yaml
  tests/ka/light_HassTurnOff.yaml
  tests/ka/light_HassTurnOn.yaml
Labels: cla-signed, lang: ka

#527 Small cleanup of codeowner script
  script/intentfest/codeowners.py
Labels: cla-signed

#526 Add Kannada correctly under kn
  languages.yaml
  responses/kn/HassClimateGetTemperature.yaml
  sentences/kn/_common.yaml
  sentences/kn/climate_HassClimateGetTemperature.yaml
  sentences/kn/climate_HassClimateSetTemperature.yaml
  sentences/kn/cover_HassCloseCover.yaml
  sentences/kn/cover_HassOpenCover.yaml
  sentences/kn/fan_HassTurnOff.yaml
  sentences/kn/fan_HassTurnOn.yaml
  sentences/kn/homeassistant_HassTurnOff.yaml
  sentences/kn/homeassistant_HassTurnOn.yaml
  sentences/kn/light_HassLightSet.yaml
  sentences/kn/light_HassTurnOff.yaml
  sentences/kn/light_HassTurnOn.yaml
  tests/kn/_fixtures.yaml
  tests/kn/climate_HassClimateGetTemperature.yaml
  tests/kn/climate_HassClimateSetTemperature.yaml
  tests/kn/cover_HassCloseCover.yaml
  tests/kn/cover_HassOpenCover.yaml
  tests/kn/fan_HassTurnOff.yaml
  tests/kn/fan_HassTurnOn.yaml
  tests/kn/homeassistant_HassTurnOff.yaml
  tests/kn/homeassistant_HassTurnOn.yaml
  tests/kn/light_HassLightSet.yaml
  tests/kn/light_HassTurnOff.yaml
  tests/kn/light_HassTurnOn.yaml
Labels: cla-signed, lang: kn

#533 [SK] Add cover domain
  sentences/sk/_common.yaml
  sentences/sk/cover_HassCloseCover.yaml
  sentences/sk/cover_HassOpenCover.yaml
  tests/sk/_fixtures.yaml
  tests/sk/cover_HassCloseCover.yaml
  tests/sk/cover_HassOpenCover.yaml
Labels: cla-signed, lang: sk

#537 Add problem matcher for intentfest
  .github/workflows/ci.yaml
  .github/workflows/matchers/intentfest.json
  .vscode/tasks.json
  script/intentfest/validate.py
  script/test
Labels: cla-signed, lang: nl

#515 Neo-branch
  languages.yaml
  sentences/bg/_common.yaml
  sentences/bg/fan_HassTurnOn.yaml
  tests/bg/_fixtures.yaml
  tests/bg/fan_HassTurnOn.yaml
Labels: cla-signed, lang: bg

#225 Improving Spanish intents, adding synonyms
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  sentences/es/climate_HassClimateSetTemperature.yaml
  sentences/es/cover_HassCloseCover.yaml
  sentences/es/cover_HassOpenCover.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/light_HassTurnOff.yaml
  tests/es/_fixtures.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
  tests/es/cover_HassCloseCover.yaml
  tests/es/cover_HassOpenCover.yaml
  tests/es/fan_HassTurnOff.yaml
  tests/es/fan_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#546 Update _common.yaml and HassLightSet.yaml
  sentences/el/_common.yaml
  sentences/el/light_HassLightSet.yaml
  tests/el/light_HassLightSet.yaml
Labels: cla-signed, lang: el

#548 Add Arabic language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#549 Add Romanian language leaders
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#550 Add Catalan leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#551 Add Spanish leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#553 Allow device_class in test fixtures
  script/intentfest/validate.py
Labels: cla-signed

#484 [BG] cover_HassCloseCover and its test
  sentences/bg/cover_HassCloseCover.yaml
  sentences/bg/cover_HassOpenCover.yaml
  tests/bg/_fixtures.yaml
  tests/bg/cover_HassCloseCover.yaml
  tests/bg/cover_HassOpenCover.yaml
Labels: cla-signed, lang: bg

#554 Add Malayalam language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#532 [KA] Lights
  sentences/ka/_common.yaml
  sentences/ka/light_HassTurnOn.yaml
  tests/ka/_fixtures.yaml
  tests/ka/light_HassTurnOn.yaml
Labels: cla-signed, lang: ka

#451 Updates with synonymous and clean code
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateGetTemperature.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
  sentences/it/cover_HassCloseCover.yaml
Labels: cla-signed, lang: it

#555 Add Georgian leader (ka)
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#462 [MS] added HassClimateGetTemperature
  responses/ms/HassClimateGetTemperature.yaml
  sentences/ms/_common.yaml
  sentences/ms/climate_HassClimateGetTemperature.yaml
  tests/ms/_fixtures.yaml
  tests/ms/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ms

#557 Add Portuguese language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#463 added turkish sentences for climate_HassClimateSetTemperature and cover_HassCloseCover
  sentences/tr/_common.yaml
  sentences/tr/climate_HassClimateSetTemperature.yaml
  sentences/tr/cover_HassCloseCover.yaml
  tests/tr/_fixtures.yaml
  tests/tr/climate_HassClimateSetTemperature.yaml
  tests/tr/cover_HassCloseCover.yaml
Labels: cla-signed, lang: tr

#560 Add Turkish (tr) language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#562 [EL] Update _common.yaml Create light_HassTurnOff
  sentences/el/_common.yaml
  sentences/el/light_HassTurnOff.yaml
  tests/el/light_HassTurnOff.yaml
Labels: cla-signed, lang: el

#561 New <set> expansion_rules and clean singular/plural code
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
  sentences/it/cover_HassOpenCover.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/light_HassLightSet.yaml
  sentences/it/light_HassTurnOff.yaml
Labels: cla-signed, lang: it

#565 [NL] Add sentences to get the temperature
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/_fixtures.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: nl

#569 [SK] tests typo fix
  tests/sk/_fixtures.yaml
  tests/sk/cover_HassCloseCover.yaml
  tests/sk/cover_HassOpenCover.yaml
Labels: cla-signed, lang: sk

#568 [NL] Add sentences to set the temperature
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/_fixtures.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#564 [SV] Add set color and color variants for swedish
  sentences/sv/_common.yaml
  sentences/sv/light_HassLightSet.yaml
  tests/sv/light_HassLightSet.yaml
Labels: cla-signed, lang: sv

#567 [RO] TurnOn renaming and diacritic support refactoring
  sentences/ro/_common.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#538 [SK] Update HassClimateGetTemperature.yaml
  responses/sk/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sk

#572 Adding extra skip words
  sentences/es/_common.yaml
  tests/es/cover_HassOpenCover.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#573 Adding extra ES sentences to get temperatures
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  tests/es/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: es

#571 Rechin304 patch 2
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#435 [ES] Update common temperature definition
  sentences/es/_common.yaml
  tests/es/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: es

#234 [ES] Added alternative commands to turn off
  tests/es/_fixtures.yaml
  tests/es/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: es

#233 [ES] Update tests for homeassistant_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: es

#579 [NL] Remove "de" from GetTemperature
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: nl

#581 Update _common.yaml
  sentences/nb/_common.yaml
Labels: cla-signed, lang: nb
