Repository OHF-Voice/intents, pull requests merged in 2023-04, with the labels that each got.

#1263 [ar] add "turn all lights on in area"
  sentences/ar/_common.yaml
  sentences/ar/light_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/light_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1267 [BG] Initial commit of binary sensors
  sentences/bg/_common.yaml
  sentences/bg/binary_sensor_HassGetState.yaml
  tests/bg/_fixtures.yaml
  tests/bg/binary_sensor_HassGetState.yaml
  tests/bg/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: bg

#1264 [ar] add "turn [all] lights off"
  sentences/ar/_common.yaml
  sentences/ar/light_HassTurnOff.yaml
  tests/ar/light_HassTurnOff.yaml
Labels: cla-signed, lang: ar

#1266 [ar] add set brightness and color
  sentences/ar/_common.yaml
  sentences/ar/light_HassLightSet.yaml
  tests/ar/_fixtures.yaml
  tests/ar/light_HassLightSet.yaml
Labels: cla-signed, lang: ar

#1270 Adding support for the infinitive form of verbs in french
  sentences/fr/_common.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/fan_HassTurnOff.yaml
  tests/fr/fan_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1274 Add AR language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1273 [ar] add tests for fan_HassTurnOn and fan_HassTurnOff
  sentences/ar/_common.yaml
  sentences/ar/fan_HassTurnOff.yaml
  sentences/ar/fan_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/fan_HassTurnOff.yaml
  tests/ar/fan_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1272 [fr] Stick to a single convention
  sentences/fr/_common.yaml
  sentences/fr/climate_HassClimateGetTemperature.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  sentences/fr/cover_HassGetState.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/fan_HassTurnOn.yaml
  sentences/fr/homeassistant_HassGetState.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  sentences/fr/lock_HassGetState.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1243 [DE] added new phrases for lock_states
  sentences/de/_common.yaml
  tests/de/lock_HassGetState.yaml
Labels: cla-signed, lang: de

#1278 [ar] cover_HassTurnOn
  responses/ar/HassTurnOn.yaml
  sentences/ar/cover_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/cover_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1282 [ar] cover_HassTurnOff
  responses/ar/HassTurnOff.yaml
  sentences/ar/_common.yaml
  sentences/ar/cover_HassTurnOff.yaml
  tests/ar/cover_HassTurnOff.yaml
Labels: cla-signed, lang: ar

#1275 [DE] Add new variations to lock_HassGetState
  sentences/de/_common.yaml
  tests/de/lock_HassGetState.yaml
Labels: cla-signed, lang: de

#1285 [ar] homeassistant_HassTurnOn
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1281 [ar] cover_HassTurnOff
  responses/ar/HassTurnOff.yaml
  responses/ar/HassTurnOn.yaml
  sentences/ar/_common.yaml
  sentences/ar/cover_HassTurnOff.yaml
  tests/ar/cover_HassTurnOff.yaml
  tests/ar/cover_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1288 [ar] homeassistant_HassTurnOff
  sentences/ar/homeassistant_HassTurnOff.yaml
  tests/ar/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: ar

#1290 [ar] light_HassTurnOn && light_HassTurnOff
  sentences/ar/light_HassTurnOff.yaml
  sentences/ar/light_HassTurnOn.yaml
  tests/ar/light_HassTurnOff.yaml
  tests/ar/light_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1295 add missing word for some items (light,window,etc)
  sentences/ar/_common.yaml
Labels: cla-signed, lang: ar

#1296 [ar] add more sentences to light_HassLightSet
  sentences/ar/light_HassLightSet.yaml
  tests/ar/light_HassLightSet.yaml
Labels: cla-signed, lang: ar

#1297 [ar] add responses to light_HassLightSet
  responses/ar/HassLightSet.yaml
  sentences/ar/light_HassLightSet.yaml
  tests/ar/light_HassLightSet.yaml
Labels: cla-signed, lang: ar

#1294 [Fr] Simplify response "All" and add binary_sensors.py with tests
  responses/fr/HassGetState.yaml
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  sentences/fr/climate_HassClimateGetTemperature.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
  tests/fr/cover_HassGetState.yaml
  tests/fr/lock_HassGetState.yaml
Labels: cla-signed, lang: fr

#1280 [ar] cover_HassGetState
  responses/ar/HassGetState.yaml
  sentences/ar/cover_HassGetState.yaml
  tests/ar/_fixtures.yaml
  tests/ar/cover_HassGetState.yaml
Labels: cla-signed, lang: ar

#1299 Add pl language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1300 [ar] script_HassTurnOn
  sentences/ar/_common.yaml
  sentences/ar/script_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/script_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1301 [cs] Add intents to open/close one cover by its name
  responses/cs/HassTurnOff.yaml
  responses/cs/HassTurnOn.yaml
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1287 [DE] Add all to (un)locking
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/_common.yaml
  sentences/de/lock_HassTurnOff.yaml
  sentences/de/lock_HassTurnOn.yaml
  tests/de/lock_HassTurnOff.yaml
  tests/de/lock_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1286 [DE] Update to scene_HassTurnOn
  sentences/de/scene_HassTurnOn.yaml
  tests/de/scene_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1303 [cs] Add intents to open/close only one cover in area
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1255 [IS] Add intents and tests to turn lights on and off
  responses/is/HassClimateSetTemperature.yaml
  responses/is/HassTurnOff.yaml
  responses/is/HassTurnOn.yaml
  sentences/is/_common.yaml
  sentences/is/light_HassTurnOff.yaml
  sentences/is/light_HassTurnOn.yaml
  tests/is/_fixtures.yaml
  tests/is/light_HassTurnOff.yaml
  tests/is/light_HassTurnOn.yaml
Labels: cla-signed, lang: is

#1307 Add is leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1302 [Fr] Add intents and test for CO2 binary sensors
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1309 Add get_domains_and_languages
  package/home_assistant_intents/__init__.py
  package/home_assistant_intents/domains.py
  package/pyproject.toml
  package/script/write_languages.py
  script/format
  script/lint
  script/package
Labels: cla-signed

#1311 [cs] Add support for awning and shade cover types
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1312 Add lock and scene sentences
  sentences/ar/_common.yaml
  sentences/ar/fan_HassTurnOn.yaml
  sentences/ar/lock_HassTurnOn.yaml
  sentences/ar/scene_HassTurnOn.yaml
  tests/ar/_fixtures.yaml
  tests/ar/fan_HassTurnOn.yaml
  tests/ar/lock_HassTurnOn.yaml
  tests/ar/scene_HassTurnOn.yaml
Labels: cla-signed, lang: ar

#1314 [ar] add climate_HassClimateSetTemperature missing responses
  sentences/ar/_common.yaml
  sentences/ar/climate_HassClimateSetTemperature.yaml
  tests/ar/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ar

#1315 Add optional space
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  sentences/nl/lock_HassTurnOff.yaml
  sentences/nl/lock_HassTurnOn.yaml
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/lock_HassTurnOff.yaml
  tests/nl/lock_HassTurnOn.yaml
  tests/nl/scene_HassTurnOn.yaml
  tests/nl/script_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1304 [DE] Add binary sensor battery
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1316 [ar] add homeassistant_HassGetState sentences
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassGetState.yaml
  tests/ar/_fixtures.yaml
  tests/ar/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: ar

#1318 [DE] Add binary sensor battery charging
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1321 [ar] add more fixtures to test with
  responses/ar/HassGetState.yaml
  sentences/ar/_common.yaml
  tests/ar/_fixtures.yaml
  tests/ar/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: ar

#1324 [Fr] Add cold and connectivity binary sensors
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1306 [DE] Fix fan responses
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1325 [FR] Add more sentences for HassLightSet
  responses/fr/HassLightSet.yaml
  sentences/fr/_common.yaml
  sentences/fr/light_HassLightSet.yaml
  tests/fr/light_HassLightSet.yaml
Labels: cla-signed, lang: fr

#1326 [FR] Add more sentences for HassLightTurnOn and HassLightTurnOff
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1327 [FR] more sentence for Get State. And simplification of some answers
  responses/fr/HassGetState.yaml
  sentences/fr/homeassistant_HassGetState.yaml
  tests/fr/binary_sensor_HassGetState.yaml
  tests/fr/cover_HassGetState.yaml
  tests/fr/homeassistant_HassGetState.yaml
  tests/fr/lock_HassGetState.yaml
Labels: cla-signed, lang: fr

#1328 [DE] Fix responses for light
  responses/de/HassLightSet.yaml
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/light_HassLightSet.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1331 [DE] Fix responses for cover
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/_common.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1320 [DE] Add binary sensor carbon monoxide
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de
