Repository OHF-Voice/intents, pull requests merged in 2023-03, with the labels that each got.

#1162 [DE] Minor updates in German
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1159 [NL] Apply newly created expansion rules
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/cover_HassGetState.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassGetState.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  sentences/nl/lock_HassGetState.yaml
  tests/nl/binary_sensor_HassGetState.yaml
  tests/nl/homeassistant_HassGetState.yaml
  tests/nl/lock_HassGetState.yaml
Labels: cla-signed, lang: nl

#1170 TR - Fixing some minor issues
  sentences/tr/cover_HassTurnOff.yaml
  sentences/tr/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: tr

#1150 [CS] bs-commons
  sentences/cs/_common.yaml
Labels: cla-signed, lang: cs

#1164 [NB] Fix get temperature
  responses/nb/HassClimateGetTemperature.yaml
  responses/nb/HassClimateSetTemperature.yaml
  tests/nb/_fixtures.yaml
  tests/nb/climate_HassClimateGetTemperature.yaml
  tests/nb/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nb

#1163 [NB] Fix light response bug
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#1173 [zh-tw] Support for locking/unlocking locks
  responses/zh-tw/HassTurnOff.yaml
  responses/zh-tw/HassTurnOn.yaml
  sentences/zh-tw/lock_HassTurnOff.yaml
  sentences/zh-tw/lock_HassTurnOn.yaml
  tests/zh-tw/lock_HassTurnOff.yaml
  tests/zh-tw/lock_HassTurnOn.yaml
Labels: cla-signed

#1176 [DE] Small updates to German intents
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/homeassistant_HassGetState.yaml
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1183 [PT] Small fixes
  responses/pt/HassGetState.yaml
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassGetState.yaml
  sentences/pt/homeassistant_HassTurnOff.yaml
  tests/pt/cover_HassGetState.yaml
  tests/pt/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pt

#1178 Add hass turn on sentences to pt br
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: pt-br

#1168 added skipwords to PT-BR
  sentences/pt-br/_common.yaml
Labels: cla-signed, lang: pt-br

#1184 [pt-BR] Added sentences and responses for Turn Off Intention
  responses/pt-br/HassTurnOff.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
Labels: cla-signed

#1153 Excessive whitespace removal
  sentences/pl/_common.yaml
  sentences/pl/cover_HassTurnOff.yaml
  sentences/pl/cover_HassTurnOn.yaml
  sentences/pl/homeassistant_HassTurnOff.yaml
  sentences/pl/homeassistant_HassTurnOn.yaml
  sentences/pl/light_HassLightSet.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  tests/pl/_fixtures.yaml
Labels: cla-signed, lang: pl

#1175 [NL] Support for opening and closing locks
  responses/nl/HassTurnOff.yaml
  responses/nl/HassTurnOn.yaml
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/cover_HassGetState.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  sentences/nl/lock_HassTurnOff.yaml
  sentences/nl/lock_HassTurnOn.yaml
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  tests/nl/lock_HassTurnOff.yaml
  tests/nl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1180 [FR] Add one sentence in climate_HassClimateGetTemperature
  sentences/fr/climate_HassClimateGetTemperature.yaml
  tests/fr/_fixtures.yaml
  tests/fr/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: fr

#1177 [EN] Add area sentences to lock/unlock
  sentences/en/lock_HassTurnOff.yaml
  sentences/en/lock_HassTurnOn.yaml
  tests/en/lock_HassTurnOff.yaml
  tests/en/lock_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1187 Update languages.yaml
  languages.yaml
Labels: cla-signed

#1188 [PT] Temperature
  responses/pt/HassClimateSetTemperature.yaml
  sentences/pt/climate_HassClimateGetTemperature.yaml
  sentences/pt/climate_HassClimateSetTemperature.yaml
  tests/pt/_fixtures.yaml
  tests/pt/climate_HassClimateGetTemperature.yaml
  tests/pt/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: pt

#1146 [pt-BR] Adding on/off lights sentences
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/homeassistant_HassTurnOn.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt-br

#1189 [hr] covers get state
  responses/hr/HassGetState.yaml
  sentences/hr/_common.yaml
  sentences/hr/cover_HassGetState.yaml
  tests/hr/_fixtures.yaml
  tests/hr/cover_HassGetState.yaml
Labels: cla-signed, lang: hr

#1023 [IT] Translate `GetState`
  responses/it/HassGetState.yaml
  responses/it/HassTurnOff.yaml
  responses/it/HassTurnOn.yaml
  sentences/it/_common.yaml
  sentences/it/cover_HassGetState.yaml
  sentences/it/cover_HassTurnOff.yaml
  sentences/it/cover_HassTurnOn.yaml
  sentences/it/homeassistant_HassGetState.yaml
  tests/it/_fixtures.yaml
  tests/it/cover_HassGetState.yaml
  tests/it/cover_HassTurnOff.yaml
  tests/it/cover_HassTurnOn.yaml
  tests/it/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: it

#1190 [zh-tw] Binary sensor sentences and other minor update
  responses/zh-tw/HassTurnOff.yaml
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/binary_sensor_HassGetState.yaml
  sentences/zh-tw/fan_HassTurnOff.yaml
  sentences/zh-tw/homeassistant_HassTurnOff.yaml
  sentences/zh-tw/homeassistant_HassTurnOn.yaml
  sentences/zh-tw/light_HassTurnOff.yaml
  sentences/zh-tw/lock_HassTurnOff.yaml
  sentences/zh-tw/lock_HassTurnOn.yaml
  tests/zh-tw/_fixtures.yaml
  tests/zh-tw/binary_sensor_HassGetState.yaml
  tests/zh-tw/fan_HassTurnOff.yaml
  tests/zh-tw/homeassistant_HassGetState.yaml
  tests/zh-tw/homeassistant_HassTurnOff.yaml
  tests/zh-tw/homeassistant_HassTurnOn.yaml
  tests/zh-tw/light_HassTurnOff.yaml
  tests/zh-tw/lock_HassTurnOff.yaml
  tests/zh-tw/lock_HassTurnOn.yaml
Labels: cla-signed

#1191 [hr] Added some variations for cover sentences
  sentences/hr/_common.yaml
  tests/hr/cover_HassGetState.yaml
Labels: cla-signed, lang: hr

#1192 [hr] Added missing responses
  responses/hr/HassClimateGetTemperature.yaml
  responses/hr/HassClimateSetTemperature.yaml
  responses/hr/HassLightSet.yaml
  responses/hr/HassTurnOff.yaml
  responses/hr/HassTurnOn.yaml
  sentences/hr/climate_HassClimateGetTemperature.yaml
  sentences/hr/light_HassLightSet.yaml
  tests/hr/_fixtures.yaml
  tests/hr/climate_HassClimateGetTemperature.yaml
  tests/hr/climate_HassClimateSetTemperature.yaml
  tests/hr/light_HassLightSet.yaml
  tests/hr/light_HassTurnOff.yaml
  tests/hr/light_HassTurnOn.yaml
Labels: cla-signed, lang: hr

#1193 [zh-cn] Add support for locking/unlocking
  responses/zh-cn/HassTurnOff.yaml
  responses/zh-cn/HassTurnOn.yaml
  sentences/zh-cn/lock_HassTurnOff.yaml
  sentences/zh-cn/lock_HassTurnOn.yaml
  tests/zh-cn/lock_HassTurnOff.yaml
  tests/zh-cn/lock_HassTurnOn.yaml
Labels: cla-signed

#1194 [hr] Added fan intents
  responses/hr/HassTurnOff.yaml
  responses/hr/HassTurnOn.yaml
  sentences/hr/fan_HassTurnOff.yaml
  sentences/hr/fan_HassTurnOn.yaml
  tests/hr/_fixtures.yaml
  tests/hr/fan_HassTurnOff.yaml
  tests/hr/fan_HassTurnOn.yaml
  tests/hr/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: hr

#1179 [De] Improve climate sentences and tests
  responses/de/HassClimateGetTemperature.yaml
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/homeassistant_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: de

#1182 [De] Improve cover sentences, responses and tests
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1181 [De] Improve HassTurnOn and HassTurnOff sentences and tests
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1197 [PL] Added support for work with scene and script
  responses/pl/HassGetState.yaml
  responses/pl/HassTurnOff.yaml
  responses/pl/HassTurnOn.yaml
  sentences/pl/_common.yaml
  sentences/pl/scene_HassTurnOn.yaml
  sentences/pl/script_HassTurnOn.yaml
  tests/pl/_fixtures.yaml
  tests/pl/scene_HassTurnOn.yaml
  tests/pl/script_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#903 [FI] Get temperature sentences for Finnish
  sentences/fi/_common.yaml
  sentences/fi/climate_HassClimateGetTemperature.yaml
  tests/fi/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: fi

#1201 [HE] Common update + one new sentence & test
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: he

#1185 [NL] any/all/which/how many for binary sensor
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  tests/nl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: nl

#1195 Translated light_HassLightSet in zh-hk
  responses/zh-hk/HassGetState.yaml
  sentences/zh-cn/_common.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassGetState.yaml
  sentences/zh-hk/light_HassLightSet.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/homeassistant_HassGetState.yaml
  tests/zh-hk/light_HassLightSet.yaml
Labels: cla-signed, lang: zh-hk

#1205 [FI] Add better Finnish support
  responses/fi/HassClimateGetTemperature.yaml
  responses/fi/HassClimateSetTemperature.yaml
  responses/fi/HassGetState.yaml
  responses/fi/HassLightSet.yaml
  responses/fi/HassTurnOff.yaml
  responses/fi/HassTurnOn.yaml
  sentences/fi/_common.yaml
  sentences/fi/climate_HassClimateGetTemperature.yaml
  sentences/fi/climate_HassClimateSetTemperature.yaml
  sentences/fi/cover_HassGetState.yaml
  sentences/fi/cover_HassTurnOff.yaml
  sentences/fi/cover_HassTurnOn.yaml
  sentences/fi/fan_HassTurnOff.yaml
  sentences/fi/fan_HassTurnOn.yaml
  sentences/fi/homeassistant_HassGetState.yaml
  sentences/fi/homeassistant_HassTurnOff.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  sentences/fi/light_HassLightSet.yaml
  sentences/fi/light_HassTurnOff.yaml
  sentences/fi/light_HassTurnOn.yaml
  sentences/fi/lock_HassGetState.yaml
  sentences/fi/lock_HassTurnOff.yaml
  sentences/fi/lock_HassTurnOn.yaml
  tests/fi/_fixtures.yaml
  tests/fi/climate_HassClimateGetTemperature.yaml
  tests/fi/climate_HassClimateSetTemperature.yaml
  tests/fi/cover_HassGetState.yaml
  tests/fi/cover_HassTurnOff.yaml
  tests/fi/cover_HassTurnOn.yaml
  tests/fi/fan_HassTurnOff.yaml
  tests/fi/fan_HassTurnOn.yaml
  tests/fi/homeassistant_HassGetState.yaml
  tests/fi/homeassistant_HassTurnOff.yaml
  tests/fi/homeassistant_HassTurnOn.yaml
  tests/fi/light_HassLightSet.yaml
  tests/fi/light_HassTurnOff.yaml
  tests/fi/light_HassTurnOn.yaml
  tests/fi/lock_HassGetState.yaml
  tests/fi/lock_HassTurnOff.yaml
  tests/fi/lock_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#890 [HI] Adding Hindi common sentences
  sentences/hi/_common.yaml
Labels: cla-signed, lang: hi

#1208 [zh-hk] cover_Hass
  responses/zh-hk/HassTurnOff.yaml
  responses/zh-hk/HassTurnOn.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/cover_HassGetState.yaml
  sentences/zh-hk/cover_HassTurnOff.yaml
  sentences/zh-hk/cover_HassTurnOn.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/cover_HassGetState.yaml
  tests/zh-hk/cover_HassTurnOff.yaml
  tests/zh-hk/cover_HassTurnOn.yaml
Labels: cla-signed

#1207 Add total_results property to query
  shared/__init__.py
Labels: cla-signed

#1209 [zh-hk] homeassistant_Hass
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassTurnOff.yaml
  sentences/zh-hk/homeassistant_HassTurnOn.yaml
  tests/zh-hk/homeassistant_HassTurnOff.yaml
  tests/zh-hk/homeassistant_HassTurnOn.yaml
  tests/zh-hk/light_HassTurnOff.yaml
  tests/zh-hk/light_HassTurnOn.yaml
Labels: cla-signed

#1210 [FR] add missing answers in sentences and tests
  responses/fr/HassClimateGetTemperature.yaml
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/fan_HassTurnOff.yaml
  sentences/fr/fan_HassTurnOn.yaml
  tests/fr/_fixtures.yaml
  tests/fr/climate_HassClimateGetTemperature.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/fan_HassTurnOff.yaml
  tests/fr/fan_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1212 [PL] Added support for "lock" domain, fixed "cover" domain and added other small updates
  responses/pl/HassGetState.yaml
  responses/pl/HassTurnOff.yaml
  responses/pl/HassTurnOn.yaml
  sentences/pl/_common.yaml
  sentences/pl/climate_HassClimateGetTemperature.yaml
  sentences/pl/cover_HassGetState.yaml
  sentences/pl/cover_HassTurnOff.yaml
  sentences/pl/cover_HassTurnOn.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/homeassistant_HassGetState.yaml
  sentences/pl/homeassistant_HassTurnOff.yaml
  sentences/pl/homeassistant_HassTurnOn.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  sentences/pl/lock_HassGetState.yaml
  sentences/pl/lock_HassTurnOff.yaml
  sentences/pl/lock_HassTurnOn.yaml
  tests/pl/_fixtures.yaml
  tests/pl/climate_HassClimateGetTemperature.yaml
  tests/pl/cover_HassGetState.yaml
  tests/pl/cover_HassTurnOff.yaml
  tests/pl/cover_HassTurnOn.yaml
  tests/pl/fan_HassTurnOff.yaml
  tests/pl/fan_HassTurnOn.yaml
  tests/pl/homeassistant_HassGetState.yaml
  tests/pl/homeassistant_HassTurnOff.yaml
  tests/pl/homeassistant_HassTurnOn.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
  tests/pl/lock_HassGetState.yaml
  tests/pl/lock_HassTurnOff.yaml
  tests/pl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#1203 [DE] Add lock intents
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  sentences/de/_common.yaml
  sentences/de/lock_HassTurnOff.yaml
  sentences/de/lock_HassTurnOn.yaml
  tests/de/lock_HassTurnOff.yaml
  tests/de/lock_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1227 [zh-cn] Add `excludes_context` domains
  sentences/zh-cn/homeassistant_HassGetState.yaml
  sentences/zh-cn/homeassistant_HassTurnOff.yaml
  sentences/zh-cn/homeassistant_HassTurnOn.yaml
Labels: cla-signed

#1223 [NB] Correct hvilke vs hva
  sentences/nb/_common.yaml
  sentences/nb/cover_HassGetState.yaml
  sentences/nb/homeassistant_HassGetState.yaml
  sentences/nb/lock_HassGetState.yaml
  tests/nb/lock_HassGetState.yaml
Labels: cla-signed, lang: nb

#1229 [EN] added an optional word for Get state
  sentences/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#1231 [UR] fix typo
  sentences/ur/homeassistant_HassGetState.yaml
  tests/ur/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: ur

#1234 [UR] Cleaned up files
  sentences/ur/_common.yaml
  sentences/ur/climate_HassClimateGetTemperature.yaml
  sentences/ur/fan_HassTurnOff.yaml
  sentences/ur/fan_HassTurnOn.yaml
  sentences/ur/homeassistant_HassTurnOff.yaml
  sentences/ur/homeassistant_HassTurnOn.yaml
  sentences/ur/light_HassLightSet.yaml
  sentences/ur/light_HassTurnOff.yaml
  sentences/ur/light_HassTurnOn.yaml
  tests/ur/climate_HassClimateGetTemperature.yaml
  tests/ur/climate_HassClimateSetTemperature.yaml
  tests/ur/fan_HassTurnOn.yaml
  tests/ur/homeassistant_HassTurnOn.yaml
  tests/ur/light_HassLightSet.yaml
  tests/ur/light_HassTurnOn.yaml
Labels: cla-signed, lang: ur

#1235 [UR] Add cover get state
  sentences/ur/_common.yaml
  sentences/ur/cover_HassGetState.yaml
  tests/ur/_fixtures.yaml
  tests/ur/cover_HassGetState.yaml
Labels: cla-signed, lang: ur

#1115 [WIP][RU] Initial commit on GetState
  responses/ru/HassGetState.yaml
  sentences/ru/_common.yaml
  sentences/ru/cover_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/cover_HassGetState.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#1236 Nl_climate_set
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: nl

#1237 Revert "Nl_climate_set"
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: nl

#1238 [NL] Small change to climate set
  sentences/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#1239 [RU] Add support for homeassistant_HassGetState
  responses/ru/HassGetState.yaml
  sentences/ru/_common.yaml
  sentences/ru/homeassistant_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/cover_HassGetState.yaml
  tests/ru/homeassistant_HassGetState.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/light_HassLightSet.yaml
Labels: cla-signed, lang: ru

#1240 [EN] Add more optional words
  sentences/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#1242 [RU] Remove TODO comment from responses
  responses/ru/HassGetState.yaml
Labels: cla-signed, lang: ru

#1241 [EN] Added increase and decrease to set
  sentences/en/_common.yaml
  sentences/en/climate_HassClimateSetTemperature.yaml
  sentences/en/light_HassLightSet.yaml
Labels: cla-signed, lang: en

#1215 [NL] Next batch of binary sensors
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  tests/nl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: nl

#1226 [HE] Varioud fixes
  responses/he/HassGetState.yaml
  responses/he/HassTurnOff.yaml
  responses/he/HassTurnOn.yaml
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateGetTemperature.yaml
  sentences/he/cover_HassGetState.yaml
  sentences/he/cover_HassTurnOff.yaml
  sentences/he/cover_HassTurnOn.yaml
  sentences/he/light_HassTurnOff.yaml
  sentences/he/light_HassTurnOn.yaml
  tests/he/_fixtures.yaml
  tests/he/cover_HassGetState.yaml
  tests/he/cover_HassTurnOff.yaml
  tests/he/cover_HassTurnOn.yaml
  tests/he/homeassistant_HassGetState.yaml
  tests/he/homeassistant_HassTurnOff.yaml
  tests/he/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: he

#1246 [hr] lock intents
  responses/hr/HassTurnOff.yaml
  responses/hr/HassTurnOn.yaml
  sentences/hr/_common.yaml
  sentences/hr/lock_HassGetState.yaml
  sentences/hr/lock_HassTurnOff.yaml
  sentences/hr/lock_HassTurnOn.yaml
  tests/hr/_fixtures.yaml
  tests/hr/lock_HassGetState.yaml
  tests/hr/lock_HassTurnOff.yaml
  tests/hr/lock_HassTurnOn.yaml
Labels: cla-signed, lang: hr

#1247 [FI] Add Finnish fixture words for states based on lokalise content
  tests/fi/_fixtures.yaml
  tests/fi/cover_HassGetState.yaml
  tests/fi/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: fi

#1221 [DE] Add scene and script
  responses/de/HassTurnOn.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  sentences/de/scene_HassTurnOn.yaml
  sentences/de/script_HassTurnOn.yaml
  tests/de/_fixtures.yaml
  tests/de/scene_HassTurnOn.yaml
  tests/de/script_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1248 [RU] Change word endings depending on numeric state in HassClimateGetTemperature
  responses/ru/HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  tests/ru/_fixtures.yaml
  tests/ru/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ru

#1202 [De] Fix set light acts on all
  sentences/de/light_HassLightSet.yaml
  tests/de/_fixtures.yaml
  tests/de/homeassistant_HassGetState.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de

#1253 [RU] Change word endings depending on numeric state in HassClimateSetTemperature
  responses/ru/HassClimateSetTemperature.yaml
  sentences/ru/_common.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateSetTemperature.yaml
  tests/ru/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ru

#1250 [DE] exclude cover and lock from homeassistant_HassTurnOff and homeassistant_HassTurnOn
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1251 [DE] Add more variants to (un)locking
  sentences/de/_common.yaml
  sentences/de/lock_HassTurnOn.yaml
  tests/de/lock_HassTurnOff.yaml
  tests/de/lock_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1252 [DA] Aligned Danish version of _common.yaml with English version
  sentences/da/_common.yaml
Labels: cla-signed, lang: da
