Repository OHF-Voice/intents, pull requests merged in 2023-10, with the labels that each got.

#1536 [BG]Update _common.yaml
  sentences/bg/_common.yaml
Labels: cla-signed, lang: bg

#1454 Add further German sentences for the cover domain
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1547 [RO] Add optional "din area" for lights and generic HassTurnOn/Off
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#1546 [EN] Add optional "in area" to light and generic HassTurnOn/Off
  sentences/en/homeassistant_HassTurnOff.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1549 Add HassNevermind (not yet supported in HA)
  intents.yaml
  sentences/en/homeassistant_HassNevermind.yaml
  tests/en/homeassistant_HassNevermind.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed, lang: en

#1551 [RO] Nevermind
  sentences/ro/homeassistant_HassNevermind.yaml
  tests/ro/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: ro

#1550 [DE] Add HassNevermind
  sentences/de/homeassistant_HassNevermind.yaml
  tests/de/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: de

#1555 (hr) Scene and Script Croatian sentences
  responses/hr/HassTurnOn.yaml
  sentences/hr/scene_HassTurnOn.yaml
  sentences/hr/script_HassTurnOn.yaml
  tests/hr/_fixtures.yaml
  tests/hr/scene_HassTurnOn.yaml
  tests/hr/script_HassTurnOn.yaml
Labels: cla-signed, lang: hr

#1554 Fix missing NB translations
  responses/nb/HassTurnOff.yaml
  responses/nb/HassTurnOn.yaml
  tests/nb/homeassistant_HassTurnOff.yaml
  tests/nb/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nb, cla-error

#1544 [FR] Add skip words for more natural sentences
  sentences/fr/_common.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1449 [DE] Improve <area> rule
  sentences/de/_common.yaml
  tests/de/_fixtures.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: de

#1575 1565 hr less strict expansion rules
  sentences/hr/_common.yaml
Labels: cla-signed, lang: hr

#1571 [EL] Add HassNevermind
  sentences/el/homeassistant_HassNevermind.yaml
  tests/el/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: el

#1576 [EL] homeassistant_HassNevermind Add abbreviation
  sentences/el/homeassistant_HassNevermind.yaml
  tests/el/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: el, Hacktoberfest

#1572 [EL] Added HassShoppingListAddItem
  responses/el/HassShoppingListAddItem.yaml
  sentences/el/_common.yaml
  sentences/el/shopping_list_HassShoppingListAddItem.yaml
  tests/el/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: el

#1578 [hr] added shopping list support
  responses/hr/HassShoppingListAddItem.yaml
  sentences/hr/_common.yaml
  sentences/hr/shopping_list_HassShoppingListAddItem.yaml
  tests/hr/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: hr, Hacktoberfest

#1587 on off functions expansions for serbian
  sentences/sr/light_HassTurnOff.yaml
  sentences/sr/light_HassTurnOn.yaml
  tests/sr/light_HassTurnOn.yaml
Labels: cla-signed, lang: sr, Hacktoberfest

#1345 [de] Add Rollo to cover shutter and Vorhang to abdeckungen
  sentences/de/_common.yaml
  tests/de/_fixtures.yaml
  tests/de/cover_HassGetState.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1590 [sv] possibility to turn on and off individual lights
  responses/sv/HassTurnOff.yaml
  responses/sv/HassTurnOn.yaml
  sentences/sv/light_HassTurnOff.yaml
  sentences/sv/light_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/light_HassTurnOff.yaml
  tests/sv/light_HassTurnOn.yaml
Labels: cla-signed, lang: sv, Hacktoberfest

#1599 Add pt language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed, Hacktoberfest

#1600 [hr] Sensor states
  responses/hr/HassGetState.yaml
  sentences/hr/_common.yaml
  sentences/hr/homeassistant_HassGetState.yaml
  sentences/hr/homeassistant_HassTurnOff.yaml
  sentences/hr/homeassistant_HassTurnOn.yaml
  sentences/hr/sensor_HassGetState.yaml
  tests/hr/_fixtures.yaml
  tests/hr/homeassistant_HassGetState.yaml
  tests/hr/sensor_HassGetState.yaml
Labels: cla-signed, lang: hr, Hacktoberfest
