Repository OHF-Voice/intents, pull requests merged in 2023-05, with the labels that each got.

#1330 [fr] add a new expansion rule <sontils>
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1329 [PL] Added some missing sentences with tests and removed redundant default response keys
  sentences/pl/climate_HassClimateGetTemperature.yaml
  sentences/pl/climate_HassClimateSetTemperature.yaml
  sentences/pl/homeassistant_HassTurnOff.yaml
  sentences/pl/homeassistant_HassTurnOn.yaml
  sentences/pl/script_HassTurnOn.yaml
  tests/pl/climate_HassClimateGetTemperature.yaml
  tests/pl/script_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#1337 [fr] add new intents in binary_sensors_HassGetState
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1341 [es] Added some voseo options from rioplatense Spanish
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#1340 [fr] adds intents for binary senors moisture ans motion + expansion rule changes
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1346 [PL] Simplified scene/script intent sentences, added missing activation variants and tests
  sentences/pl/_common.yaml
  sentences/pl/scene_HassTurnOn.yaml
  sentences/pl/script_HassTurnOn.yaml
  tests/pl/scene_HassTurnOn.yaml
  tests/pl/script_HassTurnOn.yaml
Labels: cla-signed, lang: pl

#1349 [fr] adds intents for binary sensors and HassLightSet
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  sentences/fr/light_HassLightSet.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
  tests/fr/light_HassLightSet.yaml
Labels: cla-signed, lang: fr

#1359 [de-ch] minor fixes
  sentences/de-CH/_common.yaml
  sentences/de-CH/climate_HassClimateGetTemperature.yaml
  sentences/de-CH/light_HassTurnOff.yaml
  sentences/de-CH/light_HassTurnOn.yaml
Labels: cla-signed

#1332 [DE] exclude sensor and binary sensor from homeassistant_HassTurnOff and homeassistant_HassTurnOn
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1360 [EN] Add short form of what's in HassGetState
  sentences/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#1362 [zh-tw] Update respond on _common.yaml
  sentences/zh-tw/_common.yaml
Labels: cla-signed

#1364 [zh-tw] Update _common.yaml
  sentences/zh-tw/_common.yaml
Labels: cla-signed

#1344 [EN] Add (switched|turned|set) to `all` question on `on_off_domains`
  sentences/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#1365 [zh-tw] Responses improvement & update
  responses/zh-tw/HassClimateSetTemperature.yaml
  responses/zh-tw/HassLightSet.yaml
  responses/zh-tw/HassTurnOff.yaml
  responses/zh-tw/HassTurnOn.yaml
  sentences/zh-tw/_common.yaml
  sentences/zh-tw/fan_HassTurnOn.yaml
  sentences/zh-tw/homeassistant_HassTurnOn.yaml
  tests/zh-tw/climate_HassClimateSetTemperature.yaml
  tests/zh-tw/cover_HassTurnOff.yaml
  tests/zh-tw/cover_HassTurnOn.yaml
  tests/zh-tw/fan_HassTurnOff.yaml
  tests/zh-tw/fan_HassTurnOn.yaml
  tests/zh-tw/homeassistant_HassTurnOff.yaml
  tests/zh-tw/homeassistant_HassTurnOn.yaml
  tests/zh-tw/light_HassLightSet.yaml
  tests/zh-tw/light_HassTurnOff.yaml
  tests/zh-tw/light_HassTurnOn.yaml
  tests/zh-tw/lock_HassTurnOff.yaml
  tests/zh-tw/lock_HassTurnOn.yaml
  tests/zh-tw/scene_HassTurnOn.yaml
  tests/zh-tw/script_HassTurnOn.yaml
Labels: cla-signed

#1368 Add English language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1369 Update HassGetState.yaml
  responses/el/HassGetState.yaml
Labels: cla-signed, lang: el

#1370 Update _common.yaml
  sentences/el/_common.yaml
Labels: cla-signed, lang: el

#1372 [el] Fix/test responses for lights and climate
  responses/el/HassLightSet.yaml
  responses/el/HassTurnOff.yaml
  responses/el/HassTurnOn.yaml
  sentences/el/light_HassLightSet.yaml
  sentences/el/light_HassTurnOff.yaml
  sentences/el/light_HassTurnOn.yaml
  tests/el/_fixtures.yaml
  tests/el/climate_HassClimateGetTemperature.yaml
  tests/el/climate_HassClimateSetTemperature.yaml
  tests/el/light_HassLightSet.yaml
  tests/el/light_HassTurnOff.yaml
  tests/el/light_HassTurnOn.yaml
Labels: cla-signed, lang: el

#1336 [DE] Add binary sensor cold
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1373 [DE] improve homeassistant_HassTurnOn and homeassistant_HassTurnOff
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1371 [el] HassGetState sentences/responses/tests for binary_sensor
  responses/el/HassGetState.yaml
  sentences/el/_common.yaml
  sentences/el/binary_sensor_HassGetState.yaml
  tests/el/_fixtures.yaml
  tests/el/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: el

#1374 [FR] Match french answers to the official Response Style Guide (part 1)
  responses/fr/HassLightSet.yaml
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/fan_HassTurnOff.yaml
  sentences/fr/fan_HassTurnOn.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/fan_HassTurnOff.yaml
  tests/fr/fan_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
Labels: cla-signed, lang: fr

#1376 [fr] New expansion rules and split binary_sensors intents
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1381 [el] Add sentences/test for homeassistant_HassGetState
  sentences/el/_common.yaml
  sentences/el/homeassistant_HassGetState.yaml
  tests/el/_fixtures.yaml
  tests/el/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: el

#1385 [el] fix typo in homeassistant_HassGetState
  sentences/el/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: el

#1384 [fr] add last intents and tests for binary_sensors
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/_fixtures.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#1350 Add ko Korean language
  languages.yaml
  responses/ko/HassClimateGetTemperature.yaml
  responses/ko/HassClimateSetTemperature.yaml
  responses/ko/HassGetState.yaml
  responses/ko/HassLightSet.yaml
  responses/ko/HassTurnOff.yaml
  responses/ko/HassTurnOn.yaml
  sentences/ko/_common.yaml
  sentences/ko/binary_sensor_HassGetState.yaml
  sentences/ko/climate_HassClimateGetTemperature.yaml
  sentences/ko/climate_HassClimateSetTemperature.yaml
  sentences/ko/cover_HassGetState.yaml
  sentences/ko/cover_HassTurnOff.yaml
  sentences/ko/cover_HassTurnOn.yaml
  sentences/ko/fan_HassTurnOff.yaml
  sentences/ko/fan_HassTurnOn.yaml
  sentences/ko/homeassistant_HassGetState.yaml
  sentences/ko/homeassistant_HassTurnOff.yaml
  sentences/ko/homeassistant_HassTurnOn.yaml
  sentences/ko/light_HassLightSet.yaml
  sentences/ko/light_HassTurnOff.yaml
  sentences/ko/light_HassTurnOn.yaml
  sentences/ko/lock_HassGetState.yaml
  sentences/ko/lock_HassTurnOff.yaml
  sentences/ko/lock_HassTurnOn.yaml
  sentences/ko/scene_HassTurnOn.yaml
  sentences/ko/script_HassTurnOn.yaml
  tests/ko/_fixtures.yaml
  tests/ko/binary_sensor_HassGetState.yaml
  tests/ko/climate_HassClimateGetTemperature.yaml
  tests/ko/climate_HassClimateSetTemperature.yaml
  tests/ko/cover_HassGetState.yaml
  tests/ko/cover_HassTurnOff.yaml
  tests/ko/cover_HassTurnOn.yaml
  tests/ko/fan_HassTurnOff.yaml
  tests/ko/fan_HassTurnOn.yaml
  tests/ko/homeassistant_HassGetState.yaml
  tests/ko/homeassistant_HassTurnOff.yaml
  tests/ko/homeassistant_HassTurnOn.yaml
  tests/ko/light_HassLightSet.yaml
  tests/ko/light_HassTurnOff.yaml
  tests/ko/light_HassTurnOn.yaml
  tests/ko/lock_HassGetState.yaml
  tests/ko/lock_HassTurnOff.yaml
  tests/ko/lock_HassTurnOn.yaml
  tests/ko/scene_HassTurnOn.yaml
  tests/ko/script_HassTurnOn.yaml
Labels: cla-signed, lang: ko

#1378 [DE] small improvements to lights
  sentences/de/_common.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1379 [DE] small improvements to covers
  sentences/de/_common.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1392 [it] - correction to cover expansion rule
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#1406 Add more flexible wording to generic HassGetState
  sentences/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#1387 [DE] improvements to locks
  sentences/de/_common.yaml
  sentences/de/lock_HassGetState.yaml
  sentences/de/lock_HassTurnOff.yaml
  sentences/de/lock_HassTurnOn.yaml
  tests/de/lock_HassGetState.yaml
Labels: cla-signed, lang: de

#1411 [Fr] A few adjustments in homeassistant_hassgetState
  sentences/fr/homeassistant_HassGetState.yaml
  tests/fr/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: fr
