Repository OHF-Voice/intents, pull requests merged in 2024-01, with the labels that each got.

#1841 [FR] TODO improvements 20240101
  sentences/fr/todo_HassListAddItem.yaml
  tests/fr/_fixtures.yaml
  tests/fr/todo_HassListAddItem.yaml
Labels: cla-signed, lang: fr

#1838 [NB] Add Norwegian translations for GetWeather
  responses/nb/HassGetWeather.yaml
  sentences/nb/weather_HassGetWeather.yaml
  tests/nb/_fixtures.yaml
  tests/nb/weather_HassGetWeather.yaml
Labels: cla-signed, lang: nb

#1842 [NB] Add support for more todo sentences
  sentences/nb/_common.yaml
  sentences/nb/todo_HassListAddItem.yaml
  tests/nb/todo_HassListAddItem.yaml
Labels: cla-signed, lang: nb

#1830 [de] Add area slots for scenes
  sentences/de/scene_HassTurnOn.yaml
  tests/de/scene_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1844 Fix context awareness
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl, lang: fr

#1846 [NL] Update ClimateGetTemperature
  responses/nl/HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/_fixtures.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: nl

#1858 Change French language leaders
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1804 add utf8 encoding option on validate.py
  script/intentfest/validate.py
Labels: cla-signed

#1861 [FR] Remove name all slot for french intents
  intents.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/fan_HassTurnOff.yaml
  sentences/fr/fan_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  sentences/fr/lock_HassTurnOff.yaml
  sentences/fr/lock_HassTurnOn.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/fan_HassTurnOff.yaml
  tests/fr/fan_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
  tests/fr/lock_HassTurnOff.yaml
  tests/fr/lock_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1813 [DE] Add sentences for turning lights on/off in the area of a satellite device
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1785 [EN] Context area aware intents
  sentences/en/cover_HassTurnOff.yaml
  sentences/en/cover_HassTurnOn.yaml
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/fan_HassTurnOn.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/cover_HassTurnOff.yaml
  tests/en/cover_HassTurnOn.yaml
  tests/en/fan_HassTurnOff.yaml
  tests/en/fan_HassTurnOn.yaml
  tests/en/light_HassLightSet.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1855 [FR] Improve cover sentences
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/homeassistant_HassTurnOff.yaml
  tests/fr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#622 Improve error message for unknown areas
  script/intentfest/validate.py
Labels: cla-signed

#1857 Remove area "all" slot for all languages
  sentences/ar/fan_HassTurnOff.yaml
  sentences/ar/light_HassLightSet.yaml
  sentences/ar/light_HassTurnOff.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/hr/fan_HassTurnOff.yaml
  sentences/hr/fan_HassTurnOn.yaml
  sentences/lv/cover_HassTurnOff.yaml
  sentences/lv/cover_HassTurnOn.yaml
  sentences/nb/fan_HassTurnOff.yaml
  sentences/nb/fan_HassTurnOn.yaml
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  sentences/sl/fan_HassTurnOff.yaml
  sentences/sl/fan_HassTurnOn.yaml
  sentences/zh-tw/fan_HassTurnOff.yaml
  sentences/zh-tw/light_HassTurnOff.yaml
  tests/ar/fan_HassTurnOff.yaml
  tests/ar/light_HassLightSet.yaml
  tests/ar/light_HassTurnOff.yaml
  tests/hr/fan_HassTurnOff.yaml
  tests/hr/fan_HassTurnOn.yaml
  tests/lv/cover_HassTurnOff.yaml
  tests/lv/cover_HassTurnOn.yaml
  tests/lv/homeassistant_HassTurnOff.yaml
  tests/lv/homeassistant_HassTurnOn.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/pl/fan_HassTurnOff.yaml
  tests/pl/fan_HassTurnOn.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
  tests/sl/fan_HassTurnOff.yaml
  tests/sl/fan_HassTurnOn.yaml
  tests/zh-tw/fan_HassTurnOff.yaml
  tests/zh-tw/light_HassTurnOff.yaml
Labels: cla-signed, lang: nb, lang: nl, lang: fr, lang: pl, lang: sl, lang: es, lang: hr, lang: ar, lang: lv

#1865 [EN] Better error messages
  sentences/en/_common.yaml
Labels: cla-signed, lang: en

#1864 [FR] Add context light to sentence targeting `{name}`
  sentences/fr/light_HassLightSet.yaml
Labels: cla-signed, lang: fr

#1870 [SL] Fixes for cover_Hass* - window, blinds and garage
  sentences/sl/_common.yaml
  sentences/sl/cover_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/cover_HassGetState.yaml
  tests/sl/cover_HassTurnOff.yaml
  tests/sl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#1871 Add context awareness to brightless and color
  sentences/fr/_common.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1854 [GL] Sentences, tests & fixtures for sensor_HassGetState
  sentences/gl/_common.yaml
  sentences/gl/sensor_HassGetState.yaml
  tests/gl/_fixtures.yaml
  tests/gl/sensor_HassGetState.yaml
Labels: cla-signed, lang: gl

#1873 [SL] added presence and power for binary sensor
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1876 [SL] added binary sensor - problem, running
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1878 [SL] binary sensor - safety, smoke, sound, tamper
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1863 [FI] HassGetWeather
  responses/fi/HassGetWeather.yaml
  sentences/fi/_common.yaml
  sentences/fi/weather_HassGetWeather.yaml
  tests/fi/_fixtures.yaml
  tests/fi/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fi

#1860 [FI] shopping list
  responses/fi/HassShoppingListAddItem.yaml
  sentences/fi/_common.yaml
  sentences/fi/shopping_list_HassShoppingListAddItem.yaml
  tests/fi/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: fi

#1879 [SL] added binary sensors - update, vibration, window
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1874 Updating Hungarian intentions
  responses/hu/HassClimateGetTemperature.yaml
  responses/hu/HassClimateSetTemperature.yaml
  responses/hu/HassGetState.yaml
  responses/hu/HassGetWeather.yaml
  responses/hu/HassLightSet.yaml
  responses/hu/HassListAddItem.yaml
  responses/hu/HassShoppingListAddItem.yaml
  responses/hu/HassTurnOff.yaml
  responses/hu/HassTurnOn.yaml
  sentences/hu/_common.yaml
  sentences/hu/binary_sensor_HassGetState.yaml
  sentences/hu/climate_HassClimateGetTemperature.yaml
  sentences/hu/climate_HassClimateSetTemperature.yaml
  sentences/hu/cover_HassGetState.yaml
  sentences/hu/cover_HassTurnOff.yaml
  sentences/hu/cover_HassTurnOn.yaml
  sentences/hu/fan_HassTurnOff.yaml
  sentences/hu/fan_HassTurnOn.yaml
  sentences/hu/homeassistant_HassGetState.yaml
  sentences/hu/homeassistant_HassNevermind.yaml
  sentences/hu/homeassistant_HassTurnOff.yaml
  sentences/hu/homeassistant_HassTurnOn.yaml
  sentences/hu/light_HassLightSet.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  sentences/hu/lock_HassGetState.yaml
  sentences/hu/lock_HassTurnOff.yaml
  sentences/hu/lock_HassTurnOn.yaml
  sentences/hu/person_HassGetState.yaml
  sentences/hu/scene_HassTurnOn.yaml
  sentences/hu/script_HassTurnOn.yaml
  sentences/hu/shopping_list_HassShoppingListAddItem.yaml
  sentences/hu/todo_HassListAddItem.yaml
  sentences/hu/weather_HassGetWeather.yaml
  tests/hu/_fixtures.yaml
  tests/hu/binary_sensor_HassGetState.yaml
  tests/hu/climate_HassClimateGetTemperature.yaml
  tests/hu/climate_HassClimateSetTemperature.yaml
  tests/hu/cover_HassGetState.yaml
  tests/hu/cover_HassTurnOff.yaml
  tests/hu/cover_HassTurnOn.yaml
  tests/hu/fan_HassTurnOff.yaml
  tests/hu/fan_HassTurnOn.yaml
  tests/hu/homeassistant_HassGetState.yaml
  tests/hu/homeassistant_HassNevermind.yaml
  tests/hu/homeassistant_HassTurnOff.yaml
  tests/hu/homeassistant_HassTurnOn.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
  tests/hu/lock_HassGetState.yaml
  tests/hu/lock_HassTurnOff.yaml
  tests/hu/lock_HassTurnOn.yaml
  tests/hu/person_HassGetState.yaml
  tests/hu/scene_HassTurnOn.yaml
  tests/hu/script_HassTurnOn.yaml
  tests/hu/shopping_list_HassShoppingListAddItem.yaml
  tests/hu/todo_HassListAddItem.yaml
  tests/hu/weather_HassGetWeather.yaml
Labels: cla-signed, lang: hu

#1881 [SL] added sensor_HassGetState.yaml and sensor for apparent power
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1883 [SL] sensor added for AQI
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1884 [HU] Added the sensor_HassGetState and the 'in_here' function
  responses/hu/HassGetState.yaml
  sentences/hu/_common.yaml
  sentences/hu/cover_HassTurnOff.yaml
  sentences/hu/cover_HassTurnOn.yaml
  sentences/hu/fan_HassTurnOff.yaml
  sentences/hu/fan_HassTurnOn.yaml
  sentences/hu/light_HassLightSet.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  sentences/hu/sensor_HassGetState.yaml
  tests/hu/_fixtures.yaml
  tests/hu/cover_HassTurnOff.yaml
  tests/hu/cover_HassTurnOn.yaml
  tests/hu/fan_HassTurnOff.yaml
  tests/hu/fan_HassTurnOn.yaml
  tests/hu/homeassistant_HassGetState.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
  tests/hu/sensor_HassGetState.yaml
Labels: cla-signed, lang: hu

#1891 [hu] More flexible word order, bug fix, +2 color ver2
  responses/hu/HassLightSet.yaml
  sentences/hu/_common.yaml
  sentences/hu/climate_HassClimateSetTemperature.yaml
  sentences/hu/cover_HassGetState.yaml
  sentences/hu/cover_HassTurnOff.yaml
  sentences/hu/cover_HassTurnOn.yaml
  sentences/hu/fan_HassTurnOff.yaml
  sentences/hu/fan_HassTurnOn.yaml
  sentences/hu/homeassistant_HassTurnOff.yaml
  sentences/hu/homeassistant_HassTurnOn.yaml
  sentences/hu/light_HassLightSet.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  sentences/hu/lock_HassGetState.yaml
  sentences/hu/lock_HassTurnOff.yaml
  sentences/hu/lock_HassTurnOn.yaml
  sentences/hu/scene_HassTurnOn.yaml
  sentences/hu/script_HassTurnOn.yaml
  sentences/hu/shopping_list_HassShoppingListAddItem.yaml
  sentences/hu/todo_HassListAddItem.yaml
  tests/hu/cover_HassGetState.yaml
  tests/hu/fan_HassTurnOff.yaml
  tests/hu/fan_HassTurnOn.yaml
  tests/hu/homeassistant_HassTurnOff.yaml
  tests/hu/homeassistant_HassTurnOn.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: hu

#1892 [hu] bugfix
  sentences/hu/_common.yaml
  sentences/hu/light_HassLightSet.yaml
  tests/hu/light_HassLightSet.yaml
Labels: cla-signed, lang: hu

#1800 [EL] Update _common.yaml
  sentences/el/_common.yaml
Labels: cla-signed, lang: el

#1895 [FR] Error message improvements
  sentences/fr/_common.yaml
  tests/fr/cover_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1896 [HU] Translation of error messages + handling of articles in the erro…
  sentences/hu/_common.yaml
  sentences/hu/shopping_list_HassShoppingListAddItem.yaml
  sentences/hu/todo_HassListAddItem.yaml
Labels: cla-signed, lang: hu

#1894 [EN] Fix scene sentences
  sentences/en/scene_HassTurnOn.yaml
  tests/en/scene_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1897 [ES] Updating translations
  sentences/es/_common.yaml
  sentences/es/cover_HassTurnOff.yaml
  sentences/es/cover_HassTurnOn.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/cover_HassTurnOff.yaml
  tests/es/cover_HassTurnOn.yaml
  tests/es/fan_HassTurnOff.yaml
  tests/es/fan_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#1899 [HU] Optimization of response, handling of articles, correction of number format
  responses/hu/HassClimateGetTemperature.yaml
  responses/hu/HassGetState.yaml
  responses/hu/HassGetWeather.yaml
  responses/hu/HassListAddItem.yaml
  responses/hu/HassShoppingListAddItem.yaml
  responses/hu/HassTurnOff.yaml
  responses/hu/HassTurnOn.yaml
  sentences/hu/_common.yaml
  sentences/hu/weather_HassGetWeather.yaml
  tests/hu/_fixtures.yaml
  tests/hu/climate_HassClimateGetTemperature.yaml
  tests/hu/cover_HassTurnOff.yaml
  tests/hu/cover_HassTurnOn.yaml
  tests/hu/homeassistant_HassTurnOff.yaml
  tests/hu/homeassistant_HassTurnOn.yaml
  tests/hu/person_HassGetState.yaml
  tests/hu/shopping_list_HassShoppingListAddItem.yaml
  tests/hu/todo_HassListAddItem.yaml
  tests/hu/weather_HassGetWeather.yaml
Labels: cla-signed, lang: hu

#1903 Remove old package directory
  package/.gitignore
  package/LICENSE.md
  package/MANIFEST.in
  package/README.md
  package/home_assistant_intents/__init__.py
  package/home_assistant_intents/domains.py
  package/pyproject.toml
  package/script/write_languages.py
  script/format
  script/lint
  script/package
Labels: cla-signed

#1904 [SL] added sensor atmospheric pressure
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl
