Repository OHF-Voice/intents, pull requests merged in 2024-11, with the labels that each got.

#2438 [en] Add min as a represenation of minimum
  sentences/en/_common.yaml
  tests/en/light_HassLightSet.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2443 [nb] Get current date and time
  responses/nb/HassGetCurrentDate.yaml
  responses/nb/HassGetCurrentTime.yaml
  sentences/nb/homeassistant_HassGetCurrentDate.yaml
  sentences/nb/homeassistant_HassGetCurrentTime.yaml
  tests/nb/homeassistant_HassGetCurrentDate.yaml
  tests/nb/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: nb

#2441 [nb] Add timers
  responses/nb/HassCancelTimer.yaml
  responses/nb/HassDecreaseTimer.yaml
  responses/nb/HassIncreaseTimer.yaml
  responses/nb/HassPauseTimer.yaml
  responses/nb/HassStartTimer.yaml
  responses/nb/HassTimerStatus.yaml
  responses/nb/HassUnpauseTimer.yaml
  sentences/nb/_common.yaml
  sentences/nb/homeassistant_HassCancelTimer.yaml
  sentences/nb/homeassistant_HassDecreaseTimer.yaml
  sentences/nb/homeassistant_HassIncreaseTimer.yaml
  sentences/nb/homeassistant_HassPauseTimer.yaml
  sentences/nb/homeassistant_HassStartTimer.yaml
  sentences/nb/homeassistant_HassTimerStatus.yaml
  sentences/nb/homeassistant_HassUnpauseTimer.yaml
  tests/nb/_fixtures.yaml
  tests/nb/homeassistant_HassCancelTimer.yaml
  tests/nb/homeassistant_HassDecreaseTimer.yaml
  tests/nb/homeassistant_HassIncreaseTimer.yaml
  tests/nb/homeassistant_HassPauseTimer.yaml
  tests/nb/homeassistant_HassStartTimer.yaml
  tests/nb/homeassistant_HassTimerStatus.yaml
  tests/nb/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: nb

#2444 [nb] Add media player previous
  responses/nb/HassMediaPrevious.yaml
  sentences/nb/media_player_HassMediaPrevious.yaml
  tests/nb/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: nb

#2439 [en] Add more expansions for state values
  sentences/en/_common.yaml
  tests/en/binary_sensor_HassGetState.yaml
  tests/en/cover_HassGetState.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2448 Add HassRespond intent
  intents.yaml
  responses/en/HassRespond.yaml
  sentences/en/homeassistant_HassRespond.yaml
  tests/en/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: en

#2451 [FR] remove update sentences
  sentences/fr/_common.yaml
  sentences/fr/binary_sensor_HassGetState.yaml
  tests/fr/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: fr

#2456 [RO] HassRespond
  responses/ro/HassRespond.yaml
  sentences/ro/homeassistant_HassRespond.yaml
  tests/ro/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: ro

#2457 [NL] New attempt for HassRespond translations
  responses/nl/HassRespond.yaml
  sentences/nl/homeassistant_HassRespond.yaml
  tests/nl/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: nl

#2460 [PT-BR] Update timer sentences
  responses/pt-br/HassCancelTimer.yaml
  responses/pt-br/HassDecreaseTimer.yaml
  responses/pt-br/HassIncreaseTimer.yaml
  responses/pt-br/HassPauseTimer.yaml
  responses/pt-br/HassStartTimer.yaml
  responses/pt-br/HassTimerStatus.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassCancelTimer.yaml
  sentences/pt-br/homeassistant_HassDecreaseTimer.yaml
  sentences/pt-br/homeassistant_HassIncreaseTimer.yaml
  sentences/pt-br/homeassistant_HassPauseTimer.yaml
  sentences/pt-br/homeassistant_HassStartTimer.yaml
  sentences/pt-br/homeassistant_HassTimerStatus.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassCancelTimer.yaml
  tests/pt-br/homeassistant_HassDecreaseTimer.yaml
  tests/pt-br/homeassistant_HassIncreaseTimer.yaml
  tests/pt-br/homeassistant_HassPauseTimer.yaml
  tests/pt-br/homeassistant_HassStartTimer.yaml
  tests/pt-br/homeassistant_HassTimerStatus.yaml
Labels: cla-signed

#2461 [PT-BR] HassRespond
  responses/pt-br/HassRespond.yaml
  sentences/pt-br/homeassistant_HassRespond.yaml
  tests/pt-br/homeassistant_HassRespond.yaml
Labels: cla-signed

#2459 [NL] Add some more sentences to ask for timer status
  sentences/nl/homeassistant_HassTimerStatus.yaml
  tests/nl/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: nl

#2340 [CA] Add more Get Temperature sentences
  responses/ca/HassClimateGetTemperature.yaml
  sentences/ca/_common.yaml
  sentences/ca/climate_HassClimateGetTemperature.yaml
  tests/ca/_fixtures.yaml
  tests/ca/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: ca

#2452 [PL] added polish HassRespond intent
  responses/pl/HassRespond.yaml
  sentences/pl/homeassistant_HassRespond.yaml
  tests/pl/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: pl

#2284 [CA] Add ListAddItems
  responses/ca/HassListAddItem.yaml
  sentences/ca/_common.yaml
  sentences/ca/todo_HassListAddItem.yaml
  tests/ca/_fixtures.yaml
  tests/ca/todo_HassListAddItem.yaml
Labels: cla-signed, lang: ca

#2395 [SV] Locks sentences
  responses/sv/HassTurnOff.yaml
  responses/sv/HassTurnOn.yaml
  sentences/sv/_common.yaml
  sentences/sv/lock_HassTurnOff.yaml
  sentences/sv/lock_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/lock_HassTurnOff.yaml
  tests/sv/lock_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2470 [PT-BR] New sentences and responses
  responses/pt-br/HassUnpauseTimer.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/cover_HassGetState.yaml
  sentences/pt-br/homeassistant_HassGetState.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  sentences/pt-br/homeassistant_HassUnpauseTimer.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/cover_HassGetState.yaml
  tests/pt-br/homeassistant_HassGetState.yaml
  tests/pt-br/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: pt-br

#2466 [ES] Updating translations
  responses/es/HassRespond.yaml
  responses/es/HassTurnOff.yaml
  responses/es/HassTurnOn.yaml
  sentences/es/_common.yaml
  sentences/es/climate_HassClimateGetTemperature.yaml
  sentences/es/cover_HassGetState.yaml
  sentences/es/cover_HassSetPosition.yaml
  sentences/es/cover_HassTurnOff.yaml
  sentences/es/fan_HassTurnOff.yaml
  sentences/es/fan_HassTurnOn.yaml
  sentences/es/homeassistant_HassCancelTimer.yaml
  sentences/es/homeassistant_HassRespond.yaml
  sentences/es/light_HassLightSet.yaml
  sentences/es/lock_HassGetState.yaml
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/binary_sensor_HassGetState.yaml
  tests/es/homeassistant_HassRespond.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/lock_HassGetState.yaml
  tests/es/lock_HassTurnOn.yaml
Labels: cla-signed, lang: es

#2474 [PT-BR] Update media previous
  responses/pt-br/HassMediaPrevious.yaml
  sentences/pt-br/media_player_HassMediaPrevious.yaml
  tests/pt-br/media_player_HassMediaPrevious.yaml
Labels: cla-signed

#2468 [ES] Add more sentences to test getting the temperature
  tests/es/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: es

#2477 [sl] added respond
  responses/sl/HassRespond.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassRespond.yaml
  tests/sl/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sl

#2478 [FI] Timer
  responses/fi/HassCancelTimer.yaml
  responses/fi/HassDecreaseTimer.yaml
  responses/fi/HassIncreaseTimer.yaml
  responses/fi/HassPauseTimer.yaml
  responses/fi/HassStartTimer.yaml
  responses/fi/HassTimerStatus.yaml
  responses/fi/HassUnpauseTimer.yaml
  sentences/fi/_common.yaml
  sentences/fi/homeassistant_HassCancelTimer.yaml
  sentences/fi/homeassistant_HassDecreaseTimer.yaml
  sentences/fi/homeassistant_HassIncreaseTimer.yaml
  sentences/fi/homeassistant_HassPauseTimer.yaml
  sentences/fi/homeassistant_HassStartTimer.yaml
  sentences/fi/homeassistant_HassTimerStatus.yaml
  sentences/fi/homeassistant_HassUnpauseTimer.yaml
  tests/fi/_fixtures.yaml
  tests/fi/homeassistant_HassCancelTimer.yaml
  tests/fi/homeassistant_HassDecreaseTimer.yaml
  tests/fi/homeassistant_HassIncreaseTimer.yaml
  tests/fi/homeassistant_HassPauseTimer.yaml
  tests/fi/homeassistant_HassStartTimer.yaml
  tests/fi/homeassistant_HassTimerStatus.yaml
  tests/fi/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fi

#2475 [AR] create and fill homeassistant_HassRespond
  responses/ar/HassRespond.yaml
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassRespond.yaml
  tests/ar/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: ar

#1955 [DA]: Add binary_sensor_HassGetState
  sentences/da/_common.yaml
  sentences/da/binary_sensor_HassGetState.yaml
  tests/da/_fixtures.yaml
  tests/da/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: da

#2287 [NL] Finetune cover_HassSetPosition
  sentences/nl/cover_HassSetPosition.yaml
  tests/nl/cover_HassSetPosition.yaml
Labels: cla-signed, lang: nl

#2482 [de-CH] Add intents for timer, date and time
  responses/de-CH/HassCancelTimer.yaml
  responses/de-CH/HassDecreaseTimer.yaml
  responses/de-CH/HassGetCurrentDate.yaml
  responses/de-CH/HassGetCurrentTime.yaml
  responses/de-CH/HassIncreaseTimer.yaml
  responses/de-CH/HassPauseTimer.yaml
  responses/de-CH/HassStartTimer.yaml
  responses/de-CH/HassTimerStatus.yaml
  responses/de-CH/HassUnpauseTimer.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/homeassistant_HassCancelTimer.yaml
  sentences/de-CH/homeassistant_HassDecreaseTimer.yaml
  sentences/de-CH/homeassistant_HassGetCurrentDate.yaml
  sentences/de-CH/homeassistant_HassGetCurrentTime.yaml
  sentences/de-CH/homeassistant_HassIncreaseTimer.yaml
  sentences/de-CH/homeassistant_HassPauseTimer.yaml
  sentences/de-CH/homeassistant_HassStartTimer.yaml
  sentences/de-CH/homeassistant_HassTimerStatus.yaml
  sentences/de-CH/homeassistant_HassUnpauseTimer.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/homeassistant_HassCancelTimer.yaml
  tests/de-CH/homeassistant_HassDecreaseTimer.yaml
  tests/de-CH/homeassistant_HassGetCurrentDate.yaml
  tests/de-CH/homeassistant_HassGetCurrentTime.yaml
  tests/de-CH/homeassistant_HassIncreaseTimer.yaml
  tests/de-CH/homeassistant_HassPauseTimer.yaml
  tests/de-CH/homeassistant_HassStartTimer.yaml
  tests/de-CH/homeassistant_HassTimerStatus.yaml
  tests/de-CH/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed

#2483 [de-CH] Add HassMediaPrevious
  responses/de-CH/HassMediaPrevious.yaml
  sentences/de-CH/media_player_HassMediaNext.yaml
  sentences/de-CH/media_player_HassMediaPrevious.yaml
  tests/de-CH/media_player_HassMediaNext.yaml
  tests/de-CH/media_player_HassMediaPrevious.yaml
Labels: cla-signed

#2481 [FI] initial get time and date commit
  responses/fi/HassGetCurrentDate.yaml
  responses/fi/HassGetCurrentTime.yaml
  sentences/fi/homeassistant_HassGetCurrentDate.yaml
  sentences/fi/homeassistant_HassGetCurrentTime.yaml
  tests/fi/homeassistant_HassGetCurrentDate.yaml
  tests/fi/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: fi

#2484 [de-CH] Add HassRespond
  responses/de-CH/HassRespond.yaml
Labels: cla-signed

#2485 [AR] HassSetPosition intent and some improvements
  responses/ar/HassSetPosition.yaml
  sentences/ar/_common.yaml
  sentences/ar/cover_HassSetPosition.yaml
  sentences/ar/lock_HassTurnOff.yaml
  sentences/ar/lock_HassTurnOn.yaml
  sentences/ar/valve_HassSetPosition.yaml
  tests/ar/_fixtures.yaml
  tests/ar/cover_HassSetPosition.yaml
  tests/ar/light_HassLightSet.yaml
  tests/ar/valve_HassSetPosition.yaml
Labels: cla-signed, lang: ar

#2479 [NL] Improvements media_player intents
  sentences/nl/_common.yaml
  sentences/nl/media_player_HassMediaNext.yaml
  sentences/nl/media_player_HassMediaPause.yaml
  sentences/nl/media_player_HassMediaUnpause.yaml
  sentences/nl/media_player_HassSetVolume.yaml
  tests/nl/media_player_HassMediaNext.yaml
  tests/nl/media_player_HassMediaPause.yaml
  tests/nl/media_player_HassMediaUnpause.yaml
  tests/nl/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: nl

#2290 [NL] Finetune HassTurnOff/On for covers and fans & align with EN
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2462 [CA] Add HassRespond intent
  responses/ca/HassRespond.yaml
  sentences/ca/homeassistant_HassRespond.yaml
  tests/ca/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: ca

#2453 [DE] Add de HassRespond translations
  responses/de/HassRespond.yaml
  sentences/de/homeassistant_HassRespond.yaml
  tests/de/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: de

#2487 [SL] running states enhanced
  sentences/sl/_common.yaml
  tests/sl/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2488 [CA] add HassCancelTimer
  responses/ca/HassCancelTimer.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassCancelTimer.yaml
  tests/ca/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: ca

#2489 [CA] Add GetCurrentTime and GetCurrentDate
  responses/ca/HassGetCurrentDate.yaml
  responses/ca/HassGetCurrentTime.yaml
  sentences/ca/homeassistant_HassGetCurrentDate.yaml
  sentences/ca/homeassistant_HassGetCurrentTime.yaml
  tests/ca/homeassistant_HassGetCurrentDate.yaml
  tests/ca/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: ca

#2490 [CA] Update _common.yaml
  sentences/ca/_common.yaml
Labels: cla-signed, lang: ca

#2486 [nb] Extend sentences for timer duration by adding half and quarter
  sentences/nb/_common.yaml
  tests/nb/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: nb

#2495 [AR] HassGetCurrentDate and improve Arabic sentence structures
  responses/ar/HassGetCurrentDate.yaml
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassGetCurrentDate.yaml
  sentences/ar/homeassistant_HassRespond.yaml
  tests/ar/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: ar

#2498 [AR] HassGetCurrentTime
  responses/ar/HassGetCurrentTime.yaml
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassGetCurrentTime.yaml
  tests/ar/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: ar

#2497 [nb] Add respond
  responses/nb/HassRespond.yaml
  sentences/nb/homeassistant_HassRespond.yaml
  tests/nb/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: en, lang: nb

#2502 Intent website: Green to mean usable, star to mean complete coverage
  script/intentfest/const.py
  script/intentfest/website_summary.py
  website/public/style.css
  website/src-11ty/index.html
Labels: cla-signed

#2503 Remove temp website build file
  website/src-11ty/_data/.gitignore
  website/src-11ty/_data/intentSummary.json
Labels: cla-signed

#2505 Add Swedish HassListAddItem
  responses/sv/HassListAddItem.yaml
  sentences/sv/todo_HassListAddItem.yaml
  tests/sv/_fixtures.yaml
  tests/sv/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sv

#2508 [SL] HassGetState sentences and test adjustment, added a few
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassGetState.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2511 [de-CH] Add sentences and tests for HassRespond
  sentences/de-CH/homeassistant_HassRespond.yaml
  tests/de-CH/homeassistant_HassRespond.yaml
Labels: cla-signed

#2494 [EN] Add timer length and name to responses
  responses/en/HassStartTimer.yaml
  responses/nl/HassStartTimer.yaml
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
  tests/nl/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en, lang: nl

#2509 [AR] HassShoppingListAddItem
  responses/ar/HassShoppingListAddItem.yaml
  sentences/ar/_common.yaml
  sentences/ar/shopping_list_HassShoppingListAddItem.yaml
  tests/ar/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ar

#2517 [NB] Fix failing test
  sentences/nb/homeassistant_HassPauseTimer.yaml
  tests/nb/_test_failures.yaml
Labels: cla-signed, lang: nb

#2518 [NB] Remove duplicated key
  tests/nb/homeassistant_HassPauseTimer.yaml
Labels: cla-signed, lang: nb

#2519 [FR] Fix typo in french timer intent
  responses/fr/HassTimerStatus.yaml
Labels: cla-signed, lang: fr

#2516 [FR] A few missing simple intents
  responses/fr/HassMediaPrevious.yaml
  responses/fr/HassRespond.yaml
  sentences/fr/homeassistant_HassNevermind.yaml
  sentences/fr/homeassistant_HassRespond.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/media_player_HassMediaPrevious.yaml
  tests/fr/homeassistant_HassNevermind.yaml
  tests/fr/homeassistant_HassRespond.yaml
  tests/fr/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: fr

#2476 [FR] Improve lights intents with AI
  sentences/fr/_common.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#2522 [NL] Add duration to increase and decrease timer
  responses/nl/HassDecreaseTimer.yaml
  responses/nl/HassIncreaseTimer.yaml
  tests/nl/homeassistant_HassDecreaseTimer.yaml
  tests/nl/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: nl

#2512 Only run tests for affected languages in PRs
  .github/workflows/ci.yaml
  tests/bg/todo_HassListAddItem.yaml
Labels: cla-signed, lang: bg

#2523 [CA] Fix actions to domain cover
  responses/ca/HassTurnOff.yaml
  responses/ca/HassTurnOn.yaml
  sentences/ca/_common.yaml
  sentences/ca/cover_HassTurnOff.yaml
  sentences/ca/cover_HassTurnOn.yaml
  sentences/ca/homeassistant_HassTurnOff.yaml
  sentences/ca/homeassistant_HassTurnOn.yaml
  tests/ca/cover_HassTurnOff.yaml
  tests/ca/cover_HassTurnOn.yaml
  tests/ca/homeassistant_HassTurnOff.yaml
  tests/ca/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2524 [CA] Add DecreaseTimer and IncreaseTimer
  responses/ca/HassDecreaseTimer.yaml
  responses/ca/HassIncreaseTimer.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassDecreaseTimer.yaml
  sentences/ca/homeassistant_HassIncreaseTimer.yaml
  tests/ca/homeassistant_HassDecreaseTimer.yaml
  tests/ca/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: ca

#2525 fix(ci): check language modified to run faster tests
  .github/workflows/ci.yaml
Labels: cla-signed, github_actions

#2506 [NL] Add HassMediaPrevious
  responses/nl/HassMediaPrevious.yaml
  sentences/nl/media_player_HassMediaPrevious.yaml
  tests/nl/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: nl

#2526 Website: list per language the missing intents
  script/intentfest/website_summary.py
  website/src-11ty/index.html
Labels: cla-signed

#2527 Website: move empty languages to own table
  script/intentfest/website_summary.py
  website/src-11ty/index.html
Labels: cla-signed

#2521 [EN] Add duration added or removed from timer
  responses/en/HassDecreaseTimer.yaml
  responses/en/HassIncreaseTimer.yaml
  tests/en/homeassistant_HassDecreaseTimer.yaml
  tests/en/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: en

#2504 [BG] Add current time and add to shopping list
  responses/bg/HassGetCurrentTime.yaml
  responses/bg/HassShoppingListAddItem.yaml
  sentences/bg/homeassistant_HassGetCurrentTime.yaml
  sentences/bg/shopping_list_HassShoppingListAddItem.yaml
  tests/bg/homeassistant_HassGetCurrentTime.yaml
  tests/bg/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: bg

#2432 [BG] Add HassGetDate and HassGetTime
  responses/bg/HassGetCurrentDate.yaml
  sentences/bg/homeassistant_HassGetCurrentDate.yaml
  tests/bg/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: bg, Hacktoberfest

#2528 Allow generating a template to feed LLMs to aid translation
  script/intentfest/llm_template.py
  script/intentfest/util.py
Labels: cla-signed

#2500 allow using imperative conjugation to interact with locks
  sentences/es/lock_HassTurnOff.yaml
  sentences/es/lock_HassTurnOn.yaml
Labels: cla-signed, lang: es

#2535 [ml] Add HassNevermind
  sentences/ml/homeassistant_HassNevermind.yaml
  tests/ml/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: ml

#2536 [HU] Updating and expanding MediaPlayer intents
  responses/hu/HassMediaPrevious.yaml
  sentences/hu/media_player_HassMediaNext.yaml
  sentences/hu/media_player_HassMediaPause.yaml
  sentences/hu/media_player_HassMediaPrevious.yaml
  sentences/hu/media_player_HassMediaUnpause.yaml
  sentences/hu/media_player_HassSetVolume.yaml
  tests/hu/media_player_HassMediaNext.yaml
  tests/hu/media_player_HassMediaPause.yaml
  tests/hu/media_player_HassMediaPrevious.yaml
  tests/hu/media_player_HassMediaUnpause.yaml
  tests/hu/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: hu

#2537 [HU] Creating Current Date/Time and Respond
  responses/hu/HassGetCurrentDate.yaml
  responses/hu/HassGetCurrentTime.yaml
  responses/hu/HassRespond.yaml
  sentences/hu/homeassistant_HassGetCurrentDate.yaml
  sentences/hu/homeassistant_HassGetCurrentTime.yaml
  sentences/hu/homeassistant_HassRespond.yaml
  tests/hu/homeassistant_HassGetCurrentDate.yaml
  tests/hu/homeassistant_HassGetCurrentTime.yaml
  tests/hu/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: hu

#2538 [NL] remove unneeded spaces in lists
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/cover_HassSetPosition.yaml
  sentences/nl/homeassistant_HassCancelTimer.yaml
  sentences/nl/homeassistant_HassDecreaseTimer.yaml
  sentences/nl/homeassistant_HassGetCurrentDate.yaml
  sentences/nl/homeassistant_HassGetCurrentTime.yaml
  sentences/nl/homeassistant_HassIncreaseTimer.yaml
  sentences/nl/homeassistant_HassPauseTimer.yaml
  sentences/nl/homeassistant_HassRespond.yaml
  sentences/nl/homeassistant_HassTimerStatus.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/homeassistant_HassUnpauseTimer.yaml
  sentences/nl/lock_HassTurnOff.yaml
  sentences/nl/lock_HassTurnOn.yaml
  sentences/nl/media_player_HassMediaUnpause.yaml
  sentences/nl/media_player_HassSetVolume.yaml
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  sentences/nl/shopping_list_HassShoppingListAddItem.yaml
  sentences/nl/todo_HassListAddItem.yaml
  sentences/nl/vacuum_HassVacuumReturnToBase.yaml
  sentences/nl/valve_HassSetPosition.yaml
  sentences/nl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: nl

#2539 [SL] sentences and test fixed according to #2507
  responses/sl/HassTurnOff.yaml
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/binary_sensor_HassGetState.yaml
  sentences/sl/cover_HassTurnOn.yaml
  sentences/sl/fan_HassTurnOff.yaml
  sentences/sl/fan_HassTurnOn.yaml
  sentences/sl/homeassistant_HassTurnOff.yaml
  tests/sl/_fixtures.yaml
  tests/sl/_test_failures.yaml
  tests/sl/binary_sensor_HassGetState.yaml
  tests/sl/cover_HassGetState.yaml
  tests/sl/cover_HassTurnOn.yaml
  tests/sl/fan_HassTurnOff.yaml
  tests/sl/fan_HassTurnOn.yaml
  tests/sl/homeassistant_HassGetState.yaml
  tests/sl/homeassistant_HassTurnOff.yaml
  tests/sl/homeassistant_HassTurnOn.yaml
  tests/sl/light_HassTurnOff.yaml
Labels: cla-signed, lang: sl

#2540 [AR] HassGetWeather
  responses/ar/HassGetWeather.yaml
  sentences/ar/_common.yaml
  sentences/ar/weather_HassGetWeather.yaml
  tests/ar/_fixtures.yaml
  tests/ar/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ar

#2542 [AR] todo_HassListAddItem
  responses/ar/HassListAddItem.yaml
  sentences/ar/todo_HassListAddItem.yaml
  tests/ar/_fixtures.yaml
  tests/ar/todo_HassListAddItem.yaml
Labels: cla-signed, lang: ar

#2446 [CS] Update media commands
  responses/cs/HassMediaPrevious.yaml
  sentences/cs/_common.yaml
  sentences/cs/media_player_HassMediaNext.yaml
  sentences/cs/media_player_HassMediaPause.yaml
  sentences/cs/media_player_HassMediaPrevious.yaml
  sentences/cs/media_player_HassMediaUnpause.yaml
  sentences/cs/media_player_HassSetVolume.yaml
  tests/cs/_fixtures.yaml
  tests/cs/media_player_HassMediaNext.yaml
  tests/cs/media_player_HassMediaPause.yaml
  tests/cs/media_player_HassMediaPrevious.yaml
  tests/cs/media_player_HassMediaUnpause.yaml
  tests/cs/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: cs

#2541 [NL] Use English for all expansion rules
  sentences/nl/_common.yaml
  sentences/nl/binary_sensor_HassGetState.yaml
  sentences/nl/climate_HassClimateGetTemperature.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  sentences/nl/cover_HassGetState.yaml
  sentences/nl/cover_HassSetPosition.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  sentences/nl/homeassistant_HassCancelTimer.yaml
  sentences/nl/homeassistant_HassDecreaseTimer.yaml
  sentences/nl/homeassistant_HassGetState.yaml
  sentences/nl/homeassistant_HassPauseTimer.yaml
  sentences/nl/homeassistant_HassTimerStatus.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  sentences/nl/homeassistant_HassUnpauseTimer.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  sentences/nl/lock_HassGetState.yaml
  sentences/nl/lock_HassTurnOff.yaml
  sentences/nl/lock_HassTurnOn.yaml
  sentences/nl/media_player_HassMediaNext.yaml
  sentences/nl/media_player_HassMediaPause.yaml
  sentences/nl/media_player_HassMediaPrevious.yaml
  sentences/nl/media_player_HassMediaUnpause.yaml
  sentences/nl/media_player_HassSetVolume.yaml
  sentences/nl/person_HassGetState.yaml
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  sentences/nl/valve_HassSetPosition.yaml
Labels: cla-signed, lang: nl

#2544 [NL] Improvements fan_HassTurnOn/Off
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2534 [DE] Add some set timer variations
  sentences/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: de

#2545 [NL] Improve cover intents
  sentences/nl/cover_HassSetPosition.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  tests/nl/cover_HassSetPosition.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2548 [HU] Floor support + GetState (Add light sensor)
  responses/hu/HassTurnOff.yaml
  responses/hu/HassTurnOn.yaml
  sentences/hu/_common.yaml
  sentences/hu/binary_sensor_HassGetState.yaml
  sentences/hu/cover_HassGetState.yaml
  sentences/hu/light_HassLightSet.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
  tests/hu/_fixtures.yaml
  tests/hu/binary_sensor_HassGetState.yaml
  tests/hu/cover_HassGetState.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#2531 [IT] Add support for HassListAdditem
  responses/it/HassListAddItem.yaml
  sentences/it/_common.yaml
  sentences/it/shopping_list_HassShoppingListAddItem.yaml
  sentences/it/todo_HassListAddItem.yaml
  tests/it/_fixtures.yaml
  tests/it/shopping_list_HassShoppingListAddItem.yaml
  tests/it/todo_HassListAddItem.yaml
Labels: cla-signed, lang: it

#2447 [IT] Add support for HassSetPosition
  responses/it/HassSetPosition.yaml
  sentences/it/_common.yaml
  sentences/it/cover_HassSetPosition.yaml
  tests/it/_fixtures.yaml
  tests/it/cover_HassSetPosition.yaml
Labels: cla-signed, lang: it

#2550 [HU] TimerStatus response optimization v2
  responses/hu/HassTimerStatus.yaml
Labels: cla-signed, lang: hu

#2552 [FI] Fixes and improvements for timers
  sentences/fi/_common.yaml
  sentences/fi/homeassistant_HassCancelTimer.yaml
  sentences/fi/homeassistant_HassStartTimer.yaml
  tests/fi/homeassistant_HassCancelTimer.yaml
  tests/fi/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: fi

#2553 [uk] Added HassStartTimer intent
  responses/uk/HassStartTimer.yaml
  sentences/uk/_common.yaml
  sentences/uk/homeassistant_HassStartTimer.yaml
  tests/uk/_fixtures.yaml
  tests/uk/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: uk

#2554 [uk] Added HassCancelTimer intent
  responses/uk/HassCancelTimer.yaml
  sentences/uk/homeassistant_HassCancelTimer.yaml
  tests/uk/_fixtures.yaml
  tests/uk/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: uk

#2559 [uk] Added HassTimerStatus intent
  responses/uk/HassTimerStatus.yaml
  sentences/uk/homeassistant_HassTimerStatus.yaml
  tests/uk/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: uk

#2561 [uk] Added HassRespond intent
  responses/uk/HassRespond.yaml
  sentences/uk/homeassistant_HassRespond.yaml
  tests/uk/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: uk

#2558 [HE] Add Hebrew for more intents
  responses/he/HassCancelTimer.yaml
  responses/he/HassListAddItem.yaml
  responses/he/HassStartTimer.yaml
  responses/he/HassTimerStatus.yaml
  sentences/he/_common.yaml
  sentences/he/homeassistant_HassCancelTimer.yaml
  sentences/he/homeassistant_HassStartTimer.yaml
  sentences/he/homeassistant_HassTimerStatus.yaml
  sentences/he/todo_HassListAddItem.yaml
  tests/he/_fixtures.yaml
  tests/he/climate_HassClimateGetTemperature.yaml
  tests/he/homeassistant_HassCancelTimer.yaml
  tests/he/homeassistant_HassStartTimer.yaml
  tests/he/homeassistant_HassTimerStatus.yaml
  tests/he/todo_HassListAddItem.yaml
Labels: cla-signed, lang: he

#2492 [CA] Add HassUnpauseTimer
  responses/ca/HassUnpauseTimer.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassUnpauseTimer.yaml
  tests/ca/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: ca

#2491 [CA] Add HassTimerStatus
  responses/ca/HassTimerStatus.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassTimerStatus.yaml
  tests/ca/_fixtures.yaml
  tests/ca/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: ca

#2563 [CA] Add HassPauseTimer
  responses/ca/HassPauseTimer.yaml
  sentences/ca/homeassistant_HassPauseTimer.yaml
  tests/ca/homeassistant_HassPauseTimer.yaml
Labels: cla-signed, lang: ca

#2564 [AR] Vacuum
  responses/ar/HassVacuumReturnToBase.yaml
  responses/ar/HassVacuumStart.yaml
  sentences/ar/_common.yaml
  sentences/ar/homeassistant_HassTurnOff.yaml
  sentences/ar/homeassistant_HassTurnOn.yaml
  sentences/ar/vacuum_HassVacuumReturnToBase.yaml
  sentences/ar/vacuum_HassVacuumStart.yaml
  tests/ar/_fixtures.yaml
  tests/ar/vacuum_HassVacuumReturnToBase.yaml
  tests/ar/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: ar

#2565 [CA] Add HassMediaPrevious
  responses/ca/HassMediaPrevious.yaml
  sentences/ca/_common.yaml
  sentences/ca/media_player_HassMediaPrevious.yaml
  tests/ca/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: ca

#2566 [CA] Improve light and climate on-off action
  sentences/ca/climate_HassTurnOff.yaml
  sentences/ca/climate_HassTurnOn.yaml
  sentences/ca/homeassistant_HassTurnOn.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  tests/ca/climate_HassTurnOff.yaml
  tests/ca/climate_HassTurnOn.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2569 [HE] Add more intents
  responses/he/HassGetCurrentDate.yaml
  responses/he/HassGetCurrentTime.yaml
  responses/he/HassRespond.yaml
  sentences/he/homeassistant_HassGetCurrentDate.yaml
  sentences/he/homeassistant_HassGetCurrentTime.yaml
  sentences/he/homeassistant_HassRespond.yaml
  tests/he/_fixtures.yaml
  tests/he/homeassistant_HassGetCurrentDate.yaml
  tests/he/homeassistant_HassGetCurrentTime.yaml
  tests/he/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: he

#2547 [NL] Add more options to timer intents
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassCancelTimer.yaml
  sentences/nl/homeassistant_HassDecreaseTimer.yaml
  sentences/nl/homeassistant_HassIncreaseTimer.yaml
  sentences/nl/homeassistant_HassPauseTimer.yaml
  sentences/nl/homeassistant_HassStartTimer.yaml
  sentences/nl/homeassistant_HassTimerStatus.yaml
  sentences/nl/homeassistant_HassUnpauseTimer.yaml
  tests/nl/homeassistant_HassCancelTimer.yaml
  tests/nl/homeassistant_HassDecreaseTimer.yaml
  tests/nl/homeassistant_HassIncreaseTimer.yaml
  tests/nl/homeassistant_HassPauseTimer.yaml
  tests/nl/homeassistant_HassStartTimer.yaml
  tests/nl/homeassistant_HassTimerStatus.yaml
  tests/nl/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: nl

#2529 [RO] HassMediaPrevious
  responses/ro/HassMediaPrevious.yaml
  sentences/ro/_common.yaml
  sentences/ro/media_player_HassMediaPrevious.yaml
  tests/ro/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: ro

#2572 [RO] Better error messages - domains
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#2574 Bump to hassil 2.0.2
  requirements.txt
Labels: cla-signed

#2576 [CA] Add context area to actions and verb improvement
  sentences/ca/_common.yaml
  sentences/ca/climate_HassClimateGetTemperature.yaml
  sentences/ca/climate_HassClimateSetTemperature.yaml
  sentences/ca/climate_HassTurnOff.yaml
  sentences/ca/climate_HassTurnOn.yaml
  sentences/ca/cover_HassSetPosition.yaml
  sentences/ca/cover_HassTurnOff.yaml
  sentences/ca/cover_HassTurnOn.yaml
  sentences/ca/light_HassLightSet.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  tests/ca/climate_HassClimateGetTemperature.yaml
  tests/ca/climate_HassClimateSetTemperature.yaml
  tests/ca/climate_HassTurnOff.yaml
  tests/ca/climate_HassTurnOn.yaml
  tests/ca/cover_HassSetPosition.yaml
  tests/ca/cover_HassTurnOff.yaml
  tests/ca/cover_HassTurnOn.yaml
  tests/ca/light_HassLightSet.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2578 [AR] Add media player next
  responses/ar/HassMediaNext.yaml
  sentences/ar/_common.yaml
  sentences/ar/media_player_HassMediaNext.yaml
  tests/ar/_fixtures.yaml
  tests/ar/media_player_HassMediaNext.yaml
Labels: cla-signed, lang: ar

#2580 [AR] Add media pause
  responses/ar/HassMediaPause.yaml
  sentences/ar/_common.yaml
  sentences/ar/media_player_HassMediaNext.yaml
  sentences/ar/media_player_HassMediaPause.yaml
  tests/ar/_fixtures.yaml
  tests/ar/media_player_HassMediaNext.yaml
  tests/ar/media_player_HassMediaPause.yaml
Labels: cla-signed, lang: ar

#2581 [CA] Add "to" STT variant for HassLightSet
  sentences/ca/_common.yaml
  sentences/ca/light_HassLightSet.yaml
Labels: cla-signed, lang: ca

#2577 [NL] Review LightTurnOn/Off
  sentences/nl/light_HassTurnOff.yaml
  sentences/nl/light_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2575 [NL] Review HassTurnOn/Off
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2372 [EN] Add "activate" phrasing for scripts
  sentences/en/script_HassTurnOn.yaml
  tests/en/script_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2570 [NL] Translate domain and device class for error responses
  responses/nl/HassTurnOff.yaml
  responses/nl/HassTurnOn.yaml
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2583 [CA] Update shopping list
  sentences/ca/shopping_list_HassShoppingListAddItem.yaml
  sentences/ca/todo_HassListAddItem.yaml
  tests/ca/shopping_list_HassShoppingListAddItem.yaml
  tests/ca/todo_HassListAddItem.yaml
Labels: cla-signed, lang: ca

#2568 [DA] added timer Start/Cancel/Status and AddItem
  responses/da/HassCancelTimer.yaml
  responses/da/HassListAddItem.yaml
  responses/da/HassStartTimer.yaml
  responses/da/HassTimerStatus.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassCancelTimer.yaml
  sentences/da/homeassistant_HassNevermind.yaml
  sentences/da/homeassistant_HassStartTimer.yaml
  sentences/da/homeassistant_HassTimerStatus.yaml
  sentences/da/todo_HassListAddItem.yaml
  tests/da/_fixtures.yaml
  tests/da/homeassistant_HassCancelTimer.yaml
  tests/da/homeassistant_HassNevermind.yaml
  tests/da/homeassistant_HassStartTimer.yaml
  tests/da/homeassistant_HassTimerStatus.yaml
  tests/da/todo_HassListAddItem.yaml
Labels: cla-signed, lang: da

#2584 [NL] Review LockTurnOn/Off
  sentences/nl/_common.yaml
  sentences/nl/lock_HassTurnOff.yaml
  sentences/nl/lock_HassTurnOn.yaml
  tests/nl/lock_HassTurnOff.yaml
  tests/nl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2585 [NL] Review Script/Scene TurnOn
  sentences/nl/scene_HassTurnOn.yaml
  sentences/nl/script_HassTurnOn.yaml
  tests/nl/scene_HassTurnOn.yaml
  tests/nl/script_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2587 [NL] Review valve intents
  sentences/nl/valve_HassSetPosition.yaml
  sentences/nl/valve_HassTurnOff.yaml
  sentences/nl/valve_HassTurnOn.yaml
  tests/nl/valve_HassSetPosition.yaml
  tests/nl/valve_HassTurnOff.yaml
  tests/nl/valve_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2592 [NL] Remove accidentally added double `[` and `]` from PersonGetState
  sentences/nl/person_HassGetState.yaml
Labels: cla-signed, lang: nl

#2588 [NL] Review ClimateSet intent
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#2593 [CA] Add case for LightSet
  sentences/ca/_common.yaml
  tests/ca/light_HassLightSet.yaml
Labels: cla-signed, lang: ca

#2594 [HU] Update error message
  sentences/hu/_common.yaml
Labels: cla-signed, lang: hu

#2595 Add count_sentences command to intentfest
  script/intentfest/count_sentences.py
  script/intentfest/util.py
Labels: cla-signed

#2590 [NL] Review HassGetState
  sentences/nl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nl

#2589 [NL] Review LightSet sentences
  sentences/nl/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: nl

#2513 [DE] Add timer length and name to responses
  responses/de/HassDecreaseTimer.yaml
  responses/de/HassIncreaseTimer.yaml
  responses/de/HassStartTimer.yaml
  tests/de/homeassistant_HassDecreaseTimer.yaml
  tests/de/homeassistant_HassIncreaseTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: de

#2579 [DE] Translate error responses
  sentences/de/_common.yaml
Labels: cla-signed, lang: de

#2596 [NL] Cleanup of _common.yaml
  sentences/nl/_common.yaml
Labels: cla-signed, lang: nl

#2598 [HU] Reducing the number of sentences through optimization and minor …
  sentences/hu/_common.yaml
  sentences/hu/light_HassLightSet.yaml
Labels: cla-signed, lang: hu

#2599 [HU] bugfix (Parenthesis error)
  sentences/hu/_common.yaml
Labels: cla-signed, lang: hu

#2557 [EU] First set of HassGetState + add some other responses
  responses/eu/HassClimateGetTemperature.yaml
  responses/eu/HassClimateSetTemperature.yaml
  responses/eu/HassGetState.yaml
  responses/eu/HassLightSet.yaml
  sentences/eu/_common.yaml
  sentences/eu/homeassistant_HassGetState.yaml
  tests/eu/_fixtures.yaml
  tests/eu/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: eu

#2597 [RU] Fix translation for moisture and humidity sensors
  sentences/ru/sensor_HassGetState.yaml
  tests/ru/sensor_HassGetState.yaml
Labels: cla-signed, lang: ru

#2601 [NL] Add `stoppen` as verb to pause media player
  sentences/nl/media_player_HassMediaPause.yaml
  tests/nl/media_player_HassMediaPause.yaml
Labels: cla-signed, lang: nl

#2604 [DE] Optimize sentences
  sentences/de/_common.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/homeassistant_HassGetState.yaml
  sentences/de/homeassistant_HassSetPosition.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/media_player_HassMediaUnpause.yaml
  sentences/de/media_player_HassSetVolume.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de

#2605 [DE] Further sentence optimizations
  sentences/de/_common.yaml
Labels: cla-signed, lang: de

#2606 [NL] Use YAML anchors for HassTurnOn/Off and HassGetState
  sentences/nl/homeassistant_HassGetState.yaml
  sentences/nl/homeassistant_HassTurnOff.yaml
  sentences/nl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2607 Add eu leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2515 [FR] Expand timer naming words
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassCancelTimer.yaml
  sentences/fr/homeassistant_HassDecreaseTimer.yaml
  sentences/fr/homeassistant_HassIncreaseTimer.yaml
  sentences/fr/homeassistant_HassPauseTimer.yaml
  sentences/fr/homeassistant_HassStartTimer.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/homeassistant_HassUnpauseTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: fr

#2611 [NL] Fix wrongly placed closing bracket in cover_HassSetPosition
  sentences/nl/cover_HassSetPosition.yaml
Labels: cla-signed, lang: nl

#2612 [PT-BR] Add more sentences to time intent
  sentences/pt-br/homeassistant_HassGetCurrentTime.yaml
  tests/pt-br/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed

#2613 [NL] Add missing responses to tests and remove unused responses
  responses/nl/HassGetState.yaml
  responses/nl/HassTurnOn.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/homeassistant_HassTurnOff.yaml
  tests/nl/homeassistant_HassTurnOn.yaml
  tests/nl/light_HassTurnOff.yaml
  tests/nl/light_HassTurnOn.yaml
  tests/nl/lock_HassTurnOff.yaml
  tests/nl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2573 [CS] Make covers area and floor aware, create intents for valves
  responses/cs/HassTurnOff.yaml
  responses/cs/HassTurnOn.yaml
  sentences/cs/_common.yaml
  sentences/cs/cover_HassGetState.yaml
  sentences/cs/cover_HassSetPosition.yaml
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  sentences/cs/homeassistant_HassSetPosition.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/valve_HassSetPosition.yaml
  sentences/cs/valve_HassTurnOff.yaml
  sentences/cs/valve_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/cover_HassGetState.yaml
  tests/cs/cover_HassSetPosition.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
  tests/cs/homeassistant_HassSetPosition.yaml
  tests/cs/valve_HassSetPosition.yaml
  tests/cs/valve_HassTurnOff.yaml
  tests/cs/valve_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#2615 [DE] remove obsolet target `name: all`
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  sentences/de/lock_HassTurnOff.yaml
  sentences/de/lock_HassTurnOn.yaml
  tests/de/fan_HassTurnOff.yaml
  tests/de/fan_HassTurnOn.yaml
  tests/de/lock_HassTurnOff.yaml
  tests/de/lock_HassTurnOn.yaml
Labels: cla-signed, lang: de

#2614 [PT-BR] Fix basic light controls
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#2617 [PT] Remove "all" name slots
  sentences/pt/fan_HassTurnOff.yaml
  sentences/pt/fan_HassTurnOn.yaml
  sentences/pt/light_HassLightSet.yaml
  tests/pt/fan_HassTurnOff.yaml
  tests/pt/fan_HassTurnOn.yaml
  tests/pt/light_HassLightSet.yaml
Labels: cla-signed, lang: pt

#2618 [CA] Remove "all" name slots
  sentences/ca/climate_HassTurnOff.yaml
  sentences/ca/climate_HassTurnOn.yaml
  sentences/ca/fan_HassTurnOff.yaml
  sentences/ca/fan_HassTurnOn.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  tests/ca/climate_HassTurnOff.yaml
  tests/ca/climate_HassTurnOn.yaml
  tests/ca/fan_HassTurnOff.yaml
  tests/ca/fan_HassTurnOn.yaml
  tests/ca/light_HassTurnOff.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2619 [CA] Improve expansion rules to generate less invalid variants
  sentences/ca/_common.yaml
  sentences/ca/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: ca

#2620 [CA] Improve expansion rules to generate less invalid variants (2)
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassDecreaseTimer.yaml
  sentences/ca/homeassistant_HassIncreaseTimer.yaml
  sentences/ca/homeassistant_HassPauseTimer.yaml
  sentences/ca/homeassistant_HassStartTimer.yaml
  sentences/ca/homeassistant_HassTimerStatus.yaml
  sentences/ca/homeassistant_HassUnpauseTimer.yaml
  sentences/ca/media_player_HassMediaNext.yaml
Labels: cla-signed, lang: ca

#2621 [CA] Improve expansion rules to generate less invalid variants (3)
  sentences/ca/_common.yaml
Labels: cla-signed, lang: ca

#2622 [DE] Another bunch of sentence optimizations
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassGetState.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/media_player_HassMediaNext.yaml
  sentences/de/media_player_HassMediaPause.yaml
  sentences/de/media_player_HassMediaPrevious.yaml
  sentences/de/media_player_HassMediaUnpause.yaml
Labels: cla-signed, lang: de

#2623 [CA] Add more intent cases
  sentences/ca/_common.yaml
  sentences/ca/media_player_HassMediaNext.yaml
  sentences/ca/media_player_HassMediaPrevious.yaml
  sentences/ca/media_player_HassSetVolume.yaml
  sentences/ca/weather_HassGetWeather.yaml
  tests/ca/media_player_HassMediaNext.yaml
  tests/ca/media_player_HassMediaPrevious.yaml
  tests/ca/media_player_HassSetVolume.yaml
  tests/ca/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ca

#2626 [CS] Make fans room aware
  sentences/cs/_common.yaml
  sentences/cs/cover_HassGetState.yaml
  sentences/cs/fan_HassTurnOff.yaml
  sentences/cs/fan_HassTurnOn.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  tests/cs/fan_HassTurnOff.yaml
  tests/cs/fan_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#2627 [HU] Optimization v3
  sentences/hu/_common.yaml
  tests/hu/binary_sensor_HassGetState.yaml
  tests/hu/cover_HassSetPosition.yaml
  tests/hu/light_HassLightSet.yaml
  tests/hu/media_player_HassSetVolume.yaml
  tests/hu/valve_HassSetPosition.yaml
Labels: cla-signed, lang: hu

#2624 [PL] Added correct pronunciation of the minus sign when ask of temperature
  responses/pl/HassClimateGetTemperature.yaml
  responses/pl/HassGetWeather.yaml
  sentences/pl/homeassistant_HassTimerStatus.yaml
  sentences/pl/weather_HassGetWeather.yaml
  tests/pl/_fixtures.yaml
  tests/pl/climate_HassClimateGetTemperature.yaml
  tests/pl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: pl

#2628 [PL] - Removed param name: all in all sentences
  responses/pl/HassTurnOff.yaml
  responses/pl/HassTurnOn.yaml
  sentences/pl/fan_HassTurnOff.yaml
  sentences/pl/fan_HassTurnOn.yaml
  sentences/pl/light_HassLightSet.yaml
  sentences/pl/light_HassTurnOff.yaml
  sentences/pl/light_HassTurnOn.yaml
  sentences/pl/lock_HassTurnOff.yaml
  sentences/pl/lock_HassTurnOn.yaml
  tests/pl/fan_HassTurnOff.yaml
  tests/pl/fan_HassTurnOn.yaml
  tests/pl/light_HassLightSet.yaml
  tests/pl/light_HassTurnOff.yaml
  tests/pl/light_HassTurnOn.yaml
  tests/pl/lock_HassTurnOff.yaml
  tests/pl/lock_HassTurnOn.yaml
Labels: cla-signed, lang: pl
