Repository OHF-Voice/intents, pull requests merged in 2024-05, with the labels that each got.

#2165 Issue 2148 correction
  sentences/fr/_common.yaml
Labels: cla-signed, lang: fr

#2166 [RU] Improved weather data output for TTS processing.
  responses/ru/HassGetWeather.yaml
  sentences/ru/weather_HassGetWeather.yaml
  tests/ru/_fixtures.yaml
  tests/ru/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ru

#2179 Add timers for English
  intents.yaml
  responses/en/HassCancelTimer.yaml
  responses/en/HassDecreaseTimer.yaml
  responses/en/HassIncreaseTimer.yaml
  responses/en/HassPauseTimer.yaml
  responses/en/HassStartTimer.yaml
  responses/en/HassTimerStatus.yaml
  responses/en/HassUnpauseTimer.yaml
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassCancelTimer.yaml
  sentences/en/homeassistant_HassDecreaseTimer.yaml
  sentences/en/homeassistant_HassIncreaseTimer.yaml
  sentences/en/homeassistant_HassPauseTimer.yaml
  sentences/en/homeassistant_HassStartTimer.yaml
  sentences/en/homeassistant_HassTimerStatus.yaml
  sentences/en/homeassistant_HassUnpauseTimer.yaml
  shared/__init__.py
  tests/en/_fixtures.yaml
  tests/en/homeassistant_HassCancelTimer.yaml
  tests/en/homeassistant_HassDecreaseTimer.yaml
  tests/en/homeassistant_HassIncreaseTimer.yaml
  tests/en/homeassistant_HassPauseTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassTimerStatus.yaml
  tests/en/homeassistant_HassUnpauseTimer.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed, lang: en

#2180 Add enhanced media sentences for English
  intents.yaml
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  tests/en/media_player_HassMediaNext.yaml
  tests/en/media_player_HassMediaPause.yaml
  tests/en/media_player_HassMediaUnpause.yaml
  tests/en/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: en

#2183 [EN] Add more timer sentences
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassCancelTimer.yaml
  sentences/en/homeassistant_HassDecreaseTimer.yaml
  sentences/en/homeassistant_HassIncreaseTimer.yaml
  sentences/en/homeassistant_HassPauseTimer.yaml
  sentences/en/homeassistant_HassStartTimer.yaml
  sentences/en/homeassistant_HassUnpauseTimer.yaml
  tests/en/homeassistant_HassCancelTimer.yaml
  tests/en/homeassistant_HassDecreaseTimer.yaml
  tests/en/homeassistant_HassIncreaseTimer.yaml
  tests/en/homeassistant_HassPauseTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: en

#2184 Require context area for media intents with no name
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  tests/en/_fixtures.yaml
  tests/en/media_player_HassMediaNext.yaml
  tests/en/media_player_HassMediaPause.yaml
  tests/en/media_player_HassMediaUnpause.yaml
  tests/en/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: en

#2185 Require context area for starting a timer
  sentences/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2186 Add area sentences for media intents
  responses/en/HassMediaUnpause.yaml
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  tests/en/media_player_HassMediaNext.yaml
  tests/en/media_player_HassMediaPause.yaml
  tests/en/media_player_HassMediaUnpause.yaml
  tests/en/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: en

#2189 [FR] Media Player Intents improvements
  sentences/fr/_common.yaml
  sentences/fr/media_player_HassMediaNext.yaml
  sentences/fr/media_player_HassMediaPause.yaml
  sentences/fr/media_player_HassMediaUnpause.yaml
  sentences/fr/media_player_HassSetVolume.yaml
  tests/fr/media_player_HassMediaNext.yaml
  tests/fr/media_player_HassMediaPause.yaml
  tests/fr/media_player_HassMediaUnpause.yaml
  tests/fr/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: fr

#2154 [pt] lights room awareness
  sentences/pt/light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOn.yaml
  tests/pt/light_HassTurnOff.yaml
  tests/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#2190 [EN] Fine-tuning timer sentences
  responses/en/HassTimerStatus.yaml
  sentences/en/homeassistant_HassCancelTimer.yaml
  sentences/en/homeassistant_HassDecreaseTimer.yaml
  sentences/en/homeassistant_HassIncreaseTimer.yaml
  sentences/en/homeassistant_HassPauseTimer.yaml
  sentences/en/homeassistant_HassStartTimer.yaml
  sentences/en/homeassistant_HassTimerStatus.yaml
  sentences/en/homeassistant_HassUnpauseTimer.yaml
  tests/en/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: en

#2191 [PT] open/close only one shutter
  sentences/pt/cover_HassTurnOff.yaml
  sentences/pt/cover_HassTurnOn.yaml
  tests/pt/cover_HassTurnOff.yaml
  tests/pt/cover_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#2182 Add timer and state/feature errors
  script/intentfest/validate.py
  sentences/en/_common.yaml
Labels: cla-signed, lang: en

#2196 Add delayed commands to timers
  intents.yaml
  responses/en/HassStartTimer.yaml
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2188 [ar] Nevermind
  sentences/ar/homeassistant_HassNevermind.yaml
  tests/ar/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: ar

#2194 [NL] Add timer support
  responses/nl/HassCancelTimer.yaml
  responses/nl/HassDecreaseTimer.yaml
  responses/nl/HassIncreaseTimer.yaml
  responses/nl/HassPauseTimer.yaml
  responses/nl/HassStartTimer.yaml
  responses/nl/HassTimerStatus.yaml
  responses/nl/HassUnpauseTimer.yaml
  sentences/nl/_common.yaml
  sentences/nl/homeassistant_HassCancelTimer.yaml
  sentences/nl/homeassistant_HassDecreaseTimer.yaml
  sentences/nl/homeassistant_HassIncreaseTimer.yaml
  sentences/nl/homeassistant_HassPauseTimer.yaml
  sentences/nl/homeassistant_HassStartTimer.yaml
  sentences/nl/homeassistant_HassTimerStatus.yaml
  sentences/nl/homeassistant_HassUnpauseTimer.yaml
  tests/nl/_fixtures.yaml
  tests/nl/homeassistant_HassCancelTimer.yaml
  tests/nl/homeassistant_HassDecreaseTimer.yaml
  tests/nl/homeassistant_HassIncreaseTimer.yaml
  tests/nl/homeassistant_HassPauseTimer.yaml
  tests/nl/homeassistant_HassStartTimer.yaml
  tests/nl/homeassistant_HassTimerStatus.yaml
  tests/nl/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: nl

#2199 [NL] Small fix for timer status response template
  responses/nl/HassTimerStatus.yaml
Labels: cla-signed, lang: nl

#2197 [RU] Basic timer support
  responses/ru/HassCancelTimer.yaml
  responses/ru/HassStartTimer.yaml
  responses/ru/HassTimerStatus.yaml
  sentences/ru/_common.yaml
  sentences/ru/homeassistant_HassCancelTimer.yaml
  sentences/ru/homeassistant_HassStartTimer.yaml
  sentences/ru/homeassistant_HassTimerStatus.yaml
  tests/ru/_fixtures.yaml
  tests/ru/homeassistant_HassCancelTimer.yaml
  tests/ru/homeassistant_HassStartTimer.yaml
  tests/ru/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: ru

#2201 [RO] Initial support for floors
  responses/ro/HassTurnOff.yaml
  responses/ro/HassTurnOn.yaml
  sentences/ro/_common.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  tests/ro/_fixtures.yaml
  tests/ro/light_HassTurnOff.yaml
  tests/ro/light_HassTurnOn.yaml
Labels: cla-signed, lang: ro

#2202 [RO] Add area-aware media sentences
  sentences/ro/media_player_HassMediaNext.yaml
  sentences/ro/media_player_HassMediaPause.yaml
  sentences/ro/media_player_HassMediaUnpause.yaml
  sentences/ro/media_player_HassSetVolume.yaml
  tests/ro/_fixtures.yaml
  tests/ro/media_player_HassMediaNext.yaml
  tests/ro/media_player_HassMediaPause.yaml
  tests/ro/media_player_HassMediaUnpause.yaml
  tests/ro/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: ro

#2205 [NL] Fix cover intents for open/close
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2206 [RO] Add timer intents
  responses/ro/HassCancelTimer.yaml
  responses/ro/HassDecreaseTimer.yaml
  responses/ro/HassIncreaseTimer.yaml
  responses/ro/HassPauseTimer.yaml
  responses/ro/HassStartTimer.yaml
  responses/ro/HassTimerStatus.yaml
  responses/ro/HassUnpauseTimer.yaml
  sentences/ro/_common.yaml
  sentences/ro/homeassistant_HassCancelTimer.yaml
  sentences/ro/homeassistant_HassDecreaseTimer.yaml
  sentences/ro/homeassistant_HassIncreaseTimer.yaml
  sentences/ro/homeassistant_HassPauseTimer.yaml
  sentences/ro/homeassistant_HassStartTimer.yaml
  sentences/ro/homeassistant_HassTimerStatus.yaml
  sentences/ro/homeassistant_HassUnpauseTimer.yaml
  tests/ro/_fixtures.yaml
  tests/ro/homeassistant_HassCancelTimer.yaml
  tests/ro/homeassistant_HassDecreaseTimer.yaml
  tests/ro/homeassistant_HassIncreaseTimer.yaml
  tests/ro/homeassistant_HassPauseTimer.yaml
  tests/ro/homeassistant_HassStartTimer.yaml
  tests/ro/homeassistant_HassTimerStatus.yaml
  tests/ro/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: ro

#2207 [RO] Add delayed commands
  responses/ro/HassStartTimer.yaml
  sentences/ro/_common.yaml
  sentences/ro/homeassistant_HassStartTimer.yaml
  tests/ro/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: ro
