Repository OHF-Voice/intents, pull requests merged in 2024-08, with the labels that each got.

#2361 [RO] HassGetCurrentDate and HassGetCurrentTime
  responses/ro/HassGetCurrentDate.yaml
  responses/ro/HassGetCurrentTime.yaml
  sentences/ro/homeassistant_HassGetCurrentDate.yaml
  sentences/ro/homeassistant_HassGetCurrentTime.yaml
  tests/ro/homeassistant_HassGetCurrentDate.yaml
  tests/ro/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: ro

#2362 Add some more light control sentences
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2363 [SV] Add vacuum intents
  responses/sv/HassVacuumReturnToBase.yaml
  responses/sv/HassVacuumStart.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  sentences/sv/vacuum_HassVacuumReturnToBase.yaml
  sentences/sv/vacuum_HassVacuumStart.yaml
  tests/sv/_fixtures.yaml
  tests/sv/vacuum_HassVacuumReturnToBase.yaml
  tests/sv/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: sv

#2365 [SV] Add more sentences for getting the weather
  sentences/sv/weather_HassGetWeather.yaml
  tests/sv/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sv

#2354 [PT] add expansion rule for luz
  sentences/pt/_common.yaml
  sentences/pt/light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#2235 [PT] room awareness for covers
  responses/pt/HassSetPosition.yaml
  sentences/pt/_common.yaml
  sentences/pt/cover_HassSetPosition.yaml
  sentences/pt/cover_HassTurnOff.yaml
  sentences/pt/cover_HassTurnOn.yaml
  tests/pt/cover_HassSetPosition.yaml
  tests/pt/cover_HassTurnOff.yaml
  tests/pt/cover_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#2366 [PT] Add support for timers
  responses/pt/HassCancelTimer.yaml
  responses/pt/HassDecreaseTimer.yaml
  responses/pt/HassIncreaseTimer.yaml
  responses/pt/HassPauseTimer.yaml
  responses/pt/HassStartTimer.yaml
  responses/pt/HassTimerStatus.yaml
  responses/pt/HassUnpauseTimer.yaml
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassCancelTimer.yaml
  sentences/pt/homeassistant_HassDecreaseTimer.yaml
  sentences/pt/homeassistant_HassIncreaseTimer.yaml
  sentences/pt/homeassistant_HassPauseTimer.yaml
  sentences/pt/homeassistant_HassStartTimer.yaml
  sentences/pt/homeassistant_HassTimerStatus.yaml
  sentences/pt/homeassistant_HassUnpauseTimer.yaml
  tests/pt/_fixtures.yaml
  tests/pt/homeassistant_HassCancelTimer.yaml
  tests/pt/homeassistant_HassDecreaseTimer.yaml
  tests/pt/homeassistant_HassIncreaseTimer.yaml
  tests/pt/homeassistant_HassPauseTimer.yaml
  tests/pt/homeassistant_HassStartTimer.yaml
  tests/pt/homeassistant_HassTimerStatus.yaml
  tests/pt/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: pt

#2364 [EN] Rename CO2 binary sensor fixture
  tests/en/_fixtures.yaml
  tests/en/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: en

#2373 [de] Consider correct case in shopping list add item sentences
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: de

#2374 [PT] Add HassGetDate and HassGetTime
  responses/pt/HassGetCurrentDate.yaml
  responses/pt/HassGetCurrentTime.yaml
  sentences/pt/homeassistant_HassGetCurrentDate.yaml
  sentences/pt/homeassistant_HassGetCurrentTime.yaml
  tests/pt/homeassistant_HassGetCurrentDate.yaml
  tests/pt/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: pt

#2370 [RU] Add HassGetCurrentDate
  responses/ru/HassGetCurrentDate.yaml
  sentences/ru/homeassistant_HassGetCurrentDate.yaml
  tests/ru/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: ru

#2381 [SL] temperature value fix for tests
  responses/sl/HassClimateGetTemperature.yaml
  responses/sl/HassGetWeather.yaml
  sentences/sl/weather_HassGetWeather.yaml
  tests/sl/_fixtures.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sl

#2383 [SL] fixes responses for values with decimals
  responses/sl/HassGetState.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassGetState.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl
