Repository OHF-Voice/intents, pull requests merged in 2024-12, with the labels that each got.

#2686 [FR] allow using verbs
  responses/fr/HassTimerStatus.yaml
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassCancelTimer.yaml
  sentences/fr/homeassistant_HassDecreaseTimer.yaml
  sentences/fr/homeassistant_HassIncreaseTimer.yaml
  sentences/fr/homeassistant_HassPauseTimer.yaml
  sentences/fr/homeassistant_HassStartTimer.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/homeassistant_HassUnpauseTimer.yaml
  tests/fr/_fixtures.yaml
  tests/fr/homeassistant_HassCancelAllTimers.yaml
  tests/fr/homeassistant_HassCancelTimer.yaml
  tests/fr/homeassistant_HassDecreaseTimer.yaml
  tests/fr/homeassistant_HassIncreaseTimer.yaml
  tests/fr/homeassistant_HassPauseTimer.yaml
  tests/fr/homeassistant_HassStartTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
  tests/fr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fr

#2637 [SV] Update _common.yaml error messages for floors
  sentences/sv/_common.yaml
Labels: cla-signed, lang: sv

#2696 [NB] Cancel all timers
  responses/nb/HassCancelAllTimers.yaml
  sentences/nb/_common.yaml
  sentences/nb/homeassistant_HassCancelAllTimers.yaml
  tests/nb/homeassistant_HassCancelAllTimers.yaml
  tests/nb/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: nb

#2660 [SV] Support for scenes
  responses/sv/HassTurnOn.yaml
  sentences/sv/_common.yaml
  sentences/sv/scene_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/scene_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2709 Add Greek language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2710 [HR] HassCancelAllTimers
  responses/hr/HassCancelAllTimers.yaml
  responses/hr/HassCancelTimer.yaml
  sentences/hr/_common.yaml
  sentences/hr/homeassistant_HassCancelAllTimers.yaml
  tests/hr/homeassistant_HassCancelAllTimers.yaml
  tests/hr/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: hr

#2706 [EN] HassGetState floor support
  sentences/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: en

#2712 [hr] Timers pause/unpause
  responses/hr/HassDecreaseTimer.yaml
  responses/hr/HassIncreaseTimer.yaml
  responses/hr/HassPauseTimer.yaml
  responses/hr/HassUnpauseTimer.yaml
  sentences/hr/homeassistant_HassDecreaseTimer.yaml
  sentences/hr/homeassistant_HassIncreaseTimer.yaml
  sentences/hr/homeassistant_HassPauseTimer.yaml
  sentences/hr/homeassistant_HassUnpauseTimer.yaml
  tests/hr/homeassistant_HassDecreaseTimer.yaml
  tests/hr/homeassistant_HassIncreaseTimer.yaml
  tests/hr/homeassistant_HassPauseTimer.yaml
  tests/hr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: hr

#2714 [DE] fix Rollladen vs Rolladen
  sentences/de/_common.yaml
  tests/de/_fixtures.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#2705 [sk] prepositions refactoring
  sentences/sk/_common.yaml
  sentences/sk/climate_HassClimateGetTemperature.yaml
  sentences/sk/climate_HassClimateSetTemperature.yaml
  sentences/sk/cover_HassTurnOff.yaml
  sentences/sk/cover_HassTurnOn.yaml
  sentences/sk/fan_HassTurnOff.yaml
  sentences/sk/fan_HassTurnOn.yaml
  sentences/sk/homeassistant_HassGetState.yaml
  sentences/sk/homeassistant_HassTurnOff.yaml
  sentences/sk/homeassistant_HassTurnOn.yaml
  sentences/sk/light_HassLightSet.yaml
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#2679 [GL] Add intents to query the current date and time
  responses/gl/HassGetCurrentDate.yaml
  responses/gl/HassGetCurrentTime.yaml
  sentences/gl/_common.yaml
  sentences/gl/homeassistant_HassGetCurrentDate.yaml
  sentences/gl/homeassistant_HassGetCurrentTime.yaml
  sentences/gl/homeassistant_HassGetState.yaml
  tests/gl/homeassistant_HassGetCurrentDate.yaml
  tests/gl/homeassistant_HassGetCurrentTime.yaml
  tests/gl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: gl

#2718 [GL] Improve turn on / turn off sentences
  responses/gl/HassLightSet.yaml
  responses/gl/HassTurnOff.yaml
  responses/gl/HassTurnOn.yaml
  sentences/gl/_common.yaml
  sentences/gl/light_HassTurnOn.yaml
  tests/gl/_fixtures.yaml
  tests/gl/cover_HassTurnOff.yaml
  tests/gl/homeassistant_HassGetState.yaml
  tests/gl/light_HassTurnOn.yaml
Labels: cla-signed, lang: gl

#2721 [GL] Expand sentences to turn off lights to support areas and floors, long with adding more possible sentences
  responses/gl/HassTurnOff.yaml
  responses/gl/HassTurnOn.yaml
  sentences/gl/_common.yaml
  sentences/gl/light_HassTurnOff.yaml
  tests/gl/light_HassTurnOff.yaml
Labels: cla-signed, lang: gl

#2722 [GL] Add Respond intents
  responses/gl/HassRespond.yaml
  sentences/gl/homeassistant_HassRespond.yaml
  tests/gl/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: gl

#2723 [GL] SetPosition intents
  responses/gl/HassSetPosition.yaml
  sentences/gl/_common.yaml
  sentences/gl/cover_HassSetPosition.yaml
  sentences/gl/valve_HassSetPosition.yaml
  tests/gl/_fixtures.yaml
  tests/gl/cover_HassSetPosition.yaml
  tests/gl/valve_HassSetPosition.yaml
Labels: cla-signed, lang: gl

#2708 [DE] HassGetState floor support
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassGetState.yaml
  tests/de/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: de

#2716 [NL] Add options for Pause and Unpause media
  sentences/nl/media_player_HassMediaPause.yaml
  sentences/nl/media_player_HassMediaUnpause.yaml
  tests/nl/media_player_HassMediaPause.yaml
  tests/nl/media_player_HassMediaUnpause.yaml
Labels: cla-signed, lang: nl

#2471 Improve sentence structure for common.yaml
  sentences/en/_common.yaml
Labels: cla-signed, lang: en

#2730 [DE] add "fahre ... hoch/herunter" for covers
  sentences/de/_common.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#2731 [GL] Add more verbs for closing
  sentences/gl/_common.yaml
  tests/gl/cover_HassSetPosition.yaml
  tests/gl/valve_HassSetPosition.yaml
Labels: cla-signed, lang: gl

#2732 [DE] comma as decimal separator
  responses/de/HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: de

#2699 [CA] Multiple improvements
  responses/ca/HassTurnOff.yaml
  responses/ca/HassTurnOn.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassGetState.yaml
  sentences/ca/homeassistant_HassStartTimer.yaml
  sentences/ca/homeassistant_HassTimerStatus.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
  sentences/ca/lock_HassTurnOff.yaml
  sentences/ca/lock_HassTurnOn.yaml
  sentences/ca/person_HassGetState.yaml
  tests/ca/_fixtures.yaml
  tests/ca/homeassistant_HassGetState.yaml
  tests/ca/lock_HassTurnOff.yaml
  tests/ca/lock_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2736 [PL] - Added correct comma seperator for decimal number
  responses/pl/HassGetState.yaml
  tests/pl/_fixtures.yaml
  tests/pl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: pl

#2726 [PT-BR] Improve fan operation
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/fan_HassTurnOff.yaml
  sentences/pt-br/fan_HassTurnOn.yaml
  tests/pt-br/fan_HassTurnOff.yaml
  tests/pt-br/fan_HassTurnOn.yaml
Labels: cla-signed

#2729 [SK] binary_sensor HassGetState added
  responses/sk/HassGetState.yaml
  sentences/sk/_common.yaml
  sentences/sk/binary_sensor_HassGetState.yaml
  tests/sk/_fixtures.yaml
  tests/sk/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sk

#2738 [IT] Fix responses for cover_HassSetPosition
  responses/it/HassSetPosition.yaml
  sentences/it/cover_HassSetPosition.yaml
  tests/it/cover_HassSetPosition.yaml
Labels: cla-signed, lang: it

#2742 [ES] Adding sentences to cancel timers
  responses/es/HassCancelAllTimers.yaml
  sentences/es/_common.yaml
  sentences/es/homeassistant_HassCancelAllTimers.yaml
  tests/es/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: es

#2743 List almost complete languages
  script/intentfest/website_summary.py
  website/src-11ty/index.html
Labels: cla-signed

#2745 [PT] Add HassRespond
  responses/pt/HassRespond.yaml
  sentences/pt/homeassistant_HassRespond.yaml
  tests/pt/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: pt

#2746 [PT] Add HassCancelAllTimers
  responses/pt/HassCancelAllTimers.yaml
  sentences/pt/_common.yaml
  sentences/pt/homeassistant_HassCancelAllTimers.yaml
  sentences/pt/homeassistant_HassCancelTimer.yaml
  tests/pt/homeassistant_HassCancelAllTimers.yaml
  tests/pt/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: pt

#2724 Fix apartment typo in sentences-en-_common.yaml
  sentences/en/_common.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2747 [PT] Add HassSetVolume for media_player
  responses/pt/HassSetVolume.yaml
  sentences/pt/_common.yaml
  sentences/pt/media_player_HassSetVolume.yaml
  tests/pt/_fixtures.yaml
  tests/pt/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: pt

#2748 [PT] Add HassMedia intents
  responses/pt/HassMediaNext.yaml
  responses/pt/HassMediaPause.yaml
  responses/pt/HassMediaPrevious.yaml
  responses/pt/HassMediaUnpause.yaml
  sentences/pt/media_player_HassMediaNext.yaml
  sentences/pt/media_player_HassMediaPause.yaml
  sentences/pt/media_player_HassMediaPrevious.yaml
  sentences/pt/media_player_HassMediaUnpause.yaml
  tests/pt/media_player_HassMediaNext.yaml
  tests/pt/media_player_HassMediaPause.yaml
  tests/pt/media_player_HassMediaPrevious.yaml
  tests/pt/media_player_HassMediaUnpause.yaml
Labels: cla-signed, lang: pt

#2703 Rework of conjugated areas
  responses/fi/HassCancelAllTimers.yaml
  sentences/fi/_common.yaml
  sentences/fi/fan_HassTurnOff.yaml
  sentences/fi/fan_HassTurnOn.yaml
  sentences/fi/homeassistant_HassCancelAllTimers.yaml
  sentences/fi/homeassistant_HassTurnOff.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  sentences/fi/light_HassTurnOff.yaml
  sentences/fi/light_HassTurnOn.yaml
  tests/fi/_fixtures.yaml
  tests/fi/fan_HassTurnOn.yaml
  tests/fi/homeassistant_HassCancelAllTimers.yaml
  tests/fi/homeassistant_HassGetState.yaml
  tests/fi/light_HassTurnOff.yaml
  tests/fi/light_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#2702 Fixed responses and some sentences.
  responses/fi/HassGetWeather.yaml
  sentences/fi/weather_HassGetWeather.yaml
  tests/fi/_fixtures.yaml
  tests/fi/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fi

#2749 [SK] cleaning in prepositions
  sentences/sk/_common.yaml
  tests/sk/_fixtures.yaml
  tests/sk/homeassistant_HassTurnOff.yaml
  tests/sk/homeassistant_HassTurnOn.yaml
  tests/sk/light_HassTurnOff.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#2750 Add response to HassRespond
  intents.yaml
  responses/en/HassRespond.yaml
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassRespond.yaml
  tests/en/homeassistant_HassRespond.yaml
  tests/test_language_sentences.py
Labels: cla-signed, lang: en

#2752 [DE] say xyz
  responses/de/HassRespond.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassRespond.yaml
  tests/de/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: de

#2753 Fix HassRespond tests
  .pre-commit-config.yaml
  tests/test_language_sentences.py
Labels: cla-signed

#2715 [IT] Add support for HassRespond
  responses/it/HassRespond.yaml
  sentences/it/_common.yaml
  sentences/it/homeassistant_HassRespond.yaml
  tests/it/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: it

#2751 [IT] Add support for HassGetCurrentTime
  responses/it/HassGetCurrentTime.yaml
  sentences/it/homeassistant_HassGetCurrentTime.yaml
  tests/it/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: it

#2755 [IT] Add support for vacuum_HassVacuumStart.yaml
  sentences/it/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: it

#2756 [IT] Current Date
  responses/it/HassGetCurrentDate.yaml
  sentences/it/homeassistant_HassGetCurrentDate.yaml
  tests/it/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: it

#2757 [IT] Add support for CancelAllTimers
  responses/it/HassCancelAllTimers.yaml
  sentences/it/_common.yaml
  sentences/it/homeassistant_HassCancelAllTimers.yaml
  tests/it/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: it

#2704 [FR] overhaul of the weather intent, with detailed report
  responses/fr/HassGetWeather.yaml
  sentences/fr/_common.yaml
  sentences/fr/weather_HassGetWeather.yaml
  tests/fr/_fixtures.yaml
  tests/fr/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fr

#2758 [RU] Add HassCancelAllTimers
  responses/ru/HassCancelAllTimers.yaml
  sentences/ru/homeassistant_HassCancelAllTimers.yaml
  sentences/ru/homeassistant_HassCancelTimer.yaml
  tests/ru/_fixtures.yaml
  tests/ru/homeassistant_HassCancelAllTimers.yaml
  tests/ru/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: ru

#2761 [PT] Fixed typo on turning lights on
  responses/pt/HassTurnOn.yaml
Labels: cla-signed, lang: pt

#2760 [FI] Area conjugations for HassLightSet and some optimization
  sentences/fi/_common.yaml
  sentences/fi/light_HassLightSet.yaml
  tests/fi/light_HassLightSet.yaml
Labels: cla-signed, lang: fi

#2765 [CA] Add alias typos for light
  sentences/ca/_common.yaml
Labels: cla-signed, lang: ca

#2766 [CA] Add response to HassRespond
  responses/ca/HassRespond.yaml
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassRespond.yaml
  tests/ca/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: ca

#2764 [RU] add HassMediaPrevious
  responses/ru/HassMediaPrevious.yaml
  sentences/ru/media_player_HassMediaNext.yaml
  sentences/ru/media_player_HassMediaPrevious.yaml
  tests/ru/media_player_HassMediaNext.yaml
  tests/ru/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: ru

#2740 [BG] Add HassCancelAllTimers
  responses/bg/HassCancelAllTimers.yaml
  sentences/bg/homeassistant_HassCancelAllTimers.yaml
  tests/bg/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: bg

#2727 [en] Enable the use of possessives for some nouns
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassGetCurrentDate.yaml
  sentences/en/homeassistant_HassGetCurrentTime.yaml
  tests/en/homeassistant_HassGetState.yaml
  tests/en/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2769 LV Added Scene TurnOn
  responses/lv/HassTurnOn.yaml
  sentences/lv/_common.yaml
  sentences/lv/scene_HassTurnOn.yaml
  tests/lv/_fixtures.yaml
  tests/lv/scene_HassTurnOn.yaml
Labels: cla-signed, lang: lv

#2773 [CA] Add typo variant and new word case for StartTimer
  sentences/ca/_common.yaml
  sentences/ca/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: ca

#2774 [LV] Improve translations for setting light brightness
  sentences/lv/light_HassLightSet.yaml
  tests/lv/light_HassLightSet.yaml
Labels: cla-signed, lang: lv

#2778 [IT] Update _common.yaml with two more errors
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#2698 [NE] Added Initial Support for Nepali Language
  languages.yaml
  responses/ne/HassTurnOff.yaml
  responses/ne/HassTurnOn.yaml
  sentences/ne/_common.yaml
  sentences/ne/homeassistant_HassTurnOff.yaml
  sentences/ne/homeassistant_HassTurnOn.yaml
  tests/ne/_fixtures.yaml
  tests/ne/homeassistant_HassTurnOff.yaml
  tests/ne/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ne

#2786 [DE] allow targeting switchables in areas for HassTurnOn/Off
  sentences/de/homeassistant_HassTurnOff.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  tests/de/homeassistant_HassTurnOff.yaml
  tests/de/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: de

#2785 [LV] Simple responses intent
  responses/lv/HassRespond.yaml
  sentences/lv/_common.yaml
  sentences/lv/homeassistant_HassRespond.yaml
  tests/lv/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: lv

#2788 [DE] Add area-awareness to HassClimateGetTemperature
  sentences/de/climate_HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: de

#2791 [CA] Add typo variants for lights
  sentences/ca/_common.yaml
  sentences/ca/light_HassTurnOff.yaml
  sentences/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2787 [BG] Аdd media control
  responses/bg/HassMediaNext.yaml
  responses/bg/HassMediaPause.yaml
  responses/bg/HassMediaPrevious.yaml
  responses/bg/HassMediaUnpause.yaml
  responses/bg/HassSetVolume.yaml
  sentences/bg/_common.yaml
  sentences/bg/media_player_HassMediaNext.yaml
  sentences/bg/media_player_HassMediaPause.yaml
  sentences/bg/media_player_HassMediaPrevious.yaml
  sentences/bg/media_player_HassMediaUnpause.yaml
  sentences/bg/media_player_HassSetVolume.yaml
  tests/bg/_fixtures.yaml
  tests/bg/media_player_HassMediaNext.yaml
  tests/bg/media_player_HassMediaPause.yaml
  tests/bg/media_player_HassMediaPrevious.yaml
  tests/bg/media_player_HassMediaUnpause.yaml
  tests/bg/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: bg

#2792 [PT-BR] Update sentence
  responses/pt-br/HassGetState.yaml
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/climate_HassClimateGetTemperature.yaml
  sentences/pt-br/homeassistant_HassGetState.yaml
  sentences/pt-br/homeassistant_HassRespond.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/homeassistant_HassRespond.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/homeassistant_HassTurnOn.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#2793 [EN] Add area-awareness to HassClimateGetTemperature
  sentences/en/climate_HassClimateGetTemperature.yaml
  tests/en/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: en

#2772 [CS] Fix failing tests due to same entity names across domains
  sentences/cs/_common.yaml
  sentences/cs/binary_sensor_HassGetState.yaml
  sentences/cs/cover_HassGetState.yaml
  sentences/cs/sensor_HassGetState.yaml
  sentences/cs/weather_HassGetWeather.yaml
  tests/cs/_fixtures.yaml
  tests/cs/binary_sensor_HassGetState.yaml
  tests/cs/sensor_HassGetState.yaml
Labels: cla-signed, lang: cs

#2780 [SR] Add GetWeather
  responses/sr/HassGetWeather.yaml
  sentences/sr/weather_HassGetWeather.yaml
  tests/sr/_fixtures.yaml
  tests/sr/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sr

#2781 [SR] Add ListAddItem
  responses/sr/HassListAddItem.yaml
  sentences/sr/todo_HassListAddItem.yaml
  tests/sr/_fixtures.yaml
  tests/sr/todo_HassListAddItem.yaml
Labels: cla-signed, lang: sr

#2789 [SR] Add Vacuum
  responses/sr/HassVacuumReturnToBase.yaml
  responses/sr/HassVacuumStart.yaml
  sentences/sr/_common.yaml
  sentences/sr/vacuum_HassVacuumReturnToBase.yaml
  sentences/sr/vacuum_HassVacuumStart.yaml
  tests/sr/_fixtures.yaml
  tests/sr/vacuum_HassVacuumReturnToBase.yaml
  tests/sr/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: sr

#2803 [de-CH] Add CancelAllTimers
  responses/de-CH/HassCancelAllTimers.yaml
  sentences/de-CH/homeassistant_HassCancelAllTimers.yaml
  tests/de-CH/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed

#2812 [BG] improve HassGetCurrentTime sentences
  sentences/bg/homeassistant_HassGetCurrentTime.yaml
  tests/bg/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: bg

#2811 [BG] add HassRespond, HassSetPosition, HassVacuumStart, HassVacuumReturnToBase
  responses/bg/HassRespond.yaml
  responses/bg/HassSetPosition.yaml
  responses/bg/HassVacuumReturnToBase.yaml
  responses/bg/HassVacuumStart.yaml
  sentences/bg/_common.yaml
  sentences/bg/cover_HassSetPosition.yaml
  sentences/bg/homeassistant_HassRespond.yaml
  sentences/bg/vacuum_HassVacuumReturnToBase.yaml
  sentences/bg/vacuum_HassVacuumStart.yaml
  tests/bg/_fixtures.yaml
  tests/bg/cover_HassSetPosition.yaml
  tests/bg/homeassistant_HassRespond.yaml
  tests/bg/vacuum_HassVacuumReturnToBase.yaml
  tests/bg/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: bg
