Repository OHF-Voice/intents, pull requests merged in 2024-10, with the labels that each got.

#2405 [PL] - added more sentences for checking active timers
  sentences/pl/_common.yaml
  sentences/pl/homeassistant_HassTimerStatus.yaml
  tests/pl/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: pl, Hacktoberfest

#2406 [PL] - bug fix and added more sentences for timers
  sentences/pl/homeassistant_HassTimerStatus.yaml
  tests/pl/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: pl, Hacktoberfest

#2408 [EN] Add "lock all doors"
  sentences/en/_common.yaml
  sentences/en/lock_HassTurnOn.yaml
  tests/en/lock_HassTurnOn.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2407 [PL] - added area for running and finishing vacuum cleaning
  sentences/pl/_common.yaml
  sentences/pl/vacuum_HassVacuumReturnToBase.yaml
  sentences/pl/vacuum_HassVacuumStart.yaml
  tests/pl/_fixtures.yaml
  tests/pl/vacuum_HassVacuumReturnToBase.yaml
  tests/pl/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: pl, Hacktoberfest

#2411 [SK] Cleanup and more possibilities - edit
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassTurnOff.yaml
  sentences/sk/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: sk, Hacktoberfest

#2401 [cs] Room awarness for climate
  responses/cs/HassClimateGetTemperature.yaml
  sentences/cs/_common.yaml
  sentences/cs/climate_HassClimateGetTemperature.yaml
  sentences/cs/climate_HassClimateSetTemperature.yaml
  tests/cs/_fixtures.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: cs

#2416 [SL] fixes for duplicate floors
  responses/sl/HassGetState.yaml
  sentences/sl/_common.yaml
Labels: cla-signed, lang: sl, Hacktoberfest

#2415 [PL] Improved exposed error messages
  sentences/pl/_common.yaml
Labels: cla-signed, lang: pl, Hacktoberfest

#2419 Add "sticky" to table header
  website/public/style.css
Labels: cla-signed, Hacktoberfest

#2418 [EN] Explicit and friendly domain name for HassTurnOn/HassTurnOff
  responses/en/HassTurnOff.yaml
  responses/en/HassTurnOn.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2420 [FR] Various Small Improvements
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassCancelTimer.yaml
  sentences/fr/homeassistant_HassDecreaseTimer.yaml
  sentences/fr/homeassistant_HassIncreaseTimer.yaml
  sentences/fr/homeassistant_HassPauseTimer.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/homeassistant_HassUnpauseTimer.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/homeassistant_HassCancelTimer.yaml
  tests/fr/homeassistant_HassDecreaseTimer.yaml
  tests/fr/homeassistant_HassIncreaseTimer.yaml
  tests/fr/homeassistant_HassPauseTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
  tests/fr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fr, Hacktoberfest

#2423 Update intents.yaml
  intents.yaml
Labels: cla-signed, Hacktoberfest

#2424 [FR] New lock support
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/lock_HassTurnOff.yaml
  sentences/fr/lock_HassTurnOn.yaml
  tests/fr/_fixtures.yaml
  tests/fr/lock_HassGetState.yaml
  tests/fr/lock_HassTurnOff.yaml
  tests/fr/lock_HassTurnOn.yaml
Labels: cla-signed, lang: fr, Hacktoberfest

#2425 [FR] Improve whole house intents
  sentences/fr/_common.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/cover_HassTurnOff.yaml
  tests/fr/cover_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr, Hacktoberfest

#2427 Tidy timer status file, added "how long" phrase
  sentences/en/homeassistant_HassTimerStatus.yaml
  tests/en/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2413 [CS] Cleanup of common aliases
  responses/cs/HassVacuumReturnToBase.yaml
  responses/cs/HassVacuumStart.yaml
  sentences/cs/_common.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/sensor_HassGetState.yaml
  sentences/cs/vacuum_HassVacuumReturnToBase.yaml
  sentences/cs/vacuum_HassVacuumStart.yaml
  sentences/cs/weather_HassGetWeather.yaml
  tests/cs/vacuum_HassVacuumReturnToBase.yaml
  tests/cs/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: cs, Hacktoberfest

#2304 [NL] Update intents to turn fans on and off
  sentences/nl/_common.yaml
  sentences/nl/fan_HassTurnOff.yaml
  sentences/nl/fan_HassTurnOn.yaml
  tests/nl/fan_HassTurnOff.yaml
  tests/nl/fan_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#1834 Update _common.yaml
  sentences/lt/_common.yaml
Labels: cla-signed, lang: lt

#1832 [LT] Update HassTurnOff.yaml
  responses/lt/HassTurnOff.yaml
Labels: cla-signed, lang: lt

#2347 Update README with devcontainer recommendation
  README.md
Labels: cla-signed

#2428 [en] Add "take off/from" timer to decrease
  sentences/en/homeassistant_HassDecreaseTimer.yaml
  tests/en/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2431 [PT-BR] update sentences (person and timer)
  responses/pt-br/HassGetState.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/person_HassGetState.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/person_HassGetState.yaml
Labels: cla-signed, Hacktoberfest

#2430 [en] Standardised template spacing across sentences
  sentences/en/climate_HassClimateGetTemperature.yaml
  sentences/en/cover_HassSetPosition.yaml
  sentences/en/cover_HassTurnOff.yaml
  sentences/en/cover_HassTurnOn.yaml
  sentences/en/fan_HassTurnOff.yaml
  sentences/en/fan_HassTurnOn.yaml
  sentences/en/homeassistant_HassCancelTimer.yaml
  sentences/en/homeassistant_HassGetCurrentDate.yaml
  sentences/en/homeassistant_HassGetCurrentTime.yaml
  sentences/en/homeassistant_HassGetState.yaml
  sentences/en/homeassistant_HassIncreaseTimer.yaml
  sentences/en/homeassistant_HassPauseTimer.yaml
  sentences/en/homeassistant_HassStartTimer.yaml
  sentences/en/homeassistant_HassUnpauseTimer.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/lock_HassGetState.yaml
  sentences/en/lock_HassTurnOff.yaml
  sentences/en/lock_HassTurnOn.yaml
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaPrevious.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  sentences/en/shopping_list_HassShoppingListAddItem.yaml
  sentences/en/todo_HassListAddItem.yaml
  sentences/en/vacuum_HassVacuumReturnToBase.yaml
  sentences/en/valve_HassSetPosition.yaml
  sentences/en/weather_HassGetWeather.yaml
Labels: cla-signed, lang: en, Hacktoberfest

#2434 [PL] typo in CurrentDate and CurrentTime sentences
  sentences/pl/homeassistant_HassGetCurrentDate.yaml
  sentences/pl/homeassistant_HassGetCurrentTime.yaml
  tests/pl/homeassistant_HassGetCurrentDate.yaml
  tests/pl/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: pl, Hacktoberfest

#2436 Update en language leaders
  CODEOWNERS
  languages.yaml
Labels: cla-signed, Hacktoberfest

#2437 Add vividboarder as an en language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed, Hacktoberfest
