Repository OHF-Voice/intents, pull requests merged in 2024-07, with the labels that each got.

#2268 [IT] Add support for timers
  responses/it/HassCancelTimer.yaml
  responses/it/HassDecreaseTimer.yaml
  responses/it/HassIncreaseTimer.yaml
  responses/it/HassPauseTimer.yaml
  responses/it/HassStartTimer.yaml
  responses/it/HassTimerStatus.yaml
  responses/it/HassUnpauseTimer.yaml
  sentences/it/_common.yaml
  sentences/it/homeassistant_HassCancelTimer.yaml
  sentences/it/homeassistant_HassDecreaseTimer.yaml
  sentences/it/homeassistant_HassIncreaseTimer.yaml
  sentences/it/homeassistant_HassPauseTimer.yaml
  sentences/it/homeassistant_HassStartTimer.yaml
  sentences/it/homeassistant_HassTimerStatus.yaml
  sentences/it/homeassistant_HassUnpauseTimer.yaml
  tests/it/_fixtures.yaml
  tests/it/homeassistant_HassCancelTimer.yaml
  tests/it/homeassistant_HassDecreaseTimer.yaml
  tests/it/homeassistant_HassIncreaseTimer.yaml
  tests/it/homeassistant_HassPauseTimer.yaml
  tests/it/homeassistant_HassStartTimer.yaml
  tests/it/homeassistant_HassTimerStatus.yaml
  tests/it/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: it

#2269 [RU] A few fixes for binary sensors
  sentences/ru/_common.yaml
  sentences/ru/binary_sensor_HassGetState.yaml
  tests/ru/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: ru

#2275 [IT] Add support for media_player control
  responses/it/HassMediaNext.yaml
  responses/it/HassMediaPause.yaml
  responses/it/HassMediaPrevious.yaml
  responses/it/HassMediaUnpause.yaml
  responses/it/HassSetVolume.yaml
  sentences/it/_common.yaml
  sentences/it/media_player_HassMediaNext.yaml
  sentences/it/media_player_HassMediaPause.yaml
  sentences/it/media_player_HassMediaPrevious.yaml
  sentences/it/media_player_HassMediaUnpause.yaml
  sentences/it/media_player_HassSetVolume.yaml
  tests/it/_fixtures.yaml
  tests/it/media_player_HassMediaNext.yaml
  tests/it/media_player_HassMediaPause.yaml
  tests/it/media_player_HassMediaPrevious.yaml
  tests/it/media_player_HassMediaUnpause.yaml
  tests/it/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: it

#2279 [SL] added CancelTimer
  responses/sl/HassCancelTimer.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassCancelTimer.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: sl

#2280 Don't set up another venv when venv already is setup
  script/setup
Labels: cla-signed

#2266 [DE] add queries for window states
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#2267 [DE] add degrees to HassClimateGetTemperature
  responses/de/HassClimateGetTemperature.yaml
  tests/de/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: de

#2260 [DE] Don't require area to start a timer
  sentences/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: de

#2254 [DE] add HassMediaPrevious
  responses/de/HassMediaPrevious.yaml
  sentences/de/_common.yaml
  sentences/de/media_player_HassMediaNext.yaml
  sentences/de/media_player_HassMediaPrevious.yaml
  tests/de/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: de

#2281 [NL] Add context aware pause media player intent
  sentences/nl/media_player_HassMediaPause.yaml
  tests/nl/media_player_HassMediaPause.yaml
Labels: cla-signed, lang: nl

#2219 [EN] Add more english sentences for lock get state queries
  sentences/en/_common.yaml
  sentences/en/lock_HassGetState.yaml
  sentences/en/lock_HassTurnOff.yaml
  sentences/en/lock_HassTurnOn.yaml
  tests/en/_fixtures.yaml
  tests/en/lock_HassGetState.yaml
Labels: cla-signed, lang: en

#2283 [RO] Don't require area to start timer
  sentences/ro/homeassistant_HassStartTimer.yaml
  tests/ro/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: ro

#2282 [NL] Align ClimateTemperatureSet with EN
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#2293 [SL] Added HassStartTimer
  responses/sl/HassStartTimer.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassStartTimer.yaml
  tests/sl/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: sl

#2294 [SL] Added HassPauseTimer
  responses/sl/HassPauseTimer.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassPauseTimer.yaml
  tests/sl/homeassistant_HassPauseTimer.yaml
Labels: cla-signed, lang: sl

#2295 [SL] Added Hass_Decrease, Increase, Pause and UnpauseTimer
  responses/sl/HassDecreaseTimer.yaml
  responses/sl/HassIncreaseTimer.yaml
  responses/sl/HassUnpauseTimer.yaml
  sentences/sl/homeassistant_HassDecreaseTimer.yaml
  sentences/sl/homeassistant_HassIncreaseTimer.yaml
  sentences/sl/homeassistant_HassUnpauseTimer.yaml
  tests/sl/homeassistant_HassDecreaseTimer.yaml
  tests/sl/homeassistant_HassIncreaseTimer.yaml
  tests/sl/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: sl

#2291 [DE] add variants to HassMediaPrevious
  sentences/de/_common.yaml
  sentences/de/media_player_HassMediaPrevious.yaml
  tests/de/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: de

#2297 [SL] Added Timer Status
  responses/sl/HassTimerStatus.yaml
  sentences/sl/homeassistant_HassTimerStatus.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: sl

#2298 [SL] Added MediaPrevious
  responses/sl/HassMediaPrevious.yaml
  sentences/sl/media_player_HassMediaNext.yaml
  sentences/sl/media_player_HassMediaPrevious.yaml
  tests/sl/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: sl

#2299 Bump hassil to 1.7.4
  requirements.txt
  script/intentfest/sample_template.py
  tests/test_language_intents.py
Labels: cla-signed

#2300 Add HassGetDate and HassGetTime
  intents.yaml
  responses/en/HassGetCurrentDate.yaml
  responses/en/HassGetCurrentTime.yaml
  script/intentfest/generate_day_ordinals.py
  script/intentfest/util.py
  script/intentfest/validate.py
  sentences/en/homeassistant_HassGetCurrentDate.yaml
  sentences/en/homeassistant_HassGetCurrentTime.yaml
  shared/__init__.py
  tests/en/homeassistant_HassGetCurrentDate.yaml
  tests/en/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: en

#2301 Don't use strftime in date/time responses
  responses/en/HassGetCurrentDate.yaml
  responses/en/HassGetCurrentTime.yaml
Labels: cla-signed, lang: en

#2302 Use date and time objects specifically
  script/intentfest/validate.py
  shared/__init__.py
Labels: cla-signed

#2303 [SL] added Current Date and Current Time
  responses/sl/HassGetCurrentDate.yaml
  responses/sl/HassGetCurrentTime.yaml
  sentences/sl/homeassistant_HassGetCurrentDate.yaml
  sentences/sl/homeassistant_HassGetCurrentTime.yaml
  tests/sl/homeassistant_HassGetCurrentDate.yaml
  tests/sl/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sl

#2276 [IT] Add support for script activation
  sentences/it/_common.yaml
  sentences/it/script_HassTurnOn.yaml
  tests/it/_fixtures.yaml
  tests/it/script_HassTurnOn.yaml
Labels: cla-signed, lang: it

#2307 [SL] HassGetCurrentTime code cleanup
  responses/sl/HassGetCurrentTime.yaml
  tests/sl/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sl

#2308 [SL] Current Time fix for time format
  responses/sl/HassGetCurrentTime.yaml
  tests/sl/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sl

#2311 [es] Current date and time
  responses/es/HassGetCurrentDate.yaml
  responses/es/HassGetCurrentTime.yaml
  sentences/es/homeassistant_HassGetCurrentDate.yaml
  sentences/es/homeassistant_HassGetCurrentTime.yaml
  tests/es/homeassistant_HassGetCurrentDate.yaml
  tests/es/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: es

#2312 Translation (zh-hk) - HassGetCurrentDate & Time
  responses/zh-hk/HassGetCurrentDate.yaml
  responses/zh-hk/HassGetCurrentTime.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassGetCurrentDate.yaml
  sentences/zh-hk/homeassistant_HassGetCurrentTime.yaml
  tests/zh-hk/homeassistant_HassGetCurrentDate.yaml
  tests/zh-hk/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed

#2313 [pt-br] Current date and time
  responses/pt-br/HassGetCurrentDate.yaml
  responses/pt-br/HassGetCurrentTime.yaml
  sentences/pt-br/homeassistant_HassGetCurrentDate.yaml
  sentences/pt-br/homeassistant_HassGetCurrentTime.yaml
  tests/pt-br/homeassistant_HassGetCurrentDate.yaml
  tests/pt-br/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed

#2315 HassGetWeather
  responses/zh-hk/HassGetWeather.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassGetCurrentDate.yaml
  sentences/zh-hk/weather_HassGetWeather.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/weather_HassGetWeather.yaml
Labels: cla-signed

#2310 [SL] added weekday to current date response
  responses/sl/HassGetCurrentDate.yaml
  tests/sl/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: sl

#2316 HassNevermind
  sentences/zh-hk/homeassistant_HassNevermind.yaml
  tests/zh-hk/homeassistant_HassNevermind.yaml
Labels: cla-signed

#2317 [he] added `nevermind` intent
  sentences/he/homeassistant_HassNevermind.yaml
  tests/he/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: he

#2314 [DE] Add HassGetDate and HassGetTime
  responses/de/HassGetCurrentDate.yaml
  responses/de/HassGetCurrentTime.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassGetCurrentDate.yaml
  sentences/de/homeassistant_HassGetCurrentTime.yaml
  tests/de/homeassistant_HassGetCurrentDate.yaml
  tests/de/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: de

#2318 lb-CurrentDate-CurrentTime
  responses/lb/HassGetCurrentDate.yaml
  responses/lb/HassGetCurrentTime.yaml
  sentences/lb/_common.yaml
  sentences/lb/homeassistant_HassGetCurrentDate.yaml
  sentences/lb/homeassistant_HassGetCurrentTime.yaml
  tests/lb/homeassistant_HassGetCurrentDate.yaml
  tests/lb/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: lb

#2278 [de] Weather sentences without a name
  sentences/de/weather_HassGetWeather.yaml
  tests/de/weather_HassGetWeather.yaml
Labels: cla-signed, lang: de

#2320 HassSetPosition
  responses/zh-hk/HassSetPosition.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/cover_HassSetPosition.yaml
  sentences/zh-hk/valve_HassSetPosition.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/cover_HassSetPosition.yaml
  tests/zh-hk/valve_HassSetPosition.yaml
Labels: cla-signed

#2321 HassVacuumStart
  responses/zh-hk/HassVacuumStart.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/vacuum_HassVacuumStart.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/vacuum_HassVacuumStart.yaml
Labels: cla-signed

#2322 HassVacuumReturnToBase
  responses/zh-hk/HassVacuumReturnToBase.yaml
  responses/zh-hk/HassVacuumStart.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/vacuum_HassVacuumReturnToBase.yaml
  tests/zh-hk/vacuum_HassVacuumReturnToBase.yaml
  tests/zh-hk/vacuum_HassVacuumStart.yaml
Labels: cla-signed

#2323 HassListAdditem
  responses/zh-hk/HassListAddItem.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/todo_HassListAddItem.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/todo_HassListAddItem.yaml
Labels: cla-signed

#2325 HassTimerStatus
  responses/zh-hk/HassTimerStatus.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassTimerStatus.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/homeassistant_HassTimerStatus.yaml
Labels: cla-signed

#2326 HassPauseTimer
  responses/zh-hk/HassPauseTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassPauseTimer.yaml
  tests/zh-hk/homeassistant_HassPauseTimer.yaml
Labels: cla-signed

#2327 HassUnpauseTimer
  responses/zh-hk/HassUnpauseTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassUnpauseTimer.yaml
  tests/zh-hk/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed

#2329 [zh-hk] HassStartTimer
  responses/zh-hk/HassStartTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassStartTimer.yaml
  tests/zh-hk/homeassistant_HassStartTimer.yaml
Labels: cla-signed

#2330 [zh-hk] HassCancelTimer
  responses/zh-hk/HassCancelTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassCancelTimer.yaml
  sentences/zh-hk/homeassistant_HassPauseTimer.yaml
  sentences/zh-hk/homeassistant_HassStartTimer.yaml
  sentences/zh-hk/homeassistant_HassUnpauseTimer.yaml
  tests/zh-hk/homeassistant_HassCancelTimer.yaml
  tests/zh-hk/homeassistant_HassPauseTimer.yaml
  tests/zh-hk/homeassistant_HassStartTimer.yaml
  tests/zh-hk/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed

#2331 [zh-hk] HassIncreaseTimer
  responses/zh-hk/HassIncreaseTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassIncreaseTimer.yaml
  tests/zh-hk/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed

#2332 [Zh-hk] HassDecreaseTimer
  responses/zh-hk/HassDecreaseTimer.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassDecreaseTimer.yaml
  sentences/zh-hk/homeassistant_HassIncreaseTimer.yaml
  tests/zh-hk/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed

#2333 [zh-hk] HassSetVolume
  responses/zh-hk/HassSetVolume.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/media_player_HassSetVolume.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/media_player_HassSetVolume.yaml
Labels: cla-signed

#2334 [zh-hk] HassMediaPause
  responses/zh-hk/HassMediaPause.yaml
  sentences/zh-hk/media_player_HassMediaPause.yaml
  tests/zh-hk/media_player_HassMediaPause.yaml
Labels: cla-signed

#2336 [zh-hk] HassMediaNext
  responses/zh-hk/HassMediaNext.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/media_player_HassMediaNext.yaml
  tests/zh-hk/media_player_HassMediaNext.yaml
Labels: cla-signed

#2337 [zh-hk] HassMediaPrevious
  responses/zh-hk/HassMediaPrevious.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/media_player_HassMediaPrevious.yaml
  tests/zh-hk/media_player_HassMediaPrevious.yaml
Labels: cla-signed

#2328 [FI] added HassMediaPrevious
  responses/fi/HassMediaPrevious.yaml
  sentences/fi/media_player_HassMediaPrevious.yaml
  tests/fi/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: fi

#2343 [SL] HassTurnOff, lightHassLightSet fix
  responses/sl/HassTurnOff.yaml
  sentences/sl/homeassistant_HassTurnOff.yaml
  sentences/sl/light_HassLightSet.yaml
  sentences/sl/light_HassTurnOff.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassTurnOff.yaml
  tests/sl/light_HassLightSet.yaml
Labels: cla-signed, lang: sl

#2348 [zh-hk] error message
  sentences/zh-hk/_common.yaml
Labels: cla-signed

#2351 Fix several typos
  sentences/ru/_common.yaml
Labels: cla-signed, lang: ru

#2349 [SV] Add sentences for getting the current date and time
  responses/sv/HassGetCurrentDate.yaml
  responses/sv/HassGetCurrentTime.yaml
  sentences/sv/homeassistant_HassGetCurrentDate.yaml
  sentences/sv/homeassistant_HassGetCurrentTime.yaml
  tests/sv/homeassistant_HassGetCurrentDate.yaml
  tests/sv/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sv
