Repository OHF-Voice/intents, pull requests merged in 2024-04, with the labels that each got.

#2116 [SL] added initial support for floors
  responses/sl/HassTurnOff.yaml
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/light_HassTurnOff.yaml
  sentences/sl/light_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/light_HassTurnOff.yaml
  tests/sl/light_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#2119 Fix floor slot combinations
  intents.yaml
Labels: cla-signed

#2117 [nb] Initial support for floors
  responses/nb/HassTurnOff.yaml
  responses/nb/HassTurnOn.yaml
  sentences/nb/_common.yaml
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  tests/nb/_fixtures.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#2120 [FR] Floor basic support for lights TurnOn and TurnOff
  sentences/fr/_common.yaml
  sentences/fr/cover_HassSetPosition.yaml
  sentences/fr/cover_HassTurnOff.yaml
  sentences/fr/cover_HassTurnOn.yaml
  sentences/fr/light_HassLightSet.yaml
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/_fixtures.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#2123 [PT-BR] Initial support for floors
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#2126 [PT] Add vacuum
  responses/pt/HassVacuumReturnToBase.yaml
  responses/pt/HassVacuumStart.yaml
  sentences/pt/homeassistant_HassTurnOn.yaml
  sentences/pt/vacuum_HassVacuumReturnToBase.yaml
  sentences/pt/vacuum_HassVacuumStart.yaml
  tests/pt/_fixtures.yaml
  tests/pt/vacuum_HassVacuumReturnToBase.yaml
  tests/pt/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: pt

#2118 [nb] Improve errors
  sentences/nb/_common.yaml
Labels: cla-signed, lang: nb

#2110 [RU] Adding new intents for lighting control in the whole house
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  sentences/ru/light_HassTurnOff.yaml
  sentences/ru/light_HassTurnOn.yaml
  tests/ru/light_HassTurnOff.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2135 [IT] Update Shoppinglist
  sentences/it/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: it

#2134 [IT] Update Common
  sentences/it/_common.yaml
  sentences/it/cover_HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  tests/it/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: it

#2133 [RU]Correction of errors in the selection of participle endings
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2140 [SV] Add weather and media
  responses/sv/HassGetWeather.yaml
  responses/sv/HassMediaNext.yaml
  responses/sv/HassMediaPause.yaml
  responses/sv/HassMediaUnpause.yaml
  responses/sv/HassSetVolume.yaml
  sentences/sv/_common.yaml
  sentences/sv/media_player_HassMediaNext.yaml
  sentences/sv/media_player_HassMediaPause.yaml
  sentences/sv/media_player_HassMediaUnpause.yaml
  sentences/sv/media_player_HassSetVolume.yaml
  sentences/sv/weather_HassGetWeather.yaml
  tests/sv/_fixtures.yaml
  tests/sv/media_player_HassMediaNext.yaml
  tests/sv/media_player_HassMediaPause.yaml
  tests/sv/media_player_HassMediaUnpause.yaml
  tests/sv/media_player_HassSetVolume.yaml
  tests/sv/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sv

#2138 Adding intent translations for latvian (lv)
  responses/lv/HassClimateSetTemperature.yaml
  responses/lv/HassGetWeather.yaml
  responses/lv/HassLightSet.yaml
  responses/lv/HassTurnOff.yaml
  responses/lv/HassTurnOn.yaml
  sentences/lv/weather_HassGetWeather.yaml
  tests/lv/_fixtures.yaml
  tests/lv/cover_HassTurnOff.yaml
  tests/lv/cover_HassTurnOn.yaml
  tests/lv/weather_HassGetWeather.yaml
Labels: cla-signed, lang: lv

#2145 [FI] script_HassTurnOn
  responses/fi/HassTurnOn.yaml
  sentences/fi/_common.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  sentences/fi/script_HassTurnOn.yaml
  tests/fi/script_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#2149 [uk] added floor lights
  responses/uk/HassTurnOff.yaml
  responses/uk/HassTurnOn.yaml
  sentences/uk/_common.yaml
  sentences/uk/light_HassTurnOff.yaml
  sentences/uk/light_HassTurnOn.yaml
  tests/uk/_fixtures.yaml
  tests/uk/light_HassTurnOff.yaml
  tests/uk/light_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#2125 [AR] Improve the Arabic language responses
  sentences/ar/_common.yaml
  tests/ar/light_HassLightSet.yaml
Labels: cla-signed, lang: ar

#2151 [ca] Update cover actions
  sentences/ca/cover_HassTurnOff.yaml
  sentences/ca/cover_HassTurnOn.yaml
  tests/ca/cover_HassTurnOff.yaml
  tests/ca/cover_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2152 [he] added female pronounce to `sentences`
  sentences/he/_common.yaml
  sentences/he/climate_HassClimateSetTemperature.yaml
  sentences/he/cover_HassTurnOff.yaml
  sentences/he/cover_HassTurnOn.yaml
  sentences/he/fan_HassTurnOff.yaml
  sentences/he/fan_HassTurnOn.yaml
  sentences/he/homeassistant_HassTurnOff.yaml
  sentences/he/homeassistant_HassTurnOn.yaml
  sentences/he/light_HassLightSet.yaml
  sentences/he/light_HassTurnOff.yaml
  sentences/he/light_HassTurnOn.yaml
  tests/he/climate_HassClimateSetTemperature.yaml
  tests/he/cover_HassTurnOff.yaml
  tests/he/cover_HassTurnOn.yaml
  tests/he/fan_HassTurnOff.yaml
  tests/he/fan_HassTurnOn.yaml
  tests/he/homeassistant_HassTurnOff.yaml
  tests/he/homeassistant_HassTurnOn.yaml
  tests/he/light_HassLightSet.yaml
  tests/he/light_HassTurnOff.yaml
  tests/he/light_HassTurnOn.yaml
Labels: cla-signed, lang: he

#2153 [es] Updating Spanish translations
  responses/es/HassTurnOff.yaml
  responses/es/HassTurnOn.yaml
  sentences/es/_common.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/homeassistant_HassGetState.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassLightSet.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es
