Repository OHF-Voice/intents, pull requests merged in 2024-06, with the labels that each got.

#2210 Send area name to timer response
  shared/__init__.py
  tests/en/_fixtures.yaml
Labels: cla-signed, lang: en

#2200 [DE] Add timer support
  responses/de/HassCancelTimer.yaml
  responses/de/HassDecreaseTimer.yaml
  responses/de/HassIncreaseTimer.yaml
  responses/de/HassPauseTimer.yaml
  responses/de/HassStartTimer.yaml
  responses/de/HassTimerStatus.yaml
  responses/de/HassUnpauseTimer.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassCancelTimer.yaml
  sentences/de/homeassistant_HassDecreaseTimer.yaml
  sentences/de/homeassistant_HassIncreaseTimer.yaml
  sentences/de/homeassistant_HassPauseTimer.yaml
  sentences/de/homeassistant_HassStartTimer.yaml
  sentences/de/homeassistant_HassTimerStatus.yaml
  sentences/de/homeassistant_HassUnpauseTimer.yaml
  tests/de/_fixtures.yaml
  tests/de/homeassistant_HassCancelTimer.yaml
  tests/de/homeassistant_HassDecreaseTimer.yaml
  tests/de/homeassistant_HassIncreaseTimer.yaml
  tests/de/homeassistant_HassPauseTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassTimerStatus.yaml
  tests/de/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: de

#2211 [DE] Add delayed commands to timers
  responses/de/HassStartTimer.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: de

#2208 Fr timers
  responses/fr/HassCancelTimer.yaml
  responses/fr/HassDecreaseTimer.yaml
  responses/fr/HassIncreaseTimer.yaml
  responses/fr/HassPauseTimer.yaml
  responses/fr/HassStartTimer.yaml
  responses/fr/HassTimerStatus.yaml
  responses/fr/HassUnpauseTimer.yaml
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassCancelTimer.yaml
  sentences/fr/homeassistant_HassDecreaseTimer.yaml
  sentences/fr/homeassistant_HassIncreaseTimer.yaml
  sentences/fr/homeassistant_HassPauseTimer.yaml
  sentences/fr/homeassistant_HassStartTimer.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/homeassistant_HassUnpauseTimer.yaml
  tests/fr/_fixtures.yaml
  tests/fr/homeassistant_HassCancelTimer.yaml
  tests/fr/homeassistant_HassDecreaseTimer.yaml
  tests/fr/homeassistant_HassIncreaseTimer.yaml
  tests/fr/homeassistant_HassPauseTimer.yaml
  tests/fr/homeassistant_HassStartTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
  tests/fr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fr

#2223 [RO] Fix media_player_HassMediaPause
  sentences/ro/_common.yaml
  sentences/ro/media_player_HassMediaPause.yaml
  tests/ro/homeassistant_HassTurnOff.yaml
  tests/ro/media_player_HassMediaPause.yaml
Labels: cla-signed, lang: ro

#2214 Parallelize tests
  README.md
  requirements.txt
  script/test
  script/test_file
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#2213 [DE] Optimize usage of spaces in optional sentence parts
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/climate_HassClimateSetTemperature.yaml
  sentences/de/cover_HassGetState.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  sentences/de/fan_HassTurnOff.yaml
  sentences/de/fan_HassTurnOn.yaml
  sentences/de/homeassistant_HassCancelTimer.yaml
  sentences/de/homeassistant_HassDecreaseTimer.yaml
  sentences/de/homeassistant_HassGetState.yaml
  sentences/de/homeassistant_HassIncreaseTimer.yaml
  sentences/de/homeassistant_HassPauseTimer.yaml
  sentences/de/homeassistant_HassSetPosition.yaml
  sentences/de/homeassistant_HassStartTimer.yaml
  sentences/de/homeassistant_HassUnpauseTimer.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/light_HassTurnOff.yaml
  sentences/de/light_HassTurnOn.yaml
  sentences/de/lock_HassGetState.yaml
  sentences/de/lock_HassTurnOff.yaml
  sentences/de/lock_HassTurnOn.yaml
  sentences/de/media_player_HassMediaNext.yaml
  sentences/de/media_player_HassMediaPause.yaml
  sentences/de/media_player_HassMediaUnpause.yaml
  sentences/de/media_player_HassSetVolume.yaml
  sentences/de/scene_HassTurnOn.yaml
  sentences/de/script_HassTurnOn.yaml
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
  sentences/de/todo_HassListAddItem.yaml
  sentences/de/vacuum_HassVacuumReturnToBase.yaml
  sentences/de/weather_HassGetWeather.yaml
Labels: cla-signed, lang: de

#2226 Update Devcontainer/CI to Python 3.12
  .devcontainer.json
  .github/workflows/ci.yaml
  .github/workflows/gh-pages.yml
Labels: cla-signed

#2127 [DE] Add more variants to Nevermind
  sentences/de/homeassistant_HassNevermind.yaml
  tests/de/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: de

#2144 [LB] Add support for weather
  responses/lb/HassGetWeather.yaml
  sentences/lb/weather_HassGetWeather.yaml
  tests/lb/_fixtures.yaml
  tests/lb/weather_HassGetWeather.yaml
Labels: cla-signed, lang: lb

#1802 [EL] Update HassTurnOn and LightsOn.yaml
  responses/el/HassTurnOn.yaml
  sentences/el/light_HassTurnOn.yaml
  tests/el/light_HassTurnOn.yaml
Labels: cla-signed, lang: el

#2204 [RU]Аdded media control for area
  sentences/ru/media_player_HassMediaNext.yaml
  sentences/ru/media_player_HassMediaPause.yaml
  sentences/ru/media_player_HassMediaUnpause.yaml
  sentences/ru/media_player_HassSetVolume.yaml
  tests/ru/media_player_HassMediaNext.yaml
  tests/ru/media_player_HassMediaPause.yaml
  tests/ru/media_player_HassMediaUnpause.yaml
  tests/ru/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: ru

#2233 [RU]Added translation of error
  sentences/ru/_common.yaml
Labels: cla-signed, lang: ru

#2239 [FR] Make timers great again
  sentences/fr/_common.yaml
  tests/fr/homeassistant_HassCancelTimer.yaml
  tests/fr/homeassistant_HassDecreaseTimer.yaml
  tests/fr/homeassistant_HassIncreaseTimer.yaml
  tests/fr/homeassistant_HassPauseTimer.yaml
  tests/fr/homeassistant_HassStartTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
  tests/fr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fr

#2240 [RU]Fixed climate intents
  responses/ru/HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateGetTemperature.yaml
  sentences/ru/climate_HassClimateSetTemperature.yaml
  tests/ru/_fixtures.yaml
  tests/ru/climate_HassClimateGetTemperature.yaml
  tests/ru/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ru

#2238 [PT-BR] improving intents
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassNevermind.yaml
  sentences/pt-br/homeassistant_HassSetPosition.yaml
  sentences/pt-br/light_HassLightSet.yaml
  sentences/pt-br/media_player_HassSetVolume.yaml
  sentences/pt-br/vacuum_HassVacuumReturnToBase.yaml
Labels: cla-signed

#2241 [RU]optimizations of the Cover classes
  responses/ru/HassSetPosition.yaml
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  sentences/ru/_common.yaml
  sentences/ru/cover_HassSetPosition.yaml
  sentences/ru/cover_HassTurnOff.yaml
  sentences/ru/cover_HassTurnOn.yaml
  sentences/ru/homeassistant_HassTurnOff.yaml
  sentences/ru/homeassistant_HassTurnOn.yaml
  tests/ru/cover_HassSetPosition.yaml
  tests/ru/cover_HassTurnOff.yaml
  tests/ru/cover_HassTurnOn.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2243 [RU] Improved response for cover_device_class
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  tests/ru/cover_HassTurnOff.yaml
  tests/ru/cover_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2245 [ES] Updating Spanish translations to 2024.6.21
  responses/es/HassCancelTimer.yaml
  responses/es/HassDecreaseTimer.yaml
  responses/es/HassIncreaseTimer.yaml
  responses/es/HassPauseTimer.yaml
  responses/es/HassStartTimer.yaml
  responses/es/HassTimerStatus.yaml
  responses/es/HassUnpauseTimer.yaml
  sentences/es/_common.yaml
  sentences/es/cover_HassGetState.yaml
  sentences/es/homeassistant_HassCancelTimer.yaml
  sentences/es/homeassistant_HassDecreaseTimer.yaml
  sentences/es/homeassistant_HassIncreaseTimer.yaml
  sentences/es/homeassistant_HassPauseTimer.yaml
  sentences/es/homeassistant_HassStartTimer.yaml
  sentences/es/homeassistant_HassTimerStatus.yaml
  sentences/es/homeassistant_HassUnpauseTimer.yaml
  sentences/es/light_HassTurnOn.yaml
  sentences/es/media_player_HassMediaNext.yaml
  sentences/es/media_player_HassMediaPause.yaml
  sentences/es/media_player_HassMediaUnpause.yaml
  sentences/es/media_player_HassSetVolume.yaml
  tests/es/_fixtures.yaml
  tests/es/cover_HassGetState.yaml
  tests/es/homeassistant_HassCancelTimer.yaml
  tests/es/homeassistant_HassDecreaseTimer.yaml
  tests/es/homeassistant_HassIncreaseTimer.yaml
  tests/es/homeassistant_HassPauseTimer.yaml
  tests/es/homeassistant_HassStartTimer.yaml
  tests/es/homeassistant_HassTimerStatus.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/homeassistant_HassUnpauseTimer.yaml
  tests/es/media_player_HassMediaNext.yaml
  tests/es/media_player_HassMediaPause.yaml
  tests/es/media_player_HassMediaUnpause.yaml
  tests/es/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: es

#2247 [es] Fixing minor bugs
  responses/es/HassTimerStatus.yaml
  tests/es/_fixtures.yaml
Labels: cla-signed, lang: es

#2080 [en] Add previous_track intent
  intents.yaml
  responses/en/HassMediaPrevious.yaml
  sentences/en/media_player_HassMediaPrevious.yaml
  tests/en/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: en

#2251 A few small fixes
  intents.yaml
  script/intentfest/parse.py
  sentences/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2252 [EN] Add half an hour/minute for timers
  sentences/en/_common.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2253 [EN] Add "1/2" alongside "half"
  sentences/en/_common.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2256 [PT-BR] update media sentences
  sentences/pt-br/media_player_HassMediaNext.yaml
  sentences/pt-br/media_player_HassMediaPause.yaml
  sentences/pt-br/media_player_HassMediaUnpause.yaml
  sentences/pt-br/media_player_HassSetVolume.yaml
  tests/pt-br/media_player_HassMediaNext.yaml
  tests/pt-br/media_player_HassMediaPause.yaml
  tests/pt-br/media_player_HassMediaUnpause.yaml
  tests/pt-br/media_player_HassSetVolume.yaml
Labels: cla-signed

#2257 [EN] Don't require area to start a timer
  sentences/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#1853 update zh-hk translation for lock_hass, scene_hass, script_hass
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/lock_HassGetState.yaml
  sentences/zh-hk/lock_HassTurnOff.yaml
  sentences/zh-hk/lock_HassTurnOn.yaml
  sentences/zh-hk/scene_HassTurnOn.yaml
  sentences/zh-hk/script_HassTurnOn.yaml
  tests/zh-hk/_fixtures.yaml
  tests/zh-hk/lock_HassGetState.yaml
  tests/zh-hk/lock_HassTurnOff.yaml
  tests/zh-hk/lock_HassTurnOn.yaml
  tests/zh-hk/scene_HassTurnOn.yaml
  tests/zh-hk/script_HassTurnOn.yaml
Labels: cla-signed

#2258 Add zh-hk leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2259 [RU] Тimer improvements
  sentences/ru/homeassistant_HassStartTimer.yaml
  tests/ru/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: ru

#2261 [FR] Add delay command in french
  responses/fr/HassStartTimer.yaml
  sentences/fr/homeassistant_HassStartTimer.yaml
  tests/fr/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: fr

#2263 [EN] Clean up some English templates
  sentences/en/_common.yaml
  sentences/en/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: en

#2265 [ES] Timer halves & quarters, and HassMediaPrevious intent
  responses/es/HassMediaPrevious.yaml
  sentences/es/_common.yaml
  sentences/es/homeassistant_HassStartTimer.yaml
  sentences/es/media_player_HassMediaPrevious.yaml
  tests/es/homeassistant_HassStartTimer.yaml
  tests/es/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: es

#2264 [PT-BR] Media area
  sentences/pt-br/_common.yaml
  sentences/pt-br/media_player_HassMediaNext.yaml
  sentences/pt-br/media_player_HassMediaPause.yaml
  sentences/pt-br/media_player_HassMediaUnpause.yaml
  sentences/pt-br/media_player_HassSetVolume.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/media_player_HassMediaNext.yaml
  tests/pt-br/media_player_HassMediaPause.yaml
  tests/pt-br/media_player_HassMediaUnpause.yaml
  tests/pt-br/media_player_HassSetVolume.yaml
Labels: cla-signed
