Repository OHF-Voice/intents, pull requests merged in 2024-02, with the labels that each got.

#1905 [HU] Correction of responses.
  responses/hu/HassClimateSetTemperature.yaml
  responses/hu/HassTurnOff.yaml
  responses/hu/HassTurnOn.yaml
  sentences/hu/_common.yaml
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/lock_HassTurnOff.yaml
  sentences/hu/lock_HassTurnOn.yaml
  tests/hu/climate_HassClimateSetTemperature.yaml
  tests/hu/cover_HassTurnOff.yaml
  tests/hu/cover_HassTurnOn.yaml
  tests/hu/fan_HassTurnOff.yaml
  tests/hu/fan_HassTurnOn.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
  tests/hu/lock_HassTurnOff.yaml
  tests/hu/lock_HassTurnOn.yaml
  tests/hu/scene_HassTurnOn.yaml
  tests/hu/script_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#1906 Migrate errors
  script/intentfest/add_language.py
  script/intentfest/validate.py
  sentences/af/_common.yaml
  sentences/ar/_common.yaml
  sentences/bg/_common.yaml
  sentences/bn/_common.yaml
  sentences/ca/_common.yaml
  sentences/cs/_common.yaml
  sentences/da/_common.yaml
  sentences/de-CH/_common.yaml
  sentences/de/_common.yaml
  sentences/el/_common.yaml
  sentences/en/_common.yaml
  sentences/es/_common.yaml
  sentences/et/_common.yaml
  sentences/eu/_common.yaml
  sentences/fa/_common.yaml
  sentences/fi/_common.yaml
  sentences/fr-CA/_common.yaml
  sentences/fr/_common.yaml
  sentences/gl/_common.yaml
  sentences/gu/_common.yaml
  sentences/he/_common.yaml
  sentences/hi/_common.yaml
  sentences/hr/_common.yaml
  sentences/hu/_common.yaml
  sentences/id/_common.yaml
  sentences/is/_common.yaml
  sentences/it/_common.yaml
  sentences/ka/_common.yaml
  sentences/kn/_common.yaml
  sentences/ko/_common.yaml
  sentences/lb/_common.yaml
  sentences/lt/_common.yaml
  sentences/lv/_common.yaml
  sentences/ml/_common.yaml
  sentences/mn/_common.yaml
  sentences/ms/_common.yaml
  sentences/nb/_common.yaml
  sentences/nl/_common.yaml
  sentences/pl/_common.yaml
  sentences/pt-br/_common.yaml
  sentences/pt/_common.yaml
  sentences/ro/_common.yaml
  sentences/ru/_common.yaml
  sentences/sk/_common.yaml
  sentences/sl/_common.yaml
  sentences/sr/_common.yaml
  sentences/sv/_common.yaml
  sentences/sw/_common.yaml
  sentences/te/_common.yaml
  sentences/tr/_common.yaml
  sentences/uk/_common.yaml
  sentences/ur/_common.yaml
  sentences/vi/_common.yaml
  sentences/zh-cn/_common.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-tw/_common.yaml
Labels: cla-signed, lang: de, lang: he, lang: en, lang: fr, lang: hu, lang: ca, lang: es, lang: hr, lang: cs, lang: el, lang: it, lang: ar, lang: da, lang: ka, lang: bg, lang: fa, lang: et, lang: fi, lang: hi, lang: is, lang: gl, lang: id, lang: bn, lang: de-ch, lang: gu, lang: eu, lang: af

#1912 [RO] Migrate errors
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#1913 [HU] Migrate errors
  sentences/hu/_common.yaml
Labels: cla-signed, lang: hu

#1914 [HU] second language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1915 [RO] Context area aware intents
  sentences/ro/cover_HassTurnOff.yaml
  sentences/ro/cover_HassTurnOn.yaml
  sentences/ro/fan_HassTurnOff.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/light_HassLightSet.yaml
  tests/ro/cover_HassTurnOff.yaml
  tests/ro/cover_HassTurnOn.yaml
  tests/ro/fan_HassTurnOff.yaml
  tests/ro/fan_HassTurnOn.yaml
  tests/ro/light_HassLightSet.yaml
Labels: cla-signed, lang: ro

#1916 [hu]error fix
  sentences/hu/scene_HassTurnOn.yaml
  sentences/hu/script_HassTurnOn.yaml
  tests/hu/scene_HassTurnOn.yaml
  tests/hu/script_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#1919 [NL] Add missing new error responses
  sentences/nl/_common.yaml
Labels: cla-signed, lang: nl

#1909 [FR] New translation update
  sentences/fr/_common.yaml
Labels: cla-signed, lang: fr, cla-error

#1918 [FI] Added new error messages
  sentences/fi/_common.yaml
Labels: cla-signed, lang: fi

#1923 [SK] Fix response for get climate
  responses/sk/HassClimateGetTemperature.yaml
  tests/sk/_fixtures.yaml
  tests/sk/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sk

#1922 [de] Add missing errors
  sentences/de/_common.yaml
Labels: cla-signed, lang: de

#1924 [SL] added sensors - battery, CO2, CO, current
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1925 [DE] Add binary sensor connectivity
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1927 [DE] use more expansion rules
  sentences/de/binary_sensor_HassGetState.yaml
  sentences/de/climate_HassClimateGetTemperature.yaml
  sentences/de/cover_HassGetState.yaml
  sentences/de/homeassistant_HassGetState.yaml
  sentences/de/lock_HassGetState.yaml
Labels: cla-signed, lang: de

#1928 [DE] Add binary sensor problem
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1458 [DE] Add Support for further German Sentences for the Light Domain
  sentences/de/_common.yaml
  sentences/de/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
  tests/de/light_HassTurnOff.yaml
  tests/de/light_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1926 [DE] Add binary sensor safety
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1932 [hu]Improving lamp handling
  sentences/hu/light_HassTurnOff.yaml
  sentences/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#1935 Translating new error messages from #1906 to Spanish
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#1503 Update _common.yaml
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#1936 Improve light control in french
  sentences/fr/light_HassTurnOff.yaml
  sentences/fr/light_HassTurnOn.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1937 Add pt-br leaders
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#1938 [SV] Translating new error messages from #1906 to Swedish and added missing colors
  sentences/sv/_common.yaml
Labels: cla-signed, lang: sv

#1707 [SV] Add Nevermind command to Swedish
  sentences/sv/homeassistant_HassNevermind.yaml
  tests/sv/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sv

#1783 [PT-BR] Add support for HassListAddItem
  responses/pt-br/HassGetWeather.yaml
  responses/pt-br/HassListAddItem.yaml
  responses/pt-br/HassShoppingListAddItem.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassNevermind.yaml
  sentences/pt-br/homeassistant_HassTurnOff.yaml
  sentences/pt-br/shopping_list_HassShoppingListAddItem.yaml
  sentences/pt-br/todo_HassListAddItem.yaml
  sentences/pt-br/weather_HassGetWeather.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassNevermind.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/shopping_list_HassShoppingListAddItem.yaml
  tests/pt-br/todo_HassListAddItem.yaml
  tests/pt-br/weather_HassGetWeather.yaml
Labels: cla-signed

#1942 [uk] Fixed typo in HassClimateGetTemperature
  sentences/uk/climate_HassClimateGetTemperature.yaml
  tests/uk/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: uk

#1946 [hu]Enabling the words 'ki/be' for switching operations
  sentences/hu/_common.yaml
  sentences/hu/person_HassGetState.yaml
  tests/hu/light_HassTurnOff.yaml
  tests/hu/light_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#1947 [de-CH] add new error responses
  sentences/de-CH/_common.yaml
Labels: cla-signed, lang: de-ch

#1882 add HassNeverMind to Bulgarian
  sentences/bg/homeassistant_HassNevermind.yaml
  tests/bg/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: bg

#1949 [SV] Added all binary sensor states from the english _common.yaml
  sentences/sv/_common.yaml
Labels: cla-signed, lang: sv

#1951 Fixes for FI HassTurnOn_Off
  responses/fi/HassTurnOff.yaml
  responses/fi/HassTurnOn.yaml
  sentences/fi/homeassistant_HassTurnOff.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  tests/fi/_fixtures.yaml
  tests/fi/homeassistant_HassTurnOff.yaml
  tests/fi/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#1952 [RU] Update _common.yaml in Russian
  sentences/ru/_common.yaml
Labels: cla-signed, lang: ru

#1954 [RU] Update _common.yaml - added cover_class "damper"
  sentences/ru/_common.yaml
Labels: cla-signed, lang: ru

#1956 [SL] error responses, sensors for data rate, data size and date added
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#1950 [uk] Added new errors
  sentences/uk/_common.yaml
Labels: cla-signed, lang: uk

#1931 [DE] Add binary sensor light
  sentences/de/_common.yaml
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#1967 Add new intents for cover, valve, vacuum, media player
  intents.yaml
  responses/en/HassMediaNext.yaml
  responses/en/HassMediaPause.yaml
  responses/en/HassMediaUnpause.yaml
  responses/en/HassSetPosition.yaml
  responses/en/HassSetVolume.yaml
  responses/en/HassTurnOff.yaml
  responses/en/HassTurnOn.yaml
  responses/en/HassVacuumReturnToBase.yaml
  responses/en/HassVacuumStart.yaml
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassSetPosition.yaml
  sentences/en/homeassistant_HassTurnOn.yaml
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  sentences/en/vacuum_HassVacuumReturnToBase.yaml
  sentences/en/vacuum_HassVacuumStart.yaml
  sentences/en/valve_HassTurnOff.yaml
  sentences/en/valve_HassTurnOn.yaml
  tests/en/_fixtures.yaml
  tests/en/homeassistant_HassSetPosition.yaml
  tests/en/media_player_HassMediaNext.yaml
  tests/en/media_player_HassMediaPause.yaml
  tests/en/media_player_HassMediaUnpause.yaml
  tests/en/media_player_HassSetVolume.yaml
  tests/en/vacuum_HassVacuumReturnToBase.yaml
  tests/en/vacuum_HassVacuumStart.yaml
  tests/en/valve_HassTurnOff.yaml
  tests/en/valve_HassTurnOn.yaml
Labels: cla-signed, lang: en

#1968 [ES] Adding new intents from #1967
  responses/es/HassMediaNext.yaml
  responses/es/HassMediaPause.yaml
  responses/es/HassMediaUnpause.yaml
  responses/es/HassSetPosition.yaml
  responses/es/HassSetVolume.yaml
  responses/es/HassTurnOff.yaml
  responses/es/HassTurnOn.yaml
  responses/es/HassVacuumReturnToBase.yaml
  responses/es/HassVacuumStart.yaml
  sentences/es/_common.yaml
  sentences/es/homeassistant_HassSetPosition.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/media_player_HassMediaNext.yaml
  sentences/es/media_player_HassMediaPause.yaml
  sentences/es/media_player_HassMediaUnpause.yaml
  sentences/es/media_player_HassSetVolume.yaml
  sentences/es/vacuum_HassVacuumReturnToBase.yaml
  sentences/es/vacuum_HassVacuumStart.yaml
  sentences/es/valve_HassTurnOff.yaml
  sentences/es/valve_HassTurnOn.yaml
  tests/es/_fixtures.yaml
  tests/es/homeassistant_HassSetPosition.yaml
  tests/es/media_player_HassMediaNext.yaml
  tests/es/media_player_HassMediaPause.yaml
  tests/es/media_player_HassMediaUnpause.yaml
  tests/es/media_player_HassSetVolume.yaml
  tests/es/vacuum_HassVacuumReturnToBase.yaml
  tests/es/vacuum_HassVacuumStart.yaml
  tests/es/valve_HassTurnOff.yaml
  tests/es/valve_HassTurnOn.yaml
Labels: cla-signed, lang: es

#1972 [HU] Add new intents for cover, valve, vacuum, media player
  responses/hu/HassMediaNext.yaml
  responses/hu/HassMediaPause.yaml
  responses/hu/HassMediaUnpause.yaml
  responses/hu/HassSetPosition.yaml
  responses/hu/HassSetVolume.yaml
  responses/hu/HassTurnOff.yaml
  responses/hu/HassTurnOn.yaml
  responses/hu/HassVacuumReturnToBase.yaml
  responses/hu/HassVacuumStart.yaml
  sentences/hu/_common.yaml
  sentences/hu/homeassistant_HassSetPosition.yaml
  sentences/hu/homeassistant_HassTurnOn.yaml
  sentences/hu/lock_HassTurnOn.yaml
  sentences/hu/media_player_HassMediaNext.yaml
  sentences/hu/media_player_HassMediaPause.yaml
  sentences/hu/media_player_HassMediaUnpause.yaml
  sentences/hu/media_player_HassSetVolume.yaml
  sentences/hu/vacuum_HassVacuumReturnToBase.yaml
  sentences/hu/vacuum_HassVacuumStart.yaml
  sentences/hu/valve_HassTurnOff.yaml
  sentences/hu/valve_HassTurnOn.yaml
  tests/hu/_fixtures.yaml
  tests/hu/homeassistant_HassSetPosition.yaml
  tests/hu/media_player_HassMediaNext.yaml
  tests/hu/media_player_HassMediaPause.yaml
  tests/hu/media_player_HassMediaUnpause.yaml
  tests/hu/media_player_HassSetVolume.yaml
  tests/hu/vacuum_HassVacuumReturnToBase.yaml
  tests/hu/vacuum_HassVacuumStart.yaml
  tests/hu/valve_HassTurnOff.yaml
  tests/hu/valve_HassTurnOn.yaml
Labels: cla-signed, lang: hu

#1953 [DA] Adds missing scene_HassTurnOn for Danish
  responses/da/HassTurnOn.yaml
  sentences/da/_common.yaml
  sentences/da/scene_HassTurnOn.yaml
  tests/da/_fixtures.yaml
  tests/da/scene_HassTurnOn.yaml
Labels: cla-signed, lang: en, lang: da

#1984 [PT-BR] Add new intents for cover, valve, vacuum, media player #1967
  responses/pt-br/HassMediaNext.yaml
  responses/pt-br/HassMediaPause.yaml
  responses/pt-br/HassMediaUnpause.yaml
  responses/pt-br/HassSetPosition.yaml
  responses/pt-br/HassSetVolume.yaml
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  responses/pt-br/HassVacuumReturnToBase.yaml
  responses/pt-br/HassVacuumStart.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/homeassistant_HassSetPosition.yaml
  sentences/pt-br/homeassistant_HassTurnOn.yaml
  sentences/pt-br/media_player_HassMediaNext.yaml
  sentences/pt-br/media_player_HassMediaPause.yaml
  sentences/pt-br/media_player_HassMediaUnpause.yaml
  sentences/pt-br/media_player_HassSetVolume.yaml
  sentences/pt-br/vacuum_HassVacuumReturnToBase.yaml
  sentences/pt-br/vacuum_HassVacuumStart.yaml
  sentences/pt-br/valve_HassTurnOff.yaml
  sentences/pt-br/valve_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/homeassistant_HassSetPosition.yaml
  tests/pt-br/media_player_HassMediaNext.yaml
  tests/pt-br/media_player_HassMediaPause.yaml
  tests/pt-br/media_player_HassMediaUnpause.yaml
  tests/pt-br/media_player_HassSetVolume.yaml
  tests/pt-br/vacuum_HassVacuumReturnToBase.yaml
  tests/pt-br/vacuum_HassVacuumStart.yaml
  tests/pt-br/valve_HassTurnOff.yaml
  tests/pt-br/valve_HassTurnOn.yaml
Labels: cla-signed

#1983 [CS] Add singular for area light
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1977 [PT-BR] New sentences and some non-translated sentences translations …
  responses/pt-br/HassClimateGetTemperature.yaml
  responses/pt-br/HassClimateSetTemperature.yaml
  responses/pt-br/HassLightSet.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/climate_HassClimateGetTemperature.yaml
  sentences/pt-br/climate_HassClimateSetTemperature.yaml
  sentences/pt-br/cover_HassTurnOff.yaml
  sentences/pt-br/cover_HassTurnOn.yaml
  sentences/pt-br/fan_HassTurnOff.yaml
  sentences/pt-br/fan_HassTurnOn.yaml
  sentences/pt-br/homeassistant_HassNevermind.yaml
  sentences/pt-br/light_HassLightSet.yaml
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
  tests/pt-br/_fixtures.yaml
  tests/pt-br/climate_HassClimateGetTemperature.yaml
  tests/pt-br/climate_HassClimateSetTemperature.yaml
  tests/pt-br/cover_HassTurnOff.yaml
  tests/pt-br/cover_HassTurnOn.yaml
  tests/pt-br/fan_HassTurnOff.yaml
  tests/pt-br/fan_HassTurnOn.yaml
  tests/pt-br/homeassistant_HassNevermind.yaml
  tests/pt-br/homeassistant_HassTurnOff.yaml
  tests/pt-br/homeassistant_HassTurnOn.yaml
  tests/pt-br/light_HassLightSet.yaml
  tests/pt-br/light_HassTurnOff.yaml
  tests/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#1988 [hu] bugfix
  sentences/hu/homeassistant_HassSetPosition.yaml
  sentences/hu/media_player_HassSetVolume.yaml
  tests/hu/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: hu

#1978 [UK] Add new intents for cover, valve, vacuum, media player
  responses/uk/HassMediaNext.yaml
  responses/uk/HassMediaPause.yaml
  responses/uk/HassMediaUnpause.yaml
  responses/uk/HassSetPosition.yaml
  responses/uk/HassSetVolume.yaml
  responses/uk/HassTurnOff.yaml
  responses/uk/HassTurnOn.yaml
  responses/uk/HassVacuumReturnToBase.yaml
  responses/uk/HassVacuumStart.yaml
  sentences/uk/_common.yaml
  sentences/uk/homeassistant_HassSetPosition.yaml
  sentences/uk/homeassistant_HassTurnOff.yaml
  sentences/uk/homeassistant_HassTurnOn.yaml
  sentences/uk/media_player_HassMediaNext.yaml
  sentences/uk/media_player_HassMediaPause.yaml
  sentences/uk/media_player_HassMediaUnpause.yaml
  sentences/uk/media_player_HassSetVolume.yaml
  sentences/uk/vacuum_HassVacuumReturnToBase.yaml
  sentences/uk/vacuum_HassVacuumStart.yaml
  sentences/uk/valve_HassTurnOff.yaml
  sentences/uk/valve_HassTurnOn.yaml
  tests/uk/_fixtures.yaml
  tests/uk/homeassistant_HassSetPosition.yaml
  tests/uk/homeassistant_HassTurnOff.yaml
  tests/uk/homeassistant_HassTurnOn.yaml
  tests/uk/media_player_HassMediaNext.yaml
  tests/uk/media_player_HassMediaPause.yaml
  tests/uk/media_player_HassMediaUnpause.yaml
  tests/uk/media_player_HassSetVolume.yaml
  tests/uk/vacuum_HassVacuumReturnToBase.yaml
  tests/uk/vacuum_HassVacuumStart.yaml
  tests/uk/valve_HassTurnOff.yaml
  tests/uk/valve_HassTurnOn.yaml
Labels: cla-signed, lang: uk

#1970 [DE] Add new intents for cover, valve, vacuum, media player
  responses/de/HassMediaNext.yaml
  responses/de/HassMediaPause.yaml
  responses/de/HassMediaUnpause.yaml
  responses/de/HassSetPosition.yaml
  responses/de/HassSetVolume.yaml
  responses/de/HassTurnOff.yaml
  responses/de/HassTurnOn.yaml
  responses/de/HassVacuumReturnToBase.yaml
  responses/de/HassVacuumStart.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassSetPosition.yaml
  sentences/de/homeassistant_HassTurnOn.yaml
  sentences/de/light_HassLightSet.yaml
  sentences/de/media_player_HassMediaNext.yaml
  sentences/de/media_player_HassMediaPause.yaml
  sentences/de/media_player_HassMediaUnpause.yaml
  sentences/de/media_player_HassSetVolume.yaml
  sentences/de/vacuum_HassVacuumReturnToBase.yaml
  sentences/de/vacuum_HassVacuumStart.yaml
  sentences/de/valve_HassTurnOff.yaml
  sentences/de/valve_HassTurnOn.yaml
  tests/de/_fixtures.yaml
  tests/de/homeassistant_HassSetPosition.yaml
  tests/de/media_player_HassMediaNext.yaml
  tests/de/media_player_HassMediaPause.yaml
  tests/de/media_player_HassMediaUnpause.yaml
  tests/de/media_player_HassSetVolume.yaml
  tests/de/vacuum_HassVacuumReturnToBase.yaml
  tests/de/vacuum_HassVacuumStart.yaml
  tests/de/valve_HassTurnOff.yaml
  tests/de/valve_HassTurnOn.yaml
Labels: cla-signed, lang: de

#1991 [DE] Implement additions from #1970
  sentences/de/_common.yaml
  tests/de/homeassistant_HassSetPosition.yaml
  tests/de/light_HassLightSet.yaml
  tests/de/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: de

#1995 [CS] Add sentence for turning on/off lights in the satelite area. Added expansion rule for lights in plural/singular
  responses/cs/HassTurnOn.yaml
  sentences/cs/_common.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#1994 [RU] add intents for media_player
  responses/ru/HassMediaNext.yaml
  responses/ru/HassMediaPause.yaml
  responses/ru/HassMediaUnpause.yaml
  responses/ru/HassSetVolume.yaml
  sentences/ru/_common.yaml
  sentences/ru/media_player_HassMediaNext.yaml
  sentences/ru/media_player_HassMediaPause.yaml
  sentences/ru/media_player_HassMediaUnpause.yaml
  sentences/ru/media_player_HassSetVolume.yaml
  tests/ru/_fixtures.yaml
  tests/ru/media_player_HassMediaNext.yaml
  tests/ru/media_player_HassMediaPause.yaml
  tests/ru/media_player_HassMediaUnpause.yaml
  tests/ru/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: ru

#1989 [RO] Fixes and improvements
  sentences/ro/_common.yaml
  sentences/ro/binary_sensor_HassGetState.yaml
  sentences/ro/climate_HassClimateGetTemperature.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
  sentences/ro/cover_HassGetState.yaml
  sentences/ro/cover_HassTurnOff.yaml
  sentences/ro/cover_HassTurnOn.yaml
  sentences/ro/fan_HassTurnOff.yaml
  sentences/ro/fan_HassTurnOn.yaml
  sentences/ro/homeassistant_HassGetState.yaml
  sentences/ro/homeassistant_HassNevermind.yaml
  sentences/ro/homeassistant_HassSetPosition.yaml
  sentences/ro/homeassistant_HassTurnOff.yaml
  sentences/ro/homeassistant_HassTurnOn.yaml
  sentences/ro/light_HassGetState.yaml
  sentences/ro/light_HassLightSet.yaml
  sentences/ro/light_HassTurnOff.yaml
  sentences/ro/light_HassTurnOn.yaml
  sentences/ro/lock_HassGetState.yaml
  sentences/ro/media_player_HassMediaPause.yaml
  sentences/ro/media_player_HassMediaUnpause.yaml
  sentences/ro/media_player_HassSetVolume.yaml
  sentences/ro/scene_HassTurnOn.yaml
  sentences/ro/script_HassTurnOn.yaml
  sentences/ro/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: ro

#1998 [PT-BR] expansion_rules adjustment e new errors
  sentences/pt-br/_common.yaml
Labels: cla-signed

#1985 [DE] Add a few more variations to shopping list add item
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
  sentences/de/todo_HassListAddItem.yaml
  tests/de/shopping_list_HassShoppingListAddItem.yaml
  tests/de/todo_HassListAddItem.yaml
Labels: cla-signed, lang: de

#1973 [Fr] Add new intents for cover, valve, vacuum, media player
  responses/fr/HassMediaNext.yaml
  responses/fr/HassMediaPause.yaml
  responses/fr/HassMediaUnpause.yaml
  responses/fr/HassSetPosition.yaml
  responses/fr/HassSetVolume.yaml
  responses/fr/HassTurnOff.yaml
  responses/fr/HassTurnOn.yaml
  responses/fr/HassVacuumReturnToBase.yaml
  responses/fr/HassVacuumStart.yaml
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassSetPosition.yaml
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
  sentences/fr/media_player_HassMediaNext.yaml
  sentences/fr/media_player_HassMediaPause.yaml
  sentences/fr/media_player_HassMediaUnpause.yaml
  sentences/fr/media_player_HassSetVolume.yaml
  sentences/fr/vacuum_HassVacuumReturnToBase.yaml
  sentences/fr/vacuum_HassVacuumStart.yaml
  sentences/fr/valve_HassTurnOff.yaml
  sentences/fr/valve_HassTurnOn.yaml
  tests/fr/_fixtures.yaml
  tests/fr/homeassistant_HassSetPosition.yaml
  tests/fr/media_player_HassMediaNext.yaml
  tests/fr/media_player_HassMediaPause.yaml
  tests/fr/media_player_HassMediaUnpause.yaml
  tests/fr/media_player_HassSetVolume.yaml
  tests/fr/vacuum_HassVacuumReturnToBase.yaml
  tests/fr/vacuum_HassVacuumStart.yaml
  tests/fr/valve_HassTurnOff.yaml
  tests/fr/valve_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#2003 Test all YAML sentence files
  tests/ro/light_HassGetState.yaml
  tests/test_language_sentences.py
Labels: cla-signed, lang: ro

#2004 Allow other files in intent foler too
  tests/test_language_intents.py
Labels: cla-signed

#2008 [ES] Add another sentence to turn on/off all lights in an area
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#2007 [ES] Improve success response for turning on a light
  responses/es/HassTurnOn.yaml
Labels: cla-signed, lang: es

#2006 [ES] Add new sentence to set a light to a specific brightness
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#1986 Suggested custom sentences for media players
  sentences/en/media_player_HassMediaNext.yaml
  sentences/en/media_player_HassMediaPause.yaml
  sentences/en/media_player_HassMediaUnpause.yaml
  sentences/en/media_player_HassSetVolume.yaml
  tests/en/media_player_HassMediaNext.yaml
  tests/en/media_player_HassMediaPause.yaml
  tests/en/media_player_HassMediaUnpause.yaml
  tests/en/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: en

#2009 [es] Removing unneeded article. Correcting answers for domain light
  responses/es/HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOff.yaml
  sentences/es/homeassistant_HassTurnOn.yaml
  sentences/es/light_HassTurnOff.yaml
  sentences/es/light_HassTurnOn.yaml
  tests/es/homeassistant_HassTurnOff.yaml
  tests/es/homeassistant_HassTurnOn.yaml
  tests/es/light_HassTurnOff.yaml
  tests/es/light_HassTurnOn.yaml
Labels: cla-signed, lang: es

#2015 [RO] Fix tests
  tests/ro/light_HassGetState.yaml
Labels: cla-signed, lang: ro

#2005 [FR] Add excluded domains in homeassistant_HassTurnOn/Off
  sentences/fr/homeassistant_HassTurnOff.yaml
  sentences/fr/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#1990 [FI] Add new intents for cover, valve, vacuum, media_player
  responses/fi/HassMediaNext.yaml
  responses/fi/HassMediaPause.yaml
  responses/fi/HassMediaUnpause.yaml
  responses/fi/HassSetPosition.yaml
  responses/fi/HassSetVolume.yaml
  responses/fi/HassTurnOff.yaml
  responses/fi/HassTurnOn.yaml
  responses/fi/HassVacuumReturnToBase.yaml
  responses/fi/HassVacuumStart.yaml
  sentences/fi/_common.yaml
  sentences/fi/homeassistant_HassSetPosition.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  sentences/fi/media_player_HassMediaNext.yaml
  sentences/fi/media_player_HassMediaPause.yaml
  sentences/fi/media_player_HassMediaUnpause.yaml
  sentences/fi/media_player_HassSetVolume.yaml
  sentences/fi/vacuum_HassVacuumReturnToBase.yaml
  sentences/fi/vacuum_HassVacuumStart.yaml
  sentences/fi/valve_HassTurnOff.yaml
  sentences/fi/valve_HassTurnOn.yaml
  tests/fi/_fixtures.yaml
  tests/fi/homeassistant_HassSetPosition.yaml
  tests/fi/media_player_HassMediaNext.yaml
  tests/fi/media_player_HassMediaPause.yaml
  tests/fi/media_player_HassMediaUnpause.yaml
  tests/fi/media_player_HassSetVolume.yaml
  tests/fi/vacuum_HassVacuumReturnToBase.yaml
  tests/fi/vacuum_HassVacuumStart.yaml
  tests/fi/valve_HassTurnOff.yaml
  tests/fi/valve_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#1997 [CS] Add person state
  responses/cs/HassGetState.yaml
  sentences/cs/_common.yaml
  sentences/cs/person_HassGetState.yaml
  tests/cs/_fixtures.yaml
  tests/cs/person_HassGetState.yaml
Labels: cla-signed, lang: cs
