Repository OHF-Voice/intents, pull requests merged in 2024-09, with the labels that each got.

#2338 [BG] Added timers
  responses/bg/HassCancelTimer.yaml
  responses/bg/HassDecreaseTimer.yaml
  responses/bg/HassIncreaseTimer.yaml
  responses/bg/HassPauseTimer.yaml
  responses/bg/HassStartTimer.yaml
  responses/bg/HassTimerStatus.yaml
  responses/bg/HassUnpauseTimer.yaml
  sentences/bg/_common.yaml
  sentences/bg/homeassistant_HassCancelTimer.yaml
  sentences/bg/homeassistant_HassDecreaseTimer.yaml
  sentences/bg/homeassistant_HassIncreaseTimer.yaml
  sentences/bg/homeassistant_HassPauseTimer.yaml
  sentences/bg/homeassistant_HassStartTimer.yaml
  sentences/bg/homeassistant_HassTimerStatus.yaml
  sentences/bg/homeassistant_HassUnpauseTimer.yaml
  tests/bg/_fixtures.yaml
  tests/bg/homeassistant_HassCancelTimer.yaml
  tests/bg/homeassistant_HassDecreaseTimer.yaml
  tests/bg/homeassistant_HassIncreaseTimer.yaml
  tests/bg/homeassistant_HassPauseTimer.yaml
  tests/bg/homeassistant_HassStartTimer.yaml
  tests/bg/homeassistant_HassTimerStatus.yaml
  tests/bg/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: bg

#2387 [SL] climate_HassClimateGetTemperature added sentece and tests
  sentences/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sl

#2357 [sv] Add timer intents
  responses/sv/HassCancelTimer.yaml
  responses/sv/HassDecreaseTimer.yaml
  responses/sv/HassIncreaseTimer.yaml
  responses/sv/HassPauseTimer.yaml
  responses/sv/HassStartTimer.yaml
  responses/sv/HassTimerStatus.yaml
  responses/sv/HassUnpauseTimer.yaml
  sentences/sv/_common.yaml
  sentences/sv/homeassistant_HassCancelTimer.yaml
  sentences/sv/homeassistant_HassDecreaseTimer.yaml
  sentences/sv/homeassistant_HassIncreaseTimer.yaml
  sentences/sv/homeassistant_HassPauseTimer.yaml
  sentences/sv/homeassistant_HassStartTimer.yaml
  sentences/sv/homeassistant_HassTimerStatus.yaml
  sentences/sv/homeassistant_HassUnpauseTimer.yaml
  tests/sv/_fixtures.yaml
  tests/sv/homeassistant_HassCancelTimer.yaml
  tests/sv/homeassistant_HassDecreaseTimer.yaml
  tests/sv/homeassistant_HassIncreaseTimer.yaml
  tests/sv/homeassistant_HassPauseTimer.yaml
  tests/sv/homeassistant_HassStartTimer.yaml
  tests/sv/homeassistant_HassTimerStatus.yaml
  tests/sv/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: sv

#2225 [EN] More common expansions
  sentences/en/_common.yaml
  sentences/en/cover_HassGetState.yaml
  tests/en/cover_HassGetState.yaml
Labels: cla-signed, lang: en

#2390 [NL] Remove area slot for start timer intent
  sentences/nl/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: nl

#2234 [LV] Add Latvian binary sensor get state translations
  responses/lv/HassGetState.yaml
  sentences/lv/_common.yaml
  sentences/lv/binary_sensor_HassGetState.yaml
  tests/lv/_fixtures.yaml
  tests/lv/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: lv

#2396 Add lv leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2398 [PL] - small bug fix with response date
  responses/pl/HassGetCurrentDate.yaml
Labels: cla-signed, lang: pl

#2399 [FR&EN] Floor Support for HassLightSet
  intents.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/fr/light_HassLightSet.yaml
  tests/en/light_HassLightSet.yaml
  tests/fr/light_HassLightSet.yaml
Labels: cla-signed, lang: en, lang: fr

#2403 Make linter happy about positional arguments
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed

#2404 [PL] - improved sentence for get window state
  sentences/pl/cover_HassGetState.yaml
Labels: cla-signed, lang: pl
