Repository OHF-Voice/intents, pull requests merged in 2024-03, with the labels that each got.

#2020 [de-CH] implement new features (including tests)
  responses/de-CH/HassClimateGetTemperature.yaml
  responses/de-CH/HassClimateSetTemperature.yaml
  responses/de-CH/HassGetState.yaml
  responses/de-CH/HassLightSet.yaml
  responses/de-CH/HassListAddItem.yaml
  responses/de-CH/HassMediaNext.yaml
  responses/de-CH/HassMediaPause.yaml
  responses/de-CH/HassMediaUnpause.yaml
  responses/de-CH/HassSetPosition.yaml
  responses/de-CH/HassSetVolume.yaml
  responses/de-CH/HassTurnOff.yaml
  responses/de-CH/HassTurnOn.yaml
  responses/de-CH/HassVacuumReturnToBase.yaml
  responses/de-CH/HassVacuumStart.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/homeassistant_HassSetPosition.yaml
  sentences/de-CH/media_player_HassMediaNext.yaml
  sentences/de-CH/media_player_HassMediaPause.yaml
  sentences/de-CH/media_player_HassMediaUnpause.yaml
  sentences/de-CH/media_player_HassSetVolume.yaml
  sentences/de-CH/person_HassGetState.yaml
  sentences/de-CH/vacuum_HassVacuumReturnToBase.yaml
  sentences/de-CH/vacuum_HassVacuumStart.yaml
  tests/de-CH/_fixtures.yaml
  tests/de-CH/climate_HassClimateSetTemperature.yaml
  tests/de-CH/cover_HassGetState.yaml
  tests/de-CH/cover_HassTurnOff.yaml
  tests/de-CH/cover_HassTurnOn.yaml
  tests/de-CH/fan_HassTurnOff.yaml
  tests/de-CH/fan_HassTurnOn.yaml
  tests/de-CH/homeassistant_HassSetPosition.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/de-CH/light_HassLightSet.yaml
  tests/de-CH/light_HassTurnOff.yaml
  tests/de-CH/light_HassTurnOn.yaml
  tests/de-CH/media_player_HassMediaNext.yaml
  tests/de-CH/media_player_HassMediaPause.yaml
  tests/de-CH/media_player_HassMediaUnpause.yaml
  tests/de-CH/media_player_HassSetVolume.yaml
  tests/de-CH/person_HassGetState.yaml
  tests/de-CH/todo_HassListAddItem.yaml
  tests/de-CH/vacuum_HassVacuumReturnToBase.yaml
  tests/de-CH/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: de-ch

#2021 [SL] added HassSetPosition and valve_HassTurnOn
  responses/sl/HassSetPosition.yaml
  responses/sl/HassTurnOn.yaml
  sentences/sl/_common.yaml
  sentences/sl/homeassistant_HassSetPosition.yaml
  sentences/sl/valve_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/homeassistant_HassSetPosition.yaml
  tests/sl/valve_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#2022 [CS] Add HassSetPosition and sensorHassGetState
  responses/cs/HassGetState.yaml
  responses/cs/HassGetWeather.yaml
  responses/cs/HassMediaNext.yaml
  responses/cs/HassMediaPause.yaml
  responses/cs/HassMediaUnpause.yaml
  responses/cs/HassSetPosition.yaml
  responses/cs/HassSetVolume.yaml
  sentences/cs/_common.yaml
  sentences/cs/binary_sensor_HassGetState.yaml
  sentences/cs/homeassistant_HassSetPosition.yaml
  sentences/cs/media_player_HassMediaNext.yaml
  sentences/cs/media_player_HassMediaPause.yaml
  sentences/cs/media_player_HassMediaUnpause.yaml
  sentences/cs/media_player_HassSetVolume.yaml
  sentences/cs/sensor_HassGetState.yaml
  sentences/cs/weather_HassGetWeather.yaml
  tests/cs/_fixtures.yaml
  tests/cs/binary_sensor_HassGetState.yaml
  tests/cs/climate_HassClimateGetTemperature.yaml
  tests/cs/homeassistant_HassSetPosition.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/media_player_HassMediaNext.yaml
  tests/cs/media_player_HassMediaPause.yaml
  tests/cs/media_player_HassMediaUnpause.yaml
  tests/cs/media_player_HassSetVolume.yaml
  tests/cs/sensor_HassGetState.yaml
  tests/cs/weather_HassGetWeather.yaml
Labels: cla-signed, lang: cs

#2024 [HU]valve_HassSetPosition.yaml and cover_HassSetPosition.yaml files should be split
  sentences/hu/_common.yaml
  sentences/hu/cover_HassSetPosition.yaml
  sentences/hu/valve_HassSetPosition.yaml
  tests/hu/_fixtures.yaml
  tests/hu/cover_HassGetState.yaml
  tests/hu/cover_HassSetPosition.yaml
  tests/hu/homeassistant_HassSetPosition.yaml
  tests/hu/valve_HassSetPosition.yaml
Labels: cla-signed, lang: hu

#2025 [SL] cover_HassGetState fix
  sentences/sl/cover_HassGetState.yaml
Labels: cla-signed, lang: sl

#2027 [NL] Avoid HassGetState getting triggered on only name
  sentences/nl/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: nl

#2028 [SK] Add vacuum intents
  responses/sk/HassVacuumReturnToBase.yaml
  responses/sk/HassVacuumStart.yaml
  sentences/sk/vacuum_HassVacuumReturnToBase.yaml
  sentences/sk/vacuum_HassVacuumStart.yaml
  tests/sk/_fixtures.yaml
  tests/sk/vacuum_HassVacuumReturnToBase.yaml
  tests/sk/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: sk

#2029 [SK] Add setPosition intents
  responses/sk/HassSetPosition.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassSetPosition.yaml
  tests/sk/_fixtures.yaml
  tests/sk/homeassistant_HassSetPosition.yaml
Labels: cla-signed, lang: sk

#2030 [SK] Add setVolume intent
  responses/sk/HassSetVolume.yaml
  sentences/sk/_common.yaml
  sentences/sk/media_player_HassSetVolume.yaml
  tests/sk/_fixtures.yaml
  tests/sk/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: sk

#2031 [SK] Add MediaNextUnPause
  responses/sk/HassMediaNext.yaml
  responses/sk/HassMediaPause.yaml
  responses/sk/HassMediaUnpause.yaml
  sentences/sk/media_player_HassMediaNext.yaml
  sentences/sk/media_player_HassMediaPause.yaml
  sentences/sk/media_player_HassMediaUnpause.yaml
  tests/sk/_fixtures.yaml
  tests/sk/media_player_HassMediaNext.yaml
  tests/sk/media_player_HassMediaPause.yaml
  tests/sk/media_player_HassMediaUnpause.yaml
Labels: cla-signed, lang: sk

#1945 [NL] Add support for the word dim to set brightness
  sentences/nl/light_HassLightSet.yaml
  tests/nl/light_HassLightSet.yaml
Labels: cla-signed, lang: nl

#1993 [PL] Add basic weather sentences
  responses/pl/HassGetWeather.yaml
  sentences/pl/_common.yaml
  sentences/pl/weather_HassGetWeather.yaml
  tests/pl/_fixtures.yaml
  tests/pl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: de, lang: pl, lang: cs

#2037 [hu] more correct error message + weather correction
  responses/hu/HassGetWeather.yaml
  sentences/hu/_common.yaml
  tests/hu/weather_HassGetWeather.yaml
Labels: cla-signed, lang: hu

#2038 [hu] weather update
  responses/hu/HassGetWeather.yaml
Labels: cla-signed, lang: hu

#2016 [FI] better HassTurnOn and HassTurnOff
  sentences/fi/homeassistant_HassTurnOff.yaml
  sentences/fi/homeassistant_HassTurnOn.yaml
  sentences/fi/light_HassTurnOff.yaml
  tests/fi/_fixtures.yaml
  tests/fi/homeassistant_HassTurnOff.yaml
  tests/fi/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: fi

#2033 [FR] Add variety to media player sentences
  sentences/fr/media_player_HassMediaNext.yaml
  sentences/fr/media_player_HassMediaPause.yaml
  sentences/fr/media_player_HassMediaUnpause.yaml
  sentences/fr/media_player_HassSetVolume.yaml
  tests/fr/media_player_HassMediaPause.yaml
  tests/fr/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: fr

#2040 [SL] added media_player sentences
  responses/sl/HassMediaNext.yaml
  responses/sl/HassMediaPause.yaml
  responses/sl/HassMediaUnpause.yaml
  responses/sl/HassSetVolume.yaml
  sentences/sl/_common.yaml
  sentences/sl/media_player_HassMediaNext.yaml
  sentences/sl/media_player_HassMediaPause.yaml
  sentences/sl/media_player_HassMediaUnpause.yaml
  sentences/sl/media_player_HassSetVolume.yaml
  tests/sl/_fixtures.yaml
  tests/sl/media_player_HassMediaNext.yaml
  tests/sl/media_player_HassMediaPause.yaml
  tests/sl/media_player_HassMediaUnpause.yaml
  tests/sl/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: sl

#2041 [NL] Add Vacuum intents
  responses/nl/HassVacuumReturnToBase.yaml
  responses/nl/HassVacuumStart.yaml
  sentences/nl/vacuum_HassVacuumReturnToBase.yaml
  sentences/nl/vacuum_HassVacuumStart.yaml
  tests/nl/vacuum_HassVacuumReturnToBase.yaml
  tests/nl/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: nl

#2039 [NL] Add intents for valve en set position
  responses/nl/HassSetPosition.yaml
  responses/nl/HassTurnOff.yaml
  responses/nl/HassTurnOn.yaml
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  sentences/nl/cover_HassTurnOn.yaml
  sentences/nl/homeassistant_HassSetPosition.yaml
  sentences/nl/light_HassLightSet.yaml
  sentences/nl/valve_HassTurnOff.yaml
  sentences/nl/valve_HassTurnOn.yaml
  tests/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOn.yaml
  tests/nl/homeassistant_HassSetPosition.yaml
  tests/nl/valve_HassTurnOff.yaml
  tests/nl/valve_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#2018 [FR] Cleaning of scene/script_HassTurnOn
  responses/fr/HassTurnOn.yaml
  sentences/fr/_common.yaml
  sentences/fr/scene_HassTurnOn.yaml
  sentences/fr/script_HassTurnOn.yaml
  tests/fr/scene_HassTurnOn.yaml
  tests/fr/script_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#2036 [CS] add and fix intents in the satellite area
  sentences/cs/_common.yaml
  sentences/cs/cover_HassTurnOff.yaml
  sentences/cs/cover_HassTurnOn.yaml
  sentences/cs/homeassistant_HassNevermind.yaml
  sentences/cs/homeassistant_HassSetPosition.yaml
  sentences/cs/light_HassLightSet.yaml
  sentences/cs/light_HassTurnOff.yaml
  sentences/cs/light_HassTurnOn.yaml
  tests/cs/cover_HassTurnOff.yaml
  tests/cs/cover_HassTurnOn.yaml
  tests/cs/homeassistant_HassNevermind.yaml
  tests/cs/homeassistant_HassSetPosition.yaml
  tests/cs/light_HassLightSet.yaml
  tests/cs/light_HassTurnOff.yaml
  tests/cs/light_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#2043 [SL] added vacuum_Hass sentences
  responses/sl/HassVacuumReturnToBase.yaml
  sentences/sl/vacuum_HassVacuumReturnToBase.yaml
  tests/sl/_fixtures.yaml
  tests/sl/vacuum_HassVacuumReturnToBase.yaml
Labels: cla-signed, lang: sl

#2044 [SL] added vacuum_HassStart sentence
  responses/sl/HassVacuumStart.yaml
  sentences/sl/vacuum_HassVacuumStart.yaml
  tests/sl/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: sl

#2046 [SL] cover_HassTurnOn and cover_HassTurnOff fixes
  sentences/sl/_common.yaml
  sentences/sl/cover_HassTurnOff.yaml
  sentences/sl/cover_HassTurnOn.yaml
  tests/sl/_fixtures.yaml
  tests/sl/cover_HassTurnOff.yaml
  tests/sl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#2045 [EN] Separate HassSetPosition into domains
  sentences/en/_common.yaml
  sentences/en/cover_HassSetPosition.yaml
  sentences/en/homeassistant_HassSetPosition.yaml
  sentences/en/valve_HassSetPosition.yaml
  tests/en/cover_HassSetPosition.yaml
  tests/en/valve_HassSetPosition.yaml
Labels: cla-signed, lang: en

#1992 Fix links and styling/typos in README files
  README.md
  docs/codespace/README.md
  docs/forking/README.md
Labels: cla-signed

#2048 [NL] Split HassSetPosition in cover and valve
  sentences/nl/cover_HassSetPosition.yaml
  sentences/nl/homeassistant_HassSetPosition.yaml
  sentences/nl/valve_HassSetPosition.yaml
  tests/nl/cover_HassSetPosition.yaml
  tests/nl/valve_HassSetPosition.yaml
Labels: cla-signed, lang: nl

#2049 [RO] HassSetPosition refactoring
  sentences/ro/cover_HassSetPosition.yaml
  sentences/ro/valve_HassSetPosition.yaml
  tests/ro/cover_HassSetPosition.yaml
  tests/ro/valve_HassSetPosition.yaml
Labels: cla-signed, lang: ro

#2042 added HassShoppingListAddItem intent for italian language
  responses/it/HassShoppingListAddItem.yaml
  sentences/it/_common.yaml
  sentences/it/shopping_list_HassShoppingListAddItem.yaml
  tests/it/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: it

#2012 Update HassLightSet.yaml
  responses/tr/HassLightSet.yaml
Labels: cla-signed, lang: tr

#2050 [tr] Fix responses
  responses/tr/HassTurnOn.yaml
  tests/tr/cover_HassTurnOn.yaml
Labels: cla-signed, lang: tr

#2013 Update HassClimateSetTemperature.yaml
  responses/tr/HassClimateSetTemperature.yaml
Labels: cla-signed, lang: tr

#2052 [SL] added duration and distance sensors
  responses/sl/HassGetState.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2054 [ES] Separate HassSetPosition into domains
  sentences/es/_common.yaml
  sentences/es/cover_HassSetPosition.yaml
  sentences/es/homeassistant_HassSetPosition.yaml
  sentences/es/valve_HassSetPosition.yaml
  tests/es/cover_HassSetPosition.yaml
  tests/es/valve_HassSetPosition.yaml
Labels: cla-signed, lang: es

#2058 [ES] Translating device classes and domains in error messages
  sentences/es/_common.yaml
Labels: cla-signed, lang: es

#2062 [de-CH] add additional sentence for setPosition
  sentences/de-CH/homeassistant_HassSetPosition.yaml
  tests/de-CH/homeassistant_HassSetPosition.yaml
Labels: cla-signed

#2065 [SL] added sensor for gas, energy, frequency and energy storage
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2068 [RU] Fix negative temperature pronouncing
  responses/ru/HassGetWeather.yaml
  tests/ru/_fixtures.yaml
  tests/ru/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ru

#2071 [CS] re-implement intents removed in previous PR
  sentences/cs/light_HassLightSet.yaml
Labels: cla-signed, lang: cs

#2061 [CS] vacuum cleaner
  responses/cs/HassVacuumReturnToBase.yaml
  responses/cs/HassVacuumStart.yaml
  sentences/cs/vacuum_HassVacuumReturnToBase.yaml
  sentences/cs/vacuum_HassVacuumStart.yaml
  tests/cs/_fixtures.yaml
  tests/cs/vacuum_HassVacuumReturnToBase.yaml
  tests/cs/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: cs

#1929 [IT] Add alternative name for cover blinds
  sentences/it/_common.yaml
  tests/it/cover_HassTurnOff.yaml
  tests/it/cover_HassTurnOn.yaml
Labels: cla-signed, lang: it

#1930 [IT] Add first support to scenes
  responses/it/HassTurnOn.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/scene_HassTurnOn.yaml
  tests/it/_fixtures.yaml
  tests/it/scene_HassTurnOn.yaml
Labels: cla-signed, lang: it

#1964 Migliorati messaggi di errore
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#1962 Delete expansion rule for temp in Italian
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateGetTemperature.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: it

#1961 Update climate_HassClimateGetTemperature.yaml
  sentences/it/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: it

#1959 Update italian expansion rule for <all>
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#1957 Correct error in the italian expansion rule for the
  sentences/it/_common.yaml
Labels: cla-signed, lang: it

#1859 IT - updating sentences and adding area control for climate entities
  responses/it/HassClimateGetTemperature.yaml
  responses/it/HassLightSet.yaml
  responses/it/HassTurnOff.yaml
  responses/it/HassTurnOn.yaml
  sentences/it/_common.yaml
  sentences/it/climate_HassTurnOff.yaml
  sentences/it/climate_HassTurnOn.yaml
  sentences/it/cover_HassGetState.yaml
  sentences/it/cover_HassTurnOff.yaml
  sentences/it/cover_HassTurnOn.yaml
  sentences/it/fan_HassTurnOff.yaml
  sentences/it/fan_HassTurnOn.yaml
  sentences/it/homeassistant_HassNevermind.yaml
  sentences/it/homeassistant_HassTurnOff.yaml
  sentences/it/homeassistant_HassTurnOn.yaml
  sentences/it/light_HassLightSet.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  tests/it/_fixtures.yaml
  tests/it/climate_HassTurnOff.yaml
  tests/it/climate_HassTurnOn.yaml
  tests/it/cover_HassGetState.yaml
  tests/it/cover_HassTurnOff.yaml
  tests/it/cover_HassTurnOn.yaml
  tests/it/homeassistant_HassNevermind.yaml
  tests/it/light_HassLightSet.yaml
  tests/it/light_HassTurnOff.yaml
  tests/it/light_HassTurnOn.yaml
Labels: cla-signed, lang: it

#1542 Update homeassistant_HassGetState.yaml
  sentences/it/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: it

#2075 [SL] added sensors
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2076 Fix description in intents.yaml for HassGetState
  intents.yaml
Labels: cla-signed

#2077 Add common/fixtures for sw
  sentences/sw/_common.yaml
  tests/sw/_fixtures.yaml
Labels: cla-signed, lang: sw

#2078 Add sw leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2084 [SL] added sensors for N2O, O3, PM1, PM2.5, PM10, Power, Precipitation
  sentences/sl/_common.yaml
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2085 [RU]Add intent options for HassMediaUnpause
  responses/ru/HassMediaPause.yaml
  sentences/ru/media_player_HassMediaUnpause.yaml
  tests/ru/media_player_HassMediaPause.yaml
  tests/ru/media_player_HassMediaUnpause.yaml
Labels: cla-signed, lang: ru

#2081 [CA] Update sentences for opening the lights
  sentences/ca/light_HassTurnOn.yaml
  tests/ca/light_HassTurnOn.yaml
Labels: cla-signed, lang: ca

#2087 [SL] sensor intents added
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2088 [Fr] Add "pour cent" in the expansion rule <pourcent>
  sentences/fr/_common.yaml
Labels: cla-signed, lang: fr

#2089 [CA] Add new main actions
  responses/ca/HassGetWeather.yaml
  responses/ca/HassNevermind.yaml
  responses/ca/HassSetPosition.yaml
  responses/ca/HassSetVolume.yaml
  responses/ca/HassVacuumReturnToBase.yaml
  responses/ca/HassVacuumStart.yaml
  sentences/ca/_common.yaml
  sentences/ca/cover_HassSetPosition.yaml
  sentences/ca/homeassistant_HassNevermind.yaml
  sentences/ca/homeassistant_HassTurnOn.yaml
  sentences/ca/media_player_HassSetVolume.yaml
  sentences/ca/vacuum_HassVacuumReturnToBase.yaml
  sentences/ca/vacuum_HassVacuumStart.yaml
  sentences/ca/valve_HassSetPosition.yaml
  sentences/ca/weather_HassGetWeather.yaml
  tests/ca/_fixtures.yaml
  tests/ca/cover_HassSetPosition.yaml
  tests/ca/homeassistant_HassNevermind.yaml
  tests/ca/media_player_HassSetVolume.yaml
  tests/ca/vacuum_HassVacuumReturnToBase.yaml
  tests/ca/vacuum_HassVacuumStart.yaml
  tests/ca/valve_HassSetPosition.yaml
  tests/ca/weather_HassGetWeather.yaml
Labels: cla-signed, lang: ca

#2091 [CS) add alternative intent to cover get state
  sentences/cs/cover_HassGetState.yaml
  tests/cs/cover_HassGetState.yaml
Labels: cla-signed, lang: cs

#2092 [SL] sensors added
  sentences/sl/sensor_HassGetState.yaml
  tests/sl/_fixtures.yaml
  tests/sl/sensor_HassGetState.yaml
Labels: cla-signed, lang: sl

#2094 [RU] add intents for binary_sensor
  responses/ru/HassGetState.yaml
  sentences/ru/_common.yaml
  sentences/ru/binary_sensor_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: ru

#2090 [it] Add support for weather
  responses/it/HassGetWeather.yaml
  sentences/it/_common.yaml
  sentences/it/weather_HassGetWeather.yaml
  tests/it/_fixtures.yaml
  tests/it/weather_HassGetWeather.yaml
Labels: cla-signed, lang: it

#2096 [SL] some fixes in responses and HassTurnOn
  responses/sl/HassGetState.yaml
  responses/sl/HassTurnOff.yaml
  sentences/sl/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: sl

#2099 [SL] HassClimateGetTemperature fixed
  sentences/sl/climate_HassClimateGetTemperature.yaml
  tests/sl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sl

#2083 [FR] Quick Fix on HassSetVolume: Use expansion rule instead of hardcoded `de`
  sentences/fr/media_player_HassSetVolume.yaml
  tests/fr/_fixtures.yaml
  tests/fr/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: fr

#2102 add HasGetWeather and tests [BG]
  responses/bg/HassGetWeather.yaml
  sentences/bg/weather_HassGetWeather.yaml
  tests/bg/_fixtures.yaml
  tests/bg/weather_HassGetWeather.yaml
Labels: cla-signed, lang: bg

#2103 Remove el leader (not enough time)
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#2104 [RU] Improving the interaction experience
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  sentences/ru/_common.yaml
  tests/ru/light_HassTurnOff.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2106 add [ outside] to HassGetWeather [BG]
  sentences/bg/weather_HassGetWeather.yaml
  tests/bg/weather_HassGetWeather.yaml
Labels: cla-signed, lang: bg

#2101 [PT] Improve cover intent
  sentences/pt/_common.yaml
  sentences/pt/cover_HassGetState.yaml
  tests/pt/_fixtures.yaml
  tests/pt/cover_HassGetState.yaml
Labels: cla-signed, lang: pt

#2105 [RU] Adding a mechanism for selecting the correct ending in responses
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  tests/ru/cover_HassTurnOff.yaml
  tests/ru/cover_HassTurnOn.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
  tests/ru/light_HassTurnOff.yaml
  tests/ru/light_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#2100 [EN] Improvement on how we turn on and off lights in a room and in the whole house.
  responses/en/HassTurnOn.yaml
  sentences/en/_common.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2107 Bump hassil to 1.7.0
  requirements.txt
Labels: cla-signed

#2109 [NL] Improve HassSetVolume intent
  sentences/nl/media_player_HassSetVolume.yaml
  tests/nl/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: nl

#2067 [NB] Add Norwegian translations for valve
  responses/nb/HassSetPosition.yaml
  responses/nb/HassTurnOff.yaml
  responses/nb/HassTurnOn.yaml
  sentences/nb/_common.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  sentences/nb/light_HassLightSet.yaml
  sentences/nb/valve_HassSetPosition.yaml
  sentences/nb/valve_HassTurnOff.yaml
  sentences/nb/valve_HassTurnOn.yaml
  tests/nb/_fixtures.yaml
  tests/nb/valve_HassSetPosition.yaml
  tests/nb/valve_HassTurnOff.yaml
  tests/nb/valve_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#2069 [NB] Add translations for media player & volume
  responses/nb/HassMediaNext.yaml
  responses/nb/HassMediaPause.yaml
  responses/nb/HassMediaUnpause.yaml
  responses/nb/HassSetVolume.yaml
  sentences/nb/_common.yaml
  sentences/nb/media_player_HassMediaNext.yaml
  sentences/nb/media_player_HassMediaPause.yaml
  sentences/nb/media_player_HassMediaUnpause.yaml
  sentences/nb/media_player_HassSetVolume.yaml
  tests/nb/_fixtures.yaml
  tests/nb/media_player_HassMediaNext.yaml
  tests/nb/media_player_HassMediaPause.yaml
  tests/nb/media_player_HassMediaUnpause.yaml
  tests/nb/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: nb

#2070 [NB] Add translations for vacuum cmds
  responses/nb/HassVacuumReturnToBase.yaml
  responses/nb/HassVacuumStart.yaml
  sentences/nb/homeassistant_HassTurnOff.yaml
  sentences/nb/homeassistant_HassTurnOn.yaml
  sentences/nb/vacuum_HassVacuumReturnToBase.yaml
  sentences/nb/vacuum_HassVacuumStart.yaml
  tests/nb/_fixtures.yaml
  tests/nb/vacuum_HassVacuumReturnToBase.yaml
  tests/nb/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: nb

#2111 Add initial support for floors
  intents.yaml
  responses/en/HassTurnOff.yaml
  responses/en/HassTurnOn.yaml
  script/intentfest/validate.py
  sentences/en/_common.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  shared/__init__.py
  tests/en/_fixtures.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
  tests/test_language_intents.py
Labels: cla-signed, lang: en
