Repository OHF-Voice/intents, pull requests merged in 2025-05, with the labels that each got.

#3155 [SR| Add HassShoppingListCompleteItem
  requirements.txt
  responses/sr/HassShoppingListCompleteItem.yaml
  sentences/sr/shopping_list_HassShoppingListCompleteItem.yaml
  sentences/sr/todo_HassListAddItem.yaml
  tests/sr/shopping_list_HassShoppingListCompleteItem.yaml
Labels: cla-signed, lang: sr

#3153 [FR] Add "ouvrir" and "fermer" to light intents
  sentences/fr/_common.yaml
  tests/fr/light_HassLightSet.yaml
  tests/fr/light_HassTurnOff.yaml
  tests/fr/light_HassTurnOn.yaml
Labels: cla-signed, lang: fr

#3157 [zh-cn] Fix HassGetCurrentTime response error
  responses/zh-cn/HassGetCurrentTime.yaml
Labels: cla-signed

#3163 [NL] HassClimateSetTemperature: allow verwarming next to temperatuur
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#3159 [CA] Add HassListCompleteItem
  responses/ca/HassListCompleteItem.yaml
  sentences/ca/_common.yaml
  sentences/ca/todo_HassListAddItem.yaml
  sentences/ca/todo_HassListCompleteItem.yaml
  tests/ca/_fixtures.yaml
  tests/ca/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: ca

#3160 [CA] Add HassShoppingListCompleteItem
  responses/ca/HassShoppingListCompleteItem.yaml
  sentences/ca/shopping_list_HassShoppingListCompleteItem.yaml
  tests/ca/shopping_list_HassShoppingListCompleteItem.yaml
Labels: cla-signed, lang: ca

#3169 Add English sentences for HassMediaSearchAndPlay
  intents.yaml
  lists/lights.yaml
  lists/media.yaml
  responses/en/HassMediaSearchAndPlay.yaml
  script/intentfest/validate.py
  sentences/en/HassMediaSearchAndPlay/area_only.yaml
  sentences/en/HassMediaSearchAndPlay/default.yaml
  sentences/en/HassMediaSearchAndPlay/name_area.yaml
  sentences/en/HassMediaSearchAndPlay/name_only.yaml
  sentences/en/_common.yaml
  sentences/en/media_player_HassMediaSearchAndPlay.yaml
  shared/__init__.py
  tests/en/HassMediaSearchAndPlay/area_only.yaml
  tests/en/HassMediaSearchAndPlay/default.yaml
  tests/en/HassMediaSearchAndPlay/name_area.yaml
  tests/en/HassMediaSearchAndPlay/name_only.yaml
  tests/en/_fixtures.yaml
  tests/en/media_player_HassMediaSearchAndPlay.yaml
  tests/test_language_sentences.py
  tests/test_slot_combinations.py
Labels: cla-signed, lang: en

#3170 Remove en leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#3027 [DE] Set brightness for all lights in the same area as a satellite device
  sentences/de/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de

#3171 [DE] HassMediaSearchAndPlay
  responses/de/HassMediaSearchAndPlay.yaml
  sentences/de/_common.yaml
  sentences/de/media_player_HassMediaSearchAndPlay.yaml
  tests/de/_fixtures.yaml
  tests/de/media_player_HassMediaSearchAndPlay.yaml
Labels: cla-signed, lang: de

#3172 [DE] query for all doors / windows
  sentences/de/binary_sensor_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: de

#3164 [NL] cover: add verbs to control blind|shutter|shade
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOn.yaml
  tests/nl/cover_HassTurnOn.yaml
Labels: cla-signed, lang: nl

#3175 [FR] Add a simpler sentence to stop a vacuum
  sentences/fr/vacuum_HassVacuumReturnToBase.yaml
  tests/fr/vacuum_HassVacuumReturnToBase.yaml
Labels: cla-signed, lang: fr

#2108 Allow sentence metadata in responses
  script/intentfest/validate.py
  shared/__init__.py
Labels: cla-signed

#3177 [DE] Update light_HassLightSet.yaml
  sentences/de/_common.yaml
  sentences/de/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
Labels: cla-signed, lang: de

#3179 [NL] cover: add verbs to close blind|shutter|shade
  sentences/nl/_common.yaml
  sentences/nl/cover_HassTurnOff.yaml
  tests/nl/cover_HassTurnOff.yaml
Labels: cla-signed, lang: nl

#3184 [NL] Add Media Search and Play
  responses/nl/HassMediaSearchAndPlay.yaml
  sentences/nl/_common.yaml
  sentences/nl/media_player_HassMediaSearchAndPlay.yaml
  tests/nl/_fixtures.yaml
  tests/nl/media_player_HassMediaSearchAndPlay.yaml
Labels: cla-signed, lang: nl

#3181 adding GetCurrentTime for hindi language
  responses/hi/HassGetCurrentTime.yaml
  sentences/hi/homeassistant_HassGetCurrentTime.yaml
  tests/hi/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: hi

#3187 Add hi leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#3189 Fix responses for get temperature
  responses/ca/HassClimateGetTemperature.yaml
  responses/cs/HassClimateGetTemperature.yaml
  responses/da/HassClimateGetTemperature.yaml
  responses/en/HassClimateGetTemperature.yaml
  responses/es/HassClimateGetTemperature.yaml
  responses/gl/HassClimateGetTemperature.yaml
  responses/he/HassClimateGetTemperature.yaml
  responses/hu/HassClimateGetTemperature.yaml
  responses/it/HassClimateGetTemperature.yaml
  responses/kw/HassClimateGetTemperature.yaml
  responses/mr/HassClimateGetTemperature.yaml
  responses/nl/HassClimateGetTemperature.yaml
  responses/pl/HassClimateGetTemperature.yaml
  responses/pt-br/HassClimateGetTemperature.yaml
  responses/ro/HassClimateGetTemperature.yaml
  responses/ru/HassClimateGetTemperature.yaml
  responses/sk/HassClimateGetTemperature.yaml
  responses/sl/HassClimateGetTemperature.yaml
  responses/sr-Latn/HassClimateGetTemperature.yaml
  responses/sr/HassClimateGetTemperature.yaml
  responses/th/HassClimateGetTemperature.yaml
  responses/vi/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: he, lang: en, lang: nl, lang: hu, lang: pl, lang: sl, lang: ca, lang: es, lang: cs, lang: it, lang: sr, lang: sk, lang: vi, lang: ro, lang: da, lang: ru, lang: gl, lang: th, lang: kw, lang: mr

#3190 [CS] Add intents for HassMediaSearchAndPlay
  responses/cs/HassMediaSearchAndPlay.yaml
  sentences/cs/_common.yaml
  sentences/cs/media_player_HassMediaSearchAndPlay.yaml
  tests/cs/_fixtures.yaml
  tests/cs/media_player_HassMediaSearchAndPlay.yaml
Labels: cla-signed, lang: cs
