Repository OHF-Voice/intents, pull requests merged in 2025-02, with the labels that each got.

#2947 [PL] Added HassBroadcast intents
  responses/pl/HassBroadcast.yaml
  sentences/pl/_common.yaml
  sentences/pl/assist_satellite_HassBroadcast.yaml
  tests/pl/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: pl

#2953 [PT-BR] Broadcast and Set Temperature
  responses/pt-br/HassBroadcast.yaml
  responses/pt-br/HassClimateSetTemperature.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/assist_satellite_HassBroadcast.yaml
  sentences/pt-br/climate_HassClimateSetTemperature.yaml
  tests/pt-br/assist_satellite_HassBroadcast.yaml
  tests/pt-br/climate_HassClimateSetTemperature.yaml
Labels: cla-signed

#2954 [DE] fix person_HassGetState for home zone
  responses/de/HassGetState.yaml
  sentences/de/person_HassGetState.yaml
  tests/de/_fixtures.yaml
  tests/de/person_HassGetState.yaml
Labels: cla-signed, lang: de

#2942 [DE] add floors to cover_*
  sentences/de/cover_HassGetState.yaml
  sentences/de/cover_HassTurnOff.yaml
  sentences/de/cover_HassTurnOn.yaml
  tests/de/cover_HassGetState.yaml
  tests/de/cover_HassTurnOff.yaml
  tests/de/cover_HassTurnOn.yaml
Labels: cla-signed, lang: de

#2956 [NL] Add context sentences for HassClimateGetTemperature
  sentences/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: nl

#2945 [DA] Add intents for Valve domain
  responses/da/HassTurnOff.yaml
  responses/da/HassTurnOn.yaml
  sentences/da/homeassistant_HassTurnOff.yaml
  sentences/da/homeassistant_HassTurnOn.yaml
  sentences/da/valve_HassSetPosition.yaml
  sentences/da/valve_HassTurnOff.yaml
  sentences/da/valve_HassTurnOn.yaml
  tests/da/_fixtures.yaml
  tests/da/valve_HassSetPosition.yaml
  tests/da/valve_HassTurnOff.yaml
  tests/da/valve_HassTurnOn.yaml
Labels: cla-signed, lang: da

#2943 [DA] Add TurnOn intents for Script domain
  responses/da/HassTurnOn.yaml
  sentences/da/_common.yaml
  sentences/da/script_HassTurnOn.yaml
  tests/da/_fixtures.yaml
  tests/da/script_HassTurnOn.yaml
Labels: cla-signed, lang: da

#2941 [DA] Add intents for GetState for Person domain
  responses/da/HassGetState.yaml
  sentences/da/_common.yaml
  sentences/da/person_HassGetState.yaml
  tests/da/_fixtures.yaml
  tests/da/person_HassGetState.yaml
Labels: cla-signed, lang: da

#2959 Bump hassil and fix wildcards inside/outside words
  requirements.txt
  sentences/sv/homeassistant_HassCancelTimer.yaml
  sentences/sv/homeassistant_HassDecreaseTimer.yaml
  sentences/sv/homeassistant_HassIncreaseTimer.yaml
  sentences/sv/homeassistant_HassPauseTimer.yaml
  sentences/sv/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: sv

#2841 [SV] Added `binary_sensor_HassGetState.yaml` + "som" as skip word
  sentences/sv/_common.yaml
  sentences/sv/binary_sensor_HassGetState.yaml
  tests/sv/_fixtures.yaml
  tests/sv/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: sv

#2962 SV: Move cover from generic HassTurnOn
  sentences/sv/cover_HassTurnOn.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/cover_HassTurnOn.yaml
  tests/sv/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2963 SV: Move cover from generic HassTurnOff
  sentences/sv/cover_HassTurnOff.yaml
  sentences/sv/homeassistant_HassTurnOff.yaml
  tests/sv/cover_HassTurnOff.yaml
  tests/sv/homeassistant_HassTurnOff.yaml
Labels: cla-signed, lang: sv

#2964 SV: Move light from generic HassTurnOn/HassTurnOn
  sentences/sv/homeassistant_HassTurnOff.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  sentences/sv/light_HassTurnOff.yaml
  sentences/sv/light_HassTurnOn.yaml
  tests/sv/homeassistant_HassTurnOff.yaml
  tests/sv/homeassistant_HassTurnOn.yaml
  tests/sv/light_HassTurnOff.yaml
  tests/sv/light_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2965 SV: Add assist_satellite_HassBroadcast to Swedish
  responses/sv/HassBroadcast.yaml
  sentences/sv/_common.yaml
  sentences/sv/assist_satellite_HassBroadcast.yaml
  tests/sv/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: sv

#2958 [NL] Update ClimateSetTemperature
  responses/nl/HassClimateSetTemperature.yaml
  sentences/nl/_common.yaml
  sentences/nl/climate_HassClimateSetTemperature.yaml
  tests/nl/_fixtures.yaml
  tests/nl/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: nl

#2961 [DA] Fix ClimateGetTemperature
  responses/da/HassClimateGetTemperature.yaml
  sentences/da/_common.yaml
  sentences/da/climate_HassClimateGetTemperature.yaml
  tests/da/_fixtures.yaml
  tests/da/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: da

#2967 [CS] Add intents for HassBroadcast
  responses/cs/HassBroadcast.yaml
  sentences/cs/_common.yaml
  sentences/cs/assist_satellite_HassBroadcast.yaml
  tests/cs/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: cs

#2972 [DA] Add GetState intents for Sensor domain
  responses/da/HassGetState.yaml
  sentences/da/_common.yaml
  sentences/da/sensor_HassGetState.yaml
  tests/da/_fixtures.yaml
  tests/da/sensor_HassGetState.yaml
Labels: cla-signed, lang: da

#2966 SV: Add response check to light_HassLightSet
  tests/sv/light_HassLightSet.yaml
Labels: cla-signed, lang: sv

#2976 SV: media play previous
  responses/sv/HassMediaPrevious.yaml
  sentences/sv/media_player_HassMediaPrevious.yaml
  tests/sv/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: sv

#2977 SV: add homeassistant_HassCancelAllTimers
  sentences/sv/_common.yaml
  sentences/sv/homeassistant_HassCancelAllTimers.yaml
  tests/sv/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: sv

#2974 [DA] Move Cover from homeassistant_HassTurnOn/Off and extend Cover intents
  sentences/da/_common.yaml
  sentences/da/cover_HassTurnOff.yaml
  sentences/da/cover_HassTurnOn.yaml
  sentences/da/homeassistant_HassTurnOff.yaml
  tests/da/_fixtures.yaml
  tests/da/cover_HassTurnOff.yaml
  tests/da/cover_HassTurnOn.yaml
  tests/da/homeassistant_HassTurnOff.yaml
  tests/da/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: da

#2978 [DA] Extend TurnOn/Off for Light domain
  responses/da/HassTurnOff.yaml
  responses/da/HassTurnOn.yaml
  sentences/da/_common.yaml
  sentences/da/light_HassTurnOff.yaml
  sentences/da/light_HassTurnOn.yaml
  tests/da/light_HassTurnOff.yaml
  tests/da/light_HassTurnOn.yaml
Labels: cla-signed, lang: da

#2980 [DE] "zu Hause" for person_HassGetState
  responses/de/HassGetState.yaml
  sentences/de/_common.yaml
  sentences/de/person_HassGetState.yaml
  tests/de/person_HassGetState.yaml
Labels: cla-signed, lang: de

#2981 [DA] Extend LightSet intents
  responses/da/HassLightSet.yaml
  sentences/da/_common.yaml
  sentences/da/light_HassLightSet.yaml
  tests/da/light_HassLightSet.yaml
Labels: cla-signed, lang: da

#2969 [PL] Update homeassistant_HassGetCurrentDate.yaml
  sentences/pl/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: pl

#2984 [DE] more options to cancel a timer
  sentences/de/_common.yaml
  tests/de/homeassistant_HassCancelAllTimers.yaml
  tests/de/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: de, cla-error

#2957 [RU] Improved responses
  responses/ru/HassTurnOff.yaml
  responses/ru/HassTurnOn.yaml
  tests/ru/_fixtures.yaml
  tests/ru/cover_HassTurnOff.yaml
  tests/ru/cover_HassTurnOn.yaml
  tests/ru/homeassistant_HassGetState.yaml
  tests/ru/homeassistant_HassTurnOff.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
  tests/ru/light_HassLightSet.yaml
Labels: cla-signed, lang: ru

#2998 [DA] Extend TurnOn/Off intents for Fan domain
  responses/da/HassTurnOff.yaml
  responses/da/HassTurnOn.yaml
  sentences/da/_common.yaml
  sentences/da/fan_HassTurnOff.yaml
  sentences/da/fan_HassTurnOn.yaml
  sentences/da/homeassistant_HassTurnOff.yaml
  sentences/da/homeassistant_HassTurnOn.yaml
  tests/da/fan_HassTurnOff.yaml
  tests/da/fan_HassTurnOn.yaml
  tests/da/homeassistant_HassTurnOff.yaml
  tests/da/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: da

#3001 [RU] Improvements for HassGetState
  responses/ru/HassGetState.yaml
  sentences/ru/_common.yaml
  sentences/ru/homeassistant_HassGetState.yaml
  tests/ru/_fixtures.yaml
  tests/ru/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: ru

#3006 [CS] Add intents for Date and Time
  responses/cs/HassGetCurrentDate.yaml
  responses/cs/HassGetCurrentTime.yaml
  sentences/cs/homeassistant_HassGetCurrentDate.yaml
  sentences/cs/homeassistant_HassGetCurrentTime.yaml
  tests/cs/homeassistant_HassGetCurrentDate.yaml
  tests/cs/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: cs

#3009 [ES] Support new sentence to set brightness of current area light
  sentences/es/light_HassLightSet.yaml
  tests/es/light_HassLightSet.yaml
Labels: cla-signed, lang: es

#3010 [RU] fix typo
  responses/ru/HassTurnOn.yaml
  tests/ru/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ru

#3000 [HR] Fix a typo in expansion rules
  sentences/hr/_common.yaml
Labels: cla-signed, lang: hr

#3012 [HR] Support another form in canceling a timer
  sentences/hr/homeassistant_HassCancelTimer.yaml
  tests/hr/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: hr

#3011 [HR] Improve timer response
  responses/hr/HassTimerStatus.yaml
  tests/hr/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: hr

#3013 [HR] Pause timer: drop doubly-pausing sentences
  sentences/hr/homeassistant_HassPauseTimer.yaml
  tests/hr/homeassistant_HassPauseTimer.yaml
Labels: cla-signed, lang: hr

#3015 [HR] Increase timer: provide an area according to the Croatian grammar
  sentences/hr/homeassistant_HassIncreaseTimer.yaml
  tests/hr/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: hr

#3017 [HR] Decrease timer: require area preposition
  sentences/hr/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed, lang: hr

#3018 [HR] Decrease timer: Require a "remove" verb
  sentences/hr/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed, lang: hr

#3020 [HR] Cancel timer: support a female gender timer noun
  sentences/hr/homeassistant_HassCancelTimer.yaml
  tests/hr/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: hr

#3019 [HR] Decrease timer: support a female gender timer noun
  sentences/hr/homeassistant_HassDecreaseTimer.yaml
  tests/hr/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed, lang: hr

#3003 Allow storing TTS and STT support
  languages.yaml
  script/intentfest/validate.py
Labels: cla-signed

#3021 [HR] Cancel timer: support an adjective form
  sentences/hr/_common.yaml
  tests/hr/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: hr

#3002 [HR] Start timer: fix logic for count and cases
  responses/hr/HassStartTimer.yaml
  sentences/hr/_common.yaml
  tests/hr/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: hr
