Repository OHF-Voice/intents, pull requests merged in 2025-01, with the labels that each got.

#2818 [sl] add HassCancelAllTimers
  responses/sl/HassCancelAllTimers.yaml
  sentences/sl/homeassistant_HassCancelAllTimers.yaml
  tests/sl/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: sl

#2820 [SR] Add GetCurrentDate/Time
  responses/sr/HassGetCurrentDate.yaml
  responses/sr/HassGetCurrentTime.yaml
  sentences/sr/_common.yaml
  sentences/sr/homeassistant_HassGetCurrentDate.yaml
  sentences/sr/homeassistant_HassGetCurrentTime.yaml
  tests/sr/homeassistant_HassGetCurrentDate.yaml
  tests/sr/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sr

#2819 [PL] Fix HassGetState closed state
  responses/pl/HassGetState.yaml
  tests/pl/cover_HassGetState.yaml
Labels: cla-signed, lang: pl

#2822 [SR] Add Nevermind
  sentences/sr/homeassistant_HassNevermind.yaml
  tests/sr/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sr

#2813 [EN] Fix AM/PM for times with hour of 12
  responses/en/HassGetCurrentTime.yaml
Labels: cla-signed, lang: en

#2814 [CA] Add alternatives for HassGetCurrentTime
  sentences/ca/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: ca

#2825 [sv] correct "i" -> "på" for floor response
  sentences/sv/_common.yaml
Labels: cla-signed, lang: sv

#2815 [CA] Add alternatives for HassGetCurrentDate
  sentences/ca/homeassistant_HassGetCurrentDate.yaml
  tests/ca/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: ca

#2828 Added `HassCancelAllTimers.yaml`
  responses/sv/HassCancelAllTimers.yaml
Labels: cla-signed, lang: sv

#2829 [SV] Added `HassTurnOff.yaml`and `HassTurnOn.yaml`
  responses/sv/HassTurnOff.yaml
  responses/sv/HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2805 [SK] lights on/off with satellite
  sentences/sk/light_HassTurnOff.yaml
  sentences/sk/light_HassTurnOn.yaml
  tests/sk/light_HassTurnOff.yaml
  tests/sk/light_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#2831 [SV] Added HassRespond
  responses/sv/HassRespond.yaml
  sentences/sv/_common.yaml
  sentences/sv/homeassistant_HassRespond.yaml
  tests/sv/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sv

#2839 [SK] Implemented set timer intent for sk language
  responses/sk/HassStartTimer.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassStartTimer.yaml
  tests/sk/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: sk

#2840 [DE] harmonize todo and shopping lists
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
  sentences/de/todo_HassListAddItem.yaml
  tests/de/shopping_list_HassShoppingListAddItem.yaml
  tests/de/todo_HassListAddItem.yaml
Labels: cla-signed, lang: de

#2832 [SV] Added word "på" for adding items to shoppinglist
  sentences/sv/shopping_list_HassShoppingListAddItem.yaml
  tests/sv/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: sv

#2834 [SV] Scripts
  sentences/sv/homeassistant_HassTurnOff.yaml
  sentences/sv/homeassistant_HassTurnOn.yaml
  sentences/sv/script_HassTurnOn.yaml
  tests/sv/_fixtures.yaml
  tests/sv/script_HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2843 [SV] better handling for defaults in `HassTurnOn.yaml` and `HassTurnOff.yaml`
  responses/sv/HassTurnOff.yaml
  responses/sv/HassTurnOn.yaml
Labels: cla-signed, lang: sv

#2836 Fix incorrect French responses in HassGetWeather.yaml
  responses/fr/HassGetWeather.yaml
  tests/fr/weather_HassGetWeather.yaml
Labels: cla-signed, lang: fr

#2810 [FR] Set temperature with area context
  sentences/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: fr

#2842 [DE] Add more german shopping list examples
  sentences/de/shopping_list_HassShoppingListAddItem.yaml
  tests/de/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: de

#2851 [EN] Update commands URL
  responses/en/HassRespond.yaml
  tests/en/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: en

#2728 [En] remove `the` from `<light>`
  sentences/en/_common.yaml
  sentences/en/light_HassLightSet.yaml
  sentences/en/light_HassTurnOff.yaml
  sentences/en/light_HassTurnOn.yaml
  tests/en/light_HassTurnOff.yaml
  tests/en/light_HassTurnOn.yaml
Labels: cla-signed, lang: en

#2853 [SK] - add sk GetCurrentDate
  responses/sk/HassGetCurrentDate.yaml
  sentences/sk/homeassistant_HassGetCurrentDate.yaml
  tests/sk/homeassistant_HassGetCurrentDate.yaml
Labels: cla-signed, lang: sk

#2855 [SR] Add Respond
  responses/sr/HassRespond.yaml
  sentences/sr/homeassistant_HassRespond.yaml
  tests/sr/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sr

#2856 [SR] Add Respond + fix
  responses/sr/HassRespond.yaml
  tests/sr/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sr

#2857 [SK] - add sk GetCurrentTime
  responses/sk/HassGetCurrentTime.yaml
  sentences/sk/homeassistant_HassGetCurrentTime.yaml
  tests/sk/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: sk

#2848 [IT] Add all lights control
  responses/it/HassTurnOff.yaml
  responses/it/HassTurnOn.yaml
  sentences/it/_common.yaml
  sentences/it/light_HassTurnOff.yaml
  sentences/it/light_HassTurnOn.yaml
  tests/it/light_HassTurnOff.yaml
  tests/it/light_HassTurnOn.yaml
Labels: cla-signed, cla-error, lang: it

#2869 [IT] Clean and merge 'todo' sentences
  sentences/it/todo_HassListAddItem.yaml
  tests/it/todo_HassListAddItem.yaml
Labels: cla-signed, lang: it

#2870 [IT] Cleanup in _common.yaml
  sentences/it/_common.yaml
  sentences/it/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: it

#2871 [HU] Fix HassGetWeather.yaml Error #2826
  responses/hu/HassGetWeather.yaml
Labels: cla-signed, lang: hu

#2873 [DE] Add some sentences for timer status
  sentences/de/homeassistant_HassTimerStatus.yaml
  tests/de/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: de

#2872 [DE] Add some shorter sentences for "set timer"
  sentences/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: de

#2863 [BG] Update binary_sensor_HassGetState.yaml
  sentences/bg/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: bg

#2876 [EN] Remove say from English
  sentences/en/_common.yaml
  sentences/en/homeassistant_HassRespond.yaml
  tests/en/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: en

#2879 [SR] Add Media
  responses/sr/HassMediaNext.yaml
  responses/sr/HassMediaPause.yaml
  responses/sr/HassMediaPrevious.yaml
  responses/sr/HassMediaUnpause.yaml
  responses/sr/HassSetVolume.yaml
  sentences/sr/_common.yaml
  sentences/sr/media_player_HassMediaNext.yaml
  sentences/sr/media_player_HassMediaPause.yaml
  sentences/sr/media_player_HassMediaPrevious.yaml
  sentences/sr/media_player_HassMediaUnpause.yaml
  sentences/sr/media_player_HassSetVolume.yaml
  tests/sr/_fixtures.yaml
  tests/sr/media_player_HassMediaNext.yaml
  tests/sr/media_player_HassMediaPause.yaml
  tests/sr/media_player_HassMediaPrevious.yaml
  tests/sr/media_player_HassMediaUnpause.yaml
  tests/sr/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: sr

#2880 [DA] Add support for HassGetCurrentDate and HassGetCurrentTime
  responses/da/HassGetCurrentDate.yaml
  responses/da/HassGetCurrentTime.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassGetCurrentDate.yaml
  sentences/da/homeassistant_HassGetCurrentTime.yaml
  tests/da/homeassistant_HassGetCurrentDate.yaml
  tests/da/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: da

#2881 fix typo (in a comment)
  intents.yaml
Labels: cla-signed

#2882 [DE] Add HassBroadcast
  responses/de/HassBroadcast.yaml
  sentences/de/_common.yaml
  sentences/de/assist_satellite_HassBroadcast.yaml
  tests/de/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: de

#2884 [SR] Add advanced Timer
  responses/sr/HassCancelAllTimers.yaml
  responses/sr/HassDecreaseTimer.yaml
  responses/sr/HassIncreaseTimer.yaml
  responses/sr/HassPauseTimer.yaml
  responses/sr/HassUnpauseTimer.yaml
  sentences/sr/homeassistant_HassCancelAllTimers.yaml
  sentences/sr/homeassistant_HassDecreaseTimer.yaml
  sentences/sr/homeassistant_HassIncreaseTimer.yaml
  sentences/sr/homeassistant_HassPauseTimer.yaml
  sentences/sr/homeassistant_HassUnpauseTimer.yaml
  tests/sr/homeassistant_HassCancelAllTimers.yaml
  tests/sr/homeassistant_HassDecreaseTimer.yaml
  tests/sr/homeassistant_HassIncreaseTimer.yaml
  tests/sr/homeassistant_HassPauseTimer.yaml
  tests/sr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: sr

#2885 [SR] Add HassBroadcast
  responses/sr/HassBroadcast.yaml
  sentences/sr/_common.yaml
  sentences/sr/assist_satellite_HassBroadcast.yaml
  sentences/sr/homeassistant_HassRespond.yaml
  tests/sr/assist_satellite_HassBroadcast.yaml
  tests/sr/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sr

#2883 Revert "[DE] say xyz"
  responses/de/HassRespond.yaml
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassRespond.yaml
  tests/de/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: de

#2890 [SL] Add HassBroadcast
  responses/sl/HassBroadcast.yaml
  sentences/sl/_common.yaml
  sentences/sl/assist_satellite_HassBroadcast.yaml
  tests/sl/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: sl

#2886 [DA] Add support for HassRespond
  responses/da/HassRespond.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassRespond.yaml
  tests/da/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: da

#2889 [DA] Add support for HassGetWeather
  responses/da/HassGetWeather.yaml
  sentences/da/weather_HassGetWeather.yaml
  tests/da/_fixtures.yaml
  tests/da/weather_HassGetWeather.yaml
Labels: cla-signed, lang: da

#2173 [DA] added support for shopping list
  responses/da/HassShoppingListAddItem.yaml
  sentences/da/_common.yaml
  sentences/da/shopping_list_HassShoppingListAddItem.yaml
  tests/da/shopping_list_HassShoppingListAddItem.yaml
Labels: cla-signed, lang: da

#2893 [NL] Add assist_satellite_HassBroadcast
  responses/nl/HassBroadcast.yaml
  sentences/nl/_common.yaml
  sentences/nl/assist_satellite_HassBroadcast.yaml
  tests/nl/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: nl

#2892 [DA] Change of default wording for timer
  sentences/da/_common.yaml
  tests/da/homeassistant_HassCancelTimer.yaml
Labels: cla-signed, lang: da

#2847 [EN] Add sentence option "an"
  sentences/en/homeassistant_HassStartTimer.yaml
  tests/en/homeassistant_HassStartTimer.yaml
Labels: cla-signed, lang: en

#2816 [DA] added cancel all timer and test, and change of default wording for timer
  responses/da/HassCancelAllTimers.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassCancelAllTimers.yaml
  sentences/da/homeassistant_HassCancelTimer.yaml
  tests/da/homeassistant_HassCancelAllTimers.yaml
Labels: cla-signed, lang: da

#2895 [DA] Add support for Cover HassSetPosition
  responses/da/HassSetPosition.yaml
  sentences/da/_common.yaml
  sentences/da/cover_HassSetPosition.yaml
  tests/da/cover_HassSetPosition.yaml
Labels: cla-signed, lang: da

#2896 [DA] Add support for Timer pause/unpause
  responses/da/HassPauseTimer.yaml
  responses/da/HassUnpauseTimer.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassPauseTimer.yaml
  sentences/da/homeassistant_HassUnpauseTimer.yaml
  tests/da/homeassistant_HassPauseTimer.yaml
  tests/da/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: da

#2900 [DA] Add support for Timer increase/decrease in Danish
  responses/da/HassDecreaseTimer.yaml
  responses/da/HassIncreaseTimer.yaml
  sentences/da/_common.yaml
  sentences/da/homeassistant_HassDecreaseTimer.yaml
  sentences/da/homeassistant_HassIncreaseTimer.yaml
  sentences/da/homeassistant_HassPauseTimer.yaml
  sentences/da/homeassistant_HassUnpauseTimer.yaml
  tests/da/homeassistant_HassDecreaseTimer.yaml
  tests/da/homeassistant_HassIncreaseTimer.yaml
  tests/da/homeassistant_HassPauseTimer.yaml
  tests/da/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: da

#2901 [NL] Fix HassGetWeather
  responses/nl/HassGetWeather.yaml
  tests/nl/_fixtures.yaml
  tests/nl/weather_HassGetWeather.yaml
Labels: cla-signed, lang: nl

#2903 [EU] Fix _common + added some sentences and tests in HassLightSet
  sentences/eu/_common.yaml
  sentences/eu/homeassistant_HassGetState.yaml
  sentences/eu/homeassistant_HassTurnOff.yaml
  sentences/eu/homeassistant_HassTurnOn.yaml
  sentences/eu/light_HassLightSet.yaml
  tests/eu/_fixtures.yaml
  tests/eu/homeassistant_HassGetState.yaml
  tests/eu/homeassistant_HassTurnOff.yaml
  tests/eu/homeassistant_HassTurnOn.yaml
  tests/eu/light_HassLightSet.yaml
Labels: cla-signed, lang: eu

#2904 [sr-Latn] Add support for HassBroadcast
  responses/sr-Latn/HassBroadcast.yaml
  sentences/sr-Latn/_common.yaml
  sentences/sr-Latn/assist_satellite_HassBroadcast.yaml
  tests/sr-Latn/assist_satellite_HassBroadcast.yaml
Labels: cla-signed

#2907 [DA] Fix HassGetWeather
  responses/da/HassGetWeather.yaml
  tests/da/_fixtures.yaml
Labels: cla-signed, lang: da

#2908 Revert "[DA] Fix HassGetWeather"
  responses/da/HassGetWeather.yaml
  tests/da/_fixtures.yaml
Labels: cla-signed, lang: da

#2905 [RU] Add HassBroadcast
  responses/ru/HassBroadcast.yaml
  sentences/ru/_common.yaml
  sentences/ru/assist_satellite_HassBroadcast.yaml
  tests/ru/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: ru

#2912 [zh-hk] CancelAllTimers, Rspond
  responses/zh-hk/HassCancelAllTimers.yaml
  responses/zh-hk/HassRespond.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/homeassistant_HassCancelAllTimers.yaml
  sentences/zh-hk/homeassistant_HassRespond.yaml
  tests/zh-hk/homeassistant_HassCancelAllTimers.yaml
  tests/zh-hk/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: zh-hk

#2913 [zh-hk] HassBroadcast
  responses/zh-hk/HassBroadcast.yaml
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/assist_satellite_HassBroadcast.yaml
  sentences/zh-hk/homeassistant_HassCancelAllTimers.yaml
  sentences/zh-hk/homeassistant_HassRespond.yaml
  tests/zh-hk/assist_satellite_HassBroadcast.yaml
  tests/zh-hk/homeassistant_HassCancelAllTimers.yaml
  tests/zh-hk/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: zh-hk

#2915 [CS] Revision of binary sensors
  responses/cs/HassGetState.yaml
  sentences/cs/_common.yaml
  sentences/cs/binary_sensor_HassGetState.yaml
  tests/cs/_fixtures.yaml
  tests/cs/binary_sensor_HassGetState.yaml
Labels: cla-signed, lang: cs

#2914 [PT-BR] Support controlling shades
  sentences/pt-br/cover_HassTurnOff.yaml
  sentences/pt-br/cover_HassTurnOn.yaml
Labels: cla-signed

#2917 [CS] Review scene and script intents
  responses/cs/HassTurnOn.yaml
  sentences/cs/_common.yaml
  sentences/cs/homeassistant_HassTurnOff.yaml
  sentences/cs/homeassistant_HassTurnOn.yaml
  sentences/cs/scene_HassTurnOn.yaml
  sentences/cs/script_HassTurnOn.yaml
  tests/cs/_fixtures.yaml
  tests/cs/script_HassTurnOn.yaml
Labels: cla-signed, lang: cs

#2922 [uk] Added HassBrodcast intent
  responses/uk/HassBroadcast.yaml
  sentences/uk/_common.yaml
  sentences/uk/assist_satellite_HassBroadcast.yaml
  tests/uk/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: uk

#2906 [DA] Add HassVacuum support
  responses/da/HassVacuumReturnToBase.yaml
  responses/da/HassVacuumStart.yaml
  sentences/da/_common.yaml
  sentences/da/vacuum_HassVacuumReturnToBase.yaml
  sentences/da/vacuum_HassVacuumStart.yaml
  tests/da/_fixtures.yaml
  tests/da/vacuum_HassVacuumReturnToBase.yaml
  tests/da/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: da

#2924 [RO] HassBroadcast
  responses/ro/HassBroadcast.yaml
  sentences/ro/_common.yaml
  sentences/ro/assist_satellite_HassBroadcast.yaml
  tests/ro/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: ro

#2925 Fix domain of timer intents
  intents.yaml
Labels: cla-signed

#2926 [RO] HassClimateSetTemperature
  sentences/ro/_common.yaml
  sentences/ro/climate_HassClimateSetTemperature.yaml
  tests/ro/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ro

#2928 [zh-hk]weather_HassGetWeather
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/weather_HassGetWeather.yaml
  tests/zh-hk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: zh-hk

#2927 [RU] Improvements for HassClimateSetTemperature
  sentences/ru/climate_HassClimateSetTemperature.yaml
  tests/ru/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: ru

#2929 [Zh-hk] weather_HassGetWeather
  sentences/zh-hk/_common.yaml
  sentences/zh-hk/weather_HassGetWeather.yaml
  tests/zh-hk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: zh-hk

#2935 [RO] Fix HassClimateSetTemperature
  sentences/ro/_common.yaml
Labels: cla-signed, lang: ro

#2934 [DA] Extend HassClimateSetTemperature intents
  sentences/da/_common.yaml
  sentences/da/climate_HassClimateSetTemperature.yaml
  tests/da/_fixtures.yaml
  tests/da/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: da

#2930 [IT] Update HassClimateSetTemperature
  responses/it/HassClimateSetTemperature.yaml
  sentences/it/_common.yaml
  sentences/it/climate_HassClimateSetTemperature.yaml
  tests/it/_fixtures.yaml
  tests/it/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: it

#2936 [FR] Broadcast and Set Temperature Intents
  responses/fr/HassBroadcast.yaml
  sentences/fr/_common.yaml
  sentences/fr/assist_satellite_HassBroadcast.yaml
  sentences/fr/climate_HassClimateSetTemperature.yaml
  tests/fr/_fixtures.yaml
  tests/fr/assist_satellite_HassBroadcast.yaml
  tests/fr/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: fr

#2937 [IT ] Add HassBroadcast
  responses/it/HassBroadcast.yaml
  sentences/it/_common.yaml
  sentences/it/assist_satellite_HassBroadcast.yaml
  tests/it/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: it

#2932 [DA] Add HassMedia support
  responses/da/HassMediaNext.yaml
  responses/da/HassMediaPause.yaml
  responses/da/HassMediaPrevious.yaml
  responses/da/HassMediaUnpause.yaml
  responses/da/HassSetVolume.yaml
  sentences/da/_common.yaml
  sentences/da/media_player_HassMediaNext.yaml
  sentences/da/media_player_HassMediaPause.yaml
  sentences/da/media_player_HassMediaPrevious.yaml
  sentences/da/media_player_HassMediaUnpause.yaml
  sentences/da/media_player_HassSetVolume.yaml
  tests/da/_fixtures.yaml
  tests/da/media_player_HassMediaNext.yaml
  tests/da/media_player_HassMediaPause.yaml
  tests/da/media_player_HassMediaPrevious.yaml
  tests/da/media_player_HassMediaUnpause.yaml
  tests/da/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: da

#2939 [SR] update common and fixtures
  responses/sr/HassClimateGetTemperature.yaml
  sentences/sr/_common.yaml
  tests/sr/_fixtures.yaml
  tests/sr/light_HassTurnOff.yaml
  tests/sr/media_player_HassMediaNext.yaml
  tests/sr/media_player_HassMediaPause.yaml
  tests/sr/media_player_HassMediaPrevious.yaml
  tests/sr/media_player_HassMediaUnpause.yaml
  tests/sr/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: sr
