Repository OHF-Voice/intents, pull requests merged in 2025-04, with the labels that each got.

#3118 [RO] ListCompleteItem
  responses/ro/HassListCompleteItem.yaml
  responses/ro/HassShoppingListCompleteItem.yaml
  sentences/ro/shopping_list_HassShoppingListCompleteItem.yaml
  sentences/ro/todo_HassListCompleteItem.yaml
  tests/ro/shopping_list_HassShoppingListCompleteItem.yaml
  tests/ro/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: ro

#3119 [DE] Add HassListCompleteItem
  responses/de/HassListCompleteItem.yaml
  sentences/de/todo_HassListCompleteItem.yaml
  tests/de/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: de

#3121 [GL] Add intents HassMediaNext and HassMediaPrevious
  responses/gl/HassMediaNext.yaml
  responses/gl/HassMediaPrevious.yaml
  sentences/gl/_common.yaml
  sentences/gl/media_player_HassMediaNext.yaml
  sentences/gl/media_player_HassMediaPrevious.yaml
  tests/gl/_fixtures.yaml
  tests/gl/homeassistant_HassGetState.yaml
  tests/gl/media_player_HassMediaNext.yaml
  tests/gl/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: gl

#3123 [GL] Support HassMediaPause
  responses/gl/HassMediaPause.yaml
  sentences/gl/_common.yaml
  sentences/gl/media_player_HassMediaPause.yaml
  tests/gl/media_player_HassMediaPause.yaml
Labels: cla-signed, lang: gl

#3120 [DE] Extend HassListCompleteItem
  sentences/de/todo_HassListCompleteItem.yaml
  tests/de/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: de

#3127 [SR| Add HassListCompleteItem
  responses/sr/HassListCompleteItem.yaml
  sentences/sr/_common.yaml
  sentences/sr/todo_HassListCompleteItem.yaml
  tests/sr/_fixtures.yaml
  tests/sr/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: sr

#3128 Move language scores script to intents repo
  .github/workflows/gh-pages.yml
  script/write_language_scores.py
Labels: cla-signed

#3131 [RU] Minor edits
  responses/ru/HassGetState.yaml
  responses/ru/HassTimerStatus.yaml
  tests/ru/sensor_HassGetState.yaml
Labels: cla-signed, lang: ru

#3133 [GL] Add Unpause and SetVolume intents
  responses/gl/HassMediaUnpause.yaml
  responses/gl/HassSetVolume.yaml
  sentences/gl/_common.yaml
  sentences/gl/media_player_HassMediaUnpause.yaml
  sentences/gl/media_player_HassSetVolume.yaml
  tests/gl/media_player_HassMediaUnpause.yaml
  tests/gl/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: gl

#3134 [DA] Add shopping/todo list complete item intents
  responses/da/HassListCompleteItem.yaml
  responses/da/HassShoppingListCompleteItem.yaml
  sentences/da/_common.yaml
  sentences/da/shopping_list_HassShoppingListAddItem.yaml
  sentences/da/shopping_list_HassShoppingListCompleteItem.yaml
  sentences/da/todo_HassListCompleteItem.yaml
  tests/da/_fixtures.yaml
  tests/da/shopping_list_HassShoppingListCompleteItem.yaml
  tests/da/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: da

#3126 [SK] Improve cover and lock domains.
  responses/sk/HassGetState.yaml
  sentences/sk/_common.yaml
  sentences/sk/binary_sensor_HassGetState.yaml
  sentences/sk/cover_HassGetState.yaml
  sentences/sk/lock_HassGetState.yaml
  tests/sk/_fixtures.yaml
  tests/sk/cover_HassGetState.yaml
  tests/sk/lock_HassGetState.yaml
Labels: cla-signed, lang: sk

#3132 [SK] Add shopping/todo list complete item intent.
  responses/sk/HassListCompleteItem.yaml
  responses/sk/HassShoppingListCompleteItem.yaml
  sentences/sk/_common.yaml
  sentences/sk/shopping_list_HassShoppingListCompleteItem.yaml
  sentences/sk/todo_HassListCompleteItem.yaml
  tests/sk/_fixtures.yaml
  tests/sk/shopping_list_HassShoppingListCompleteItem.yaml
  tests/sk/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: sk

#3130 [PT-BR] Fix cover turn on-off
  sentences/pt-br/_common.yaml
  sentences/pt-br/cover_HassTurnOff.yaml
  sentences/pt-br/cover_HassTurnOn.yaml
  tests/pt-br/cover_HassTurnOff.yaml
  tests/pt-br/cover_HassTurnOn.yaml
Labels: cla-signed

#3129 [NL] Add ListRemoveItem
  responses/nl/HassListCompleteItem.yaml
  responses/nl/HassShoppingListCompleteItem.yaml
  sentences/nl/shopping_list_HassShoppingListCompleteItem.yaml
  sentences/nl/todo_HassListCompleteItem.yaml
  tests/nl/_fixtures.yaml
  tests/nl/shopping_list_HassShoppingListCompleteItem.yaml
  tests/nl/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: nl

#3138 Add pt-br language leader
  CODEOWNERS
  languages.yaml
Labels: cla-signed

#3139 [PT-BR] Added HassShoppingListCompleteItem
  responses/pt-br/HassShoppingListCompleteItem.yaml
  sentences/pt-br/_common.yaml
  sentences/pt-br/shopping_list_HassShoppingListCompleteItem.yaml
  tests/pt-br/shopping_list_HassShoppingListCompleteItem.yaml
Labels: cla-signed

#3145 [EN] Fix list name on todo_HassListAddItem
  sentences/en/todo_HassListAddItem.yaml
Labels: cla-signed, lang: en

#3136 [FI] HassBroadcast initial commit
  responses/fi/HassBroadcast.yaml
  sentences/fi/_common.yaml
  sentences/fi/assist_satellite_HassBroadcast.yaml
  tests/fi/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: fi

#3151 [NL] HassClimateGetTemperature improvement:
  sentences/nl/climate_HassClimateGetTemperature.yaml
  tests/nl/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: nl

#3112 [NB] Lights on/off with required 'area' context
  sentences/nb/light_HassTurnOff.yaml
  sentences/nb/light_HassTurnOn.yaml
  tests/nb/light_HassTurnOff.yaml
  tests/nb/light_HassTurnOn.yaml
Labels: cla-signed, lang: nb

#3149 Add "minuterie" french translation for timer
  sentences/fr/_common.yaml
  sentences/fr/homeassistant_HassCancelAllTimers.yaml
  sentences/fr/homeassistant_HassCancelTimer.yaml
  sentences/fr/homeassistant_HassDecreaseTimer.yaml
  sentences/fr/homeassistant_HassIncreaseTimer.yaml
  sentences/fr/homeassistant_HassPauseTimer.yaml
  sentences/fr/homeassistant_HassStartTimer.yaml
  sentences/fr/homeassistant_HassTimerStatus.yaml
  sentences/fr/homeassistant_HassUnpauseTimer.yaml
  tests/fr/homeassistant_HassCancelAllTimers.yaml
  tests/fr/homeassistant_HassCancelTimer.yaml
  tests/fr/homeassistant_HassDecreaseTimer.yaml
  tests/fr/homeassistant_HassPauseTimer.yaml
  tests/fr/homeassistant_HassStartTimer.yaml
  tests/fr/homeassistant_HassTimerStatus.yaml
  tests/fr/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: fr
