Repository OHF-Voice/intents, pull requests merged in 2025-03, with the labels that each got.

#3022 [CS] Fix typo in Czech intents.
  sentences/cs/sensor_HassGetState.yaml
Labels: cla-signed, lang: cs

#3029 [PT] Lights consistency improvements
  sentences/pt/_common.yaml
  sentences/pt/light_HassTurnOff.yaml
  sentences/pt/light_HassTurnOn.yaml
Labels: cla-signed, lang: pt

#3032 [SK] Prepare _common.yml for future additions.
  sentences/sk/_common.yaml
Labels: cla-signed, lang: sk

#3026 [CS] Use correct brackets in HassMediaPrevious.
  sentences/cs/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: cs

#3028 [PT-BR] Lights consistency improvements
  sentences/pt-br/light_HassTurnOff.yaml
  sentences/pt-br/light_HassTurnOn.yaml
Labels: cla-signed

#3023 [DE] fix ambiguities for covers
  sentences/de/_common.yaml
  tests/de/_fixtures.yaml
  tests/de/cover_HassGetState.yaml
Labels: cla-signed, lang: de

#3038 [PT-BR] Improve cover turn on-off usage cases
  responses/pt-br/HassTurnOff.yaml
  responses/pt-br/HassTurnOn.yaml
  sentences/pt-br/cover_HassTurnOff.yaml
  sentences/pt-br/cover_HassTurnOn.yaml
  tests/pt-br/cover_HassTurnOff.yaml
  tests/pt-br/cover_HassTurnOn.yaml
Labels: cla-signed

#3040 [zh-hk] update weather format support
  sentences/zh-hk/weather_HassGetWeather.yaml
  tests/zh-hk/weather_HassGetWeather.yaml
Labels: cla-signed

#3024 [CS] Fix typo in test for Czech intents.
  tests/cs/_fixtures.yaml
  tests/cs/sensor_HassGetState.yaml
Labels: cla-signed, lang: cs

#3042 [es] Checks that "cierra persiana" works closing a blind
  tests/es/_fixtures.yaml
  tests/es/cover_HassTurnOff.yaml
Labels: cla-signed, lang: es

#3044 Add cloud to stt in language support
  languages.yaml
  script/intentfest/validate.py
Labels: cla-signed

#3046 Update prettier
  .pre-commit-config.yaml
Labels: cla-signed

#3047 Add possible slot combinations to all intents
  intents.yaml
  script/intentfest/check_slot_combinations.py
  script/intentfest/util.py
  script/intentfest/validate.py
  sentences/de-CH/homeassistant_HassTurnOff.yaml
  sentences/de-CH/homeassistant_HassTurnOn.yaml
  sentences/el/cover_HassTurnOn.yaml
  sentences/el/homeassistant_HassTurnOn.yaml
  sentences/en/media_player_HassMediaPrevious.yaml
  sentences/lb/cover_HassTurnOff.yaml
  sentences/lb/cover_HassTurnOn.yaml
  sentences/lb/homeassistant_HassTurnOff.yaml
  sentences/lb/homeassistant_HassTurnOn.yaml
  sentences/lt/cover_HassTurnOff.yaml
  sentences/lt/cover_HassTurnOn.yaml
  sentences/lt/homeassistant_HassTurnOff.yaml
  sentences/lt/homeassistant_HassTurnOn.yaml
  sentences/nb/binary_sensor_HassGetState.yaml
  sentences/nb/light_HassLightSet.yaml
  tests/de-CH/homeassistant_HassTurnOff.yaml
  tests/de-CH/homeassistant_HassTurnOn.yaml
  tests/el/cover_HassTurnOn.yaml
  tests/el/homeassistant_HassTurnOn.yaml
  tests/lb/cover_HassTurnOff.yaml
  tests/lb/cover_HassTurnOn.yaml
  tests/lb/homeassistant_HassTurnOff.yaml
  tests/lb/homeassistant_HassTurnOn.yaml
  tests/lt/cover_HassTurnOff.yaml
  tests/lt/cover_HassTurnOn.yaml
  tests/lt/homeassistant_HassTurnOff.yaml
  tests/lt/homeassistant_HassTurnOn.yaml
  tests/test_language_intents.py
  tests/test_language_sentences.py
Labels: cla-signed, lang: en, lang: nb, lang: lt, lang: el, lang: lb

#3039 [SK] Add dať/daj as an alternative to "set".
  sentences/sk/_common.yaml
Labels: cla-signed, lang: sk

#3045 Language support data (Initial v0)
  .pre-commit-config.yaml
  languages.yaml
  script/lint
Labels: cla-signed

#3049 Add importance level to intents
  intents.yaml
  script/intentfest/validate.py
Labels: cla-signed

#3053 Add "usable" label for intent importance
  intents.yaml
  script/intentfest/validate.py
Labels: cla-signed

#3050 [SK] Update Nevermind with a new phrase.
  sentences/sk/homeassistant_HassNevermind.yaml
  tests/sk/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sk

#3051 [SK] Respond: update site URL and extend test.
  responses/sk/HassRespond.yaml
  tests/sk/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: sk

#2910 [FR] weather state is now exposed raw and untranslated
  responses/fr/HassGetWeather.yaml
  tests/fr/_fixtures.yaml
Labels: cla-signed, lang: fr

#3058 [SK] Update LightSet intent.
  responses/sk/HassLightSet.yaml
  sentences/sk/light_HassLightSet.yaml
  tests/sk/light_HassLightSet.yaml
Labels: cla-signed, lang: sk

#3067 [SK] Update MediaNext intent.
  sentences/sk/media_player_HassMediaNext.yaml
  tests/sk/_fixtures.yaml
  tests/sk/media_player_HassMediaNext.yaml
Labels: cla-signed, lang: sk

#3063 [SK] Update VacuumStart intent.
  sentences/sk/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: sk

#3064 [SK] Update VacuumReturnToBase intent.
  sentences/sk/vacuum_HassVacuumReturnToBase.yaml
  tests/sk/vacuum_HassVacuumReturnToBase.yaml
Labels: cla-signed, lang: sk

#3060 [SK] Update ClimateGetTemperature intent.
  sentences/sk/climate_HassClimateGetTemperature.yaml
  tests/sk/_fixtures.yaml
  tests/sk/climate_HassClimateGetTemperature.yaml
Labels: cla-signed, lang: sk

#3068 [SK] Add MediaPrevious intent.
  responses/sk/HassMediaPrevious.yaml
  sentences/sk/media_player_HassMediaPrevious.yaml
  tests/sk/_fixtures.yaml
  tests/sk/media_player_HassMediaPrevious.yaml
Labels: cla-signed, lang: sk

#3061 [CS] add basic timer commands, aligned with minimal voice set
  responses/cs/HassCancelTimer.yaml
  responses/cs/HassStartTimer.yaml
  responses/cs/HassTimerStatus.yaml
  sentences/cs/_common.yaml
  sentences/cs/homeassistant_HassCancelTimer.yaml
  sentences/cs/homeassistant_HassStartTimer.yaml
  sentences/cs/homeassistant_HassTimerStatus.yaml
  tests/cs/_fixtures.yaml
  tests/cs/homeassistant_HassCancelTimer.yaml
  tests/cs/homeassistant_HassStartTimer.yaml
  tests/cs/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: cs

#3062 [SK] Update GetWeather intent.
  responses/sk/HassGetWeather.yaml
  sentences/sk/sensor_HassGetState.yaml
  sentences/sk/weather_HassGetWeather.yaml
  tests/sk/_fixtures.yaml
  tests/sk/sensor_HassGetState.yaml
  tests/sk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sk

#3070 [SK] Improve tests for SetVolume.
  tests/sk/_fixtures.yaml
  tests/sk/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: sk

#3071 [SK] Add TimerStatus intent.
  responses/sk/HassTimerStatus.yaml
  sentences/sk/homeassistant_HassTimerStatus.yaml
  tests/sk/_fixtures.yaml
  tests/sk/homeassistant_HassCancelAllTimers.yaml
  tests/sk/homeassistant_HassTimerStatus.yaml
Labels: cla-signed, lang: sk

#3072 [SK] Add IncreaseTimer intent.
  responses/sk/HassIncreaseTimer.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassIncreaseTimer.yaml
  tests/sk/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: sk

#3073 [CS] hass respond
  responses/cs/HassRespond.yaml
  sentences/cs/homeassistant_HassRespond.yaml
  tests/cs/homeassistant_HassRespond.yaml
Labels: cla-signed, lang: cs

#3077 [SK] Add infinitives to commands.
  sentences/sk/_common.yaml
Labels: cla-signed, lang: sk

#3075 [SK] Add DecreaseTimer intent.
  responses/sk/HassDecreaseTimer.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassDecreaseTimer.yaml
  tests/sk/homeassistant_HassDecreaseTimer.yaml
Labels: cla-signed, lang: sk

#3076 [SK] Add PauseTimer intent.
  responses/sk/HassPauseTimer.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassPauseTimer.yaml
  tests/sk/homeassistant_HassPauseTimer.yaml
Labels: cla-signed, lang: sk

#3081 [SK] Add unpause timer intent
  responses/sk/HassUnpauseTimer.yaml
  sentences/sk/_common.yaml
  sentences/sk/homeassistant_HassUnpauseTimer.yaml
  tests/sk/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: sk

#3083 [SK] Improve tests for ClimateSetTemperature.
  sentences/sk/_common.yaml
  tests/sk/climate_HassClimateSetTemperature.yaml
Labels: cla-signed, lang: sk

#3086 [SK] Add more sentences to Nevermind intent.
  sentences/sk/homeassistant_HassNevermind.yaml
  tests/sk/homeassistant_HassNevermind.yaml
Labels: cla-signed, lang: sk

#3085 [SK] Improve GetState sentences (person domain).
  sentences/sk/person_HassGetState.yaml
  tests/sk/person_HassGetState.yaml
Labels: cla-signed, lang: sk

#3088 [BG] HassBroadcast translated
  node_modules/.cache/prettier/.prettier-caches/4e6fbaf08c90c67f0b087caec191971c323a085e.json
  responses/bg/HassBroadcast.yaml
  sentences/bg/_common.yaml
  sentences/bg/assist_satellite_HassBroadcast.yaml
  tests/bg/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: bg

#3087 [SK] Improve IncreaseTimer intent.
  sentences/sk/_common.yaml
  tests/sk/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: sk

#3090 Add importance to slot combinations
  intents.yaml
  script/intentfest/validate.py
Labels: cla-signed

#3095 Update Speech-To-Phrase support for NL
  languages.yaml
Labels: cla-signed

#3097 A few updates on the languages scores.
  languages.yaml
Labels: cla-signed

#3074 [CS] timer (un)pause
  responses/cs/HassPauseTimer.yaml
  responses/cs/HassUnpauseTimer.yaml
  sentences/cs/_common.yaml
  sentences/cs/homeassistant_HassPauseTimer.yaml
  sentences/cs/homeassistant_HassUnpauseTimer.yaml
  tests/cs/homeassistant_HassPauseTimer.yaml
  tests/cs/homeassistant_HassUnpauseTimer.yaml
Labels: cla-signed, lang: cs

#3092 [SK] Improve LightSet intent.
  responses/sk/HassLightSet.yaml
  sentences/sk/_common.yaml
  sentences/sk/light_HassLightSet.yaml
  tests/sk/light_HassLightSet.yaml
Labels: cla-signed, lang: sk

#3099 [SK] Improve GetWeather intent.
  responses/sk/HassGetWeather.yaml
  sentences/sk/_common.yaml
  sentences/sk/weather_HassGetWeather.yaml
  tests/sk/_fixtures.yaml
  tests/sk/weather_HassGetWeather.yaml
Labels: cla-signed, lang: sk

#3101 [SK] Improve TurnOn intent (cover domain).
  responses/sk/HassTurnOn.yaml
  sentences/sk/_common.yaml
  sentences/sk/cover_HassTurnOn.yaml
  tests/sk/cover_HassTurnOn.yaml
Labels: cla-signed, lang: sk

#3108 [SL] fix assist_satellite
  node_modules/.cache/prettier/.prettier-caches/4e6fbaf08c90c67f0b087caec191971c323a085e.json
  sentences/sl/assist_satellite_HassBroadcast.yaml
  tests/sl/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: sl

#3096 [EN] Add area aware HassSetPosition for covers
  responses/en/HassSetPosition.yaml
  sentences/en/cover_HassSetPosition.yaml
  tests/en/cover_HassSetPosition.yaml
Labels: cla-signed, lang: en

#3035 feat: Add HassShoppingListCompleteItem
  intents.yaml
  responses/en/HassShoppingListCompleteItem.yaml
  sentences/en/shopping_list_HassShoppingListCompleteItem.yaml
  tests/en/shopping_list_HassShoppingListCompleteItem.yaml
Labels: cla-signed, lang: en

#3004 feat: Add HassListCompleteItem
  intents.yaml
  responses/en/HassListCompleteItem.yaml
  sentences/en/_common.yaml
  sentences/en/todo_HassListCompleteItem.yaml
  tests/en/_fixtures.yaml
  tests/en/todo_HassListCompleteItem.yaml
Labels: cla-signed, lang: en

#3111 [SK] Fix and improve intents related to covers and bs.
  responses/sk/HassGetState.yaml
  sentences/sk/_common.yaml
  sentences/sk/binary_sensor_HassGetState.yaml
  sentences/sk/cover_HassGetState.yaml
  sentences/sk/cover_HassTurnOff.yaml
  sentences/sk/homeassistant_HassGetState.yaml
  tests/sk/_fixtures.yaml
  tests/sk/binary_sensor_HassGetState.yaml
  tests/sk/cover_HassGetState.yaml
  tests/sk/homeassistant_HassGetState.yaml
Labels: cla-signed, lang: sk

#3113 [PL] Added extra sentences for HassBroadcast and updated few wrong words
  sentences/pl/_common.yaml
  sentences/pl/assist_satellite_HassBroadcast.yaml
  tests/pl/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: pl

#3115 Mark complete item intents as optional
  intents.yaml
Labels: cla-signed

#3116 Revert prettier back to v3
  .pre-commit-config.yaml
Labels: cla-signed

#3114 [CA] Add HassBroadcast
  responses/ca/HassBroadcast.yaml
  sentences/ca/_common.yaml
  sentences/ca/assist_satellite_HassBroadcast.yaml
  tests/ca/assist_satellite_HassBroadcast.yaml
Labels: cla-signed, lang: ca

#3109 [IT] Fix state and tests for cover GetState.
  tests/it/_fixtures.yaml
  tests/it/cover_HassGetState.yaml
Labels: cla-signed, lang: it
