Repository OHF-Voice/intents, pull requests merged in 2025-10, with the labels that each got.

#3499 [DE] restructure expansion rules in common.yaml
  sentences/de/_common.yaml
Labels: lang: de

#3465 [DE] HassLightSet: add more variations to color controls
  sentences/de/light_HassLightSet.yaml
  tests/de/light_HassLightSet.yaml
Labels: lang: de

#3511 [EL] MediaPlayerUnmute
  responses/el/HassMediaPlayerUnmute.yaml
  sentences/el/media_player_HassMediaPlayerUnmute.yaml
  tests/el/media_player_HassMediaPlayerUnmute.yaml
Labels: lang: el

#3512 Update _common.yaml
  sentences/el/_common.yaml
Labels: lang: el

#3509 [de-CH] Add HassListAddItem
  responses/de-CH/HassListCompleteItem.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/todo_HassListAddItem.yaml
  sentences/de-CH/todo_HassListCompleteItem.yaml
  tests/de-CH/todo_HassListCompleteItem.yaml
Labels: lang: de-ch

#3496 [de-CH] Add HassShoppingListCompleteItem
  responses/de-CH/HassShoppingListCompleteItem.yaml
  sentences/de-CH/_common.yaml
  sentences/de-CH/shopping_list_HassShoppingListAddItem.yaml
  sentences/de-CH/shopping_list_HassShoppingListCompleteItem.yaml
  tests/de-CH/shopping_list_HassShoppingListCompleteItem.yaml
Labels: lang: de-ch

#3506 [DE] add skip word "noch"
  sentences/de/_common.yaml
  sentences/de/homeassistant_HassTimerStatus.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: lang: de

#3514 [EL] add AQ sensors
  sentences/el/sensor_HassGetState.yaml
  tests/el/_fixtures.yaml
  tests/el/sensor_HassGetState.yaml
Labels: lang: el

#3513 [DE] reduce sentences count and ajust starTimer sentences
  sentences/de/homeassistant_HassStartTimer.yaml
  tests/de/homeassistant_HassStartTimer.yaml
Labels: lang: de

#3503 [DE] add "doch" to list of skip_words
  sentences/de/_common.yaml
  tests/de/cover_HassTurnOff.yaml
Labels: lang: de

#3463 [GA] Add HassRespond
  responses/ga/HassRespond.yaml
  sentences/ga/homeassistant_HassRespond.yaml
  tests/ga/homeassistant_HassRespond.yaml
Labels: lang: ga

#3462 [GA] Add HassNevermind
  responses/ga/HassNevermind.yaml
  sentences/ga/homeassistant_HassNevermind.yaml
  tests/ga/homeassistant_HassNevermind.yaml
Labels: lang: ga

#3464 [GA] Translate some errors
  sentences/ga/_common.yaml
Labels: lang: ga

#3228 [GA] Add Irish language support for HassGetCurrentTime intent
  responses/ga/HassGetCurrentTime.yaml
  sentences/ga/homeassistant_HassGetCurrentTime.yaml
  tests/ga/homeassistant_HassGetCurrentTime.yaml
Labels: lang: ga
