Repository OHF-Voice/intents, pull requests merged in 2025-06, with the labels that each got.

#3212 Fix grammar of Italia add to timer intent
  sentences/it/homeassistant_HassIncreaseTimer.yaml
  tests/it/homeassistant_HassIncreaseTimer.yaml
Labels: cla-signed, lang: it

#2894 [NE] Added LightSet,Climate, CurrentTime, CurrentDate, Respond, Nevermind and Cover Intent
  responses/ne/HassClimateGetTemperature.yaml
  responses/ne/HassClimateSetTemperature.yaml
  responses/ne/HassGetCurrentDate.yaml
  responses/ne/HassGetCurrentTime.yaml
  responses/ne/HassGetState.yaml
  responses/ne/HassLightSet.yaml
  responses/ne/HassRespond.yaml
  responses/ne/HassSetPosition.yaml
  responses/ne/HassTurnOff.yaml
  responses/ne/HassTurnOn.yaml
  sentences/ne/_common.yaml
  sentences/ne/climate_HassClimateGetTemperature.yaml
  sentences/ne/climate_HassClimateSetTemperature.yaml
  sentences/ne/cover_HassGetState.yaml
  sentences/ne/cover_HassSetPosition.yaml
  sentences/ne/cover_HassTurnOff.yaml
  sentences/ne/cover_HassTurnOn.yaml
  sentences/ne/fan_HassTurnOff.yaml
  sentences/ne/fan_HassTurnOn.yaml
  sentences/ne/homeassistant_HassGetCurrentDate.yaml
  sentences/ne/homeassistant_HassGetCurrentTime.yaml
  sentences/ne/homeassistant_HassNevermind.yaml
  sentences/ne/homeassistant_HassRespond.yaml
  sentences/ne/homeassistant_HassTurnOff.yaml
  sentences/ne/homeassistant_HassTurnOn.yaml
  sentences/ne/light_HassLightSet.yaml
  sentences/ne/light_HassTurnOff.yaml
  sentences/ne/light_HassTurnOn.yaml
  tests/ne/_fixtures.yaml
  tests/ne/climate_HassClimateGetTemperature.yaml
  tests/ne/climate_HassClimateSetTemperature.yaml
  tests/ne/cover_HassGetState.yaml
  tests/ne/cover_HassSetPosition.yaml
  tests/ne/cover_HassTurnOff.yaml
  tests/ne/cover_HassTurnOn.yaml
  tests/ne/fan_HassTurnOff.yaml
  tests/ne/fan_HassTurnOn.yaml
  tests/ne/homeassistant_HassGetCurrentDate.yaml
  tests/ne/homeassistant_HassGetCurrentTime.yaml
  tests/ne/homeassistant_HassNevermind.yaml
  tests/ne/homeassistant_HassRespond.yaml
  tests/ne/homeassistant_HassTurnOff.yaml
  tests/ne/homeassistant_HassTurnOn.yaml
  tests/ne/light_HassLightSet.yaml
  tests/ne/light_HassTurnOff.yaml
  tests/ne/light_HassTurnOn.yaml
Labels: cla-signed, lang: ne

#3215 Add more errors to add_language script
  script/intentfest/add_language.py
Labels: cla-signed

#3200 [EL] Refactor temperature response logic for Greek language base on Fix PR
  responses/el/HassClimateGetTemperature.yaml
Labels: cla-signed, lang: el

#3165 intents: improved description of HassClimateGetTemperature
  intents.yaml
Labels: documentation, cla-signed

#3202 [EL] Add Greek responses and tests for vacuum intents
  responses/el/HassVacuumReturnToBase.yaml
  responses/el/HassVacuumStart.yaml
  sentences/el/_common.yaml
  sentences/el/vacuum_HassVacuumReturnToBase.yaml
  sentences/el/vacuum_HassVacuumStart.yaml
  tests/el/_fixtures.yaml
  tests/el/vacuum_HassVacuumReturnToBase.yaml
  tests/el/vacuum_HassVacuumStart.yaml
Labels: cla-signed, lang: el

#3211 [JA]Add ja language
  languages.yaml
  responses/ja/HassTurnOff.yaml
  responses/ja/HassTurnOn.yaml
  sentences/ja/_common.yaml
  sentences/ja/homeassistant_HassTurnOff.yaml
  sentences/ja/homeassistant_HassTurnOn.yaml
  tests/ja/_fixtures.yaml
  tests/ja/homeassistant_HassTurnOff.yaml
  tests/ja/homeassistant_HassTurnOn.yaml
Labels: cla-signed, lang: ja

#3207 [EL] Add valve intents and responses for Valve Control
  responses/el/HassSetPosition.yaml
  responses/el/HassTurnOff.yaml
  responses/el/HassTurnOn.yaml
  sentences/el/_common.yaml
  sentences/el/valve_HassSetPosition.yaml
  sentences/el/valve_HassTurnOff.yaml
  sentences/el/valve_HassTurnOn.yaml
  tests/el/_fixtures.yaml
  tests/el/valve_HassSetPosition.yaml
  tests/el/valve_HassTurnOff.yaml
  tests/el/valve_HassTurnOn.yaml
Labels: cla-signed, lang: el

#3192 [EL] Add Greek language support for media player intents and responses
  responses/el/HassMediaNext.yaml
  responses/el/HassMediaPause.yaml
  responses/el/HassMediaPrevious.yaml
  responses/el/HassMediaUnpause.yaml
  responses/el/HassSetVolume.yaml
  sentences/el/_common.yaml
  sentences/el/media_player_HassMediaNext.yaml
  sentences/el/media_player_HassMediaPause.yaml
  sentences/el/media_player_HassMediaPrevious.yaml
  sentences/el/media_player_HassMediaUnpause.yaml
  sentences/el/media_player_HassSetVolume.yaml
  tests/el/media_player_HassMediaNext.yaml
  tests/el/media_player_HassMediaPause.yaml
  tests/el/media_player_HassMediaPrevious.yaml
  tests/el/media_player_HassMediaUnpause.yaml
  tests/el/media_player_HassSetVolume.yaml
Labels: cla-signed, lang: el

#3195 [EL] Add Greek language support for current date and time intents
  responses/el/HassGetCurrentDate.yaml
  responses/el/HassGetCurrentTime.yaml
  sentences/el/homeassistant_HassGetCurrentDate.yaml
  sentences/el/homeassistant_HassGetCurrentTime.yaml
  tests/el/homeassistant_HassGetCurrentDate.yaml
  tests/el/homeassistant_HassGetCurrentTime.yaml
Labels: cla-signed, lang: el

#3198 [EL] Add lock intents and responses for Greek language support
  responses/el/HassTurnOff.yaml
  sentences/el/_common.yaml
  sentences/el/lock_HassGetState.yaml
  sentences/el/lock_HassTurnOff.yaml
  sentences/el/lock_HassTurnOn.yaml
  tests/el/_fixtures.yaml
  tests/el/lock_HassGetState.yaml
  tests/el/lock_HassTurnOff.yaml
  tests/el/lock_HassTurnOn.yaml
Labels: cla-signed, lang: el

#3197 [EL] Add Greek responses and tests for HassShoppingListCompleteItem intent
  responses/el/HassShoppingListCompleteItem.yaml
  sentences/el/shopping_list_HassShoppingListAddItem.yaml
  sentences/el/shopping_list_HassShoppingListCompleteItem.yaml
  tests/el/shopping_list_HassShoppingListCompleteItem.yaml
Labels: cla-signed, lang: el
